### ISSUE TITLE
JSON error when opening from URL

### ISSUE THREAD

**Issue by JasonWeill** [jupyterlite/jupyterlite#1011]
## Description

Moved from https://github.com/jupyterlab/jupyterlab/issues/14194, opened by @oeway.

When opening a notebook via URL, JupyterLite displays a JSON error but JupyterLab does not.

## Reproduce

1. Launch JupyterLite here: https://jupyter.org/try-jupyter/lab/
2. Choose File > Open from URL…
3. Open https://raw.githubusercontent.com/InsightSoftwareConsortium/itkwidgets/00a7ae180f3abf3f90222ce514ad17a8e5ba0402/docs/jupyterlite/files/Hello3DWorld.ipynb
4. See error: 

>    Upload Error
>   JSON.parse: unterminated string at line 48 column 470833 of the JSON data

## Expected behavior

Notebook opens. (This happens with JupyterLab 4.0.0a35, when installed locally.)

## Context

- JupyterLite version: 0.1.0-beta.19
- Operating System and version: macOS 12.6.3 "Monterey"
- Browser and version: Firefox 102.8.0esr (64-bit)

**Comment by vaddisrinivas** [comment]
Is this issue still open? I'd like to contribute here!

**Comment by JasonWeill** [comment]
I was able to reproduce it just now. Please free to submit a pull request when you're ready! You can also keep the conversation going on this issue or on our other social channels, like [Gitter](https://gitter.im/jupyterlab/jupyterlab#) and [Discourse](https://discourse.jupyter.org/).
