### ISSUE TITLE
Comment on core/optional packages in `requirements.txt`

### ISSUE THREAD

**Issue by pierrepo** [jupyterlite/jupyterlite#1017]
### Problem

JupyterLite [documentation](https://jupyterlite.readthedocs.io/en/latest/quickstart/deploy.html) provides a step-by-step guide on how to deploy one's own instance of JupyterLite. This works very well, thank you for that :pray:

The documentation [ends](https://jupyterlite.readthedocs.io/en/latest/quickstart/deploy.html#deploy-a-new-version-of-jupyterlite) by mentioning the file [`requirements.txt`](https://github.com/jupyterlite/demo/blob/main/requirements.txt) that can be customized to some extent.

However, it is not very obvious to understand which package is core/mandatory or optional in `requirements.txt`.

### Suggested Improvement

Since, [pip supports comments](https://pip.pypa.io/en/latest/reference/requirements-file-format/) in `requirements.txt`, would it be possible to reorganize and annotate this file?

For instance:

```
# Core modules (mandatory)
jupyterlite-core==0.1.0b19
jupyterlite-pyodide-kernel==0.0.5
jupyterlab~=3.5.1

# Language support (optional)
jupyterlab-language-pack-fr-FR
jupyterlab-language-pack-zh-CN

# SQLite kernel (optional)
jupyterlite-xeus-sqlite==0.2.1
# P5 kernel (optional)
jupyterlite-p5-kernel==0.1.0
# Lua kernel (optional)
jupyterlite-xeus-lua==0.3.1

# JupyterLab: Fasta file renderer (optional)
jupyterlab-fasta>=3,<4
# JupyterLab: Geojson file renderer (optional)
jupyterlab-geojson>=3,<4
# JupyterLab: guided tour (optional)
jupyterlab-tour
# JupyterLab: dark theme
jupyterlab-night
# JupyterLab: Miami nights theme (optional)
jupyterlab_miami_nights

# Python: ipywidget library (optional)
ipywidgets>=8.0.0,<9
# Python: plotting libraries (optional)
plotly>=5,<6
bqplot
# Python: interative Matplotlib library in notebooks (optional)
ipympl>=0.8.2
# Python: ipycanvas library (optional)
ipycanvas>=0.9.1
# Python: ipyleaflet library (optional)
ipyleaflet

# No idea
ipyevents>=2.0.1
```

Of course, a word of caution should be added in the documentation to warn user that examples in the demo might fail if this file is modified (for instance, if kernels or librairies are removed)

**Comment by jtpio** [comment]
Thanks @pierrepo for the suggestion.

Some of these points will be addressed by https://github.com/jupyterlite/jupyterlite/pull/1018.

**Comment by jtpio** [comment]
A second step would be to open a PR on https://github.com/jupyterlite/demo to add the comments to `requirements.txt`.

@pierrepo would you like to open the PR? Thanks!

**Comment by pierrepo** [comment]
Sure. I will. Could you please tell me what `ipyevents` is used for?

**Comment by jtpio** [comment]
I think it added for the `pyb2d` examples: https://github.com/jupyterlite/demo/pull/74.

It's available here: https://github.com/mwcraig/ipyevents

**Comment by pierrepo** [comment]
Thanks @jtpio 
PR is available [here](https://github.com/jupyterlite/demo/pull/110)
