### ISSUE TITLE
Adding custom extension to the demo site does not seem to include/activate it

### ISSUE THREAD

**Issue by stevejpurves** [jupyterlite/jupyterlite#1020]
## Description

I am trying to build [a demo site based on the jupyterlite demo template repo](https://github.com/stevejpurves/jupyterlab-myst-quickstart-lite). The aim is to include a prebuilt jupyterlab only frontend extension (`jupyterlab-myst`) and some demo notebooks to accompany it.

I started out by forking the template and then:

- added `jupyterlab-myst` to the `requirements.txt` file
- added notebooks to the `content` folder
- pushed to `main` and redeployed

when accessing the site https://stevejpurves.github.io/jupyterlab-myst-quickstart-lite/lab/index.html I can see the notebooks I added and open them - however he myst content does not render. I am not sure how to check that the `jupyterlab-myst` extension was loaded, or how to debug further.

The `juptyerlab-myst` extension overrides the default markdown renderer and is functional in `jupyterlab` -- should this be expected to work out of the box in jupyterlite?

## Reproduce
Check the deployed demo site here: https://stevejpurves.github.io/jupyterlab-myst-quickstart-lite/lab/index.html

## Expected behavior

I would expect the markdown cells that contain myst in the demo notebooks to render myst directives correctly.

## Context

- JupyterLite version: forked from latest demo repo
- Operating System and version: MacOS
- Browser and version: Chrome

<details><summary>Browser Output</summary>
On opening the notebook `01-jupyterlab-myst.ipynb` the follow appears in the JS console
<pre>
VM356 react_devtools_backend.js:2655 TypeError: Cannot set properties of undefined (setting 'text')
    at m._setValue (jsoneditor.ts:331:19)
    at set source [as source] (jsoneditor.ts:134:10)
    at e.NotebookMetadataEditorTool._update (notebooktools.ts:637:19)
    at e.NotebookMetadataEditorTool.onActiveNotebookPanelChanged (notebooktools.ts:623:12)
    at e.NotebookMetadataEditorTool.processMessage (notebooktools.ts:345:16)
    at c (index.ts:530:15)
    at Object.e [as sendMessage] (index.ts:220:7)
    at notebooktools.ts:172:7
    at f (iter.ts:227:9)
    at P._onActiveNotebookPanelChanged (notebooktools.ts:171:5)
overrideMethod @ VM356 react_devtools_backend.js:2655
s @ index.ts:467
c @ index.ts:532
e @ index.ts:220
(anonymous) @ notebooktools.ts:172
f @ iter.ts:227
_onActiveNotebookPanelChanged @ notebooktools.ts:171
u @ index.ts:673
n.emit @ index.ts:594
n.emit @ index.ts:208
(anonymous) @ widgettracker.ts:144
u @ index.ts:673
n.emit @ index.ts:594
n.emit @ index.ts:208
_onInstanceDisposed @ restorablepool.ts:314
u @ index.ts:673
n.emit @ index.ts:594
n.emit @ index.ts:208
e.dispose @ widget.ts:68
dispose @ panel.ts:150
(anonymous) @ mainareawidget.ts:85
u @ index.ts:673
n.emit @ index.ts:594
n.emit @ index.ts:208
e.dispose @ widget.ts:68
dispose @ widget.ts:379
dispose @ widget.ts:1328
dispose @ panel.ts:149
onClose @ widgetmanager.ts:318
await in onClose (async)
messageHook @ widgetmanager.ts:232
(anonymous) @ index.ts:515
(anonymous) @ index.ts:226
c @ iter.ts:266
e @ index.ts:225
e.close @ widget.ts:417
t._onTabCloseRequested @ dockpanel.ts:1031
u @ index.ts:673
n.emit @ index.ts:594
n.emit @ index.ts:208
t._evtMouseUp @ tabbar.ts:978
t.handleEvent @ tabbar.ts:609
VM356 react_devtools_backend.js:2655 TypeError: Cannot set properties of undefined (setting 'text')
    at m._setValue (jsoneditor.ts:331:19)
    at set source [as source] (jsoneditor.ts:134:10)
    at e.CellMetadataEditorTool._update (notebooktools.ts:672:19)
    at e.CellMetadataEditorTool.onActiveCellChanged (notebooktools.ts:660:12)
    at e.CellMetadataEditorTool.processMessage (notebooktools.ts:348:16)
    at c (index.ts:530:15)
    at Object.e [as sendMessage] (index.ts:220:7)
    at notebooktools.ts:195:7
    at f (iter.ts:227:9)
    at P._onActiveCellChanged (notebooktools.ts:194:5)
overrideMethod @ VM356 react_devtools_backend.js:2655
s @ index.ts:467
c @ index.ts:532
e @ index.ts:220
(anonymous) @ notebooktools.ts:195
f @ iter.ts:227
_onActiveCellChanged @ notebooktools.ts:194
u @ index.ts:673
n.emit @ index.ts:594
n.emit @ index.ts:208
onCurrentChanged @ tracker.ts:82
(anonymous) @ widgettracker.ts:143
u @ index.ts:673
n.emit @ index.ts:594
n.emit @ index.ts:208
set current @ restorablepool.ts:61
add @ widgettracker.ts:225
await in add (async)
add @ tracker.ts:52
(anonymous) @ index.ts:1356
u @ index.ts:673
n.emit @ index.ts:594
n.emit @ index.ts:208
createNew @ default.ts:428
createWidget @ widgetmanager.ts:73
_createOrOpenDocument @ manager.ts:600
open @ manager.ts:365
openOrReveal @ manager.ts:401
handleOpen @ listing.ts:1021
evtDblClick @ listing.ts:1116
handleEvent @ listing.ts:666
48[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
default.ts:1251 Starting WebSocket: wss://stevejpurves.github.io/jupyterlab-myst-quickstart-lite/api/kernels/5064befe-3f3a-4c3f-9cb7-86988d35ff0e
VM356 react_devtools_backend.js:2655 Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm did not respond in time
overrideMethod @ VM356 react_devtools_backend.js:2655
_loadFromKernel @ 150.267f129ae5fd6a33b390.js?v=267f129ae5fd6a33b390:1
await in _loadFromKernel (async)
_loadFromKernel @ 134.c61b95b04e00f8487eeb.js?v=c61b95b04e00f8487eeb:1
restoreWidgets @ 134.c61b95b04e00f8487eeb.js?v=c61b95b04e00f8487eeb:1
_handleKernelConnectionStatusChange @ 134.c61b95b04e00f8487eeb.js?v=c61b95b04e00f8487eeb:1
(anonymous) @ 134.c61b95b04e00f8487eeb.js?v=c61b95b04e00f8487eeb:1
u @ index.ts:673
n.emit @ index.ts:594
n.emit @ index.ts:208
_onConnectionStatusChanged @ sessioncontext.tsx:1115
u @ index.ts:673
n.emit @ index.ts:594
n.emit @ index.ts:208
onKernelConnectionStatus @ default.ts:348
u @ index.ts:673
n.emit @ index.ts:594
n.emit @ index.ts:208
_updateConnectionStatus @ default.ts:1391
_onWSOpen @ default.ts:1535
(anonymous) @ mock-socket.js:800
w.dispatchEvent @ mock-socket.js:796
(anonymous) @ mock-socket.js:1472
(anonymous) @ mock-socket.js:698
setTimeout (async)
g @ mock-socket.js:698
e @ mock-socket.js:1437
_createSocket @ default.ts:1264
v @ default.ts:59
connectTo @ manager.ts:122
_connectToKernel @ manager.ts:343
setupKernel @ default.ts:315
t.SessionConnection @ default.ts:39
connectTo @ manager.ts:107
_initialize @ sessioncontext.tsx:750
await in _initialize (async)
initialize @ sessioncontext.tsx:725
(anonymous) @ context.ts:565
Promise.then (async)
_populate @ context.ts:549
(anonymous) @ context.ts:708
Promise.then (async)
_revert @ context.ts:678
initialize @ context.ts:269
await in initialize (async)
(anonymous) @ manager.ts:590
Promise.then (async)
_createOrOpenDocument @ manager.ts:590
open @ manager.ts:365
openOrReveal @ manager.ts:401
handleOpen @ listing.ts:1021
evtDblClick @ listing.ts:1116
handleEvent @ listing.ts:666
</pre>
</details>

**Comment by jtpio** [comment]
Looking into this in https://github.com/jupyterlite/jupyterlite/pull/1021

**Comment by stevejpurves** [comment]
awesome thanks @jtpio !

**Comment by rowanc1** [comment]
So cool!! This is amazing.

**Comment by jtpio** [comment]
FYI @stevejpurves @rowanc1 I just released `0.1.0b21` which includes #1021
