### ISSUE TITLE
Docs: How to manually add an extension to JupyterLite

### ISSUE THREAD

**Issue by JustinGirard** [jupyterlite/jupyterlite#1028]
I'm very excited about Jupyter in the browser. However, I am stuck. I'm interested in adding a kernel extension manually to JupyterLite. I have "npm run build" and have successfully launched by jupyter from the /app/ dir to my custom host. 

How does one, (interested in doing things manually, not via the CLI) add in the pyodide Kernel extension once built?

I am also interested in developing my own kernel, so I figured learning this now would be great. I've tried several config locations / methods but none of them seem to get picked up in the "npm run build" process.

Once I figure this out, I am happy to submit a documentation PR for others, to pay the lesson forward.

**Comment by jtpio** [comment]
Thanks @JustinGirard for trying this out :+1: 

> from the /app/ dir

JupyterLite uses the same extension system as in JupyterLab. It looks like you are trying to build JupyterLite from source? Which should not be necessary.
Maybe this guide for creating extensions can help? https://jupyterlite.readthedocs.io/en/latest/howto/extensions/frontend.html

> add in the pyodide Kernel extension once built?

This is detailed here: https://jupyterlite.readthedocs.io/en/latest/howto/configure/kernels.html#adding-a-python-kernel

> I am also interested in developing my own kernel,

And there is a guide about that too: https://jupyterlite.readthedocs.io/en/latest/howto/extensions/kernel.html

---

Hope this helps, let us know if you have any question. We can indeed always improve the docs!

**Comment by jtpio** [comment]
Also to do things even more manually there is a "The Hard Way" guide: https://jupyterlite.readthedocs.io/en/latest/howto/configure/advanced/hard.html#extensions-the-hard-way

**Comment by JustinGirard** [comment]
Thanks for letting me know about the hard way (and the easy way)!! This is all indeed what I was looking for.  I'll keep a log of my progress and if I see anything I can contribute I'll submit it!

Thanks!! I was excited to keep going so thanks for helping.
