### ISSUE TITLE
npm packages aren't published on release 

### ISSUE THREAD

**Issue by joemarshall** [jupyterlite/jupyterlite#1043]
The release builds a bunch of packages to .tgz files in the release. 

Most of these are on npm somewhere, but almost all in older versions than the release. It would be great if the github action also updated the npm versions to be up to date, for those of us who are using npm / webpack to use components of jupyterlite.

**Comment by jtpio** [comment]
@joemarshall normally the JS packages are also published to npm. For example: https://www.npmjs.com/package/@jupyterlite/application?activeTab=code

![image](https://user-images.githubusercontent.com/591645/230401364-b3f31dc8-027b-44c2-b391-58fa84cf04e9.png)


As an example they are used in downstream applications or kernels like https://github.com/jupyterlite/xeus-python-kernel/blob/b9e96d1f994ad075b4e191eb01fdbb0b27389c28/package.json#L55.

**Comment by joemarshall** [comment]
Weird, I must have had some caching weirdness and i can see them all now. Closing, sorry.
