### ISSUE TITLE
Add a download button to the notebook top bar

### ISSUE THREAD

**Issue by pierrepo** [jupyterlite/jupyterlite#1049]
### Problem

Hello, I'm using JupyterLite for an introductory Python course in a university curriculum. JupyterLite really fits my needs and students are very happy with it.

I'm presenting JupyterLite as a *disposable* environment, as students are not guaranteed to find their modified notebooks since they can change computer rooms between classes. I advise students to export notebooks they worked with after a class. For that, they can right-click on the notebook name in the left panel and select "Download".

### Proposed Solution

I wondered if a download button could be implemented in the notebook top bar to quickly download a notebook.

This would be similar to what is offered in Binder:

![image](https://user-images.githubusercontent.com/733861/231295378-b3bb6143-dd21-44db-97d5-1103fb9d1425.png)

Do you think this is a good idea?

**Comment by jtpio** [comment]
Thanks @pierrepo.

Not sure it should be in the notebook toolbar by default.
However this could be implemented as a JupyterLab extension. The extension could then be included in JupyterLite deployments, or even be used in stock JupyterLab.

**Comment by pierrepo** [comment]
Oh yes, this is a good idea

**Comment by jtpio** [comment]
Actually it should be possible to do it via the settings directly without needing a dedicated extension:

![image](https://user-images.githubusercontent.com/591645/231449012-27be0073-862c-4d82-be41-a746777325dd.png)

So a JupyterLite deployment could include an `overrides.json` with the extra toolbar item definition.

**Comment by jtpio** [comment]
Maybe this could be documented in one of the existing "Contents" guides, or as a separate guide: https://jupyterlite.readthedocs.io/en/latest/howto/index.html#contents

**Comment by pierrepo** [comment]
:exploding_head:

**Comment by jtpio** [comment]
Another place for writing documentation could be the "Customizing Settings" that could contain a second example: https://jupyterlite.readthedocs.io/en/latest/howto/configure/settings.html

**Comment by jtpio** [comment]
@pierrepo would you like to open a PR to add this to the docs?

**Comment by pierrepo** [comment]
Sure. But don't complain if I break the internet :rofl:

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlite/jupyterlite/pull/1051, thanks @pierrepo!
