### ISSUE TITLE
Real Time Collaboration does not work consistently and reliably

### ISSUE THREAD

**Issue by gitskim** [jupyterlite/jupyterlite#1052]
## Description

I enabled the Real Time Collaboration (RTC) feature by following the documentation here (https://jupyterlite.readthedocs.io/en/latest/howto/configure/rtc.html) and implemented it here (https://github.com/gitskim/gitskim.github.io). My website (https://www.dspractice.com) uses the jupyterlite web pages hosted on my github mentioned above. I got the RTC feature to work on my github directly as well as my website. However, the feature doesn't work reliably. 

The cases where it didn't work:
1. Creating multiple rooms didn't work after one room worked. After we created our first room, we created a second one. In the second room, My collaborator and I  couldn't see what each other were typing and on the top right, it said "sharing with 0 peers"
2. Initially, we could use RTC in a newly created room, both from my github and from dspractice.com. But then, we tried to use the same room ten minutes later (after creating the second room in point 1. and it didn't work at all. We could not see what each other were typing and on the top right it said "sharing with 0 peers".

Here's how to reproduce the behavior:

## Reproduce

1. Enable the RTC feature following the instructions here (https://jupyterlite.readthedocs.io/en/latest/howto/configure/rtc.html)
2. Create a room number 12345 and add it at the end of the URL like here: https://www.dspractice.com/questions/binaryclass?content=problem&room=12345
3. The real time collaboration feature works.
4. Create another room like this: https://www.dspractice.com/questions/metrics?content=problem&room=97dd421f-3cf8-4ce5-a9a3-6de3a25e46ba
5. The real time feature doesn't work anymore in the second room created in Step 4. 
6. Go back to the first room that worked, which was created in Step 2.
7. The originally working first room doesn't work again either.  

## Expected behavior
The second room `97dd421f-3cf8-4ce5-a9a3-6de3a25e46ba` should work like the first room `12345` worked. And the first room `12345` should work again when we went back to it.
![Screen Shot 2023-04-12 at 7 11 34 PM](https://user-images.githubusercontent.com/8352119/231654117-e841512f-9821-49bc-b46c-cea213a1fc83.png)

## Context

- JupyterLite version: 0.1.0-beta.15
- Operating System and version: macOS Big Sur Version 11.7 
- Browser and version: Chrome Version 112.0.5615.49 (Official Build) (x86_64)

<details><summary>Browser Output</summary>
<pre>
recognized feature: 'web-share'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
 Unsatisfied version 1.34.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/widgets (required ^1.37.2)
u @ gitskim.github.io/ex…8cdb1093cc4e2f.js:1
 Unsatisfied version 6.0.4 of shared singleton module @jupyter-widgets/base (required ^1.0.4 || ^2 || ^3 || ^4)
l @ gitskim.github.io/ex…dcbfb677ea36fb.js:1
 Plugin '@jupyterlab/drawio-extension:plugin' failed to activate.
(anonymous) @ gitskim.github.io/bu…d/6731.c807ff1.js:2
 Error: No provider for: @jupyterlab/application:ILayoutRestorer.
    at e.resolveRequiredService (gitskim.github.io/build/6731.c807ff1.js:2:2045)
    at gitskim.github.io/build/6731.c807ff1.js:2:1436
    at Array.map (<anonymous>)
    at e.activatePlugin (gitskim.github.io/build/6731.c807ff1.js:2:1410)
    at gitskim.github.io/build/6731.c807ff1.js:2:2729
    at Array.map (<anonymous>)
    at e.start (gitskim.github.io/build/6731.c807ff1.js:2:2703)
    at l (gitskim.github.io/build/2738.92eb0cb.js:1:4655)
(anonymous) @ gitskim.github.io/bu…d/6731.c807ff1.js:2
 Using default public WebRTC signaling servers: not recommended for production.
get signalingUrls @ gitskim.github.io/ex…b092f123028dfb417:1
 WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed: 
s @ gitskim.github.io/ex…74f380b4cef5cfd00:2
 WebSocket connection to 'wss://signaling.yjs.dev/' failed: 
s @ gitskim.github.io/ex…74f380b4cef5cfd00:2
 WebSocket connection to 'wss://y-webrtc-signaling-eu.herokuapp.com/' failed: 
s @ gitskim.github.io/ex…74f380b4cef5cfd00:2
 WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed: 
s @ gitskim.github.io/ex…74f380b4cef5cfd00:2
 WebSocket connection to 'wss://signaling.yjs.dev/' failed: 
s @ gitskim.github.io/ex…74f380b4cef5cfd00:2
 WebSocket connection to 'wss://y-webrtc-signaling-eu.herokuapp.com/' failed: 
s @ gitskim.github.io/ex…74f380b4cef5cfd00:2
 Settings failed to load for (@jupyterlab/csvviewer-extension:csv) Array(1)
(anonymous) @ gitskim.github.io/bu…d/4030.1244c7d.js:1
 This may happen if {autoStart: false} in (@jupyterlab/csvviewer-extension:csv) or if it is one of the deferredExtensions in page config.
(anonymous) @ gitskim.github.io/bu…d/4030.1244c7d.js:1
 Settings failed to load for (@jupyterlab/csvviewer-extension:tsv) Array(1)
(anonymous) @ gitskim.github.io/bu…d/4030.1244c7d.js:1
 This may happen if {autoStart: false} in (@jupyterlab/csvviewer-extension:tsv) or if it is one of the deferredExtensions in page config.
(anonymous) @ gitskim.github.io/bu…d/4030.1244c7d.js:1
 Settings failed to load for (@jupyterlab/filebrowser-extension:widget) Array(1)
(anonymous) @ gitskim.github.io/bu…d/4030.1244c7d.js:1
 This may happen if {autoStart: false} in (@jupyterlab/filebrowser-extension:widget) or if it is one of the deferredExtensions in page config.
(anonymous) @ gitskim.github.io/bu…d/4030.1244c7d.js:1
 Settings failed to load for (@jupyterlab/fileeditor-extension:plugin) Array(1)
(anonymous) @ gitskim.github.io/bu…d/4030.1244c7d.js:1
 This may happen if {autoStart: false} in (@jupyterlab/fileeditor-extension:plugin) or if it is one of the deferredExtensions in page config.
(anonymous) @ gitskim.github.io/bu…d/4030.1244c7d.js:1
 Settings failed to load for (@jupyterlab/htmlviewer-extension:plugin) Array(1)
(anonymous) @ gitskim.github.io/bu…d/4030.1244c7d.js:1
 This may happen if {autoStart: false} in (@jupyterlab/htmlviewer-extension:plugin) or if it is one of the deferredExtensions in page config.
(anonymous) @ gitskim.github.io/bu…d/4030.1244c7d.js:1
 No exact match found for python, using kernel python that matches language=python
e.getDefaultKernel @ gitskim.github.io/bu…d/4170.b6fe75c.js:2
 WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed: 
s @ gitskim.github.io/ex…74f380b4cef5cfd00:2
 WebSocket connection to 'wss://signaling.yjs.dev/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 WebSocket connection to 'wss://y-webrtc-signaling-eu.herokuapp.com/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 WebSocket connection to 'wss://signaling.yjs.dev/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 WebSocket connection to 'wss://y-webrtc-signaling-eu.herokuapp.com/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
pyodide.asm.js:10 Loading distutils
 WebSocket connection to 'wss://signaling.yjs.dev/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 WebSocket connection to 'wss://y-webrtc-signaling-eu.herokuapp.com/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
pyodide.asm.js:10 Loaded distutils
pyodide.asm.js:10 Python initialization complete
pyodide.asm.js:10 distutils already loaded from default channel
pyodide.asm.js:10 Loading micropip, pyparsing, packaging
pyodide.asm.js:10 Loaded pyparsing, packaging, micropip
 TypeError: Cannot read properties of undefined (reading 'model')
    at gitskim.github.io/build/724.e8a987f.js:1:14589
    at b (gitskim.github.io/build/5614.4272b09.js:1:9633)
    at gitskim.github.io/build/724.e8a987f.js:1:14568
    at m.e [as expandParent] (gitskim.github.io/build/724.e8a987f.js:1:14817)
    at gitskim.github.io/build/2364.1e6fd2c.js:1:7736
    at l (gitskim.github.io/build/409.35f299f.js:1:2277)
    at n.emit (gitskim.github.io/build/409.35f299f.js:1:1988)
    at n.emit (gitskim.github.io/build/409.35f299f.js:1:386)
    at set activeCellIndex [as activeCellIndex] (gitskim.github.io/build/724.e8a987f.js:1:61334)
    at te.onCellRemoved (gitskim.github.io/build/724.e8a987f.js:1:67574)
n.exceptionHandler @ gitskim.github.io/build/409.35f299f.js:1
 TypeError: Cannot read properties of null (reading 'contentChanged')
    at d._removeToolbar (gitskim.github.io/build/7386.8fa1a12.js:1:2032)
    at d._onActiveCellChanged (gitskim.github.io/build/7386.8fa1a12.js:1:852)
    at l (gitskim.github.io/build/409.35f299f.js:1:2277)
    at n.emit (gitskim.github.io/build/409.35f299f.js:1:1988)
    at n.emit (gitskim.github.io/build/409.35f299f.js:1:386)
    at set activeCellIndex [as activeCellIndex] (gitskim.github.io/build/724.e8a987f.js:1:61334)
    at te.onCellInserted (gitskim.github.io/build/724.e8a987f.js:1:67324)
    at te._insertCell (gitskim.github.io/build/724.e8a987f.js:1:54585)
    at gitskim.github.io/build/724.e8a987f.js:1:53472
    at f (gitskim.github.io/build/5614.4272b09.js:1:390)
n.exceptionHandler @ gitskim.github.io/build/409.35f299f.js:1
 WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
pyodide.asm.js:10 distutils already loaded from default channel
pyodide.asm.js:10 packaging already loaded from default channel
pyodide.asm.js:10 pyparsing already loaded from default channel
pyodide.asm.js:10 Loading matplotlib, cycler, six, fonttools, kiwisolver, numpy, pillow, python-dateutil, pytz
 WebSocket connection to 'wss://signaling.yjs.dev/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 WebSocket connection to 'wss://y-webrtc-signaling-eu.herokuapp.com/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 WebSocket connection to 'wss://signaling.yjs.dev/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 WebSocket connection to 'wss://y-webrtc-signaling-eu.herokuapp.com/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: Control comm did not respond in time
_loadFromKernel @ gitskim.github.io/ex…d6a3a0542a41bec5a:1
pyodide.asm.js:10 Loaded six, cycler, fonttools, python-dateutil, pytz, kiwisolver, pillow, numpy, matplotlib
 WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
pyodide.asm.js:10 Loading decorator, jedi, parso, pygments
 WebSocket connection to 'wss://signaling.yjs.dev/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 WebSocket connection to 'wss://y-webrtc-signaling-eu.herokuapp.com/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 WebSocket connection to 'wss://signaling.yjs.dev/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 WebSocket connection to 'wss://y-webrtc-signaling-eu.herokuapp.com/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
pyodide.asm.js:10 Loaded decorator, parso, jedi, pygments
 WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 WebSocket connection to 'wss://signaling.yjs.dev/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 WebSocket connection to 'wss://y-webrtc-signaling-eu.herokuapp.com/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 WebSocket connection to 'wss://signaling.yjs.dev/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 WebSocket connection to 'wss://y-webrtc-signaling-eu.herokuapp.com/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1
 WebSocket connection to 'wss://y-webrtc-signaling-us.herokuapp.com/' failed
m @ gitskim.github.io/bu…d/9334.d61a1e4.js:1

</pre>
</details>
Thank you for your time!

**Comment by jtpio** [comment]
Thanks @gitskim for reporting and providing the details.

Currently support for RTC is still experimental in JupyterLite and implemented in a separate repo: https://github.com/jupyterlite/jupyterlab-webrtc-docprovider.

Hopefully https://github.com/jupyterlite/jupyterlite/pull/1019 and https://github.com/jupyterlite/jupyterlab-webrtc-docprovider/pull/17 will help improve the situation. And make it for a the `0.2.0` release of JupyterLite.

In the meantime there could also be a warning in the docs to mention RTC is still experimental.

**Comment by theonewolf** [comment]
@jtpio + @gitskim doesn't RTC require a (or multiple) signaling servers?  I found that the public default ones in the mentioned package are more often then not (and maybe permanently?) offline.

I don't think one can rely on out of the box default signaling servers.  You need to setup your own signaling server to be safe.

**Comment by jtpio** [comment]
Right. I believe the signaling servers were hosted on Heroku before. Maybe the change of policy w.r.t free instances brought them down?

The server is available here: https://github.com/yjs/y-webrtc/blob/master/bin/server.js. And should be simple to run normally.

**Comment by jtpio** [comment]
Looks like the default server was updated in https://github.com/yjs/y-webrtc/issues/43. So maybe it's just a matter of updating to the latest `y-webrtc` to pick up the change.

Or configure the list to include `wss://y-webrtc-eu.fly.dev`.

**Comment by theonewolf** [comment]
@jtpio yeah I’ve been running my own server fine for the past week.

Nice find on the freely hosted one, but I’d still be careful relying on free servers that could technically go away at any moment.  Definitely very good for testing and quick prototyping though!

**Comment by jtpio** [comment]
Agree. The default public server is fine for the demo site.

Normally the extension should allow for configuring the signaling servers: https://github.com/jupyterlite/jupyterlab-webrtc-docprovider#client-configuration

**Comment by jtpio** [comment]
Hey folks,

The previous docs about RTC were not very helpful since it was not working with the most recent versions of JupyterLite.

So https://github.com/jupyterlite/jupyterlite/pull/1536 cleaned that up.

If you are looking for RTC support, there is a reboot happening in https://github.com/davidbrochart/jupyter-shared-drive, which is still early but may be the most promising option at the moment.
