### ISSUE TITLE
 It dosen't run the code when I try to launch it, I'm using it to learn ML from corsera and it comes as the default IDE to work with, I'm obliged to take the files to Google colab and run them 

### ISSUE THREAD

**Issue by RedhaZid35** [jupyterlite/jupyterlite#1053]
## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- JupyterLite version:
- Operating System and version:
- Browser and version:

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by RedhaZid35** [comment]
It dosen't tun the code when i try to launch it, I'm using it to leanrn ML from corsera and it comes as the default IDE to work with, I'm obliged to take the files to Google colab and run them

**Comment by jtpio** [comment]
@RedhaZid35 could you describe more in details what your workflow is and how you end up using JupyterLite?

Are you using a public facing JupyterLite demo site such as https://jupyter.org/try-jupyter or https://jupyterlite.github.io/demo ?

**Comment by jtpio** [comment]
Closing as answered, feel free to open a new issue or question in https://github.com/jupyterlite/jupyterlite/discussions if needed. Thanks!
