### ISSUE TITLE
pip install tensorflow-hub

### ISSUE THREAD

**Issue by HanXiao1000** [jupyterlite/jupyterlite#1065]

**Comment by jtpio** [comment]
@HanXiao1000 would it be possible to provide more context to the issue?

It looks like you were trying to use Tensorflow in JupyterLite? I think this is very likely not possible at the moment.

**Comment by HanXiao1000** [comment]
Could it be made possible

**Comment by jtpio** [comment]
Maybe. Although it's probably more of something to investigate on the Python kernels like https://github.com/jupyterlite/pyodide-kernel and https://github.com/jupyterlite/xeus-python-kernel than JupyterLite.

If someone would like to have a look at this that would be great!

**Comment by jtpio** [comment]
Closing as this is unlikely to be fixed in this repo.

Instead it may be worth looking into what can be done in:
- https://github.com/pyodide/pyodide
- https://github.com/emscripten-forge/recipes
