### ISSUE TITLE
Cells not running in safari

### ISSUE THREAD

**Issue by vegardjervell** [jupyterlite/jupyterlite#1073]
## Description

When clicking `run`, the cells do not execute/show output in safari. Other safari users have confirmed the same behaviour. Notebook works as expected in Chrome.

## Reproduce

1. Open safari (version : 15.6.1)
2. Go to ['https://jupyter.org/try-jupyter/lab/'](https://jupyter.org/try-jupyter/lab/)
3. Type `print('Heyho')` in the first cell.
4. Click on 'run'

## Expected behavior

Output is displayed below the cell.

## Context

- JupyterLite version: 
- Operating System and version: macOS 12.5.1 (Monterey)
- Browser and version: Safari 15.6.1

**Comment by jtpio** [comment]
Thanks @vegardjervell for reporting.

This looks similar to https://github.com/jupyterlite/jupyterlite/issues/944. Would you be able to check the dev tools console to see if this is the same error message?

**Comment by vegardjervell** [comment]
Yes, this looks like the same issue, screenshot of console is attached

![Screenshot 2023-05-04 at 15 57 25](https://user-images.githubusercontent.com/32457474/236230111-8bd2235a-68e0-446c-a342-3d3697a66b7d.png)

**Comment by jtpio** [comment]
Thanks @vegardjervell for checking. 

Let's close in favor of #944?

**Comment by vegardjervell** [comment]
Agreed :)
