### ISSUE TITLE
JupyterLite sometimes crashes in broadcast.ts with a message without path

### ISSUE THREAD

**Issue by andeplane** [jupyterlite/jupyterlite#1074]
## Description

I cannot reproduce this at all times, but it is a problem occurring when JupyterLite is being embedded in an iframe. In short, we are planning to use JupyterLite to embed a notebook at my work. We are embedding the notebook as an iframe inside our webapp. 

This normally works very well, but sometimes the kernel crashes (see attached screenshot) because a message is being sent and picked up in [broadcast.ts](https://github.com/jupyterlite/jupyterlite/blob/main/packages/contents/src/broadcast.ts#L61), sometimes with `event.data = null`, and sometimes an object missing the `path` property. 

Sometimes, I also get `e.data` being [this object](https://github.com/jupyterlite/jupyterlite/blob/main/packages/contents/src/broadcast.ts#L114) which could make sense since we are doing `this._channel.postMessage(response);` [here](https://github.com/jupyterlite/jupyterlite/blob/main/packages/contents/src/broadcast.ts#LL157C5-L157C41).

<img width="1920" alt="Screenshot 2023-05-09 at 10 17 46" src="https://user-images.githubusercontent.com/16174/237039913-9a530154-d468-464a-b192-c4871623a80f.png">

<img width="1496" alt="Screenshot 2023-05-09 at 10 50 49" src="https://user-images.githubusercontent.com/16174/237045371-10f3866e-4c1d-4725-ae1d-675be487f481.png">

I have also gotten this problem with JupyterLite with no modifications, but it only happens inside an iframe, and not always (but when it happens, I can reproduce it 100% until it suddenly works again).

## Reproduce
I don't know a stable way to do it, but have JupyterLite embedded in an iframe is the only way I know, and it mostly works. No code change happens when it suddenly doesn't work anymore. This happens if I embed https://jupyterlite.readthedocs.io/en/latest/_static/lab/?path=intro.ipynb into the iframe as well.

## Expected behavior

JupyterLite kernel should not crash, but it sometimes does.

## Context

- JupyterLite version: latest as of today.
- Operating System and version: MacOS 13.0
- Browser and version: Chrome 113

So a couple of questions:
1) This is not deterministic, how can I even debug this?
2) Why is this only happening in an iframe?
3) Can a workaround be to ignore events without `path` in the `e.data` [here](https://github.com/jupyterlite/jupyterlite/blob/main/packages/contents/src/broadcast.ts#L57)?
4) Why is this happening?

**Comment by andeplane** [comment]
It seems to me like it should always fail, since the `response` object is being broadcasted [here](https://github.com/jupyterlite/jupyterlite/blob/main/packages/contents/src/broadcast.ts#LL157C5-L157C41), so all of these messages _should_ be received in the same function, but it is most likely me not understanding this :D

**Comment by sebreb** [comment]
I had the same problem. I disabled the service-worker extension in `jupyter-lite.json` and the error disappeared.

```
...
  "disabledExtensions": ["@jupyterlite/server-extension:service-worker"]
...
```

**Comment by andeplane** [comment]
But the service worker is [quite important](https://jupyterlite.readthedocs.io/en/latest/howto/configure/advanced/service-worker.html). It does the syncing of files between browser storage and the kernel and other nice things, so I probably don't want to disable that?

**Comment by jtpio** [comment]
@andeplane maybe this can be closed as fixed by https://github.com/jupyterlite/jupyterlite/pull/1075?

**Comment by andeplane** [comment]
Whops sorry, yes. Did not see your comment.
