### ISSUE TITLE
[Question] How does JupyterLite get matplotlib's plot outputs from Pyodide?

### ISSUE THREAD

**Issue by xiasongh** [jupyterlite/jupyterlite#1097]
Sorry in advance if this is not the right place to ask.

I want to write a program where a user can write some Python code in the browser and see the output of their code. Basically a very minimal version of JupyterLite.

So far, I was able to figure out how to get the stdout from Pyodide and display it, but I'm unsure of how to do it with matplotlib's plots, atleast in a "transparent" way. I've taken a look at [this stackoverflow post](https://stackoverflow.com/questions/56583696/how-to-redirect-render-pyodide-output-in-browser) and [this blog post](https://karay.me/2022/07/12/bringing-python-to-the-web.html). With these, I can see how you can display the plots, but it requires extra code on the user's end. I'd like to do it in a way where the user can just do `plt.show()`.

Clearly, JupyterLite is able to do this, but I'm not able to figure out how. Does it monkey patch the `plt.show()` function somehow? Any help or references to the code would be appreciated. Thanks!

**Comment by jtpio** [comment]
> Does it monkey patch the `plt.show()` function somehow?

It used to. But with #911 it basically tells the kernel (where `matplotlib` runs) to send a Jupyter message to display the plot via the inline backend. This means the frontend receives a message that it should display an image. 

For example when displaying a `matplotlib` plot with the demo instance available on https://jupyterlite.rtfd.io/en/latest/try/lab, we see there is a `display_data` message sent to the frontend with the encoded image to display:

![image](https://github.com/jupyterlite/jupyterlite/assets/591645/4cecb0cd-cc53-497a-9173-9af5c3a340f7)

Handling messages and display content is implemented in a JupyterLab component which JupyterLite reuses out of the box.

If you're looking into building a more minimal JupyterLite, one way would be to reuse some of the existing JupyterLab components like a code cell and the output area. Something like the existing REPL application: https://jupyterlite.readthedocs.io/en/latest/quickstart/embed-repl.html

**Comment by jtpio** [comment]
Closing as answered.

Feel free to open a new issue or discussion in https://github.com/jupyterlite/jupyterlite/discussions if needed, thanks!
