### ISSUE TITLE
Support specifying extra paths to look for federated extensions

### ISSUE THREAD

**Issue by tomjakubowski** [jupyterlite/jupyterlite#1101]
### Problem

I'm supporting a Bazel build of a Jupyterlite site. In Bazel, a wheel's package data is unpacked somewhere other than sys.prefix, and Jupyterlite searches only within sys.prefix for federated extensions. So in our Bazel build, the site wouldn't include any federated extensions from the other Python packages installed in the build's environment (e.g. jupyterlite-pyodide-kernel).

To fix it, I ended up monkeypatching FederatedExtensionsAddon.pre_build: https://github.com/jupyterlite/jupyterlite/blob/main/py/jupyterlite-core/jupyterlite_core/addons/federated_extensions.py#L61-L70

to search the locations where Bazel installed each extension's package data.

### Proposed Solution

Jupyterlite could implement this command line option from Jupyter Lab:

```
--LabServerApp.extra_labextensions_path=<list-item-1>...
    Extra paths to look for federated JupyterLab extensions
    Default: []
```

Then we could pass those paths to `jupyter lite build`

### Additional context

There's a TODO in the source related to this https://github.com/jupyterlite/jupyterlite/blob/main/py/jupyterlite-core/jupyterlite_core/addons/federated_extensions.py#L21-L22

**Comment by jtpio** [comment]
Closing as this was fixed by #1019 and is available in version `0.2.0` (currently in alpha): 

https://github.com/jupyterlite/jupyterlite/blob/1b723ba310c7956d1b17608647d7248d2f81dfca/py/jupyterlite-core/jupyterlite_core/addons/federated_extensions.py#L31-L33
