### ISSUE TITLE
Aggressive caching by the service worker

### ISSUE THREAD

**Issue by stevejpurves** [jupyterlite/jupyterlite#1103]
# Context

It seems like the Jupyterlite service worker aggressively caches all get requests, which can cause problems when jupyterlite-core assets are used in a different web contexts. The web context I'm looking at in particular is mystmd websites, and other sites that use the `thebe` library.

from [the code here](https://github.com/jupyterlite/jupyterlite/blob/f98c5c0f90f25466aea6beeb4f2bd2ce8549aa68/packages/server/src/service-worker.ts#L111) like the SW will cache all GET requests, on http[s] that does not have the `/api/' in its path.

```
/**
 * Whether the fallback behavior should be used
 */
function shouldDrop(request: Request, url: URL): boolean {
  return (
    request.method !== 'GET' ||
    url.origin.match(/^http/) === null ||
    url.pathname.includes('/api/')
  );
}
```

This causes a few issues for our usage in mystmd, namely:

* the interactive editing experience for authors needs hard refreshes to get content at times
* we get issues when we update styles, and styles are sometimes not applied correctly.
* Deployed websites created by mystmd user can end up being agreessiely cached and their content, styling or js assets don;t update without a hard reload or unregistering of the service worker.

We're looking at how to improve this situation while keeping the service worker in place to support the file system functionality.

# Questions

* are there any options or configuration available to us that would allow us to disable caching, while maintaining the message passing features needed for filesystem?
* [abit of an aside but out off interest...] is the caching behaviour of the service worker essential to the operation of the filesystem, or is it just enabled as a nice to have?
* could the service worker responsibilities be split into two service workers? one looking after the filesystem broadcast channel and a second providing the caching, with an option to disable the caching?
* from tests so far it seems like setting `"disabledExtensions": ["@jupyterlite/server-extension:service-worker"]` has no effect and the service worker still installs and activates, this was set both programmatically and on page as per [the example here](https://jupyterlite.readthedocs.io/en/latest/howto/configure/advanced/extensions.html#disabling-extensions-at-runtime) - is disabling still possible?

**Comment by jtpio** [comment]
Thanks @stevejpurves for opening the issue :+1: 

Right, the service worker has been causing a couple of issues related to caching.

Agree it would be useful to provide options or way to disable some of its features. Maybe as page config options, or by splitting functionality into separate plugins so they can be disabled.

> * from tests so far it seems like setting `"disabledExtensions": ["@jupyterlite/server-extension:service-worker"]` has no effect and the service worker still installs and activates, this was set both programmatically and on page as per [the example here](https://jupyterlite.readthedocs.io/en/latest/howto/configure/advanced/extensions.html#disabling-extensions-at-runtime) - is disabling still possible?

This is surprising and is indeed not the intended behavior. Would need to double check the plugin logic and name but normally it should indeed be possible to disable it.

**Comment by stevejpurves** [comment]
@jtpio yes, it's continuing to be an issue.

I'll attempt again to disable it and if not try to reproduce it. I think we are at the point of wanting to provide a custom SW for lite for our deployments and being able to disable the default one would allow for that.

**Comment by jtpio** [comment]
> Agree it would be useful to provide options or way to disable some of its features. Maybe as page config options, or by splitting functionality into separate plugins so they can be disabled.

Looking into this in https://github.com/jupyterlite/jupyterlite/pull/1316
