### ISSUE TITLE
Cannot read properties of undefined (reading 'PyProxy')

### ISSUE THREAD

**Issue by dhchenx** [jupyterlite/jupyterlite#1114]
Hi, 

   I created Jupyter Lite websites in my server. Then, I visit the site by using the server's IP+Port to get the jupyter lite working in browsers. 

   I used the following commands at first to create the jupyter lite webiste: 

```bash
jupyter lite init
jupyter lite build --pyodide https://github.com/pyodide/pyodide/releases/download/0.22.1/pyodide-0.22.1.tar.bz2
jupyterlite serve
```

After the browser loaded all resources and js and the jupyter UI displayed, I tried to run some python codes in `.ipynb` and failed. I checked the console output of the browser and it raised an exception like below:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'PyProxy')
    at Va.formatResult (worker.js:22:853)
    at Va.commOpen (worker.js:22:3327)
kernels.ts:68  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'PyProxy')
    at Va.formatResult (worker.js:22:853)
    at Va.commMsg (worker.js:22:3458)
kernels.ts:68  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'PyProxy')
    at Va.formatResult (worker.js:22:853)
    at Va.execute (worker.js:22:2646)
```

Any idea about how to solve the issue?

**Comment by jtpio** [comment]
> I tried to run some python codes in `.ipynb` and failed. I checked the console output of the browser and it raised an exception like below:

@dhchenx what kind of Python code are you trying to run?

**Comment by jtpio** [comment]
Ah ok, thanks for getting back!
