### ISSUE TITLE
Playback of video tag stops due to caching behavior of Range request

### ISSUE THREAD

**Issue by katotetsuro** [jupyterlite/jupyterlite#1117]
## Description

Jupyterlite caches many requests in the service worker, but when combined with range request created by video tag, the video playback stops.

## Reproduce

1. Go to https://jupyterlite.readthedocs.io/en/latest/_static/lab/
2. upload [video.ipynb](https://gist.github.com/katotetsuro/55cb65b5ff5ef35c1c583342341722a2) or just create markdown cell with
```
<video controls src="https://pub-730e5ff911ca4e468a52624635685d02.r2.dev/movie.mp4" width="640" />
```
note: This video is hosted by me
4. seek to about the middle of the video
5. seek back to the beginning of the video
6. video playback will stop

## Expected behavior

Video can be properly seeked.

## Context

- JupyterLite version: v0.1.1
- Operating System and version: Mac OS Ventura 13.4.1
- Browser and version: Chrome: 114.0.5735.198

I don't have a deep understanding of web browser implementation, but I think the problem is in the cache storage, since the requested `Range` and the response `Range` from the service worker are different.

<img width="1055" alt="image" src="https://github.com/jupyterlite/jupyterlite/assets/364002/b41466c0-cb94-43a5-b0fb-214660bec9b6">

refs
- https://web.dev/sw-range-requests/
- https://developer.chrome.com/docs/workbox/serving-cached-audio-and-video/
- https://github.com/GoogleChrome/workbox/issues/1663#issuecomment-448755945

Honestly, I don't think there is much reason to keep videos cached, so a possible workaround would be to fallback to normal fetch when Range headers are included, like this
(I could make a PR if this approach is approved.)
https://github.com/katotetsuro/jupyterlite/commit/274fca30c77d942c1afd813bcf09e0095554759d

I deployed ↑ version. Seek works on this site.
https://jupyterlite-disable-caching-range-request.pages.dev/app/lab/

Does anyone know of any other workarounds?

**Comment by koenvo** [comment]
If you control the webserver serving you could try to ignore the range request and tell the browser no range support is there. Keep in mind the range requests are sent for a reason and disabling is a workaround

**Comment by katotetsuro** [comment]
The issue has been resolved because the cache strategy for the service worker has changed significantly.
