### ISSUE TITLE
[question] How do I include static resources other than typescript ?

### ISSUE THREAD

**Issue by tanaga9** [jupyterlite/jupyterlite#1129]
I'm sorry.
This question is not directly related to jupyterlite.
But I have no one else to ask. I don't know on my own. Please help me.

i made [jupyterlab-box-drive](https://github.com/tanaga9/jupyterlab-box-drive).
This is a mostly jupyterlite-only extension that provides seamless reading and writing to box.com in your browser.

There are at least two non-typescript static resources.

- BoxSdk.js (by [box-javascript-sdk](https://github.com/box-community/box-javascript-sdk))
- auth.html

How do I include static resources other than typescript ?

- jupyter Community Forum [In extension development, how can I include non-typescript static resources?](https://discourse.jupyter.org/t/in-extension-development-how-can-i-include-non-typescript-static-resources/18136/1)
    - No response for now

This plugin actually works.
You can do a trial run with the following command.

```
docker run --rm -p 8888:8888 python:3.10-alpine /bin/sh -c "
  apk add git rust cargo linux-headers nodejs curl &&
  pip install jupyterlite jupyterlab_server git+https://github.com/tanaga9/jupyterlab-box-drive.git &&
  jupyter lite build &&
  curl https://raw.githubusercontent.com/tanaga9/jupyterlab-box-drive/main/src/auth.html           --output /_output/extensions/jupyterlab-box-drive/static/auth.html &&
  curl https://raw.githubusercontent.com/box-community/box-javascript-sdk/main/build/BoxSdk.min.js --output /_output/extensions/jupyterlab-box-drive/static/BoxSdk.min.js &&
  jupyter lite serve --port=8888 --ip=0.0.0.0"
```

http://localhost:8888/

However, I don't know how to automatically import two static files through "jupyter lite build" etc., so I use two curl commands instead.

**Comment by jtpio** [comment]
Thanks @tanaga9 for sharing, the extension looks cool.

> How do I include static resources other than typescript ?

According to the example command, it looks like you want the files to be placed alongside the extension assets (in `_output/extensions/jupyterlab-box-drive/static`)?

One way could be to use a custom `webpack.config.js` when building the JupyterLab extension and use the webpack asset modules. An example would be the `jupyterlite-pyodide-kernel` extension which ships `.whl` files in the extension:

https://github.com/jupyterlite/pyodide-kernel/blob/main/packages/pyodide-kernel-extension/webpack.config.js

The `CopyWebpackPlugin` might also work: https://webpack.js.org/plugins/copy-webpack-plugin/

**Comment by tanaga9** [comment]
Thanks @jtpio a lot!
i will try it when i have time

**Comment by tanaga9** [comment]
@jtpio 
I tried various things based on the advice I received, but...
I was troubled by the unstable behavior of jlpm for several hours, and finally solved it by giving up and writing the cp command in the build script.
Although I was worried about licensing issues, I decided to include BoxSdk.
(Because it must be included in the wheel anyway)
[48c220b](https://github.com/tanaga9/jupyterlab-box-drive/commit/48c220bd93cb5148b2916f28afb47e48f96ff8d4)

I will try the method using `webpack.config.js` again later.

**Comment by tanaga9** [comment]
By the way, if you know, please let me know. @jtpio 

Since jupyterlite(lab-extention) operates only on the client side, the App Client id and password are visible to the user during Auth.
[auth.html](https://github.com/tanaga9/jupyterlab-box-drive/blob/48c220bd93cb5148b2916f28afb47e48f96ff8d4/src/auth.html#L104C1-L105C1)

For example, is it possible to change the URL that opens during Auth from [../extensions/jupyterlab-box-drive/static/auth.html](https://github.com/tanaga9/jupyterlab-box-drive/blob/48c220bd93cb5148b2916f28afb47e48f96ff8d4/src/index.ts#L58C1-L59C1) to another location (such as foo.cgi) by giving an argument to `jupyter lite build`?


![スクリーンショット_sc_20230903_004322](https://github.com/jupyterlite/jupyterlite/assets/6501421/936c9a9f-2a50-4d65-8ae4-9b5d17e144e9)

**Comment by tanaga9** [comment]
The jupyterlab-box-drive approach is also useful for other Cloud Storage Services.

- Google Drive: [browser-samples/drive/quickstart/index.html](https://github.com/googleworkspace/browser-samples/blob/master/drive/quickstart/index.html)
- OneDrive(SharePoint): [onedrive-explorer-js](https://github.com/OneDrive/onedrive-explorer-js)

However, all have the problem that the id and secret of the OAuth client app are visible to the user.
I'm off topic.

**Comment by tanaga9** [comment]
I got off topic so I made another issue
[issues/1135](https://github.com/jupyterlite/jupyterlite/issues/1135)

I will close this issue as it looks like it will be resolved.
