### ISSUE TITLE
Added file not showing up

### ISSUE THREAD

**Issue by bbunzeck** [jupyterlite/jupyterlite#1131]
## Description

I have made a fresh install of jupyterlite 0.1.2. When I add files pre-building to a "files" directory in the jupyterlab directory, the files from this directory are indeed copied to "_output/files/". However, when accessing jupyterlite (via starting the python http server) in Firefox, the files are not shown in the files tab on the left hand side of the interface. From the documentation, I assumed that this should be the case.

## Reproduce

1. Add files to "files" directory before building.
2. Start a python http server
3. The files do not show up

## Expected behavior

Files should show up.

## Context

- JupyterLite version: 0.1.2
- Operating System and version: macOS Venture 13.4.1
- Browser and version: Firefox 116.0.3

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by jtpio** [comment]
Thanks @bbunzeck.

Yes this is the expected behavior. To properly index files so they are visible in the file browser, the build environment needs the `jupyter-server` dependency.

Would you be able to check if `jupyter-server` is installed, and then re-run the `jupyter lite build` command?

**Comment by bbunzeck** [comment]
Thank you very much, @jtpio! That solved the problem. 💯
