### ISSUE TITLE
[question] Is it possible to change the behavior of extension by giving arguments to `jupyter lite build` ?

### ISSUE THREAD

**Issue by tanaga9** [jupyterlite/jupyterlite#1135]
I made [jupyterlab-box-drive](https://github.com/tanaga9/jupyterlab-box-drive).
This is a mostly jupyterlite-only extension that provides seamless reading and writing to box.com in your browser.

Since jupyterlite(lab-extention) operates only on the client side, the OAuth App Client id and secret are visible to the user during Auth.
[auth.html](https://github.com/tanaga9/jupyterlab-box-drive/blob/48c220bd93cb5148b2916f28afb47e48f96ff8d4/src/auth.html#L104C1-L105C1)

The OAuth App Client secret, which prevents app impersonation, should be invisible to users.

For example, is it possible to change the URL that opens during Auth from [../extensions/jupyterlab-box-drive/static/auth.html](https://github.com/tanaga9/jupyterlab-box-drive/blob/48c220bd93cb5148b2916f28afb47e48f96ff8d4/src/index.ts#L58C1-L59C1) to another location (such as foo.cgi) by giving an argument to `jupyter lite build`?

![スクリーンショット_sc_20230903_004322](https://github.com/jupyterlite/jupyterlite/assets/6501421/936c9a9f-2a50-4d65-8ae4-9b5d17e144e9)

**Comment by bollwyvl** [comment]
A python-based [Addon](https://jupyterlite.readthedocs.io/en/latest/howto/extensions/cli-addons.html) can change the behavior of how things work at different stages. Basically all of the behavior of the core application is implemented as [addons](https://github.com/jupyterlite/jupyterlite/tree/main/py/jupyterlite-core/jupyterlite_core/addons). Short CLI options can be created with `aliases` and `flags`, while all configurable aspects are always accessible with e.g. `--MyAddon.my_setting=foo`

Some in-the-wild addons:
- [pyodide-kernel](https://github.com/jupyterlite/pyodide-kernel/tree/main/jupyterlite_pyodide_kernel/addons)
- [voici](https://github.com/voila-dashboards/voici/blob/1587e7bfa2a87b71be568a20e385dd9d8da6e2ae/voici/addon.py#L18)

> be invisible to users

As long as invisible _doesn't_ mean _secret_, as there is very little way to protect things in a fully-client-side application.

**Comment by jtpio** [comment]
Closing as answered.

Don't hesitate to open a new issue or question in https://github.com/jupyterlite/jupyterlite/discussions if needed, thanks!
