### ISSUE TITLE
JupyterLab 4 / Notebook 7 follow-ups

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#1141]
Tracking follow-ups of https://github.com/jupyterlite/jupyterlite/pull/1019 so they can be fixed before a `0.2.0` final.

Listing them in a single issue, but can be split into multiple if needed.

## Service Worker

Check if the following behavior is still happening:

- [x] ~after opening a bunch of notebooks, the service worker basically dies~
    - `Uncaught (in promise) DOMException: Failed to execute 'put' on 'Cache': Quota exceeded.`
    - at that point, you can't open/save anything anymore, even after reloading the page
      - requires a new (private) browser

-> can be deferred to a separate issue if needed: https://github.com/jupyterlite/jupyterlite/issues/1141#issuecomment-1743072720

## Demo site

- [x] Fix app redirect issues on RTD (and elsewhere?): https://github.com/jupyterlite/jupyterlite/pull/1019#issuecomment-1711733062
  - Might not be an issue anymore? https://github.com/jupyterlite/jupyterlite/pull/1170#issuecomment-1738642971 
- [x] all notebooks are rendering with extra newlines: https://github.com/jupyterlite/jupyterlite/pull/1176
  - this actually breaks notebooks like ipycanvas, where there are long multiline strings
- [x] sometimes saving (maybe just opening?) notebooks creates duplicates in the file browser: https://github.com/jupyterlite/jupyterlite/pull/1178
- [x] altair notebook throws a bunch of deprecation warnings: https://github.com/jupyterlite/jupyterlite/pull/1181
- [x] the `ipyvue` widgets don't have matching kernel/extension packages and appear about 50% broken
  -  but still cost a few mb of downloads on _page load_, plus the 11mb of donwload at kernel start
- [x] leaflet can't find mathjax
  -  this appears to fire pretty early, so breaks more than just mathjax
  - Investigating in https://github.com/jupyterlite/jupyterlite/pull/1184

## Console errors

- [x] mathjax missing fonts for rendered outputs (js notebook)

Fixed in https://github.com/jupyterlab/jupyterlab/pull/15230

```
_static/lab/js/output/chtml/fonts/tex-woff-v2/MathJax_Zero.woff
```

- [ ] cell toolbar appears to be throwing _more_ errors than before

```
celltoolbartracker.js:239 Uncaught TypeError: Cannot read properties of undefined (reading 'node'
```

- toc is throwing errors

```
toc.js:486 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
```  

Upstream issues:

- https://github.com/jupyterlab/jupyterlab/issues/14380
- https://github.com/jupyterlab/jupyterlab/issues/15166

## Notebook favicons

- [x] Requesting favicons give 404s: https://github.com/jupyterlite/jupyterlite/pull/1214

![image](https://github.com/jupyterlite/jupyterlite/assets/591645/91623050-efa8-4711-aa6c-2f6a7fae130e)

Upstream issue:

-  https://github.com/jupyter/notebook/issues/7076

## Build

- [x] #1319
  - See https://github.com/jupyterlite/jupyterlite/pull/1019#pullrequestreview-1613246535 for more info
- [x] #1318

## Repo

- [x] Move prettier config to `package.json`: https://github.com/jupyterlite/jupyterlite/pull/1143
- [x] https://github.com/jupyterlite/jupyterlite/pull/1010

**Comment by jtpio** [comment]
>  * [ ]  Fix app redirect issues on RTD (and elsewhere?): [Update to JupyterLab 4 and Notebook 7 #1019 (comment)](https://github.com/jupyterlite/jupyterlite/pull/1019#issuecomment-1711733062)

So testing `0.2.0a0` on a test GitHub Pages deployment seems to be working fine:

https://github.com/jupyterlite/jupyterlite/assets/591645/da225db3-70ee-4939-9547-778b47edb229

So maybe it's just an issue with the ReadTheDocs setup, needs more investigation.

**Comment by bollwyvl** [comment]
yeah, the `/` behavior is very hosting-platform-dependent, but RTD offers so much workflow value over GH pages, it's hard to ignore. 

The most reliable is of course `/index.html`, but not as pretty.

**Comment by jtpio** [comment]
Yes we need to fix it anyway. At the moment not sure what really changed at that level with the update.

**Comment by savakarrohan** [comment]
>  - all notebooks are rendering with extra newlines
>    - this actually breaks notebooks like ipycanvas, where there are long multiline strings

I have been trying to fix this, but the only issue I see is that there are two possible ways of storing the "code" in the `cell.source` Either as a `[ " " ]` (array of strings) or a string.

#### Currently (~4.0.0)
Currently if it is stored as a string:
    - The escape charater `\n` sends code to next line
Currently if stored as an array: 
    - each string in the array is rendered on the next line

This would mean that there is no need for the `\n` escape character when storing as an array.

#### Previously (~3.0.0)
Previously when stored as an array:
    - We would need the escape `\n` to render at a new line.
    
So I think that is why they are being rendered as a separate line.

Other stuff
---
If we upload a file which has `cell.source` as an `[string]` (array of strings) , when saving on the platform it saves as a `string` only
As an array 
![image](https://github.com/jupyterlite/jupyterlite/assets/50200523/1479f5ae-3a8d-4420-96f5-8f2fa85e1b8f)
Becomes
![image](https://github.com/jupyterlite/jupyterlite/assets/50200523/16ab6dd5-7907-4f2b-8aa4-6617a082a4de)

Current workaround for myself
---
My current workaround is I have a script which formats all my files to the array type and remove the trailing `\n`

I searched for anything related to `nbformat`, `codemirror`, `codeeditor` modules in the packages but did not find anything.

**Comment by jtpio** [comment]
Thanks @savakarrohan for investigating!

This is quite odd because the update to JupyterLab 4 in #1019 did not modify the notebooks. And it sounded like this could indeed be related to `nbformat` or the way notebooks are parsed in lab 4.

**Comment by jtpio** [comment]
>  sometimes saving (maybe just opening?) notebooks creates duplicates in the file browser

This is also happening on the `stable` branch of the documentation, which is for JupyterLite 0.1.x using JupyterLab 3.

Investigating a bit more, it might be related to a change in Jupyter Server in how the content is indexed. The JupyterLite contents manager seems to be having issues "merging" the same content when the `path` is different (in this case an additional `./` prefix), which seems to be now be the case according to the content of the `all.json` file:

![image](https://github.com/jupyterlite/jupyterlite/assets/591645/ec2ce31d-ba80-40b5-9029-ab1f3ef6fa38)

In comparison a response from a normal `jupyter_server` returns the following, without the leading `./`:

![image](https://github.com/jupyterlite/jupyterlite/assets/591645/7bf577e9-d064-405b-84d3-432a4cdb7aad)

Looking at an older JupyterLite deployment from June 2023, this extra `./` prefix for the `path` field does not seem to be present, and there is no file duplication issue:

![image](https://github.com/jupyterlite/jupyterlite/assets/591645/1dd5209b-6c65-4621-b349-d07498446e8d)

So this means something likely changed in `jupyter_server`, which affects the indexing in the contents addon:

https://github.com/jupyterlite/jupyterlite/blob/9e4511f8a87a6c5a1af3db8a221506f7c26adb55/py/jupyterlite-core/jupyterlite_core/addons/contents.py#L166

**Comment by jtpio** [comment]
> So this means something likely changed in `jupyter_server`, which affects the indexing in the contents addon:

Digging a bit more, this might be related to https://github.com/jupyterlite/jupyterlite/pull/1116 instead.

**Comment by jtpio** [comment]
@savakarrohan there is a chance the extra newline issue might be fixed by https://github.com/jupyter-server/jupyter_ydoc/pull/186

**Comment by savakarrohan** [comment]
Great, I didn't think about the server stuff, Thank you!

**Comment by jtpio** [comment]
>  after opening a bunch of notebooks, the service worker basically dies

Tried to reproduce this one on the latest demo site but no such error seems to be logged in the dev tools console:

![image](https://github.com/jupyterlite/jupyterlite/assets/591645/4bd9034f-1c74-4e74-8033-ee90dc4ca772)

But we can track it in a separate issue if we want to investigate more, to not block the 0.2.0 release.

**Comment by psychemedia** [comment]
Should the JupyterLite `About` splash display the current JupyterLab version too? (I don't see an obvious way of displaying the JupyterLab version number?)

<img width="411" alt="image" src="https://github.com/jupyterlite/jupyterlite/assets/82988/91c3905f-025a-45e0-b8a2-0368d72e1d9e">

**Comment by jtpio** [comment]
> Should the JupyterLite `About` splash display the current JupyterLab version too? (I don't see an obvious way of displaying the JupyterLab version number?)

Thanks @psychemedia for the suggestion. This could indeed be useful. Just opened https://github.com/jupyterlite/jupyterlite/issues/1317 to track this.

**Comment by jtpio** [comment]
Closing this issue, as the remaining issues and suggestions are now tracked either upstream or in this repo.

Thanks!
