### ISSUE TITLE
service worker named with hash makes it hard to use in downstream.

### ISSUE THREAD

**Issue by trungleduc** [jupyterlite/jupyterlite#1158]
## Description

The service worker file is named at build-time by Webpack and it contains the hash of the file content. For our use case of Voici, we still use the worker provided by Jupyterlite but the worker file name is still computed by the Voici build process. This leads to a mismatch between the file name provided by Webpack and the file provided by Jupyterlite.

## Expected behavior

Can we remove the hash from the worker file name?

## Context

- JupyterLite version:
- Operating System and version:
- Browser and version:

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by martinRenou** [comment]
We've been bit by this in jupyterlite-xeus-python many times. Whenever jupyterlite gets released and the service worker gets a new hash, it does not work anymore with jupyterlite-xeus-python unless we rebuild it and release again. So 💯 for removing it.

**Comment by jtpio** [comment]
Looking at the history, it seems the hash was introduced in https://github.com/jupyterlite/jupyterlite/pull/899.

**Comment by jtpio** [comment]
And this is where the hash gets added by webpack:

https://github.com/jupyterlite/jupyterlite/blob/62b646edffb4e4434ac9f48a967df70477b16b63/app/webpack.config.js#L312-L318

**Comment by trungleduc** [comment]
> And this is where the hash gets added by webpack:
> 
> https://github.com/jupyterlite/jupyterlite/blob/62b646edffb4e4434ac9f48a967df70477b16b63/app/webpack.config.js#L312-L318

I need to add the same thing to our Webpack setup. Without it, the worker manager can not retrieve the worker's name.

**Comment by trungleduc** [comment]
Another solution, we can allow downstream to decide on the worker URL 

https://github.com/jupyterlite/jupyterlite/blob/62b646edffb4e4434ac9f48a967df70477b16b63/packages/server/src/service-manager.ts#L34-L38
