### ISSUE TITLE
Rename the Pyolite kernel

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#116]
Looks like `pyolite` is already a thing on PyPI: https://pypi.org/project/pyolite/

To avoid confusion we can pick a different name for the default Python kernel we ship in: https://github.com/jtpio/jupyterlite/tree/main/packages/pyolite-kernel

**Comment by bollwyvl** [comment]
> @jpio on #129 
>> So now might be a good time to start having a minimal IPython (mostly IPython.display) that would run in jupyterlite.

Indeed! But answering the API mail _exactly_ on #18 will need this anyway for e.g. [`bokeh`](https://github.com/bokeh/bokeh/blob/232c5bef5b4433b1b0ed3c23ca1ca2fd6deedfff/bokeh/io/notebook.py#L337) or freaky-deaky [wrapper kernels](https://github.com/robots-from-jupyter/robotkernel/blob/a2567489fe7d766d72a0982fa398743d89905ad4/src/robotkernel/display.py#L3) that subclass `KernelBase`.

So, offspring-of-pyolite probably needs to not only offer an importable `IPython` and `ipykernel`, but also _distributions_ named `ipython` and `ipykernel` that have version-equivalence with the "real ones" on PyPI.

Further, as the pyodide one is, for the time being, _by far_ the heaviest kernel, it ideally needs to be distributed as its _own_ package(s), that _is/are_ on PyPI, a la #104. So the notional _real_ `{sys.prefix}/share/jupyter` of the building environment after installing these package(s) might be something like:

```
share/jupyter/lite/pyodide/
  ipython-7.24.0-py3-none-any.whl
  ipykernel-5.5.5-py3-none-any.whl
```

...and build up a compatible index similar to how we're doing contents for now.

Starting to get pretty fractal at this point, as these would _also_ be `.whl`s that someone could `micropip.install()`.

cc @carreau

**Comment by Carreau** [comment]
Happy to do changes needed in IPython and reduce the size. I doubt I'll have time myself.

**Comment by bollwyvl** [comment]
@careau No worries! I don't think we'll need any changes upstream, just alerting you that there might be another `whl`-in-a-`whl` of IPython on the horizon that only works in the browser. all the zmq stuff, etc. is basically a non-starter, and we're going to have to fake it. But luckily no windows problems!

**Comment by jtpio** [comment]
As a start we probably don't need the whole `ipython`, but mostly its display the module? And being able to configure or override the `publish_display_data`.

That would indeed also mean having the distributions as well, but those could be recreated by assembling pieces from the upstream ipython.

For `ipykernel`, more modularity would also benefit other projects like `xeus-python`, which [patches](https://github.com/jupyter-xeus/xeus-python/blob/ee5ef6b78ab2be5dcc47d6830af1f2cba5325aef/src/xinterpreter.cpp#L74-L75) the comms.

**Comment by bollwyvl** [comment]
How about `ipylite`? Short, not taken, decent mashup of the two?

**Comment by jtpio** [comment]
> How about `ipylite`? Short, not taken, decent mashup of the two?

Sounds good :+1: 

Just booked it on PyPI: https://pypi.org/project/ipylite

**Comment by jtpio** [comment]
Another option would be to use the "Python (Pyodide)" display name, similar to "Python (ipykernel)" and "Python (XPython)" in regular Jupyter.

And use the `jupyterlite-pyodide-kernel` package name to distribute it once it's moved to a separate repo: https://github.com/jupyterlite/jupyterlite/issues/386

**Comment by echarles** [comment]
> Another option would be to use the "Python (Pyodide)" display name, similar to "Python (ipykernel)" and "Python (XPython)" in regular Jupyter.

Simple and descriptive

+1

> And use the jupyterlite-pyodide-kernel package name to distribute it once it's moved to a separate repo: https://github.com/jupyterlite/jupyterlite/issues/386

Simple and descriptive

+1

`@jupyterlite/pyodide-kernel` would also work.

**Comment by jtpio** [comment]
> Another option would be to use the "Python (Pyodide)" display name, similar to "Python (ipykernel)" and "Python (XPython)" in regular Jupyter.

This was fixed in https://github.com/jupyterlite/jupyterlite/pull/685 and is already available in the latest releases.

> `@jupyterlite/pyodide-kernel` would also work.

Yes that would likely be the name of the underlying JS package :+1:
