### ISSUE TITLE
Dead Link to Try instance

### ISSUE THREAD

**Issue by ShalokShalom** [jupyterlite/jupyterlite#1163]
HI there :)

The link to the test instance of the classical Jupyter Notebook is broken: 

https://github.com/jupyterlite/jupyterlite#-try-it-in-your-browser-

Wonderful project 👍🏻

**Comment by jtpio** [comment]
Thanks @ShalokShalom for reporting :+1: 

https://github.com/jupyterlite/jupyterlite/pull/1164 should fix it.
