### ISSUE TITLE
notebook does not open: e.toolbar.children() is not iterable

### ISSUE THREAD

**Issue by nthiery** [jupyterlite/jupyterlite#1171]
## Description

When adding nbgrader in the build environment, notebooks do not open
anymore in the produced JupyterLite

## Reproduce

1. Clone https://github.com/jupyterlite/xeus-python-demo
2. add nbgrader to build-environment.yml
3. `mamba env create --force -f build-environment.yml`
4. `conda activate build-env`
5. Build jupyterlite `jupyter lite build --contents content --output-dir dist`
6. Launch the produced JupyterLite
7. Open a notebook, or create a notebook

The notebook won't launch; an error message shows up briefly `e.toolbar.children()` is not iterable

I have tried doing some more dichotomy (after 1 hour of earlier dichotomy to get there ...),
but to no effect; so not sure whether it's nbgrader itself or some dependency of it that triggers
the issue.

## Context

- JupyterLite version: 0.1.2
- Operating System and version: Ubuntu 22.04
- Browser and version: firefox or chromium

<details><summary>Browser Output</summary>
<pre>
TypeError: e.toolbar.children() is not iterable
    createNew 545.58791f3a342f5db1f674.js:1
    _initializeWidget widgetmanager.ts:93
    f iter.ts:227
    _initializeWidget widgetmanager.ts:92
    createWidget widgetmanager.ts:74
    _createOrOpenDocument manager.ts:600
    open manager.ts:365
    openOrReveal manager.ts:401
    execute index.tsx:593
    promise callback*execute index.tsx:593
    execute index.ts:437
    execute index.ts:1458
    execute index.ts:1487
    execute index.ts:437
    g index.tsx:397
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
[index.tsx:409:16](webpack://_JUPYTERLAB.CORE_OUTPUT/src/index.tsx)
Showing error: TypeError: e.toolbar.children() is not iterable
    createNew 545.58791f3a342f5db1f674.js:1
    _initializeWidget widgetmanager.ts:93
    f iter.ts:227
    _initializeWidget widgetmanager.ts:92
    createWidget widgetmanager.ts:74
    _createOrOpenDocument manager.ts:600
    open manager.ts:365
    openOrReveal manager.ts:401
    execute index.tsx:593
    promise callback*execute index.tsx:593
    execute index.ts:437
    execute index.ts:1458
    execute index.ts:1487
    execute index.ts:437
    g index.tsx:397
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
[dialog.tsx:43:10](webpack://_JUPYTERLAB.CORE_OUTPUT/src/dialog.tsx)
TypeError: e.value is undefined
    _setValue jsoneditor.ts:331
    set source jsoneditor.ts:134
    _update notebooktools.ts:672
    onActiveCellChanged notebooktools.ts:660
    processMessage notebooktools.ts:348
    c index.ts:530
    e index.ts:220
    _onActiveCellChanged notebooktools.ts:195
    f iter.ts:227
    _onActiveCellChanged notebooktools.ts:194
    u index.ts:679
    emit index.ts:600
    emit index.ts:212
    onCurrentChanged tracker.ts:82
    A widgettracker.ts:143
    u index.ts:679
    emit index.ts:600
    emit index.ts:212
    set current restorablepool.ts:61
    add widgettracker.ts:224
    add tracker.ts:52
    activate index.ts:1356
    u index.ts:679
    emit index.ts:600
    emit index.ts:212
    createNew default.ts:428
    createWidget widgetmanager.ts:73
    _createOrOpenDocument manager.ts:600
    open manager.ts:365
    openOrReveal manager.ts:401
    execute index.tsx:593
    promise callback*execute index.tsx:593
    execute index.ts:437
    execute index.ts:1458
    execute index.ts:1487
    execute index.ts:437
    g index.tsx:397
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
[index.ts:467:12](webpack://_JUPYTERLAB.CORE_OUTPUT/node_modules/@lumino/messaging/src/index.ts)
xeus-python contents will be synced with Jupyter Contents [20.86660aef69b5419d0e11.js:1:2688](http://127.0.0.69:8181/extensions/@jupyterlite/xeus-python-kernel/static/20.86660aef69b5419d0e11.js?v=86660aef69b5419d0e11)
Starting WebSocket: ws://127.0.0.69:8181/api/kernels/2371d77c-fabd-43e4-bcb4-0b33a82e3a65 [default.ts:1251:12](webpack://_JUPYTERLAB.CORE_OUTPUT/src/kernel/default.ts)
Default kernel not found, using 'xeus-python' [validate.ts:73:12](webpack://_JUPYTERLAB.CORE_OUTPUT/src/kernelspec/validate.ts)
GET
http://127.0.0.69:8181/extensions/@jupyterlite/xeus-python-kernel/static/213.f87671ed0b825bd10781.js?v=f87671ed0b825bd10781
[HTTP/1.1 200 OK 0ms]

GET
http://127.0.0.69:8181/extensions/@jupyterlite/xeus-python-kernel/static/xpython_wasm.js
[HTTP/1.1 200 OK 0ms]

XHRGET
http://127.0.0.69:8181/extensions/@jupyterlite/xeus-python-kernel/static/xpython_wasm.wasm
[HTTP/1.1 200 OK 0ms]

Default kernel not found, using 'xeus-python'
</pre>
</details>

**Comment by jtpio** [comment]
> JupyterLite version: 0.1.2

Just a random guess for now, but could it be that the version of `nbgrader` is for JupyterLab 4, while JupyterLite 0.1.x is on JupyterLab 3?

Would you be able to try with `jupyterlite==0.2.0a1`?

**Comment by nthiery** [comment]
Ah, yes, an incompatibility with JupyterLab 4 sounds plausible instead. Glad
to see that JupyterLite is on it's way to JupyterLab 4?

pip was complaining with versions mismatches with just jupyterlite

So I tried with:
```
name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - nbgrader
  - pip
  - pip:
#    - jupyterlite==0.2.0a1
    - jupyterlite-xeus-python==1.0.0a0
```
Which uses jupyterlite-core==0.2.0a2.

Build went fine, but I got a blank screen, with this in the console:
```
Request for font "Nimbus Roman No9 L" blocked at visibility level 2 (requires 3)
[127.0.0.80:8181](http://127.0.0.80:8181/)
Uncaught TypeError: config.appUrl is undefined
    main http://127.0.0.80:8181/config-utils.js:251
[config-utils.js:251:5](http://127.0.0.80:8181/config-utils.js)
```

**Comment by jtpio** [comment]
> pip was complaining with versions mismatches with just jupyterlite

Ah yes I meant `jupyterlite-core==0.2.0a1` (or newer). Yes There will soon be a `0.2.0` release with support for JupyterLab 4 and Notebook 7: https://github.com/jupyterlite/jupyterlite/issues/1038

> Build went fine, but I got a blank screen, with this in the console:

And adding `/lab` (or `/tree`) to the end of the URL? I think this is an issue in the recent `0.2.0ax` that should be fixed.

**Comment by jtpio** [comment]
@nthiery if you would like to try the latest `0.2.0a3`: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.2.0a3

**Comment by nthiery** [comment]
Working smoothly! Without need to add /lab or /tree.

**Comment by jtpio** [comment]
Nice thanks for checking!

**Comment by nthiery** [comment]
Thanks for the debugging :-) Looking forward 0.2.0!
