### ISSUE TITLE
'input()' fonksiyonu düzgün çalışmıyor !!!

### ISSUE THREAD

**Issue by Daktollo1** [jupyterlite/jupyterlite#1172]
print("Yapmak istediğiniz işlemi seçin:")
print("1. Toplama")
print("2. Çıkarma")
print("3. Çarpma")
print("4. Bölme")
print("5. kalan")

secim = input("yapacağınız islemi seçiniz 1/2/3/4/5 :")

sayi1 = input("ilk sayınızı giriniz :")
sayi2 = input("ikinci sayınızı giriniz :")

if secim == "1" :
    print("toplama sonucu: ",sayi1 + sayi2)

elif secim == "2" :
    print("çıkarma sonucu: ",sayi1 - sayi2)

elif secim == "3":
    print("çarpma sonucu: ",sayi1 * sayi2)
    
elif secim == "4":
    print("bölme sonucu: ",sayi1 // sayi2)
    
elif secim == "5":
    print("kalan sonucu: ",sayi1 % sayi2)
    

output:

Yapmak istediğiniz işlemi seçin:
1. Toplama
2. Çıkarma
3. Çarpma
4. Bölme
5. kalan
yapacağınız islemi seçiniz 1/2/3/4/5 :
ilk sayınızı giriniz :
ikinci sayınızı giriniz :

!!!Here, a transaction needs to be made with the value received from me, but it is not done!!!

**Comment by martinRenou** [comment]
Same as https://github.com/jupyterlite/jupyterlite/issues/1174. Please don't spam with issues.

**Comment by Daktollo1** [comment]
> #1174 ile aynı . Lütfen sorunlarla spam göndermeyin.

spam değil içerikleri çok farklı okusaydın keşke bi ?

**Comment by Daktollo1** [comment]
> #1174 ile aynı . Lütfen sorunlarla spam göndermeyin.

sadece sorunları toplu bir şekilde gönderdim aslında iyi bir şey yaptım neden gönderilerimi kapattın?

**Comment by martinRenou** [comment]
You three issues make use of input, that needs to be awaited in JupyterLite: `a = await input()`. This is a known limitation of JupyterLite (see https://github.com/jupyterlite/jupyterlite/issues/275) and may be improved in the future.
