### ISSUE TITLE
Neden böyle bir sorun var ???

### ISSUE THREAD

**Issue by Daktollo1** [jupyterlite/jupyterlite#1173]
![Screenshot_1](https://github.com/jupyterlite/jupyterlite/assets/146320099/eafde68f-baec-4a2d-84ed-15ebdae180f7)

!!! Character lengths of the values ​​received via input need to be summed, but it gives an error? !!!

**Comment by martinRenou** [comment]
Same as https://github.com/jupyterlite/jupyterlite/issues/1174. Please don't spam with issues.
