### ISSUE TITLE
!!! Why doesn't 'int'(integer) work here? !!!

### ISSUE THREAD

**Issue by Daktollo1** [jupyterlite/jupyterlite#1174]
![Screenshot_2](https://github.com/jupyterlite/jupyterlite/assets/146320099/767acc1c-caa1-4cad-8afb-edf9105233f4)

**Comment by martinRenou** [comment]
You need to `await` the input call. See https://github.com/jupyterlite/jupyterlite/issues/275. Closing as duplicate.
