### ISSUE TITLE
!!! Kullanıcıdan Giriş Bekleyen Sonsuz Döngünün böyle olmaması lazım neden böyle !!! 

### ISSUE THREAD

**Issue by Daktollo1** [jupyterlite/jupyterlite#1175]
![Screenshot_3](https://github.com/jupyterlite/jupyterlite/assets/146320099/b036c733-f392-4d9d-95cc-602693b9ca57)
![Screenshot_4](https://github.com/jupyterlite/jupyterlite/assets/146320099/f512f163-215a-4f4c-85d1-e8055adb4991)
![Screenshot_5](https://github.com/jupyterlite/jupyterlite/assets/146320099/df2357c6-0012-4727-a25a-baac225b0f4f)

**Comment by martinRenou** [comment]
😒 Please be mindful that maintainers may have many issues to process. And opening 4 issues with the same bug source does not help in any way. Also those are duplicates of https://github.com/jupyterlite/jupyterlite/issues/275. 

You need to await all input calls!
