### ISSUE TITLE
pandas.read_csv("iris.csv") FileNotFound

### ISSUE THREAD

**Issue by mklilley** [jupyterlite/jupyterlite#119]
## Description

Pandas read_csv gave `FileNotFound` error on example file `iris.csv`. I'm hope this is not a silly user error and I'm sorry in advance if it is.

<img width="798" alt="Screenshot 2021-06-01 at 17 02 46" src="https://user-images.githubusercontent.com/7937044/120355480-3d8a8480-c2fb-11eb-900f-2d61f1d3217c.png">

## Reproduce

- Create new notebook in examples folder
- `import pandas as pd`
- `pd.read_csv("iris.csv")`

## Expected behavior

Load and display the content of `iris.csv` on screen

## Context

- Operating System and version:
- MacOS 11.2.3
- MacBook Air (M1, 2020)
- Apple M1 chip
- Browser and version: Brave Version 1.24.84 Chromium: 90.0.4430.93 (Official Build) (arm64)
- JupyterLite version: can't find version number but I did this today (2021/06/01) using JupyterLite for the first time

<details><summary>Browser Output</summary>
<pre>
Dispose worker for kernel 7f928317-a338-41fb-9c00-6c1d041909fd
default.js:1228 Connection lost, reconnecting in 0 seconds.
_reconnect @ default.js:1228
reconnect @ default.js:516
restart @ default.js:487
async function (async)
restart @ default.js:484
restartKernel @ sessioncontext.js:298
restart @ sessioncontext.js:758
async function (async)
restart @ sessioncontext.js:733
onClick @ toolbar.js:343
y.createElement.onMouseDown @ toolbar.js:402
Be @ react-dom.production.min.js:52
Ke @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
xr @ react-dom.production.min.js:100
Cr @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
De @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Lr @ react-dom.production.min.js:105
Zn @ react-dom.production.min.js:75
Jn @ react-dom.production.min.js:74
n.unstable_runWithPriority @ scheduler.production.min.js:18
Bl @ react-dom.production.min.js:122
Me @ react-dom.production.min.js:292
Xn @ react-dom.production.min.js:73
pyodide.asm.js:9 Python initialization complete
pyodide.js:146 Loading matplotlib, cycler, six, kiwisolver, numpy, pillow, pyparsing, python-dateutil, pytz
pyodide.js:196 Loading matplotlib from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/matplotlib.js
pyodide.js:196 Loading cycler from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/cycler.js
pyodide.js:196 Loading six from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/six.js
pyodide.js:196 Loading kiwisolver from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/kiwisolver.js
pyodide.js:196 Loading numpy from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/numpy.js
pyodide.js:196 Loading pillow from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pillow.js
pyodide.js:196 Loading pyparsing from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyparsing.js
pyodide.js:196 Loading python-dateutil from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/python-dateutil.js
pyodide.js:196 Loading pytz from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pytz.js
pyodide.js:252 Loaded matplotlib, cycler, six, kiwisolver, numpy, pillow, pyparsing, python-dateutil, pytz
pyodide.js:146 Loading micropip, pyparsing, packaging
pyodide.js:196 Loading micropip from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/micropip.js
pyodide.js:184 pyparsing already loaded from default channel
pyodide.js:196 Loading packaging from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/packaging.js
pyodide.js:252 Loaded micropip, pyparsing, packaging
8ebb3553-36cc-44b7-9b0c-539a2f402d28:29 Pyolite kernel initialized, version 0.1.0
8ebb3553-36cc-44b7-9b0c-539a2f402d28:63 Inside worker {code: "import pandas as pd"}
pyodide.js:146 Loading pandas, numpy, python-dateutil, pytz
pyodide.js:196 Loading pandas from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pandas.js
pyodide.js:184 numpy already loaded from default channel
pyodide.js:184 python-dateutil already loaded from default channel
pyodide.js:184 pytz already loaded from default channel
pyodide.js:252 Loaded pandas, numpy, python-dateutil, pytz
8ebb3553-36cc-44b7-9b0c-539a2f402d28:63 Inside worker {code: "pd.read_csv("iris.csv")"}code: "pd.read_csv(\"iris.csv\")"__proto__: Object
</pre>
</details>

**Comment by jtpio** [comment]
Thanks @mklilley.

This sounds similar to the discussion in https://github.com/jtpio/jupyterlite/discussions/91.

Although the files show up in the file browser, they are not directly accessible by the kernel. At least not yet. https://github.com/jtpio/jupyterlite/discussions/91 provides some hints, and links to Pyodide on how this could be made possible.

As a workaround, you might want to try something similar as in this comment: https://github.com/jtpio/jupyterlite/discussions/91#discussioncomment-740288

**Comment by mklilley** [comment]
Ah I see. Thanks for replying so quickly and sorry that this is a bit of a duplicate. I did search the issues but actually never noticed the discussion tab. 🤦‍♂️

**Comment by mklilley** [comment]
Hi. Me again 👋.

I was playing around again and thought that if I can't access local files then I'd try pulling in a remote csv file. 

```
import pandas as pd
data = pd.read_csv("https://support.staffbase.com/hc/en-us/article_attachments/360009197031/username.csv")
```

This works on my locally installed python/jupyter but not on jupyter lite. I get the following error
<details>
<pre>
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/lib/python3.8/site-packages/pandas/io/parsers.py", line 430, in _read
    fp_or_buf, _, compression, should_close = get_filepath_or_buffer(
  File "/lib/python3.8/site-packages/pandas/io/common.py", line 172, in get_filepath_or_buffer
    req = urlopen(filepath_or_buffer)
  File "/lib/python3.8/site-packages/pandas/io/common.py", line 141, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/lib/python3.8/urllib/request.py", line 547, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/lib/python3.8/urllib/request.py", line 1390, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
PythonError: Traceback (most recent call last):
  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/lib/python3.8/asyncio/tasks.py", line 282, in __step
    result = coro.throw(exc)
  File "/lib/python3.8/site-packages/pyolite/interpreter.py", line 23, in run
    result = await self.run_complete
  File "/lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/lib/python3.8/site-packages/pyodide/console.py", line 253, in load_packages_and_run
    raise e
  File "/lib/python3.8/site-packages/pyodide/console.py", line 247, in load_packages_and_run
    result = await eval_code_async(
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 419, in eval_code_async
    return await CodeRunner(
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 270, in run_async
    coro = eval(mod, self.globals, self.locals)
  File "<console>", line 1, in <module>
  File "/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/lib/python3.8/site-packages/pandas/io/parsers.py", line 430, in _read
    fp_or_buf, _, compression, should_close = get_filepath_or_buffer(
  File "/lib/python3.8/site-packages/pandas/io/common.py", line 172, in get_filepath_or_buffer
    req = urlopen(filepath_or_buffer)
  File "/lib/python3.8/site-packages/pandas/io/common.py", line 141, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/lib/python3.8/urllib/request.py", line 547, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/lib/python3.8/urllib/request.py", line 1390, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>

    at new_error (https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.js:9:175413)
    at wrap_exception (https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.wasm:wasm-function[297]:0x1a6c94)
    at FutureDoneCallback_call (https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.wasm:wasm-function[379]:0x1aaab3)
    at byn$fpcast-emu$FutureDoneCallback_call (https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.wasm:wasm-function[14420]:0x7a257c)
    at _PyObject_MakeTpCall (https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.wasm:wasm-function[760]:0x1cabed)
    at __static_1198 (https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.wasm:wasm-function[2906]:0x2c54f1)
    at byn$fpcast-emu$__static_1198 (https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.wasm:wasm-function[22640]:0x7bf866)
    at __static_678 (https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.wasm:wasm-function[1621]:0x21220e)
    at byn$fpcast-emu$__static_678 (https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.wasm:wasm-function[22120]:0x7bdce6)
    at PyVectorcall_Call (https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyodide.asm.wasm:wasm-function[763]:0x1cb006)
</pre>
</details>

Is this still part of the same limitation as my first comment, or is it separate?

Thanks again for taking time to make this - it's super cool and can't wait to start using it fully. I'd love to help make it better but it's a bit beyond me at the moment.

**Comment by jtpio** [comment]
Thanks @mklilley for trying it out :+1: 

Looks like it's related to not being able to do raw network request using the Python standard library.

As a workaround, something like the following could do the job maybe?

```python
import pandas as pd
from js import fetch

URL = "https://support.staffbase.com/hc/en-us/article_attachments/360009197031/username.csv"

res = await fetch(URL)
text = await res.text()

filename = 'data.csv'

with open(filename, 'w') as f:
    f.write(text)

data = pd.read_csv(filename, sep=';')
data
```

![image](https://user-images.githubusercontent.com/591645/120774997-1a421e00-c523-11eb-9118-b8e4bda9df86.png)

**Comment by psychemedia** [comment]
@jtpio Is there a way of finding out what the path is to the current notebook? Or what directory it is in?

Eg I'm trying to come up w/ some sort of function to load a CSV directly. At the moment, you need to know the local directory a data file is in as well as the filename:

```
import js
import pandas as pd

from js import fetch
from pathlib import Path

def fetch_local_csv(filename, path, sep=','):
    """Fetch local CSV file."""
    # js.location of the form: blob:http://localhost:8112/8b22b8cd-3626-etc
    location = '/'.join(':'.join(str(js.location).split(':')[1:]).split('/')[:-1])
    url_base = Path(location) / 'files' / path

    res = await fetch(str(url_base / filename))
    text = await res.text()

    with open(filename, 'w') as f:
        f.write(text)

    df = pd.read_csv(filename, sep=sep)
    return df
```

**Comment by jtpio** [comment]
> Is there a way of finding out what the path is to the current notebook? Or what directory it is in?

Not really for now. Also retrieving the current URL might not be easy since the Python kernel is running in a web worker (as a blob inline worker)

**Comment by psychemedia** [comment]
So is `js.location` not reliable then?

**Comment by jtpio** [comment]
I would say not from a web worker.

**Comment by psychemedia** [comment]
@jptio Re: knowing where we are, and  also picking up on https://github.com/jtpio/jupyterlite/issues/110#issuecomment-866412961 (plotly checking where it's running), it may be useful to have a simple docs collection somewhere itemising various bits of generally useful introspection? Eg where am I, what jupyterlite kernel am I running in, etc?

**Comment by jtpio** [comment]
@psychemedia yes it would be useful to have that somewhere.

Either in the docs: https://jupyterlite.readthedocs.io/en/latest/kernels/pyolite.html

Or in the examples directory on the demo site directly.

**Comment by psychemedia** [comment]
Probably a naive question, but how does https://github.com/jupyterlite/jupyterlite/issues/119#issuecomment-854495013 work (fetch file from URL, write it as a csv file, load in csv file), eg in relation to why trying to read a shipped csv file fails?

**Comment by jtpio** [comment]
> in relation to why trying to read a shipped csv file fails

This should also work, but requires hardcoding and using the full URL of the JupyterLite deployment, instead of programmatically retrieving it from `js.location`.

**Comment by psychemedia** [comment]
For an alternative workaround see https://github.com/jupyterlite/jupyterlite/discussions/91#discussioncomment-1135850 in the discussion [Uploading files that can be read by python code in a notebook](https://github.com/jupyterlite/jupyterlite/discussions/91)

Are these workarounds still the best way for loading local files?

**Comment by psychemedia** [comment]
Here's another effectively file not found issue. Using `sqlite3` to create a file seems to work in one one notebook, but the sqlite3 file does not appear in the file listing, nor is it accessible from another notebook?

![image](https://user-images.githubusercontent.com/82988/132315907-0c330aee-b6ca-46dd-9ea5-840d14cafd2a.png)

**Comment by bollwyvl** [comment]
Yes, at present these are separate virtual computers.

**Comment by psychemedia** [comment]
As a temporary workaround, I've popped a couple of utilities for loading data files into pandas here: https://github.com/innovationOUtside/ouseful_jupyterlite_utils

Currently includes:

- load data from url using @jtpio trick in this thread;
- load data in from local storage using @bollwyvl trick in the discussion https://github.com/jupyterlite/jupyterlite/discussions/91
```pyhton
import micropip

package_url = "https://raw.githubusercontent.com/innovationOUtside/ouseful_jupyterlite_utils/main/ouseful_jupyterlite_utils-0.0.1-py3-none-any.whl"

await micropip.install(package_url)

from ouseful_jupyterlite_utils import pandas_utils as pdu

# Load CSV from URL
# Via @jtpio
URL = "https://support.staffbase.com/hc/en-us/article_attachments/360009197031/username.csv"
df = await pdu.read_csv_url(URL, "\t")

# Load CSV from local browser storage
# Via @bollwyvl
df = await pdu.read_csv_local("iris.csv", "\t")
df
```

**Comment by jmshea** [comment]
> Thanks @mklilley for trying it out 👍
> 
> Looks like it's related to not being able to do raw network request using the Python standard library.
> 
> As a workaround, something like the following could do the job maybe?
> 
> ```python
> import pandas as pd
> from js import fetch
> 
> URL = "https://support.staffbase.com/hc/en-us/article_attachments/360009197031/username.csv"
> 
> res = await fetch(URL)
> text = await res.text()
> 
> filename = 'data.csv'
> 
> with open(filename, 'w') as f:
>     f.write(text)
> 
> data = pd.read_csv(filename, sep=';')
> data
> ```
> 
> ![image](https://user-images.githubusercontent.com/591645/120774997-1a421e00-c523-11eb-9118-b8e4bda9df86.png)

For those who find this and are trying to work with a binary file, here is an example of unpickling a file from a URL. The key components are using the Javascript `arrayBuffer` form and then converting it into an equivalent of a Byte array via the `to_py()` method provided by Pyodide:

```
from js import fetch
import pickle

URL = "https://raw.githubusercontent.com/jmshea/digicom-jupyter/main/content/signals.pkl"

res = await fetch(URL)
buffer = await res.arrayBuffer() 

data = pickle.loads(buffer.to_py())
```

**Comment by rth** [comment]
> For those who find this and are trying to work with a binary file, here is an example of unpickling a file from a URL

Since Pyodide 0.19 (included in the latest jupyterlite) there is also the [pyodide.http.pyfetch](https://pyodide.org/en/stable/usage/api/python-api.html#pyodide.http.pyfetch) function aiming to make it a bit easier to work with JS fetch from Python. With it the above example would be,
```py
from pyodide.http import pyfetch
import pickle, numpy

URL = "https://raw.githubusercontent.com/jmshea/digicom-jupyter/main/content/signals.pkl"
res = await pyfetch(URL)
stream = await res.bytes()

data = pickle.loads(stream)
data
```

**Comment by psychemedia** [comment]
I have a function that wraps [@bollwyvl's hack](https://github.com/jupyterlite/jupyterlite/discussions/91#discussioncomment-1137213) for loading local files from storage but I note that every so often it appears to break in the demo site, presumably as a result of updates to the JupyterLite environment?

It would be *really useful* if there was an official (or even an unofficial official) provided and tested function for at least reading in local files shipped as part of a distribution (even better if there was also a complementary write function).

A workaround is to always load files from a URL, but that means you either need a network connection (and one of benefits of JupyterLite is you can work offline one the environment is loaded) or you run your own locally served jupyterlite environment.

Loading files from a served environment via a URL is also hampered by not having a programmatic way of returning the URL (domain and path) of the served jupyterlite environment.

**Comment by rodigu** [comment]
> Thanks @mklilley.
> 
> This sounds similar to the discussion in https://github.com/jtpio/jupyterlite/discussions/91.
> 
> Although the files show up in the file browser, they are not directly accessible by the kernel. At least not yet. https://github.com/jtpio/jupyterlite/discussions/91 provides some hints, and links to Pyodide on how this could be made possible.
> 
> As a workaround, you might want to try something similar as in this comment: https://github.com/jtpio/jupyterlite/discussions/91#discussioncomment-740288

These links seem to be dead. Is there an archive of them?

**Comment by jtpio** [comment]
> These links seem to be dead. Is there an archive of them?

@rodigu this is because the repo has been moved to the `jupyterlite` organization.

I updated the links in the comment above.

**Comment by psychemedia** [comment]
This looks like it will be fixed by https://github.com/jupyterlite/jupyterlite/pull/655

**Comment by bollwyvl** [comment]
The repo was renamed. Try replacing "jtpio" with "jupyterlite"
