### ISSUE TITLE
[0.2.0] Update for removed out-of-band MathJax assets

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlite/jupyterlite#1192]
### Problem

JupyterLab 4 no longer uses `mathjaxUrl`, and pre-bundles the font assets. We still have a fair amount of code hanging around for it, but it won't do anything useful.

### Proposed Solution

- [ ] determine which set of fonts (e.g. in `js/output/chtml/` or `build/`) is _correct_ (see below)
  - > pre-compressed `.woff2` would be preferable, but not supported upstream
- [ ] update code paths to only use the correct font URLs and avoid `404`
- [ ] remove the MathJax addon, CLI flags, etc.
- [ ] remove the `[mathjax]` extra
- [ ] remove `jupyter-server-mathjax` from any development deps
- [ ] remove `mathJaxUrl` from the schemas
- [ ] update the docs
  - [ ] remove most references to mathjax
  - [ ] add to migration guide
    - > I guess if you want a custom mathjax build now, you need a custom labextension)
- [ ] update ui tests
  - [ ] if we do end up changing how anything works in a meaningful way from upstream

### Additional context

While MathJax _works_, we're apparently not handling startup quite right:

| lite | lab `main` |
|--|--|
| ![image](https://github.com/jupyterlite/jupyterlite/assets/45380/11d38fab-c3c3-4180-8bd9-7cc3b33a8c27) | ![image](https://github.com/jupyterlite/jupyterlite/assets/45380/8886a6f2-d784-4d26-9c3f-a0c5f95d4193)

The lab ones pull from `js/output/chtml/`, but this is... pretty weird:

```
http://127.0.0.1:8889/lab/tree/js/output/chtml/fonts/tex-woff-v2/MathJax_Zero.woff
```

As MathJax is... large, we very likely shouldn't keep around a copy for every app.

**Comment by jtpio** [comment]
Thanks @bollwyvl for opening this, makes sense to clean that up :+1:

**Comment by bollwyvl** [comment]
Quick work! I hope to get a chance (perhaps this weekend) to look through the current state of the codebase, again, to see if there are more things we can drop.... nice opportunity at a major release...
