### ISSUE TITLE
Update to JupyterLab 4.0.7

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#1195]
This will help grab the fix from https://github.com/jupyterlab/jupyterlab/pull/15230.

See https://github.com/jupyterlite/jupyterlite/pull/1192 and https://github.com/jupyterlite/jupyterlite/pull/1193 for more context.

- [ ] Update to JupyterLab 4.0.7
- [ ] Check there is no 404 issue
- [ ] Consider adding a UI test to check for 404, and that Mathjax renders correctly.

**Comment by bollwyvl** [comment]
started https://github.com/jupyterlab/jupyterlab/pull/15231, might not be able to finish immediately
