### ISSUE TITLE
Release scripts

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#121]
At the very least, we need some easy way to:

- bump version numbers
- update dependencies

Later we'll also want to publish packages to `npm` as tarballs.

Lab has some tooling in the `buildutils`: https://github.com/jupyterlab/jupyterlab/tree/master/buildutils
Retro also has some in https://github.com/jupyterlab/retrolab/tree/main/buildutils

We could do something similar.

Or have that in Python in `dodo.py`.

**Comment by jtpio** [comment]
There is also https://github.com/jupyter-server/jupyter_releaser

**Comment by jtpio** [comment]
The version should also go to the page config so it shows up in the UI:

![image](https://user-images.githubusercontent.com/591645/120514996-22d51000-c3ce-11eb-8cee-cc5b5f6a34dc.png)

**Comment by jtpio** [comment]
Trying out the Jupyter Releaser on this repo to create the changelog for `v0.1.0a1`.

Looks like the workflow does not work just yet: https://github.com/jtpio/jupyter_releaser/runs/2931307989

**Comment by bollwyvl** [comment]
Hm... i think we'd want the version to live in the "last resort" `jupyter-config-data` in the `/app/index.html` which might be more annoying to update than `jupyter-lite.json`, as we want that to be a deployer-owned file (even if we ship a minimum viable one). If nothing else, I'd see us wanting to put that under an integrity check against "the version" in `package.json`.

**Comment by jtpio** [comment]
In terms of flow, we could probably stick to one version for all JS and Python packages to keep things simple. Instead of versioning the JS packages independently. 

There could then be a `doit` task taking care of the following:

- bump the js packages, for example using the `update-dependency` script from `@jupyterlab/buildutils`
- bump each of the Python packages (`jupyterlite` and `pyolite` for now) with `tbump`
- translate the Python specifier to npm, for example `0.1.0a3` -> `0.1.0-alpha.3`
- ensure integrity and resolutions
