### ISSUE TITLE
Issue when loading settings from federated extensions

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#1213]
## Description

Currently the JupyterLab app is missing a menu entry to open Notebook 7 in a new browser tab.

## Reproduce

On https://jupyterlite.readthedocs.io/en/latest/_static/lab/index.html :

![image](https://github.com/jupyterlite/jupyterlite/assets/591645/639e7961-7d89-4cda-98a2-1a4957df54b8)

## Expected behavior

It should be possible to open Notebook 7 from JupyterLab like with JupyterLite 0.1.x using RetroLab:

![image](https://github.com/jupyterlite/jupyterlite/assets/591645/49350f8f-768b-4c0e-bb21-9f278c06b81b)

But using the existing Notebook 7 extension that adds the following menu entry:

![image](https://github.com/jupyterlite/jupyterlite/assets/591645/6180c087-6e65-4541-a388-29c4a5162a10)

## Context

Follow-up to #1019.

**Comment by jtpio** [comment]
Installing the `notebook` package and running `jupyter lite build` correctly includes `@jupyter-notebook/lab-extension` in `jupyter-lite.json`:

```json
{
  "extension": "./extension",
  "liteExtension": false,
  "load": "static/remoteEntry.749fd42299b69250a475.js",
  "name": "@jupyter-notebook/lab-extension",
  "style": "./style"
}
```

The commands are available in the command palette, but the menu and toolbar items are missing: 

![image](https://github.com/jupyterlite/jupyterlite/assets/591645/b1b29288-371e-497c-96b9-112059e3524e)

So there might be a more general issue of loading settings from a federated extension (to be confirmed).

**Comment by jtpio** [comment]
> So there might be a more general issue of loading settings from a federated extension (to be confirmed).

Looking more into it, there does seem to be a more general issues with toolbar items and menu entries (defined via the settings). This is for example reproducible with https://github.com/jupyterlab/extension-examples/tree/main/toolbar-button.

For now not sure if it's related to a upstream change in JupyterLab 4 w.r.t how the settings are loaded. Next step would be confirm that settings based items and menu entries used to work fine in JupyterLite 0.1.0 built on JupyterLab 3.

**Comment by jtpio** [comment]
Maybe related to https://github.com/jupyterlab/jupyterlab/pull/14195 ?

**Comment by jtpio** [comment]
JupyterLab 4 now seems to be expecting **all** settings to be returned in one call at application startup.

I guess we can work around that in JupyterLite by moving (or just copying) the `schemas` directories to the single `all.json` at `jupyter lite build` (via the federated extensions addon).

Another option would have been to aggregate all the settings from federated extensions at runtime via `PageConfig.getOption('federated_extensions')`. But there is no metadata that lists all the available settings for a federated extension (no `all.json`). So it looks we would need to add a build step anyway.

In the future this might be an issue for deployments setups that would like to load extensions from a CDN or other hosts, since these extensions and their settings would not be known by the application at startup.

**Comment by bollwyvl** [comment]
>  like to load extensions from a CDN

yeah, i wouldn't worry too much about that case until someone shows up with a concrete issue... there are so many cases of extension code constructing URLs from `baseUrl` instead of webpack assets/loaders that a large chunk of extensions wouldn't even work, or would fail in mysterious ways.

**Comment by jtpio** [comment]
This is tracked upstream and would indeed likely require some other changes anyway: https://github.com/jupyterlab/jupyterlab/issues/8866
