### ISSUE TITLE
Is there a way to add a new function to the right-click file context menu?

### ISSUE THREAD

**Issue by JackYinpei** [jupyterlite/jupyterlite#1217]
Hello, I have been using jupyterlite-core recently to deploy Jupyter on my local machine. 

####Now I want to add a new feature where users can right-click on a file and save it to the cloud. 
**right here**
![image](https://github.com/jupyterlite/jupyterlite/assets/49555788/5ca3bb0b-6a57-4aa2-bd51-ae1f5ec94053)

I tried implementing this feature using extensions, but that requires modifying JupyterLab. However, if I modify JupyterLab, how can I combine it with JupyterLite? I haven't seen any articles related to this.

What I really want to know is how to combine JupyterLite with my own modified version of JupyterLab for use.🤣🤣🤣🤣

 Any information you can provide would be appreciated. Thank you in advance.

**Comment by jtpio** [comment]
Closing in favor of this discussion: https://github.com/jupyterlite/jupyterlite/discussions/1218
