### ISSUE TITLE
...

### ISSUE THREAD

**Issue by ghost** [jupyterlite/jupyterlite#1244]

**Comment by jtpio** [comment]
Thanks @terlan4 for reporting.

This seems more of a question to ask on the JupyterLab repository, as JupyterLite is based on JupyterLab.

Would you be able to open the issue on https://github.com/jupyterlab/jupyterlab?

Or even better create a new topic on the Jupyter Discourse? https://discourse.jupyter.org

Thanks!

**Comment by jtpio** [comment]
Closing the issue as there is the same discussion in https://github.com/jupyterlite/jupyterlite/discussions/1245
