### ISSUE TITLE
`build/schemas/all_federated.json` may be missing after rebuild

### ISSUE THREAD

**Issue by felixlen** [jupyterlite/jupyterlite#1268]
## Description

Sometimes the file `build/schemas/all_federated.json` is missing after build. This makes the output unusable for deployment and causes `404` errors, so that jupyterlite is not able to start up in the browser.

I use a mamba environment specified by the following `environment.yml` :
```
name: default

channels:
  - conda-forge

dependencies:
  - jupyterlab
  - jupyterlite-core
  - jupyterlite-xeus-python
  - numpy
  - python
  - scipy
  - sympy
```

Running `jupyter lite build` works fine for the first time. Running `jupyter lite build` for a second time causes the file `build/schemas/all_federated.json` to be missing from the output folder. 

A workaround is to delete both the output folder and `.jupyterlite.doit.db` before building again. Only deleting the output folder is not sufficient.

## Context

- JupyterLite version: 0.2.1
- Operating System and version: OS X
- Browser and version: Chrome

**Comment by jtpio** [comment]
Thanks @felixlen for the report :+1: 

Yes I also noticed that. Will be looking into a fix soon.

**Comment by jtpio** [comment]
cc @DerThorsten this might be the same issue as the one you also faced? (that we discussed on another channel)

**Comment by DerThorsten** [comment]
> cc @DerThorsten this might be the same issue as the one you also faced? (that we discussed on another channel)

yes, for me it worked again if I delete both `_output` and `.jupyterlite.doit.db`

Atm I always use this script to be sure =)
```bash
    
    #  go to deployment dir
    mkdir -p $DEPLOY_DIR
    cd $DEPLOY_DIR
    
    # remove old builds
    rm -rf _output
    rm -rf .jupyterlite.doit.db

    # ensure dir is empty
    if [ "$(ls -A _output)" ]; then
        echo "ERROR: _output is not empty"
        exit 1
    fi
   
    # do the actual build
    jupyter lite build 

    # check if /build/schemas/all_federated.json is in the output
    if [ ! -f _output/build/schemas/all_federated.json ]; then
        echo "ERROR: _output/build/schemas/all_federated.json not found"
        exit 1
    fi
```
