### ISSUE TITLE
JupyterLite "Help" menu incorrect

### ISSUE THREAD

**Issue by KDean-Dolphin** [jupyterlite/jupyterlite#1272]
## Description

The "Help" menu at in the JupiterLite Intro document is missing the "Welcome Tour" and has a duplicate "About Try Jupiter!". See image.

![image](https://github.com/jupyterlite/jupyterlite/assets/9698619/75615e42-ba9c-4925-986b-b34b5b181c1c)

## Reproduce

1. Go to the [JupyterLite Intro](https://jupyter.org/try-jupyter/notebooks/?path=notebooks/Intro.ipynb) page.
2. Click on "Help".

## Expected behavior

Properly constructed "Help" menu.

## Context

- JupyterLite version: 0.2.1
- Operating System and version: macOS Monterey 12.7.2
- Browser and version: Safari 17.1.2 and Chrome 120.0.6099.109

<details><summary>Browser Output</summary>
<pre>
[Warning] Unsatisfied version 2.1.2 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/coreutils (required ^1.11.0) (remoteEntry.960d5d0f875a651e597f.js, line 1)
[Warning] Unsatisfied version 2.1.2 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/signaling (required ^1.10.0) (remoteEntry.960d5d0f875a651e597f.js, line 1)
[Warning] Unsatisfied version 2.0.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/messaging (required ^1.4.3) (remoteEntry.2916befd91bdb8847e88.js, line 1)
[Warning] Unsatisfied version 2.3.0 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/widgets (required ^1.19.0) (remoteEntry.2916befd91bdb8847e88.js, line 1)
[Warning] Unsatisfied version 4.1.7 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/apputils (required ^3.5.1) (remoteEntry.6a37df5d4590b29196a3.js, line 1)
[Warning] Unsatisfied version 6.0.7 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/coreutils (required ^5.6.3) (remoteEntry.74a375733b4162d461a9.js, line 1)
[Warning] Unsatisfied version 4.0.7 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/application (required ^3.6.3) (remoteEntry.74a375733b4162d461a9.js, line 1)
[Warning] Unsatisfied version 2.3.0 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @lumino/widgets (required ^1.37.2) (remoteEntry.70a4f7e7a0383740860d.js, line 1)
[Info] JupyterLite ServiceWorker was already registered (4954.48f4fff.js, line 1)
[Info] Kernel filesystem and JupyterLite contents will be synced (1815.fefcaa0.js, line 1)
[Warning] Menu entry for command 'filemenu:close-and-cleanup' is duplicated. (jlab_core.799ed26.js, line 1)
[Warning] Menu entry for command 'application:close' is duplicated. (jlab_core.799ed26.js, line 1)
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'e.type')
	(anonymous function) (jlab_core.799ed26.js:1:952562)
[Warning] The resource https://jupyter.org/try-jupyter/build/notebooks/bundle.js?_=8620eb7 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it wasn't preloaded for nothing.
[Info] Pyodide contents will be synced with Jupyter Contents (348.04fb8c95700eb24afd0e.js, line 1)
[Debug] Starting WebSocket: wss://jupyter.org/try-jupyter/api/kernels/49bb1bb2-3c63-425b-952f-101f6c109be2 (jlab_core.799ed26.js, line 1)
[Warning] Failed to fetch ipywidgets through the "jupyter.widget.control" comm channel, fallback to fetching individual model state. Reason: – "Control comm did not respond in time" (336.ebc7a55ea1768712771f.js, line 1)
[Error] Failed to load resource: The requested URL was not found on this server.
[Error] Failed to load resource: The requested URL was not found on this server.
[Log] Loading micropip, packaging (pyodide.asm.js, line 9)
[Log] Loaded packaging, micropip (pyodide.asm.js, line 9)
[Log] Loading sqlite3 (pyodide.asm.js, line 9)
[Log] Loaded sqlite3 (pyodide.asm.js, line 9)
[Log] Loading pygments, decorator, jedi, parso, six (pyodide.asm.js, line 9)
[Log] Loaded pygments, decorator, parso, jedi, six (pyodide.asm.js, line 9)
</pre>
</details>

**Comment by jtpio** [comment]
@KDean-Dolphin the tour extension does not seem to be fully working on the latest JupyterLite, which is why it is missing at the moment. But it should be added again at some point:

- https://github.com/jupyterlite/jupyterlite/issues/1139
- https://github.com/jupyterlite/jupyterlite/pull/1258

For the duplicate about entries it should be possible to fix them yes.
