### ISSUE TITLE
The homepage does not have any pre-prepared notebooks when deployed on Vercel

### ISSUE THREAD

**Issue by jeremy-feng** [jupyterlite/jupyterlite#1288]
## Description

I followed the deployment method on Vercel and successfully obtained the JupyterLite interface similar to [this site](https://jupyter.vercel.app/lab/index.html). However, the homepage does not have any pre-prepared notebooks, and all files in the `content` folder disappear.

![image](https://github.com/diegofcornejo/vercel-jupyter-lite/assets/44312563/b3940680-920b-412d-a1a3-056de1daafdb)

## Reproduce

Just like [the official documentation](https://jupyterlite.readthedocs.io/en/stable/howto/deployment/vercel-netlify.html#vercel):

1. Use https://github.com/diegofcornejo/vercel-jupyter-lite as template.
2. Configure deployment options and follow the steps to guide you through the deployment process.
3. Open "Build and Outputs Settings"
4. Enable "Build Command" and add this text: bash ./deploy.sh
5. Enable "Output Directory" and add this text: dist
6. Click on "Deploy"

## Expected behavior

The files in the `content` folder should be included.

## Context

- JupyterLite version: 0.2.2
- Operating System and version: Windows 11
- Browser and version: Chrome 120.0.6099.200

**Comment by jtpio** [comment]
Thanks @jeremy-feng for opening the issue.

It looks like this line is commented, which could be reason for the files to be missing?

https://github.com/diegofcornejo/vercel-jupyter-lite/blob/b03d8ed7f135bc0226f64d3ad4d262c916add272/deploy.sh#L19

```
# jupyter lite build --contents content --output-dir dist
```

For reference this repo also deploys to Vercel: https://github.com/jtpio/p5-notebook

**Comment by jeremy-feng** [comment]
Thank you! @jtpio 👍 

Since I used the `deploy.sh` provided [here](https://jupyterlite.readthedocs.io/en/stable/howto/deployment/vercel-netlify.html#using-micromamba-to-create-the-build-environment), I would suggest that a tip could be added to the documentation as well.

![image](https://github.com/jupyterlite/jupyterlite/assets/44312563/3d511e77-daae-4cae-aad8-707be0a3c8b9)

**Comment by jtpio** [comment]
> Since I used the `deploy.sh` provided [here](https://jupyterlite.readthedocs.io/en/stable/howto/deployment/vercel-netlify.html#using-micromamba-to-create-the-build-environment), I would suggest that a tip could be added to the documentation as well.

Sure. A tip to mention how to add contents would be useful. Would you like to open a PR to add it? Thanks!

**Comment by jtpio** [comment]
Sounds good, especially since there is already this paragraph above in the documentation :+1: 

![image](https://github.com/jupyterlite/jupyterlite/assets/591645/50f3a8d3-c68c-47dc-90f9-d51fbc2522bf)

**Comment by jeremy-feng** [comment]
I have opened a PR. See https://github.com/jupyterlite/jupyterlite/pull/1289

Thanks for your kindly review!
