### ISSUE TITLE
Make the service worker an opt-in, not an opt-out

### ISSUE THREAD

**Issue by martinRenou** [jupyterlite/jupyterlite#1294]
cc. @trungleduc @DerThorsten @jtpio 

### Why the service worker?

The service worker fills two purposes as of today:
- file-system access for Emscripten-based kernels
- caching (with the by-product of being able to install jupyterlite as a PWA)

### What's the issue?

The service worker is also the cause of many issues in JupyterLite:
- aggressive caching causing unintended behaviors (seeing a jlite webpage whereas the server is not serving such page, outdated content etc). See https://github.com/jupyterlite/jupyterlite/issues/1103
- kernel crashing due to the flaky filesystem-service worker communication. https://github.com/voila-dashboards/voici/issues/92 
- outdated service worker file cached by the browser

### What could we do in the future?

At some point, it would be nice to ditch the service worker for file-system access, and use a probably more robust approach using shared array buffers. In that case, file-system access support will be an opt-in (behind a browser flag).

### What can we do now?

Aggressive caching may be better as an opt-in, as it's causing lots of issues for normal users who may not know how/what to debug. Also, given that we may have file-system access behind a flag at some point (not enabled in the normal usage) we can consider doing this now, even before we make use of shared array buffers. 

For those reasons, I would like to suggest putting the service worker behind a flag:
```bash
jupyter lite build . --enable-service-worker
```

**Comment by jtpio** [comment]
Thanks @martinRenou for opening the opening, this looks like a good summary of the current service worker issues :+1: 

> At some point, it would be nice to ditch the service worker for file-system access, and use a probably more robust approach using shared array buffers. In that case, file-system access support will be an opt-in (behind a browser flag).

Right. As an alternative to ditching the service worker completely, maybe have a system of priorities based on feature availability? For example:

- if `SharedArrayBuffer` is available, use it
- if not, check if service workers are available and use them (current behavior)
- if not, then contents is not sync (current behavior in a Firefox private window)

This would also be useful for https://github.com/jupyterlite/jupyterlite/pull/460.

> For those reasons, I would like to suggest putting the service worker behind a flag:

Just to clarify, are you suggesting putting the caching behavior behind a flag, not the whole service worker registration? Which would be similar to the idea expressed in https://github.com/jupyterlite/jupyterlite/issues/1103#issuecomment-1691751425.

Otherwise users might be surprised if by default they can't access their files from the kernel.

**Comment by martinRenou** [comment]
> - if SharedArrayBuffer is available, use it
> - if not, check if service workers are available and use them (current behavior)
> - if not, then contents is not sync (current behavior in a Firefox private window)

That could be a good approach indeed

> Just to clarify, are you suggesting putting the caching behavior behind a flag, not the whole service worker registration? Which would be similar to the idea expressed in https://github.com/jupyterlite/jupyterlite/issues/1103#issuecomment-1691751425.

I am suggesting putting the service worker registration behind a flag

**Comment by martinRenou** [comment]
> So that means users will not have their contents available from the kernel by default anymore?

Unless they enable shared array buffers.

Caching is not the only issue, the service worker registration behavior is not deterministic, causing issues in file system access.

I think that if we:
- document enabling shared array buffers for having file-system access support
- document enabling service worker for PWA
- 
we can have the service worker not registered by default

**Comment by jtpio** [comment]
> I think that if we:
> 
>     * document enabling shared array buffers for having file-system access support
> 
>     * document enabling service worker for PWA
> 
> 
> we can have the service worker not registered by default

Ah but then it probably does not fall in the "What can we do now?" category suggested in the top comment, because enabling shared array buffers likely requires a bit more work and investigation?

**Comment by jtpio** [comment]
Which is why putting caching behind an opt-in flag could be a good first step, and could be shipped in a `0.2.x` release quite quickly. That way we could also assess whether this already helps, for example with the `thebe` case mentioned in https://github.com/jupyterlite/jupyterlite/issues/1103.

**Comment by jtpio** [comment]
also cc @stevejpurves who may be interested in this conversation, as the author of #1103.
