### ISSUE TITLE
/drive not accesible

### ISSUE THREAD

**Issue by maartenbreddels** [jupyterlite/jupyterlite#1307]
## Description

I expected `/drive` to be accessible, but with pip install "jupyterlite[all]==0.2.3" I do not get it in a Python kernel.
## Reproduce

```
mamba create -n lite311 -c conda-forge python=3.11
conda activate lite311 
jupyter lite build --contents ../examples --output-dir dist
python -m http.server -d dist

```

Now in a kernel:
<img width="418" alt="image" src="https://github.com/jupyterlite/jupyterlite/assets/1765949/73566222-7413-405f-b5a2-7f465a30d7fc">

## Context

- JupyterLite version: 0.2.3
- Operating System and version: osx Sonoma 14.3
- Browser and version: Brave Version 1.62.153 Chromium: 121.0.6167.85 (Official Build) (arm64)

<details><summary>Browser Output</summary>
<pre>
consumes:73 Unsatisfied version 6.0.11 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/coreutils (required ^6.0.12)
p @ consumes:73
s @ consumes:44
(anonymous) @ consumes:105
(anonymous) @ consumes:85
281 @ consumes:138
(anonymous) @ consumes:183
_.f.consumes @ consumes:164
(anonymous) @ ensure chunk:6
_.e @ ensure chunk:5
./extension @ container-entry:6
o @ container-entry:13
k @ index.js:35
(anonymous) @ index.js:65
P @ index.js:63
(anonymous) @ bootstrap.js:91
await in (anonymous) (async)
54931 @ bootstrap.js:65
w @ bootstrap:19
(anonymous) @ startup:4
w.O @ chunk loaded:23
(anonymous) @ startup:5
(anonymous) @ bundle.js?_=182ef6f:1
10:56:05.321 service-manager.js:33 ServiceWorkers not supported in this browser
initialize @ service-manager.js:33
p @ service-manager.js:12
activate @ index.js:144
(anonymous) @ index.es6.js:1851
Promise.then (async)
activatePlugin @ index.es6.js:1851
resolveOptionalService @ index.es6.js:1971
(anonymous) @ index.es6.js:1848
activatePlugin @ index.es6.js:1848
(anonymous) @ index.es6.js:2015
start @ index.es6.js:2014
P @ index.js:595
await in P (async)
(anonymous) @ bootstrap.js:91
await in (anonymous) (async)
54931 @ bootstrap.js:65
w @ bootstrap:19
(anonymous) @ startup:4
w.O @ chunk loaded:23
(anonymous) @ startup:5
(anonymous) @ bundle.js?_=182ef6f:1
10:56:05.321 index.js:164 JupyterLite ServiceWorker failed to become available
o @ index.js:164
(anonymous) @ index.js:184
Promise.catch (async)
activate @ index.js:183
(anonymous) @ index.es6.js:1851
Promise.then (async)
activatePlugin @ index.es6.js:1851
(anonymous) @ index.es6.js:2015
start @ index.es6.js:2014
P @ index.js:595
await in P (async)
(anonymous) @ bootstrap.js:91
await in (anonymous) (async)
54931 @ bootstrap.js:65
w @ bootstrap:19
(anonymous) @ startup:4
w.O @ chunk loaded:23
(anonymous) @ startup:5
(anonymous) @ bundle.js?_=182ef6f:1
10:56:05.321 index.js:167 Kernel filesystem and JupyterLite contents will NOT be synced
o @ index.js:167
(anonymous) @ index.js:184
Promise.catch (async)
activate @ index.js:183
(anonymous) @ index.es6.js:1851
Promise.then (async)
activatePlugin @ index.es6.js:1851
(anonymous) @ index.es6.js:2015
start @ index.es6.js:2014
P @ index.js:595
await in P (async)
(anonymous) @ bootstrap.js:91
await in (anonymous) (async)
54931 @ bootstrap.js:65
w @ bootstrap:19
(anonymous) @ startup:4
w.O @ chunk loaded:23
(anonymous) @ startup:5
(anonymous) @ bundle.js?_=182ef6f:1
10:56:08.568 index.js:54 Pyodide contents will NOT be synced with Jupyter Contents
create @ index.js:54
await in create (async)
startNew @ kernels.js:123
startNew @ sessions.js:105
(anonymous) @ index.js:366
route @ router.js:85
await in route (async)
fetch @ app.js:90
e.handleRequest @ serverconnection.js:209
e.makeRequest @ serverconnection.js:64
t.startSession @ restapi.js:94
startNew @ manager.js:140
_changeKernel @ sessioncontext.js:551
startKernel @ sessioncontext.js:333
_startIfNecessary @ sessioncontext.js:510
_initialize @ sessioncontext.js:449
await in _initialize (async)
initialize @ sessioncontext.js:417
_populate @ context.js:469
await in _populate (async)
(anonymous) @ context.js:576
Promise.then (async)
_revert @ context.js:547
initialize @ context.js:203
(anonymous) @ manager.js:550
Promise.then (async)
_createOrOpenDocument @ manager.js:550
open @ manager.js:374
openOrReveal @ manager.js:401
(anonymous) @ index.js:511
Promise.then (async)
execute @ index.js:511
execute @ index.es6.js:364
(anonymous) @ index.js:1346
await in (anonymous) (async)
execute @ index.js:1375
execute @ index.es6.js:364
A @ widget.js:194
Oe @ react-dom.production.min.js:54
Be @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
Ir @ react-dom.production.min.js:105
Ur @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
cs @ react-dom.production.min.js:274
Le @ react-dom.production.min.js:52
Qr @ react-dom.production.min.js:109
qn @ react-dom.production.min.js:74
$n @ react-dom.production.min.js:73
10:56:08.571 default.js:70 Starting WebSocket: ws://[::]:8000/api/kernels/7978945d-d6e5-435b-a62c-f8fda2504e11
10:56:08.580 default.js:70 Starting WebSocket: ws://[::]:8000/api/kernels/7978945d-d6e5-435b-a62c-f8fda2504e11
10:56:08.586 default.js:70 Starting WebSocket: ws://[::]:8000/api/kernels/7978945d-d6e5-435b-a62c-f8fda2504e11
10:56:09.939 pyodide.asm.js:9 Loading micropip, packaging
10:56:10.028 pyodide.asm.js:9 Loaded micropip, packaging
10:56:10.835 pyodide.asm.js:9 Loading ssl, openssl
10:56:10.944 pyodide.asm.js:9 Loaded openssl, ssl
10:56:11.124 pyodide.asm.js:9 Loading sqlite3
10:56:11.167 pyodide.asm.js:9 Loaded sqlite3
10:56:12.238 pyodide.asm.js:9 Loading jedi, parso, Pygments, decorator, six
10:56:12.831 pyodide.asm.js:9 Loaded Pygments, decorator, jedi, parso, six</pre>
</details>

**Comment by maartenbreddels** [comment]
Answering my own issue: service worker is not accessible, I probably need to run on https

**Comment by maartenbreddels** [comment]
My solution

I create a Caddyfile:
```
localhost {
  reverse_proxy localhost:8000
}
```

```
$ brew install caddy
$ caddy run
# other terminal has jupyter lite serve running
```

Now go to https://localhost

**Comment by jtpio** [comment]
The service worker should be accessible on localhost normally: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#setting_up_to_play_with_service_workers

> localhost is considered a secure origin by browsers as well.

**Comment by maartenbreddels** [comment]
That's also what I thought/knew. I tried it again and now it's working. The only change is that I have restarted the browser (brave). I've seen this happen more often, if chrome/brave downloaded the upgraded version, and gives you this warning to start your browser it will have very buggy behaviour.

So, this seems to be flakey behaviour of brave/chromium 🤷

**Comment by martinRenou** [comment]
Yeah the service worker is very flaky.

FYI, jupyterlite-xeus provides a way to mount the files into the kernel, making things less flaky https://jupyterlite-xeus.readthedocs.io/en/latest/files.html#making-it-more-robust
