### ISSUE TITLE
Embedding jupyterlite into a static site

### ISSUE THREAD

**Issue by code-leen** [jupyterlite/jupyterlite#131]
Hi! 👋🏽  From what I understand, this can be embedded into an existing project. Is this project similar in concept to `jupyterlab` in having reusable components like *Consoles* or *File Browser*?

**Comment by jtpio** [comment]
Hi!

JupyterLite can definitely be embedded in an IFrame. As some point once the packages are published to `npm`, it will also be possible to reuse parts of JupyterLite in other applications.

> Is this project similar in concept to `jupyterlab` in having reusable components like _Consoles_ or _File Browser_?

In fact, JupyterLite reuses [many plugins](https://github.com/jtpio/jupyterlite/blob/7b81d32e5667647124f8e1b2e6c8009fc54942bb/app/lab/package.json#L181-L211) from JupyterLab as is, including the `console-extension` and `filebrowser-extension`.

**Comment by bollwyvl** [comment]
Right. And I think one of the additional apps we _should_ ship from this repo, if only as a baseline for these kinds of embeddings, will probably be _exactly one cell with a cut-down notebook toolbar and an outputarea in a split panel._ There are some challenges here, of course, but it would be super useful for docs etc. that just want the barest amount of an app, but still want rich output features, etc. For this to _really_ sing, one would want the kernel to exist in some space that multiple iframes can contact... or actually run the kernel in the outer page.

**Comment by psychemedia** [comment]
One thing I've been wondering is: would a `thebelab.js` connection be possible, so that eg a Jupyter Book site could make use jupyterlite code execution?

(I don't understand how `jupyterlite` works well enough to know if this would be relatively straightforward thing to achieve or a nonsense thing to ask for. Does `jupyterlite` essentially mock a jupyter server to connect the client to to a kernel?)

Loosely related: https://github.com/jtpio/jupyterlite/issues/15

**Comment by jtpio** [comment]
> Does `jupyterlite` essentially mock a jupyter server to connect the client to to a kernel?

Pretty much yes. `WebSocket` and `fetch` are mocked / intercepted, and most of this logic is in https://github.com/jtpio/jupyterlite/tree/main/packages/server.

There is a diagram in [this gist](https://gist.github.com/jtpio/3763af75ec8cd7bfdce86501563fef09), which should be added to the documentation at some point:

![image](https://user-images.githubusercontent.com/591645/121019110-6d280980-c79f-11eb-8693-b0ad14c3ec82.png)

**Comment by bollwyvl** [comment]
Yeah, we're suffering a bit from the upstream stack not having architecture diagrams like that as we "just" do that... but in the browser :laughing:.

The quickest play is going to be getting an as-easy-to-use-as-possible iframe snippet going that works with a co-deployed lite site... eventually, however, i could see having an app build that was a _little_ smarter, such that it could draw cells correctly on the page _without_ an iframe, and (optionally) tie multiple standalone cells to one kernel. We'd basically need a "NullShell" that had a very particular form of Lumino layout which knew how to put lab parts into the page where requested, but optionally allowed access to things like command palette, settings, etc.

**Comment by psychemedia** [comment]
Ah, that's really useful. So in terms of:

1. a remote ("traditional" kernel connection);
2. a thebelab connection to a JupyterLite kernel, which part should do the work - the JupyterServer or the JupyterLiteServer.

To what extent would thebelab have to behave differently to work with a `jupyterlite` kernel cf. making a connection to a "traditional" remote server?

(Apols if the questions are really naive; I'm trying to get a feeling for how likely it is for things like Jupyter Book to "just" run with either jupyterlite or a remote kernel from just a simple config. It could be really useful for online interactive textbooks, documentation demos/package, etc. Maybe then we'd start to see [R](https://github.com/iodide-project/r-wasm) like documentation vignettes in Python packages, with the added benefit of live code demos in the browser on the documentation site:-).

**Comment by bollwyvl** [comment]
> kernel and console all-in-one, 

There isn't a _convenient_ way to get to that yet, no.

There are a number of ways we can get to this:
- build a new `app` (hard)
- incrementally add some features (also hard, but more cross-applicable)
  - [workspaces](https://github.com/jtpio/jupyterlite/issues/139)
  - custom CSS
    - though you'd kinda get this with workspaces, as any rich text output (e.g. `Markdown Preview` can be a stylesheet!

So the idea would be (once we have #41):
- get your jupyterlab the way you want it, with relative paths correct, etc.
  - a `README.ipynb` open with some embedded CSS hacks
    - doesn't even have to be the front widget
  - the file you want
  - the linked console
- export the `.jupyterlab-workspace` file
- copy it to a place, might end up being `./lab/api/workspaces/<name of workspace>`
- run `jupyter lite build` 

And then when iframing, do something like:
```html
<iframe src="https://my-site.org/lite/?workspace=example-01" style="height: 60vw; width: 100%;"/>
```

**Comment by jtpio** [comment]
> build a new `app` (hard)

The JupyterLab repo has some examples with minimalist UIs, and there is one with the console only: https://github.com/jupyterlab/jupyterlab/tree/master/examples/console

![image](https://user-images.githubusercontent.com/591645/121486361-5b2dad00-c9d1-11eb-9eaf-3e8f92649cdf.png)

Depending on your use case maybe this could also be enough (assuming the backend is a traditional Jupyter Server).

**Comment by colleenkingcode** [comment]
For context, I'm interested in using the Jupyter console alongside a CodeMirror in my Vue/Nuxt app! 
Looking for a way to have the flexibility of the interactive console _and_ if a user wants to run a Python file (with the contents coming from the CodeMirror) 🐍🪞 

It seems like the most possible way to do this would be to:
1. Run the jupyter server and the jupyter console. 
2. Run my web app separately
3. Iframe the console into my webapp 

Thoughts? Let me know if I'm missing a significant step 🔍

**Comment by jtpio** [comment]
@codelleen for reference you can have a look at https://github.com/jtpio/replite, which is now being used on the https://numpy.org website to embed an interactive code console with an `iframe`.

We are working on bringing this console intro JupyterLite core so it's available by default.

Also related to #148

**Comment by bollwyvl** [comment]
Our best effort at this is released and [documented](https://jupyterlite.readthedocs.io/en/latest/applications/repl.html) now :tada: I think we can close this now and iterate on subsequent issues.
