### ISSUE TITLE
Problem Saving Notebook

### ISSUE THREAD

**Issue by psychemedia** [jupyterlite/jupyterlite#132]
Trying to save a created and untitled notebook in JupyterLab view, the notebook appears to save under a newly given name, but the dialog remains with the original default name and blocks further action:

![image](https://user-images.githubusercontent.com/82988/120677289-d43b7a80-c48e-11eb-9c95-90e04df0285f.png)

UPDATE: clicking the *Enter* button lots of times very very quickly appears to clear the dialog.

**Comment by jtpio** [comment]
Thanks @psychemedia for reporting :+1: 

It might be an issue with JupyterLite, but could also be from upstream JupyterLab. For reference this feature was added in https://github.com/jupyterlab/jupyterlab/pull/10043.

We're using the very latest packages (`3.1.0-alpha.11` at the moment), and I believe there are still a couple of things upstream to fix with the new rename flow.

**Comment by jtpio** [comment]
For reference, https://github.com/jtpio/jupyterlite/pull/136 disabled this dialog on the demo RTD site.

**Comment by psychemedia** [comment]
I've just noticed another problem with erratic save behaviour whilst running `jupyerlite` using a simple pyhton http server (`python3 -m http.server`): specificially, the save behaviour seems very hit and miss. Sometimes saves appear to occur, sometimes they don't. I'm seeing the effect with both manual and autosaves. 

The notebook download option appears to work correctly, which means I can:

- edit a notebook and see the changes;
- download the changed notebook correctly;
- close and open the notebook and the changes have disappeared,

At other times, changes do appear to be saved persistently but I can't figure out when.

**Comment by jtpio** [comment]
> specifically, the save behaviour seems very hit and miss

Would you be able to try with stock JupyterLab? Using the latest alpha release with `pip install --pre jupyterlab`, just to check whether the same happens there (which looks like it does)

**Comment by psychemedia** [comment]
I think it's Chrome.. Just noticed that my current version of Chrome seems to be completely broken cachewise trying to refresh other pages: things not refreshing at all (Firefox sees updated links fine). Not sure if this a Chrome version thing, or a side effect of the large number of open tabs (but they shouldn't have side effects, right?) With browsers continually updating themselves, it's hard to know what's going on at times..

**Comment by bollwyvl** [comment]
Over on #173, reworked some  of the contents stuff... maybe try it out on RTD?

https://jupyterlite--173.org.readthedocs.build/en/173/
