### ISSUE TITLE
Check JupyterLab 4.1 and Notebook 7.1 missing features

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#1323]
Follow-up to https://github.com/jupyterlite/jupyterlite/pull/1263

We should check what features might be missing for `0.3.0`: https://jupyterlab.readthedocs.io/en/latest/getting_started/changelog.html#v4-1

Checking with https://jupyterlite.readthedocs.io/en/latest/_static/lab/index.html :

- [x] Custom CSS: N/A ?
- [x] Diagrams in Markdown

![image](https://github.com/jupyterlite/jupyterlite/assets/591645/8cea799a-92df-41f8-a4b0-2bd5e6730c41)

- [x] Inline completer. Tested with:
  - `jupyterlite-core==0.3.0a0`
  - `jupyterlab-transformers-completer`: https://github.com/krassowski/jupyterlab-transformers-completer

[jupyterlite-inline-completer.webm](https://github.com/jupyterlite/jupyterlite/assets/591645/90f63709-9a5d-4d49-85e2-1f80ba18e114)

- [x] Keyboard navigation improvements
- [x] Execution history in notebook

[jupyterlite-kernel-history.webm](https://github.com/jupyterlite/jupyterlite/assets/591645/f687b3f3-8200-4447-b6ed-2dabb93c2003)

- [x] Opening files from tracebacks: N/A?
- [x] Error indicator in the table of contents
- [x] Plugin Manager: https://github.com/jupyterlite/jupyterlite/issues/1324
- [x] Virtual scrollbar for notebook in windowed mode

![image](https://github.com/jupyterlite/jupyterlite/assets/591645/56def393-a42e-4d6b-8956-898b3ba651ef)

- [x] Notifications in JupyterLab

[jupyterlite-notifications-lab.webm](https://github.com/jupyterlite/jupyterlite/assets/591645/4a1e4f31-d67f-4385-ac7b-42ca089da82e)

- [x] Notifications in Notebook: https://github.com/jupyterlite/jupyterlite/pull/1325

[jupyterlite-notifications-notebook-tree.webm](https://github.com/jupyterlite/jupyterlite/assets/591645/495a8c0f-58fb-4555-bd1a-a0acb1ab47e6)

- [x] Full notebook windowing mode improvements
- [x] Search improvements

[jupyterlite-search-replace-improvements.webm](https://github.com/jupyterlite/jupyterlite/assets/591645/c942e842-2799-470e-858c-0dbdeff8f9a8)

**Comment by jtpio** [comment]
All appear to be working fine, except for a few that might need to be addressed separately:

- Plugin Manager: https://github.com/jupyterlite/jupyterlite/issues/1324
- Custom CSS: not sure if this could / should be enabled?
- Opening files from tracebacks

**Comment by andeplane** [comment]
How did you test the inline auto completion? i tried to install the `jupyterlab-transformers-completer` on the 3.0.0x kernel and everything, but getting this

<img width="1312" alt="image" src="https://github.com/jupyterlite/jupyterlite/assets/16174/8f55c489-205f-4352-957c-d9c60f36d1c2">

```
SharedArrayBuffer not available
Server extension enabling `same-origin` and `require-corp` headers is required for jupyterlab-transformers-completer to access `SharedArrayBuffer` which is used to synchronously communicate with the language model WebWorker.
```

in both Chrome and Firefox.

**Comment by jtpio** [comment]
I tried locally following the steps on the repo to set the proper server headers and enable the SharedArrayBuffer.

**Comment by jtpio** [comment]
Some more info here: https://github.com/krassowski/jupyterlab-transformers-completer/issues/3#issue-2024364583
