### ISSUE TITLE
Demo not loading anymore

### ISSUE THREAD

**Issue by dondy** [jupyterlite/jupyterlite#1374]
## Description
Since today the url https://jupyterlite.github.io/demo/lab/index.html doesn't serve the demo anymore.
![image](https://github.com/jupyterlite/jupyterlite/assets/301740/aa00b8aa-1b29-4105-8d22-3bc28e0b352b)

## Reproduce
1. Go to https://jupyterlite.github.io/demo/lab/index.html
2. Observe, nothing.
3. Panic because you have two little presentations done there...

## Expected behavior
I'd really like to recover the files :s

**Comment by martinRenou** [comment]
I see it working:

![Screenshot from 2024-04-17 16-37-53](https://github.com/jupyterlite/jupyterlite/assets/21197331/7e59cff4-fbcf-4d08-b68c-e0a62750bcd4)

Can you try from a private window, to make sure you're not hitting cache?

**Comment by martinRenou** [comment]
Ah yeah, browser extension having control of the web-page, they sometimes go in your way. It's probably NoScript was blocking one of the asset needed for JupyterLite to start.

**Comment by Carreau** [comment]
May I suggest we reopen this and add a noscript tag to the page with "js must be enabled" ?

**Comment by MRYingLEE** [comment]
I tested in a few environments and met the same issues.

The issue "Repository is read only" happened when any of "Pyodide Kernel" or "P5.js Kernel" was started.
![image](https://github.com/jupyterlite/jupyterlite/assets/11193534/69dbfa21-8d08-4f9b-8a81-30e96f19dba2)

Even the readme.md couldn't be opened.
![image](https://github.com/jupyterlite/jupyterlite/assets/11193534/40a0206f-3e7a-467a-abd9-6cdf1f534b01)

**Comment by jtpio** [comment]
> The issue "Repository is read only"

This seems to be an issue in JupyterLab, which also affects JupyterLite: https://github.com/jupyterlab/jupyterlab/issues/15629

**Comment by henryiii** [comment]
Any workarounds for "Repository is read only"? I see this on both Safari and Chrome. Does an older version work? I was planning to use it to teach today and ran into the fact you an't make a new notebook anymore.

This might be a new issue and JupyterLite specific, as I can change and run the existing notebooks, I just can't make a new one. Maybe JupyterLab is being smart about the fact it thinks it can't change the repo (even though JupyterLite is caching and saving notebooks anyway?)

**Comment by bollwyvl** [comment]
Perhaps we drop `jupyterlab-github` until such a time as that project uses lite in their documentation/development cycle.

**Comment by bollwyvl** [comment]
This looks fine:

https://jupyterlite--1474.org.readthedocs.build/en/1474/_static/lab/index.html

**Comment by jtpio** [comment]
> This might be a new issue and JupyterLite specific, as I can change and run the existing notebooks, I just can't make a new one. Maybe JupyterLab is being smart about the fact it thinks it can't change the repo (even though JupyterLite is caching and saving notebooks anyway?)

This is still the same JupyterLab as mentioned above: https://github.com/jupyterlab/jupyterlab/issues/15629 (cc @brichet)

For some reasons the `jupyterlab-github` drive grabs the focus. When a user tries to create a notebook, JupyterLab still thinkgs the GitHub drive has the focus, but since the drive is read-only by default (you can't create files on GitHub without a token) we get this "Repository is read only" popup.

**Comment by jtpio** [comment]
Looks like we can keep the discussion about the drive issue in the JupyterLab repo: https://github.com/jupyterlab/jupyterlab/issues/15629

Originally, this issue reported a different bug, which let to this [comment](https://github.com/jupyterlite/jupyterlite/issues/1374#issuecomment-2063448971), and is now tracked in https://github.com/jupyterlite/jupyterlite/issues/1475.
