### ISSUE TITLE
looking if  polars and/or duckdb are possible on latest jupyterlie

### ISSUE THREAD

**Issue by stonebig** [jupyterlite/jupyterlite#1375]
is it possible with latest jupyterlite-0.3 or jupyterlite/xeus-python-demo to have duckdb or polars ?

**Comment by oscar6echo** [comment]
I would also like to see polars on jupyterlite.

Related: https://github.com/pola-rs/polars/issues/3672

**Comment by stonebig** [comment]
so we have Duckdb-1.0.0:
- that is ALREADY awesome (twice SQLite speed, more flexible for dataScience)
- could we have the bug-fix release Duckdb-1.1.2 next time ?

**Comment by bollwyvl** [comment]
Please see the links provided above https://github.com/jupyterlite/jupyterlite/issues/1375#issuecomment-2065926799 to take an active part in getting the packages you want.

**Comment by stonebig** [comment]
It's on the way \o/

**Comment by stonebig** [comment]
apparently polars just became available as wasm32:  https://github.com/pola-rs/polars/releases/tag/py-1.18.0
