### ISSUE TITLE
`Uncaught TypeError: i is undefined`

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#1424]
## Description

As noticed in https://github.com/jupyterlite/jupyterlite/pull/1423, lots of errors are logged in the dev tools console, which seem related to the use of `coincident`:

```
Uncaught TypeError: i is undefined
    a bridge.js:44
```

![image](https://github.com/jupyterlite/jupyterlite/assets/591645/dcef9b1b-141c-45a6-a5c6-83130b31ccd7)

## Reproduce

https://jupyterlite--1423.org.readthedocs.build/en/1423/_static/lab/index.html

Open a widget notebook and perform some actions.

## Expected behavior

No error in the console.

## Context

cc @martinRenou who may know more about this

**Comment by jtpio** [comment]
This seems to be coming from this line: https://github.com/WebReflection/coincident/blob/b8f9cb41a411d66a1b665212eb10e79de53a4d8b/esm/bridge.js#L44

**Comment by martinRenou** [comment]
Arf. I'm not sure what could go wrong here.

Probably coincident does not like our comm messages with widgets for some reason.

**Comment by bollwyvl** [comment]
Should, e.g. `pyodide-kernel/coincident.worker.ts` even be using `window.postMessage` anymore? That seems too unmagical for what (I think) `coincident` is doing.

**Comment by jtpio** [comment]
For reference this is also happening with `jupyterlite-xeus` and the `xeus-python` kernel:

![image](https://github.com/jupyterlite/jupyterlite/assets/591645/a85e65fc-f71e-4efe-9e30-683839683b9c)

**Comment by martinRenou** [comment]
> Should, e.g. pyodide-kernel/worker.ts even be using window.postMessage anymore? That seems too unmagical for what (I think) coincident is doing.

That's true, I'm unsure why we were still using this even when comlink was around? 

Now concerning the original issue, all kernel responses seem to go through `postMessage` and working so it's probably not the culprit

**Comment by jtpio** [comment]
Digging a bit more in the `coincident` code base, it looks like `coincident` sets its own metadata on the patch `postMessage`. So maybe switching from `postMessage` to `coincident` on the worker side could make sense and help with that issue.

**Comment by bollwyvl** [comment]
Yeah, if `coincident` is like `comlink`, there are some weird things for bidirectional stuff: we would have to decide whether to:

- wrap a `notReallyPostMessage` method on the the UI thread in `coincident` for the worker to call
  - proxying more of the UI thread is a slippery slope, and will become very fragile if used by third-party code
- add a worker-side queue, which the worker pushes to with `notReallyPostMessage` and expose a `async messages*()` which drains it from the other side, provided the async iterator semantics work correctly over the `coincident` bus

**Comment by bollwyvl** [comment]
Ugh, speaking of [fragile](https://github.com/WebReflection/coincident-next)...

**Comment by jtpio** [comment]
> Thinking we should try to fix this before `0.4.0`, so we can follow-up with the final release after.

Looks like this can be fixed in the kernel repositories directly:

- https://github.com/jupyterlite/pyodide-kernel/pull/126
- https://github.com/jupyterlite/xeus/issues/102

So we could move forward with the `0.4.0` release by making a first rc.
