### ISSUE TITLE
Collapsable cells

### ISSUE THREAD

**Issue by steltenpower** [jupyterlite/jupyterlite#1455]
### Problem

* Code I'm not currently working on captures loads of screen space and is unnecessary risk for misunderstanding

### Proposed Solution

* Add an option to collapse cells, only showing the top line, probably a comment

### Additional context

* The functionality is already available in other places of the Jupyter ecosystem.

**Comment by jtpio** [comment]
@steltenpower this should already be possible via the cell collapser:

[jupyterlab-cell-collapser.webm](https://github.com/user-attachments/assets/e13302e1-3ffb-4efd-afe7-a4febba5eac1)

Which can be tested on the demo repo: https://jupyterlite.github.io/demo/lab/index.html

**Comment by steltenpower** [comment]
Wow, thanks, works indeed.
I was clicking on many things, also near that :-)
I'll close the issue.
