### ISSUE TITLE
Pyodide becomes irresponsive after a few ipywidgets interactions

### ISSUE THREAD

**Issue by MartinaMJ** [jupyterlite/jupyterlite#1465]
## Description

Hello. I am a JupyterLite user. I have been using JupyterLite for more than one year and so far it has been very useful and helpful. I am currently using JupyterLite as a resource to host Jupyter Notebooks for a Linear Algebra class. I have created notebooks with interactive widgets with which the user can interact directly with matrices and other Linear Algebra applications. However, I noticed that, a few weeks ago, a bug started happening in which the Pyodide kernel becomes irresponsive after a few interactions. Here is a gif I made:

![gifJLite (2) (1)](https://github.com/user-attachments/assets/76e43bd2-e1a6-487d-a6bc-7027a926c00a)

You can see that, after a few interactions, the graphs stop changing. I have seen this happen with many of my other implementations. I realized that the kernel remains in Idle after a few interactions. I would like to know any possible explanations as to why this is happening currently, and why wasn't this happening before. I am kind of oblivious as to how JupyterLite is actually implemented, so I wonder if it is something that I can fix myself (like changing kernel version) or if it is something that doesn't depend on me. I noticed that this error occurs mainly when using ipywidgets in association with matplotlib. Could it be something related to them? 
I wish to know how can I fix, or at least understand, the cause of this problem. 
Thank you.

## Reproduce

1- I have only noticed this error while using JupyterLite deployed with GitHub Pages, by cloning the demo repo and commiting my own files to the content directory. 
2- If you attempt to implement an application that uses matplotlib and ipywidgets, if is possible that you notice this bug. 

I noticed this error after executing a notebook I had written months prior and was working perfectly, and realized the kernel suddenly stopped being triggered after a few interactions.

## Expected behavior

I expected the notebook to always respond to the interactions. 

## Context

- JupyterLite version: 0.4.0
- Operating System and version: Windows 10.
- Browser and version: Opera (latest version) (however, I have tested this in Chrome and asked a friend to test in Chrome in Windows 11 and the same error was observed)

(If any information is absent, please let me know and I will inform you. I apologize in advance for my possible lack of experience and formal knowledge. I am very thankful for any and all help)

**Comment by jtpio** [comment]
Thanks @MartinaMJ for opening the issue :+1: 

Would it be possible to share a minimal code snippet to be able to reproduce the issue?

**Comment by MartinaMJ** [comment]
Hello @jtpio 
Here is the code:
`escalar01 = widgets.FloatText(value = 1, description = 'Black of first plot:', disabled = False, style= {'description_width': 'initial'})
escalar02 = widgets.FloatText(value = 1, description = 'Red of first plot:', disabled = False, style= {'description_width': 'initial'})
escalar03 = widgets.FloatText(value = 1, description = 'Black of second plot:', disabled = False,style= {'description_width': 'initial'})
escalar04 = widgets.FloatText(value = 1, description = 'Red of second plot:', disabled = False, style= {'description_width': 'initial'})
formatted1 = widgets.VBox([escalar01, escalar02])
formatted2 = widgets.VBox([escalar03, escalar04])
formatted3 = widgets.HBox([formatted1, formatted2])

def setas1(escalar01, escalar02, escalar03, escalar04):
    fig, (ax1, ax2) = plt.subplots(1, 2)
    plt.figure(figsize=(2, 2))
    ax1.arrow(0, 0, escalar01, 0, width = 0.01, color = 'red', length_includes_head = True, head_width = 0.03)
    ax1.arrow(0, 0, 0, escalar02, width = 0.01, color = 'black', length_includes_head = True, head_width = 0.03)
    ax1.arrow(0, 0, escalar01, escalar02, width = 0.01, length_includes_head = True, head_width = 0.03)
    ax1.grid()
    ax2.arrow(0, 0, 4*escalar03, 3*escalar03, width = escalar03*(0.03), color = 'red', length_includes_head = True, head_width = escalar03*(0.08))
    ax2.arrow(0, 0, 0, 2*escalar04, width = escalar03*(0.03), color = 'black', length_includes_head = True, head_width = escalar03*(0.08))
    ax2.arrow(0, 0, 4*escalar03, 3*escalar03 + 2*escalar04, width = escalar03*(0.03), length_includes_head = True, head_width = escalar03*(0.08))
    ax2.grid()
    plt.show()
    return 0
    
verif = interactive_output(setas1, {'escalar01': escalar01, 'escalar02': escalar02, 
                                           'escalar03': escalar03, 'escalar04': escalar04})
display(verif, formatted3)`

I am importing: `%pip install -q ipywidgets==8.0.7`

**Comment by jtpio** [comment]
Thanks @MartinaMJ for sharing.

Testing on https://jupyterlite-pyodide-kernel.readthedocs.io/en/latest/_static/lab/index.html, adding the following cells at the top:

```py
%pip install ipywidgets
```

```py
import ipywidgets as widgets
from ipywidgets import interactive_output

import matplotlib.pyplot as plt
```

It does seem like there is no update of the graphs after changing the values a few times:

[jupyterlite-interactive-output-issue.webm](https://github.com/user-attachments/assets/b2c2afdb-cddb-4b36-a287-cee48531b412)



Wondering if this could have something to do with the handling of `interactive_output` in JupyterLite.

**Comment by MartinaMJ** [comment]
Hello @jtpio. I don't think it is exclusive to `interactive_output`. See these two test notebooks where I use `interact`,  and the same error is observed:
https://martinamj.github.io/Online-Linear-Algebra/lab/index.html?path=TestVenetianMasks.ipynb
https://martinamj.github.io/Online-Linear-Algebra/lab/index.html?path=chapter_07novo.ipynb

**Comment by jtpio** [comment]
cc @martinRenou in case you may have some hints whether this could be related to one of the latest releases of `ipywidgets`?

Cross-linking:

- https://github.com/jupyter/try-jupyter/issues/54
- https://github.com/jupyterlite/pyodide-kernel/issues/133

**Comment by martenrichter** [comment]
I have commented some analysis on the other issue, after a longer debugging session on the js side:
https://github.com/jupyterlite/pyodide-kernel/issues/133
But as I am new to the codebase, hints from experienced persons from the jupyter environment would be welcome.

**Comment by jtpio** [comment]
The fix in https://github.com/jupyterlite/pyodide-kernel/pull/148 was released in https://github.com/jupyterlite/pyodide-kernel/releases/tag/v0.4.6, thanks @martenrichter!
