### ISSUE TITLE
DriveFS cannot overwrite-truncate existing file

### ISSUE THREAD

**Issue by juntyr** [jupyterlite/jupyterlite#1472]
DriveFS currently doesn't handle setting the `size` attribute here:

https://github.com/jupyterlite/jupyterlite/blob/82007cea732ac122f3fa2b12f3f694d16af5c575/packages/contents/src/drivefs.ts#L295

This makes `open("file", "w").close()` fail silently, i.e. an existing file is not truncated.

**Comment by jtpio** [comment]
Thanks @juntyr for the report.

I don't recall if this was on purpose or temporary, but it still looks like something that could be fixed.

cc @martinRenou who may know more about this
