### ISSUE TITLE
When "Restart and run all cells" is executed, the kernel is changed to Python (Pyodide).

### ISSUE THREAD

**Issue by pea-sys** [jupyterlite/jupyterlite#1492]
## Description
When "Restart and run all cells" is executed, the kernel is changed to Python (Pyodide).

## Reproduce

I uploaded a video

https://github.com/user-attachments/assets/c90e78fc-7b16-4746-bf30-86c15e8cfd1f

## Expected behavior
Do not change the kernel

## Context

- JupyterLite version:0.4.1
- Browser and version:129.0.6668.90

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by ogrisel** [comment]
I wonder if this is related to the race condition observed in #1464 that causes some kernels to be leaked in the background without any attached session.

**Comment by ogrisel** [comment]
@pea-sys can you check if the bug you reported has been fixed in #1538 when using this [preview link](https://jupyterlite--1538.org.readthedocs.build/en/1538/_static/lab/index.html)?

I cannot play the video of the screen recording anymore, so I am not 100% sure if this is a related problem or not.

**Comment by jtpio** [comment]
It's also now available in `0.5.0a1`: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.5.0a1

**Comment by pea-sys** [comment]
@ogrisel This issue is no longer reoccurring.
thank you.

**Comment by jtpio** [comment]
Cool, closing as fixed by https://github.com/jupyterlite/jupyterlite/pull/1538 then, thanks!
