### ISSUE TITLE
New ReadTheDocs overlays make typing code impossible

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#1499]
Trying preview PRs on ReadTheDocs, it looks like it's not possible to type in code cells anymore, because the keys may be associated to some ReadTheDocs actions:

![image](https://github.com/user-attachments/assets/e04fb970-f5d2-4125-a95d-79a4a1d3b615)

Hopefully there is a way to disable these overlays.

**Comment by jtpio** [comment]
Found and disabled the following addons on https://app.readthedocs.org/dashboard/jupyterlite/addons/edit/ :

![image](https://github.com/user-attachments/assets/911a8234-b621-4e0a-bf02-5ca15cdc9378)

![image](https://github.com/user-attachments/assets/43bcf092-6e5e-42f2-bf62-f447f15e033b)

![image](https://github.com/user-attachments/assets/aa331d03-c00f-4ef8-ad6f-e46829d3874f)

**Comment by jtpio** [comment]
Looks like we can press the "d" key again on previews, closing as fixed!

**Comment by bollwyvl** [comment]
This was getting to me on some other places, opened:

https://github.com/readthedocs/addons/issues/472
