### ISSUE TITLE
Add a remote kernel powered by Binder

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#15]
It would be cool to also be able to start remote kernels on https://mybinder.org.

Similar to what the [thebe](https://github.com/executablebooks/thebe) project does.

The JupyterLite frontend would still load in seconds. But the remote kernel might of course take some time to start.

**Comment by psychemedia** [comment]
This would be interesting... for simple jobs, things could be run in the browser. If a more complex computer backend is required, then a remote kernel could do the work. (Note that in the general case, it would also be handy to connect to a local (desktop) kernel. Cf. how VS Code Jupyter extension lets you [provide a kernel connection URL](https://code.visualstudio.com/docs/python/jupyter-support#_connect-to-a-remote-jupyter-server) and run using that.

I also note a VS Code extension for working with [`pyolite`](https://marketplace.visualstudio.com/items?itemName=joyceerhl.vscode-pyolite) - not sure how that manages the connection.

**Comment by jtpio** [comment]
Thanks @psychemedia.

Ideally some parts from JupyterLite would go to upstream JupyterLab, which might require some refactoring of the underlying `@jupyterlab/services` package. This could allow having in-browser kernels in a normal JupyterLab installation too (hybrid).

Otherwise for this specific issue, it will probably be implemented as a third-party serverlite extension once #104 has landed.

**Comment by psychemedia** [comment]
Just to generalise this a bit more, it would be be useful to connect to start an arbitrary remote kernel, eg via BinderHub, a user's account on a JupyterHub server somewhere, or via a Jupyter Enterprise Gateway.

The user could then bring their own client simply via a browser (eg on a Chromebook, tablet or phone) and access arbitrary hosted Jupyter served computational environments.

**Comment by bollwyvl** [comment]
As JupyterLite is now being used to take pressure off binder, I think we probably won't be doing this.

**Comment by psychemedia** [comment]
That is a separate issue, surely?

**Comment by jtpio** [comment]
Probably could be converted to a discussion in the "Ideas" category.
