### ISSUE TITLE
Extend Examples to include notebooks in subdirectories

### ISSUE THREAD

**Issue by psychemedia** [jupyterlite/jupyterlite#150]
Perhaps a trivial example, but for generality and just to test that paths etc can be correctly defined and resolved during deployment, it would be useful to have at least one example notebook in a subdirectory that sits alongside the other examples.

**Comment by bollwyvl** [comment]
Can probably be closed, as we now have this under test: https://github.com/jtpio/jupyterlite/blob/main/py/jupyterlite/src/jupyterlite/tests/test_cli.py#L157

**Comment by jtpio** [comment]
Maybe that could be closed together with #168?

@psychemedia would you like to submit a PR? Thanks!

**Comment by psychemedia** [comment]
@jtpio So subdirs as part of an examples reorg?

Looking at examples, this could be s/thing like:

```
kernels
- js - basics.ipynb
- p5 - basics.ipynb
widgets
- py - basics.ipynb
- py - widgets.ipynb
- py - widgets - bqplot.ipynb
- py - widgets - leaflet.ipynb
```

but that feels a bit all over the place?

So maybe s/thing more like:

```
js kernel examples
- js - basics.ipynb
py kernel examples:
- py - basics.ipynb
- py - widgets.ipynb
- py - widgets - bqplot.ipynb
- py - widgets - leaflet.ipynb
```

I think the latter scales better and less scattered.

**Comment by jtpio** [comment]
The seconds looks good.

There are also other GeoJSON and Vega files that we could leave at the top-level.

**Comment by bollwyvl** [comment]
Looks like this is done
