### ISSUE TITLE
is the "slideshow" mode available in Jupyterlite-0.4.3  ?

### ISSUE THREAD

**Issue by stonebig** [jupyterlite/jupyterlite#1503]
The "SlideShow" mode , that I presume would use the metadata , would be a really nice addition.

Main Need is to "hide" some big cells of code.

Maybe it's available, but I failed to guess how to activate it... a link would be appreciated

![image](https://github.com/user-attachments/assets/12c9785e-9ff4-4a3d-b785-bfbf4b5d5d85)

**Comment by jtpio** [comment]
Maybe one these two extensions would work with JupyterLite?

- https://github.com/jupyterlab-contrib/rise
- https://github.com/deathbeds/jupyterlab-deck

**Comment by stonebig** [comment]
I discovered the menu option to compact a given cell , which is enough for my use case

**Comment by thomasliebig** [comment]
For anyone coming across this looking for RISE-style presentations in JupyterLite: I have been experimenting with a small JupyterLite-compatible implementation here:

[https://github.com/thomasliebig/RISE-lite](https://github.com/thomasliebig/RISE-lite)

It uses the usual notebook slideshow metadata and may be useful as another reference point for this use case.
