### ISSUE TITLE
Jupyterapp is not always available as global Javascript object

### ISSUE THREAD

**Issue by MRYingLEE** [jupyterlite/jupyterlite#1505]
I am trying to make a Chrome extension for Jupyterlite.

In some distribution, such as the official https://jupyterlite.readthedocs.io/en/stable/_static/lab/index.html?path=intro.ipynb, there is a global Jupyterapp. 
![image](https://github.com/user-attachments/assets/e07feb85-2cf8-45bb-86d8-1e006f9c7b54)

While in some, such as https://jtp.io/lit/lab/index.html, there is no such a global Javascript object.

It puzzles me. 

Please clarify,

**Comment by jtpio** [comment]
It follows the JupyterLab `exposeAppInBrowser` page config option, which is set here for https://jupyterlite.readthedocs.io :

https://github.com/jupyterlite/jupyterlite/blob/bcc7ac780bb49914c7130e76bef12ad0b7db8432/examples/jupyter-lite.json#L6

It's enabled only in a couple of places to allow for debugging and fiddling with the API. But it's usually not recommended to enable it for real deployments.

**Comment by MRYingLEE** [comment]
Thanks
