### ISSUE TITLE
File size in the DriveFS is broken

### ISSUE THREAD

**Issue by juntyr** [jupyterlite/jupyterlite#1508]
## Description

In jupyterlite-core v0.4.3, file sizes in the DriveFS (e.g. via `os.stat`) are broken. Downgrading to v0.4.2 changes the breakage (less cases are affected) but doesn't fix it. Since #1497 seems to have touched this code, @katotetsuro might be able to find the issue.

## Reproduce

1. Go to https://jupyterlite.readthedocs.io/en/stable/_static/lab/index.html in a browser that supports the service worker so that DriveFS will be used (check the console)
2. Open a new notebook
3. Run the following code:

```python
import os

with open("a.txt", "wb") as f:
    f.write(b"abc" * 1000)

print(os.path.getsize("a.txt"))
# prints 0 (wrong)

with open("a.txt", "rb") as f:
    print(len(f.read()))
# prints 3000 (correct)
```

This issue is also related to #1472: opening the file in write mode again (which should reset the file to zero size) just overrides existing content but never truncates the length.

## Expected behavior

File sizes should be correct and truncating writes should work.

## Context
- JupyterLite version: 0.4.3

**Comment by katotetsuro** [comment]
Hello,

I am currently reading about the implementation of DriveFS, so I am not very familiar with it yet.

However, I confirmed that by adding the size attribute set in this way and saving the size when creating the file, print(os.path.getsize("a.txt")) outputs 3000 at that point.

https://github.com/jupyterlite/jupyterlite/compare/main...katotetsuro:jupyterlite:feature/drivefs-size-attr

(Note: pyodide kernel also needs to be built using the modified jupyterlite-core)

The changes in contents.ts are still tentative, but I hope this might be of some help to you.

**Comment by juntyr** [comment]
> Hello,
> 
> I am currently reading about the implementation of DriveFS, so I am not very familiar with it yet.
> 
> However, I confirmed that by adding the size attribute set in this way and saving the size when creating the file, print(os.path.getsize("a.txt")) outputs 3000 at that point.
> 
> [main...katotetsuro:jupyterlite:feature/drivefs-size-attr](https://github.com/jupyterlite/jupyterlite/compare/main...katotetsuro:jupyterlite:feature/drivefs-size-attr)
> 
> (Note: pyodide kernel also needs to be built using the modified jupyterlite-core)
> 
> The changes in contents.ts are still tentative, but I hope this might be of some help to you.

The code looks mostly good - thanks for having a look at it!

I think the setattr for size should also change the content (definitely truncate it if the size is smaller now, I’m not sure if you can also extend it?).

One thing that confused me when trying to understand the contents drive is the constant back and forth between base64. Are contents stored in binary or in base64? If not already, it might make the code a lot clearer if all contents are stored in binary (e.g. in an Uint8Array) so that the file size is always just the binary length. The current code complexity seems to be one cause as to why there are a few issues with the file sizes

**Comment by katotetsuro** [comment]
Hi @martinRenou , I just opened this PR

https://github.com/jupyterlite/jupyterlite/pull/1511

I haven't read much of the FileSystem code, so I'd appreciate any feedback on the approach. Also, what do you think about @juntyr 's opinion?

There is an issue with the following code where the file size is not becoming 0, and I believe this must be fixed.

```
import os

with open("a.txt", "wb") as f:
    f.write(b"abc" * 1000)

print(os.path.getsize("a.txt"))
# prints 3000 (by my modification)

with open("a.txt", "rb") as f:
    pass
print(os.path.getsize("a.txt"))
# prints 3000 (should be 0)
```

As for saving data in binary, I think it seems like a good idea. However, my opinion is that it would be better to separate that from this PR.

**Comment by martinRenou** [comment]
Thanks a lot for opening a PR! I will comment there.

> Are contents stored in binary or in base64? 

IIRC everything that's not plain text or JSON (for notebooks) will be stored in base64. I'd be 👍🏽 for trying to store everything in Uint8Array. That may improve performances and simplify the code indeed. I'm not sure how many changes that involves.

> As for saving data in binary, I think it seems like a good idea. However, my opinion is that it would be better to separate that from this PR.

Agreed 👍🏽
