### ISSUE TITLE
Better manage the extra Python packages

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#151]
As a follow-up to #145, we should consider improving the way extra dependencies are handled for the Python kernel.

There is some metadata here:

https://github.com/jtpio/jupyterlite/blob/5f38f5cfbf373ad2c8a6c4bfd4f2d54124c36525/packages/pyolite-kernel/package.json#L66-L73

And the wheels are referenced here: 

https://github.com/jtpio/jupyterlite/blob/5f38f5cfbf373ad2c8a6c4bfd4f2d54124c36525/packages/pyolite-kernel/src/kernel.ts#L11-L14

Ideally there should be a single source of truth and a more streamlined way for managing these extra packages.

**Comment by bollwyvl** [comment]
I'm also passing the buck from #147 on federated-extensions-by-wheel here, as these approaches likely needs to work together _and_ be user-serviceable.

I'm leaning towards a `requirements.txt`-compatible approach, but don't know how one would differentiate between wheels meant to meant to be:
- served raw to pyodide
- unpacked and have `data_files` extracted

**Comment by bollwyvl** [comment]
With #238 in which handles wheel/conda packages for non-kernel-specific extensions, and hopefully close to merging, we have:

- a cache dir
- some basic download tooling

I think to finish out this one, and take some strides towards #225, some of the pyolite issues can start to be addressed.

This would do some new stuff during the lifecycle:
- `post_init`: copy our pre-built patched wheels for `ipy*` to the `{output_dir}/pyolite/wheels` 
- `pre_build`: copy user-specified local/downloaded wheels to same
- `post_build` create a cut-down `https://pypi.org/pypi/jupyterlite/json` in, i guess, `{output_dir}/pyolite/api/{pkg}.json`, for each of the packages, 

This would require patching `micropip` to be aware of multiple sources of files, effectively additional indexes (which we could support at the same time, though I don't know if everyone's custom registry supports the JSON API... so maybe the old-school `https://pypi.org/simple/` approach is better).

#45 is harder. The distribution stance for `pyodide` (196mb off github actions) is still a bit further off, as we'd want to see what 0.18 does, as well as how "normal means" distribution through `npm` works. If it ends up that just the stack up to `micropip` is available as a single package, we would probably be able to ship that on `pip`.

**Comment by bollwyvl** [comment]
I don't think we can do much more here!
