### ISSUE TITLE
Consider improving the message handling in the web worker

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#152]
Maybe we can get clever here in type-land, and use the [`switch ... never` pattern](https://javascript.plainenglish.io/never-miss-a-switch-case-with-typescript-684bf5d0e1d1?gi=6215774607fe). Indeed, it might be that it's actually `IKernel<T, U>` where `T` and `U` are the `messageTypes` it accepts/creates respectively.

_Originally posted by @bollwyvl in https://github.com/jtpio/jupyterlite/pull/145#discussion_r652771832_

**Comment by bollwyvl** [comment]
I think this has a few layers. I think we can agree a given kernel either can or cannot be the receiver of a given Jupyter Kernel `messageType`. So `T` is that set. Similarly `U` is the set of messages it might emit.

So the full signature of a message handler might boil down to:

```ts
async handleMessage(msg: KernelMessage<T>): Promise<void> {
  // This _might_ be doable with polymorphic overrides...
  switch (msg.msgType) {
    case 'a-message-in-T':
      // ...
      break;
    default:
      // do the `never` trick
  }
}
```


Whereas some signal or callback or something would be decorated with `U`. The implementation would **statically** tell you if you hadn't implemented all the _claimed_ features, the bare minimum: probably `kernel_info` and `execute_request`... everything else is kinda optional (or at least the clients can tolerate not having them). But this coul get interesting, as we could establish e.g. `TInIPython` as the set of, well, _everything_ probably, which would be an _aspirational_ target for browser kernels.

Where this gets interesting, with quick nod to [comlink](https://github.com/GoogleChromeLabs/comlink#typescript):

> Comlink does provide TypeScript types. When you `expose()` something of type `T`, the corresponding `wrap()` call will return something of type `Comlink.Remote<T>`. While this type has been battle-tested over some time now, it is implemented on a best-effort basis. There are some nuances that are incredibly hard if not impossible to encode correctly in TypeScript’s type system. It may sometimes be necessary to force a certain type using as `unknown as <type>`.

```ts
// kernel.ts
import * as Comlink from 'comlink';
//...
export class WorkerKernel implements IKernel<TInPython, TOutPython> {
 // this._worker = new Worker(window.URL.createObjectURL(blob));
  this._comlink = ComLink.wrap(new Worker(...)) // as Comlink.Remote<IKernel<TInIPython, TOutIPython>>;
  async handleMessage(msg: KernelMessage<TInIPython>): Promise<void> {
    return await this._comlink.handleMessage(msg);
  }
  async start() {
    while(!this.isDisposed) {
      this.emitMessage(await this._comlink.nextMessage()); // as KernelMessage<U>
    }
  }
}
```

```ts
// worker.ts
// ... the Blob has added equivalent to
//     importScripts("https://unpkg.com/comlink/dist/umd/comlink.js");
const kernel: IKernel<TInIPython, TOutIPython> = new LanguageKernelX(self)
// do <language X stuff>
Comlink.expose(self.kernel);
```

Hopefully this in turn will allow us to put _any_ kernel within a worker, which is really where we will quickly need anything of any heft actually occurring. This is _in addition_ to "artistic" kernels that can use an `IFrame`, or :scream: the main loop. 

So for the pyodide case:
```py
import js
await js.kernel.sendMessage("something in <U>")
```

...but more practically, shimmed to quack like `IPython` and `ipykernel`. On top of this could be built comms, as a `T,U,V` model, but lets not get ahead of ourselves!

**Comment by bollwyvl** [comment]
#655 adds comlink: there are a few remaining `postMessage` uses, but there is a clear path forward to well-typed kernels that abstract away the specific runner.
