### ISSUE TITLE
Widgets support, nested binary buffers don't work

### ISSUE THREAD

**Issue by martinRenou** [jupyterlite/jupyterlite#153]
## Description

In Pyolite, binary buffers seem to work properly in simple cases, but there are cases when it crashes JS side.

## Reproduce

Install bqplot and run the following:

```python
from bqplot import *

import numpy as np
import pandas as pd

np.random.seed(0)
y1 = np.cumsum(np.random.randn(150)) + 100.
y2 = np.cumsum(np.random.randn(150)) + 100.
y3 = np.cumsum(np.random.randn(150)) + 100.
y4 = np.cumsum(np.random.randn(150)) + 100.

sc_x = LinearScale()
sc_y = LinearScale()

lines = Lines(x=np.arange(len(y1)), y=[y1, y2, y3, y4],
             scales={'x': sc_x, 'y': sc_y})
ax_x = Axis(scale=sc_x, label='Index')
ax_y = Axis(scale=sc_y, orientation='vertical', label='lines')

Figure(marks=[lines], axes=[ax_x, ax_y], title='Lines')
```

## Context

I suppose it has to do with deserialization of the binary buffers.

**Comment by madhur-tandon** [comment]
Seems like the error occurs while serialising the following message:

```
{
  "channel": "iopub",
  "content": {
    "data": {
      "state": {
        "_model_module": "bqplot",
        "_model_module_version": "^0.5.31",
        "_model_name": "LinesModel",
        "_view_module": "bqplot",
        "_view_module_version": "^0.5.31",
        "_view_name": "Lines",
        "apply_clip": true,
        "close_path": false,
        "colors": [
          "#1f77b4",
          "#ff7f0e",
          "#2ca02c",
          "#d62728",
          "#9467bd",
          "#8c564b",
          "#e377c2",
          "#7f7f7f",
          "#bcbd22",
          "#17becf"
        ],
        "curves_subset": [],
        "display_legend": false,
        "enable_hover": true,
        "fill": "none",
        "fill_colors": [],
        "fill_opacities": [],
        "interactions": {
          "hover": "tooltip"
        },
        "interpolation": "linear",
        "labels": [],
        "labels_visibility": "none",
        "line_style": "solid",
        "marker_size": 64,
        "opacities": [],
        "preserve_domain": {},
        "scales": {
          "x": "IPY_MODEL_069fd001e45f475a912a2e2fb6dc70bf",
          "y": "IPY_MODEL_57f75601c29c457482711cc8c2a14a8c"
        },
        "scales_metadata": {
          "x": {
            "orientation": "horizontal",
            "dimension": "x"
          },
          "y": {
            "orientation": "vertical",
            "dimension": "y"
          },
          "color": {
            "dimension": "color"
          }
        },
        "selected_style": {},
        "stroke_width": 2,
        "tooltip_location": "mouse",
        "tooltip_style": {
          "opacity": 0.9
        },
        "unselected_style": {},
        "visible": true,
        "x": {
          "dtype": "int32",
          "shape": [
            150
          ]
        },
        "y": {
          "dtype": "float64",
          "shape": [
            4,
            150
          ]
        }
      },
      "buffer_paths": [
        [
          "x",
          "value"
        ],
        [
          "y",
          "value"
        ]
      ]
    },
    "comm_id": "fea0976a67bb4788aa90a0d54fda8d0a",
    "target_name": "jupyter.widget"
  },
  "header": {
    "date": "2021-07-19T11:22:46.706Z",
    "msg_id": "e23f2c35-78ce-4c6a-a095-4a6aaeeee942",
    "msg_type": "comm_open",
    "session": "eef53da0-d3ab-43ac-9e6b-d37cd052e646",
    "username": "",
    "version": "5.2"
  },
  "metadata": {
    "version": "2.0.0"
  },
  "parent_header": {
    "date": "2021-07-19T11:22:40.876Z",
    "msg_id": "e416261d-f857-40bc-9e48-6d1fb309bddd",
    "msg_type": "execute_request",
    "session": "eef53da0-d3ab-43ac-9e6b-d37cd052e646",
    "username": "",
    "version": "5.2"
  }
}
```

**Comment by madhur-tandon** [comment]
Uncaught RangeError: offset is outside the bounds of the DataView.

It seems like the error is in the line `const message = serialize(msg);`
But, it's imported here: `import { deserialize, serialize } from '@jupyterlab/services/lib/kernel/serialize';`

Perhaps the implementation here is not able to support this. 

Inside `serialize` (wherever that function is, I cannot see it inside the repository), the error seems to come from `view.setUint32(0, nbufs);` with the message `Uncaught RangeError: offset is outside the bounds of the DataView`

**Comment by madhur-tandon** [comment]
Maybe we can use `formatResult` instead of `serialize` here? The objective of `serialize` I assume is to convert a Python dict like structure into a JS object. Thus, maybe `formatResult` could replace `serialize` here?

**Comment by martinRenou** [comment]
> Inside serialize (wherever that function is, I cannot see it inside the repository)

This is coming from JupyterLab https://github.com/jupyterlab/jupyterlab/blob/master/packages/services/src/kernel/serialize.ts

> Maybe we can use formatResult instead of serialize here? The objective of serialize I assume is to convert a Python dict like structure into a JS object. Thus, maybe formatResult could replace serialize here?

Nope. This is in no way specific to Pyolite, so `formatResult` cannot be used here.

I believe the issue is with serialization of nested binary buffers. It would actually be a fix to push in JupyterLab itself, but as a good start you could copy/paste the serialize function into JupyterLite and try to fix it here for now.

**Comment by madhur-tandon** [comment]
I think I have been able to dig down a bit.

Here is the issue.

<img width="726" alt="Screenshot 2021-07-20 at 10 53 39 AM" src="https://user-images.githubusercontent.com/20173739/126266277-6716db78-e97e-49e3-a1be-e3183623a7cc.png">

In the screenshot above, this variable has 2 elements. One of them is a normal array of 150 elements.
The second one is an array which further contains 4 arrays as it's elements.

The issue is in the line `buffers.push(ArrayBuffer.isView(b) ? b.buffer : b);` here: https://github.com/jupyterlab/jupyterlab/blob/7c228f11e08b29dd1523116a271a858a70ba14c4/packages/services/src/kernel/serialize.ts#L87

When you execute it, the `buffers` variable ends up with the following:

<img width="619" alt="Screenshot 2021-07-20 at 10 58 39 AM" src="https://user-images.githubusercontent.com/20173739/126266672-bd152e62-677a-45f1-9b70-d0ce5f74f39d.png">

Then, in the line `offsets[offsets.length - 1] + buffers[buffers.length - 1].byteLength` here: https://github.com/jupyterlab/jupyterlab/blob/7c228f11e08b29dd1523116a271a858a70ba14c4/packages/services/src/kernel/serialize.ts#L95

`buffers[buffers.length - 1].byteLength` tries to access the `byteLength` property of the last element i.e. the nested array which is `undefined`.

Thus, this sum of `offsets[offsets.length - 1] + buffers[buffers.length - 1].byteLength` amounts to `NaN`.

which means `msgBuf` is an empty `Uint8Array`. Thus the line `const view = new DataView(msgBuf.buffer);` creates an empty `DataView` which essentially means `Uncaught RangeError: offset is outside the bounds of the DataView` error for the line `view.setUint32(0, nbufs);`

**Comment by martinRenou** [comment]
You basically want `serialize` to support nested arrays.

As you can see, `serialize` is turning the first `Int32Array` into an `ArrayBuffer` (this seems to be the serializing step for an array buffer). The `serialize` function loops over all the arrays to apply this change to all of them. But it doesn't work if there is an array of arrays. 

You basically want to modify `serialize` so that it recursively serialize all arrays, even the nested ones.

**Comment by madhur-tandon** [comment]
Even if I convert the nested arrays to `ArrayBuffer`, the outer array is still an array and not an `ArrayBuffer` while it's constituents are an `ArrayBuffer` i.e. a structure like this will exist:

<img width="521" alt="Screenshot 2021-07-20 at 12 19 18 PM" src="https://user-images.githubusercontent.com/20173739/126274818-48bb111b-b150-43a7-ac8b-18b66a2a2278.png">

Even then, we cannot access the `byteLength` property of this outer array.

**Comment by martinRenou** [comment]
> Even then, we cannot access the byteLength property of this outer array.

I guess because the rest of the code assumes you only have `ArrayBuffer` objects, you might want to change that

**Comment by madhur-tandon** [comment]
Did some logic to convert a tree structure to a linear one here: https://github.com/jupyterlite/jupyterlite/pull/280

**Comment by bollwyvl** [comment]
With #280, is this complete?

**Comment by martinRenou** [comment]
Yes, the issue seems to be resolved now! Thanks again @madhur-tandon :D
