### ISSUE TITLE
sympy no longer working due to now depending on on mpmath

### ISSUE THREAD

**Issue by drjwhitty** [jupyterlite/jupyterlite#1548]
First of all many thanks for this wonderful facility. I have been integrating usage across our undergraduate University Centre teaching.

## Description

Nothing at all now loads from the sympy library it being dependent on mpmath.

## Reproduce

Simply typing any call from sympy results in the error, e.g.:

from sympy import symbols

Results in with the error message
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
File /lib/python3.12/site-packages/sympy/__init__.py:22
     21 try:
---> 22     import mpmath
     23 except ImportError:

ModuleNotFoundError: No module named 'mpmath'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
Cell In[9], line 1
----> 1 from sympy import symbols

File /lib/python3.12/site-packages/sympy/__init__.py:24
     22     import mpmath
     23 except ImportError:
---> 24     raise ImportError("SymPy now depends on mpmath as an external library. "
     25     "See https://docs.sympy.org/latest/install.html#mpmath for more information.")
     27 del mpmath
     29 from sympy.release import __version__

ImportError: SymPy now depends on mpmath as an external library. See https://docs.sympy.org/latest/install.html#mpmath for more information.

## Expected behavior

The symbols command to become available in the the note book

## Context

- JupyterLite version: 0.4.5
- Operating System and version: Linux mint 22 (64-bit)
- Browser and version: Mozilla Firefox for Linux Mint

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by bollwyvl** [comment]
Without knowing which kernel this is, will have to assume `jupyterlite-pyodide-kernel`: `pyodide`'s `sympy` has had the [`mpmath` dependency](https://github.com/pyodide/pyodide/blame/main/packages/sympy/meta.yaml#L9) for several years.

I can't reproduce this on any of the sites I have at hand:

- https://jupyterlite.readthedocs.io/en/stable/_static/lab/index.html
- https://jupyterlite.readthedocs.io/en/latest/_static/lab/index.html
- https://jupyterlite-pyodide-kernel.readthedocs.io/en/latest/_static/lab/index.html
- https://jupyterlite-pyodide-kernel.readthedocs.io/en/stable/_static/lab/index.html

**Comment by drjwhitty** [comment]
Hi Nicholas,

Many thanks for getting back to me so promptly.

I am very sorry to have bothered you with this. I have just tried to repeat
this again after reopening a Firefox browser and all now seems well.
I can't for the life of me think what was up with it.

Best wishes,

Justin
