### ISSUE TITLE
Document developing JupyterLab federated extensions with JupyterLite 

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#187]
### Problem

With the `jupyterlite` cli now available on PyPI, folks could technically develop lab extensions with it.

### Proposed Solution

Extension authors would use the same workflow as for developing normal prebuilt JupyterLab extensions.

Normally the only thing needed might be to symlink the extensions under `PREFIX/share/jupyter/labextensions` to the lite output directory for convenience. 

### Additional context

This was mentioned by @krassowski in https://github.com/jtpio/jupyterlite/issues/79#issuecomment-828691956

**Comment by bollwyvl** [comment]
Actually, they can just get dropped right into place in `{lite_dir}/lab/extensions/{org/?}{pkg}`, and they'll get picked up by the indexing step. So either a normal `jupyter labextension build` to a regular `outputDir`, and copy, or just set `outputDir` directly. Of course, one _would_ need nodejs, etc. as `remoteEntry` and the resulting critical `package.json` metadata are... not human writeable.

This is an usecase where grabbing the `doit` stuff would be particularly useful.

At any rate, i'll probably be adding something like this to `ipydrawio` pretty soon, so will be able to report back with lessons learned.

**Comment by jtpio** [comment]
> So either a normal `jupyter labextension build` to a regular `outputDir`, and copy, or just set `outputDir` directly

Right, that should definitely work.

Although extension authors might start from the cookiecutter, which also sets up the Python package and puts things under `PREFIX/share/jupyter/labextensions`, and the `jupyter labextension develop` creates the symlink to `outputDir`. So maybe we could just plug on that. In the end the lab extensions should be built for JupyterLab anyway.

**Comment by jtpio** [comment]
Another advantage: this would make it very convenient to have faster PR previews for pure frontend lab extensions in general, as an alternative to Binder. 

Especially since dependencies for pure frontend lab extensions are usually always the same (mostly `jupyterlab`).

**Comment by jtpio** [comment]
> Another advantage: this would make it very convenient to have faster PR previews for pure frontend lab extensions in general, as an alternative to Binder.

Playing around with this idea in this toy repo: https://github.com/jtpio/jupyterlite-labextension-example

Following up on #228 

The deploy previews PRs could be really useful for dev workflows, when the lab extension is a pure frontend extension compatible with lite (in this example generated from the cookiecutter): https://github.com/jtpio/jupyterlite-labextension-example/pull/1

![image](https://user-images.githubusercontent.com/591645/124813239-eebcb400-df64-11eb-915b-775b792b489c.png)

**Comment by jtpio** [comment]
This could now be documented with [jupyterlite-sphinx](https://github.com/jupyterlite/jupyterlite-sphinx) to also show how to setup PR previews.

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlite/jupyterlite/pull/641.
