### ISSUE TITLE
ESLint allocation failure errors

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#194]
## Description

This seems to be happening more often lately.

Sometime running ESLint automatically on commits might trigger the following error:

```
<--- Last few GCs --->

[950841:0x55dffd287ed0]    25909 ms: Mark-sweep (reduce) 2046.1 (2051.7) -> 2045.4 (2053.0) MB, 815.8 / 0.0 ms  (average mu = 0.132, current mu = 0.008) allocation failure scavenge might not succeed
[950841:0x55dffd287ed0]    27405 ms: Mark-sweep (reduce) 2046.5 (2052.0) -> 2045.7 (2053.0) MB, 1487.0 / 0.0 ms  (average mu = 0.053, current mu = 0.006) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x7fe812c92489 node::Abort() [/home/jtp/miniforge3/envs/jupyterlite-dev/bin/../lib/libnode.so.83]
 2: 0x7fe812ba5dbe std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > node::SPrintFImpl<char const*>(char const
```

## Reproduce

It might be possible to reproduce by just running `doit lint` at the top-level.

## Expected behavior

ESLint shouldn't crash.

## Context

Probably we are missing some ignore clauses in the `.eslintignore`?

**Comment by jtpio** [comment]
Seeing that one locally even when committing a single file: https://github.com/jupyterlite/jupyterlite/blob/main/packages/application-extension/src/index.tsx

Could be because this one is a `.tsx`.

**Comment by bollwyvl** [comment]
So setting `DEBUG='*' doit lint` shows... everything. There's some graphviz in there. Last time a spent a bit with this, it seemed to reliably fail on initializing typescript. Similar to the webpack fail, we can try `--cache`, and _hope_ that if it OoMs, it will be able to pick up where it left off, but with slightly more done.

Getting to where we can use clean-webpack-plugin would probably _also_ help, as i just don't know whether spoor from multiple builds is causing issues (we ignore `**/build/**` but :shrug: )

**Comment by jtpio** [comment]
Seeing that one less often now with #240, although the eslint check still takes quite a bit of time on commit.

**Comment by jtpio** [comment]
> Seeing that one less often now with #240, although the eslint check still takes quite a bit of time on commit.

Still seeing it on the latest `main`.

**Comment by jtpio** [comment]
Still seeing these errors when overall RAM usage is high:

![image](https://user-images.githubusercontent.com/591645/156735129-e23e7670-28e4-4586-a2fc-3dad8a336ab8.png)

**Comment by jtpio** [comment]
Reopening as this still seems to be happening, also for other folks.

cc @martinRenou

**Comment by jtpio** [comment]
Looks like this might be more an issue with `@typescript-eslint`: https://github.com/typescript-eslint/typescript-eslint/issues/1192

Running eslint with `--debug` shows that it goes oom after trying to parse a TypeScript project:

```
  eslintrc:ignore-pattern Check {
  filePath: '/home/jtp/git/jtpio/jupyterlite/packages/_metapackage/src/index.ts',
  dot: false,
  relativePath: 'packages/_metapackage/src/index.ts',
  result: false
} +0ms
  eslint:file-enumerator Yield: index.ts +1ms
  eslintrc:cascading-config-array-factory Load config files for /home/jtp/git/jtpio/jupyterlite/packages/_metapackage/src. +1ms
  eslintrc:cascading-config-array-factory Cache hit: /home/jtp/git/jtpio/jupyterlite/packages/_metapackage/src. +0ms
  eslint:cli-engine Lint /home/jtp/git/jtpio/jupyterlite/packages/_metapackage/src/index.ts +0ms
  eslint:linter Linting code for /home/jtp/git/jtpio/jupyterlite/packages/_metapackage/src/index.ts (pass 1) +0ms
  eslint:linter Verify +0ms
  eslint:linter With ConfigArray: /home/jtp/git/jtpio/jupyterlite/packages/_metapackage/src/index.ts +0ms
  eslint:linter Parsing: /home/jtp/git/jtpio/jupyterlite/packages/_metapackage/src/index.ts +3ms
```

![image](https://github.com/jupyterlite/jupyterlite/assets/591645/a68a5b92-7ffb-48e8-ada2-4deba233a167)

**Comment by jtpio** [comment]
Looks like https://github.com/jupyterlite/jupyterlite/pull/1212 should help.

But we can still re-open the issue if not.
