### ISSUE TITLE
PIL Image does not display

### ISSUE THREAD

**Issue by dsblank** [jupyterlite/jupyterlite#223]
## Description

PIL Image should display, but does not.

## Reproduce

Small reproducible example:

```python
from PIL import Image
Image.new("RGB", (100, 100))
```

Gives this output:

![Screenshot from 2021-07-06 15-45-59](https://user-images.githubusercontent.com/168568/124675320-5691d280-de71-11eb-9098-bf620d9aece6.png)

which shows that the error is:

```html
<img src="data:image/png;base64,[object Object]">
```
but it should be:

![Screenshot from 2021-07-06 15-50-19](https://user-images.githubusercontent.com/168568/124675655-e6378100-de71-11eb-92e9-35df113fee7e.png)

I'd be glad to look at this, but not sure where to begin. Maybe a missing tostring() on Bytes?

**Comment by bollwyvl** [comment]
What about calling display on it? All the _repr_ stuff isn't quite
working...

**Comment by dsblank** [comment]
```python
from PIL import Image
display(Image.new("RGB", (100, 100)))
```
gives the same results.

FYI: what I'm working on: a pure-Python robot simulator (part of a collection of tools for exploring AI, ML, and Robotics), that is looking like it will work fine in JupyterLite:

![Screenshot from 2021-07-06 15-59-56](https://user-images.githubusercontent.com/168568/124676368-47ac1f80-de73-11eb-8430-73dd64920cb9.png)

I wasn't sure how the speed would compare. Currently it is running about 6 times slower in the Pyolite than in Python 3.8 in JupyterLab.

**Comment by bollwyvl** [comment]
re: speed. Yerp. The forthcoming pyodide (based on 3.9) upgrades half the universe and adds a lot more ctypes stuff. Building new stuff close to pyodide is... not fun, though.

**Comment by dsblank** [comment]
My suspicion seems to be correct. If you:

```python
class MyClass:
    def _repr_png_(self):
        return b"xxx"
i = MyClass()
i
```

you'll find that bytes don't know how to display themselves, and you get `[object Object]`:

```html
<img src="data:image/png;base64,[object Object]">
```
So, now the question is: what to do?

**Comment by bollwyvl** [comment]
Welp, both the [upstream](https://github.com/ipython/ipython/blob/7.25.0/IPython/core/display.py#L1102) and the [pyolite](https://github.com/jtpio/jupyterlite/blob/v0.1.0a3/packages/pyolite-kernel/py/pyolite/pyolite/display.py#L8) implementations do their own `base64` stuff... so if you subclass `pyolite.display.Image` (or, as of about this morning, `IPython.core.display.Image`) you should get that "for free".

Perhaps there's a special case for PIL.Image somewhere...

**Comment by dsblank** [comment]
I think I see! Yes, there is a special case, and it is in PIL itself:

https://github.com/python-pillow/Pillow/blob/master/src/PIL/Image.py#L672

If that is changed to:

```python
    def _repr_png_(self):
        """iPython display hook support
        :returns: png version of the image as bytes
        """
        b = io.BytesIO()
        try:
            self.image.save(b, "PNG")
        except Exception as e:
            raise ValueError("Could not save to PNG for display") from e
        data = b.getvalue()
        return base64.b64encode(data).decode()
```
then it works as desired. 

How to fix? Monkeypatch? Or someway to have bytes automatically do this when needed?

**Comment by bollwyvl** [comment]
I think if you can get a sweet robot demo out that (restart-and-)run-alls, then you have won.

```py
from PIL import Image

try:
    import pyolite, base64
    _og_repr_png_ = Image.Image._repr_png_ if "_og_repr_png_" not in locals() else _og_repr_png_
    Image.Image._repr_png_ = lambda x: base64.b64encode(_og_repr_png_(x)).decode("utf-8")
except ImportError:
    pass
```

We'd probably have to dig around a fair amount to figure out who is magically transforming the bytes, though...

**Comment by dsblank** [comment]
Nice little monkey patch, and it works! What should be the action item here? You have a set of patches for now to add this to?

**Comment by jtpio** [comment]
There is one for `matplotlib` in https://github.com/jtpio/jupyterlite/blob/5853f64f339b63cd022a2e1bc4bba2370331f5b2/packages/pyolite-kernel/py/pyolite/pyolite/patches.py#L12.

So maybe we could add it there.

**Comment by jtpio** [comment]
If that sounds good to you @dsblank, would you like to give it a try and open a PR? We could also add PIL to one of the example notebooks. Thanks!

**Comment by dsblank** [comment]
Yes, I will try that now. Thanks!

**Comment by bollwyvl** [comment]
I feel like an initial notebook that uses the hack is a definite win.

I've mentioned elsewhere, every additional package we patch the heavy way (and therefore have to import) makes every demo slower, and causes potentially pointless loads from pypi.org. I'd rather see us capture these in as a pattern, either in a `pre_execute` hook (though this gets messy), or more explicitly:

```py
try:
    import pyolite
    with pyolite.patches():
        import PIL, matplotlib
except:
    import PIL, matpllotlib
```

`patches` could also provide a nice output of things it knows how to patch.

As to nuts and bolts: there's [modulefinder](https://docs.python.org/3/library/modulefinder.html)... but it looks likes it only speaks file-on-disk... perhaps we could pre-check whether a cell (or the contents of a contents manager) includes `import` and only use it then. or maybe using `ast` directly is better.

**Comment by dsblank** [comment]
Yes, this method of patching (import the package and patch it) does not scale. If its ok for now, let's add this, and solve the lazy patching pattern in a follow-up PR (or find better ways to solve both of these patch issues). #226 is ready for review.

**Comment by dsblank** [comment]
I'll also add a demo notebook.

**Comment by dsblank** [comment]
Done!
