### ISSUE TITLE
Notebook download strips out end of line characters

### ISSUE THREAD

**Issue by psychemedia** [jupyterlite/jupyterlite#229]
Previously, notebook download would download a JSON formatted file but notebooks now seem to download the file as a single line without end of line characters.

Whilst spotting diffs on notebook `.ipynb` files is often challenging, it is all but impossible if exported files are downloaded without line breaks and then diffed against.

**Comment by jtpio** [comment]
Thanks @psychemedia for reporting.

This indeed sounds like a bug.

**Comment by jtpio** [comment]
Closing as this should now work (tested on the latest):

https://user-images.githubusercontent.com/591645/136377388-bbfae2b1-69e4-49f3-b8c1-5a7127fed3c8.mp4

Feel free to reopen if you are still experiencing the issue. Thanks!

**Comment by jtpio** [comment]
Ah actually the docmanager command doesn't format the content, only the file browser command does.
