### ISSUE TITLE
Show bundled JS libraries, versions, and licenses

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlite/jupyterlite#233]
### Problem

As a JupyterLite site builder or end user, it is pretty hard to know what software are in my final, shipped site.

### Proposed Solution

- enable the [license file webpack plugin](https://github.com/jupyterlab/jupyterlab/blob/v3.1.0b1/jupyterlab/staging/webpack.prod.config.js#L18) 
- add `licensesUrl` to `jupyter-config-data`? (it doesn't load the UI if this is missing)
- add a serverlite route for `/api/licenses`
- implement a license bundle finder
- enable the `@jupyterlab/help-extension:licenses` plugin (if not already done)

### Additional context

Somewhere in the lab 3.1 alpha progression, we got `/api/licenses` into `jupyterlab_server` (and some helper consumer stuff in `jupyterlab`) which reveals the precise name, version, license, and full license text of the core bundle and all federated extensions (there are none in the wild yet) from `(app_dir/static/|labextensions/(*/)?*/)third-party-licenses.json`.

A number of changes occurred along the way, as well as a few regressions, so we might have to wait for #207  `b2` (with the menu fix) but otherwise should be fairly straightforward.

**Comment by bollwyvl** [comment]
Our downstream-publishined npm packages lost their LICENSEs at some point:

```
WARNING in license-webpack-plugin: could not find any license file for @jupyterlite/kernel. Use the licenseTextOverrides option to add the license text if desired.

WARNING in license-webpack-plugin: could not find any license file for @jupyterlite/pyolite-kernel. Use the licenseTextOverrides option to add the license text if desired.

WARNING in license-webpack-plugin: could not find any license file for @jupyterlab/services. Use the licenseTextOverrides option to add the license text if desired.
```

@jtpio is this a thing releaser can handle?

**Comment by jtpio** [comment]
@bollwyvl I would say yes.

Do you remember when / if they were ever shipped before?
