### ISSUE TITLE
Lazy Patching

### ISSUE THREAD

**Issue by dsblank** [jupyterlite/jupyterlite#235]
### Problem

Currently, jupyterlite needs to tweak code from some Python libraries. Currently, there are [two patches](https://github.com/jupyterlite/jupyterlite/blob/main/packages/pyolite-kernel/py/pyolite/pyolite/patches.py) to make these tweaks:

* `matplotlib.pyplot.show`
* `PIL.Image.Image._repr_png_`

Eventually we may be able to remove these changes, but, for now, we need to monkey patch them. Currently we import the libraries, and change the methods. This is not ideal because it forces these libraries to be imported, even if they are not used, creating a large startup delay.

### Proposed Solution

A better solution would be to only patch them when we import the code. There are at least two possibilities for monkey patching on import:

* write a custom code loader
* use a existing library, such as [importhook](https://github.com/brettlangdon/importhook)

@bollwyvl said:

> `importhook` looks nice and has no dependencies. a perusal of some of the crazy stuff needed in the example notebooks shows some of the challenges, where to get to something functioning in sys.modules, we need to (for now) to install particular versions of upstreams.

> Looking at those, we might need something that lets us codify `preimport` (and `preinstall`) hooks. However, as we don't have persistence in the WASM filesystem, these are the same... but we're working on that upstream.

> The `preinstall` might be solveable through a patch of `micropip` (which could be done via `importhook`).

> I feel like the long con would be for site builders to be able to add required patches via config file, as their end users shouldn't even know they're doing anything special (aside from perhaps a context manager or a magic).

See also:

1. #227

**Comment by bollwyvl** [comment]
As of #913, we would no longer have _any_ heavyweight patches :tada: !
