### ISSUE TITLE
Replacement for %pip

### ISSUE THREAD

**Issue by dsblank** [jupyterlite/jupyterlite#237]
### Problem

1. The %pip that comes with IPython doesn't work with jupyterlite as there is no shell.
2. ipywidgets is not included, and requires using `await micropip.install()`. This is confusing for new users because it uses asyncio, and because it isn't pip

### Proposed Solution

If we override `%pip`, then we can install ipywidgets (and other packages) without having to use asyncio and micropip. This could make many notebooks 100% identical to their regular IPython brothers.

Here is an implementation (although this is my first asyncio code):

```python
from IPython.core.magic import register_line_magic
from IPython.core import magic_arguments
import asyncio

IN_BROWSER = None
try:
    import micropip
    IN_BROWSER = True
except ImportError:
    IN_BROWSER = False

if IN_BROWSER:
    async def pip_install(package):
        try:
            await micropip.install(package)
            return "    Success! Installed %r" % package
        except Exception as exception:
            return "    Failed installing %r: %s" % (package, exception)

    @register_line_magic
    @magic_arguments.magic_arguments()
    @magic_arguments.argument('-q', '--quiet', help='Give less output.', action='store_true')
    @magic_arguments.argument('command', help="Install.", type=str)
    @magic_arguments.argument('packages', nargs="+", type=str, help='Packages to install.')
    def pip(line):
        args = magic_arguments.parse_argstring(pip, line)
        if args.command == "help":
            print("usage: %pip install package1 package2 ...")
        elif args.command == "install":
            print("Installing %s..." % args.packages)
            loop = asyncio.get_running_loop()
            for package in args.packages:
                task = loop.create_task(pip_install(package))
                task.add_done_callback(
                    lambda t: print(t.result()))
        else:
            print("error: command should be: `install`")
```
If this is a viable solution, where would this code go?

Output examples:

![Screenshot from 2021-07-08 15-54-38](https://user-images.githubusercontent.com/168568/125000248-d7cd9e80-e004-11eb-95f4-507a4888c655.png)

**Comment by bollwyvl** [comment]
This is a good direction, though given how thin the wrapper there is around `pip`... it supports a _lot_ of options, and a lot of them will be nonsense in this context, as micropip sure as shooting won't support all of them.

@martinRenou @madhur-tandon thoughts on the relationship to #216, and specifically, where to land this?

**Comment by bollwyvl** [comment]
Note, though, that delegating to asyncio might _not_ make _restart and run all_ work, as the async tasks will happily keep spinning in the background while additional cells are executed ... might need `run_until_complete` or something.

**Comment by dsblank** [comment]
> might need run_until_complete or something.

That sounds right... I don't know what I am doing with asyncio... I just kept coding until it worked :)

**Comment by martinRenou** [comment]
> @martinRenou @madhur-tandon thoughts on the relationship to #216, and specifically, where to land this?

This PR is unrelated I think. It's just some rework of the code design but it shouldn't change any behavior (although it should have the byproduct of fixing the `Output` widget).

> This is a good direction, though given how thin the wrapper there is around pip... it supports a lot of options, and a lot of them will be nonsense in this context

Makes sense. I guess we could still do it but print a warning, something like `"Warning, this is using `micropip` and might not behave like exactly like `pip`."`

**Comment by dsblank** [comment]
@bollwyvl I have looked high and low, but I am unable to figure out a way to block until these tasks are completed (without having to have an await and async at the top level).

@martinRenou Yes, I think a message stating that this is using micropip would be very helpful. Also, do you know of a good place to put this IPython start-up code for jupyterlite? Then I can start a PR.

**Comment by davidbrochart** [comment]
> @bollwyvl I have looked high and low, but I am unable to figure out a way to block until these tasks are completed (without having to have an await and async at the top level).

Yes, this is an issue since pyodide doesn't support threads and nest-asyncio cannot be used (see #275).

**Comment by bollwyvl** [comment]
Seems like the real would be being able to re-register `%pip` as async: https://github.com/ipython/ipython/issues/11314

Given these, I'm not too even going to try it on #310... but as `piplite` would then be needed to even _install_ `pyolite`, this is still somethign that would be fixed in the kernel itself.

**Comment by oeway** [comment]
Hi, would it be also possible to override `!pip install xxxx` into the micropip version?

**Comment by bollwyvl** [comment]
Potentially... but starting to do one-off shell things is peril-fraught. It
would likely still be very brittle, as different sources say, for various
reasons:

!pip install
!python -m pip install
!pip3 install
!python3 -m pip install

Then there's things like -r and -e which, again, might be possible, but not
fun to handle robustly... And anticipate what pip might change in the
future.

At any rate: at present we're still wedged by our inability to handle
blocking on async-flavored stuff in either pyolite magics or in pyodide
without await.

**Comment by davidbrochart** [comment]
> At any rate: at present we're still wedged by our inability to handle blocking on async-flavored stuff in either pyolite magics or in pyodide without await.

I'm wondering if [syncio](https://github.com/davidbrochart/syncio) could help here. It allows to write something like this:
```python
import asyncio
from syncio import sync

async def async_function():
    await asyncio.sleep(1)

@sync
def sync_wrapper():
    async_function()

sync_wrapper()  # auto-await async_function
```

**Comment by bollwyvl** [comment]
> I'm wondering if syncio could help here. I

Did you try it in lite?

**Comment by davidbrochart** [comment]
Yes but there was a problem with using context variables. Anyway, I don't think this will work because the problem here is that the kernel code is executed from an event loop.
Maybe we could make `pyodide.webloop.WebLoop` patchable by `nest-asyncio`?

**Comment by bollwyvl** [comment]
For a potential solution: went the other way on this on #832, rewriting `%pip` to `await __import__('piplite').install`.
