### ISSUE TITLE
Tracking upstream issues?

### ISSUE THREAD

**Issue by dsblank** [jupyterlite/jupyterlite#242]
Is there a place where upstream work is listed or tracked?

Here is one I just made:

1. https://github.com/ipython/ipython/pull/13050 - allow %time and other clock-based functions to work in jupyterlite

**Comment by jtpio** [comment]
Thanks @dsblank for opening this issue.

For now we have mostly been opening issues on PRs directly on the upstream repos (jupyterlab, matplotlib, widgets) as we go. So they are a bit all over the place.

Maybe we could indeed try to track them for reference.

**Comment by jtpio** [comment]
Most of the time we end up tracking the issue on a case by case basis with links to the other repos as mentioned above.

There is also the `upstream` GitHub label now to make it easier to get a list of these issues: https://github.com/jupyterlite/jupyterlite/labels/upstream

Closing as resolved, but feel free to open a new issue if needed. Thanks!
