### ISSUE TITLE
First cell execution hangs

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlite/jupyterlite#248]
## Description

Trying https://jupyterlite.rtfd.io/en/latest/try/lab, and opening `ipympl.ipynb`, executing the first cell hangs.

## Reproduce

1. Go to https://jupyterlite.rtfd.io/en/latest/try/lab
2. Open the `ipympl.ipynb` notebook
3. Execute the first cell
4. See error in the browser console: `RecursionError: maximum recursion depth exceeded while calling a Python object`

## Expected behavior

It should not hang.

## Context

- Operating System and version: Ubuntu 21.04
- Browser and version: Google Chrome version 91.0.4472.114 (Official Build) (64-bit)
- JupyterLite version: "Version unknown" (from Help -> About JupylerLite)

<details><summary>Browser Output</summary>
<pre>
jupyter-lite.ipynb:1 Failed to load resource: the server responded with a status of 404 ()
/en/latest/_static/jupyter-lite.ipynb:1 Failed to load resource: the server responded with a status of 404 ()
config-utils.js:200 failed get jupyter-config-data from https://jupyterlite.readthedocs.io/en/latest/_static/lab/jupyter-lite.ipynb
getLiteConfig @ config-utils.js:200
config-utils.js:200 failed get jupyter-config-data from https://jupyterlite.readthedocs.io/en/latest/_static/jupyter-lite.ipynb
getLiteConfig @ config-utils.js:200
remoteEntry.ca1efc27dc965162ca86.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/notebook (required ^3.0.0)
s @ remoteEntry.ca1efc27dc965162ca86.js:1
remoteEntry.ca1efc27dc965162ca86.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/logconsole (required ^3.0.0)
s @ remoteEntry.ca1efc27dc965162ca86.js:1
remoteEntry.ca1efc27dc965162ca86.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/settingregistry (required ^3.0.0)
s @ remoteEntry.ca1efc27dc965162ca86.js:1
remoteEntry.ca1efc27dc965162ca86.js:1 Unsatisfied version 6.1.0-alpha.11 of shared singleton module @jupyterlab/services (required ^6.0.0)
s @ remoteEntry.ca1efc27dc965162ca86.js:1
remoteEntry.ca1efc27dc965162ca86.js:1 No satisfying version (^3.0.0) of shared module @jupyterlab/outputarea found in shared scope default.
Available versions: 3.1.0-alpha.11 from _JUPYTERLAB.CORE_OUTPUT
p @ remoteEntry.ca1efc27dc965162ca86.js:1
remoteEntry.ca1efc27dc965162ca86.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/mainmenu (required ^3.0.0)
s @ remoteEntry.ca1efc27dc965162ca86.js:1
remoteEntry.ca1efc27dc965162ca86.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/rendermime (required ^3.0.0)
s @ remoteEntry.ca1efc27dc965162ca86.js:1
remoteEntry.a6d92e11d5e8c375cfe6.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/apputils (required ^3.0.0)
s @ remoteEntry.a6d92e11d5e8c375cfe6.js:1
remoteEntry.db5f6701f7a352750c55.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/apputils (required ^3.0.9)
s @ remoteEntry.db5f6701f7a352750c55.js:1
remoteEntry.145e469029155b53b350.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/apputils (required ^3.0.5)
s @ remoteEntry.145e469029155b53b350.js:1
remoteEntry.8f896d6ad92823566c46.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/mainmenu (required ^3.0.7)
c @ remoteEntry.8f896d6ad92823566c46.js:1
remoteEntry.8f896d6ad92823566c46.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/apputils (required ^3.0.7)
c @ remoteEntry.8f896d6ad92823566c46.js:1
remoteEntry.8f896d6ad92823566c46.js:1 No satisfying version (^3.0.9) of shared module @jupyterlab/docregistry found in shared scope default.
Available versions: 3.1.0-alpha.11 from _JUPYTERLAB.CORE_OUTPUT
v @ remoteEntry.8f896d6ad92823566c46.js:1
remoteEntry.8f896d6ad92823566c46.js:1 Unsatisfied version 5.1.0-alpha.11 of shared singleton module @jupyterlab/coreutils (required ^5.0.5)
c @ remoteEntry.8f896d6ad92823566c46.js:1
remoteEntry.8f896d6ad92823566c46.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/launcher (required ^3.0.7)
c @ remoteEntry.8f896d6ad92823566c46.js:1
remoteEntry.8f896d6ad92823566c46.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/ui-components (required ^3.0.6)
c @ remoteEntry.8f896d6ad92823566c46.js:1
remoteEntry.8f896d6ad92823566c46.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/application (required ^3.0.9)
c @ remoteEntry.8f896d6ad92823566c46.js:1
remoteEntry.8f896d6ad92823566c46.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/filebrowser (required ^3.0.9)
c @ remoteEntry.8f896d6ad92823566c46.js:1
remoteEntry.aa1c31e56033747df726.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/mainmenu (required ^3.0.9)
s @ remoteEntry.aa1c31e56033747df726.js:1
remoteEntry.aa1c31e56033747df726.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/apputils (required ^3.0.9)
s @ remoteEntry.aa1c31e56033747df726.js:1
remoteEntry.aa1c31e56033747df726.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/notebook (required ^3.0.11)
s @ remoteEntry.aa1c31e56033747df726.js:1
remoteEntry.aa1c31e56033747df726.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/application (required ^3.0.11)
s @ remoteEntry.aa1c31e56033747df726.js:1
remoteEntry.aa1c31e56033747df726.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/ui-components (required ^3.0.7)
s @ remoteEntry.aa1c31e56033747df726.js:1
remoteEntry.b1a291f62404c698e709.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/mainmenu (required ^3.0.9)
f @ remoteEntry.b1a291f62404c698e709.js:1
remoteEntry.b1a291f62404c698e709.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/notebook (required ^3.0.11)
f @ remoteEntry.b1a291f62404c698e709.js:1
remoteEntry.b1a291f62404c698e709.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/apputils (required ^3.0.9)
f @ remoteEntry.b1a291f62404c698e709.js:1
remoteEntry.b1a291f62404c698e709.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/statedb (required ^3.0.6)
f @ remoteEntry.b1a291f62404c698e709.js:1
remoteEntry.b1a291f62404c698e709.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/translation (required ^3.0.9)
f @ remoteEntry.b1a291f62404c698e709.js:1
remoteEntry.b1a291f62404c698e709.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/settingregistry (required ^3.0.6)
f @ remoteEntry.b1a291f62404c698e709.js:1
remoteEntry.8511fe06ff367ce48f15.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/apputils (required ^3.0.9)
d @ remoteEntry.8511fe06ff367ce48f15.js:1
remoteEntry.8511fe06ff367ce48f15.js:1 Unsatisfied version 6.1.0-alpha.11 of shared singleton module @jupyterlab/services (required ^6.0.9)
d @ remoteEntry.8511fe06ff367ce48f15.js:1
remoteEntry.8511fe06ff367ce48f15.js:1 Unsatisfied version 5.1.0-alpha.11 of shared singleton module @jupyterlab/coreutils (required ^5.0.6)
d @ remoteEntry.8511fe06ff367ce48f15.js:1
remoteEntry.8511fe06ff367ce48f15.js:1 No satisfying version (^3.0.6) of shared module @jupyterlab/nbformat found in shared scope default.
Available versions: 3.1.0-alpha.11 from _JUPYTERLAB.CORE_OUTPUT
p @ remoteEntry.8511fe06ff367ce48f15.js:1
remoteEntry.8511fe06ff367ce48f15.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/settingregistry (required ^3.0.6)
d @ remoteEntry.8511fe06ff367ce48f15.js:1
remoteEntry.8511fe06ff367ce48f15.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/codemirror (required ^3.0.9)
d @ remoteEntry.8511fe06ff367ce48f15.js:1
remoteEntry.8511fe06ff367ce48f15.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/codeeditor (required ^3.0.9)
d @ remoteEntry.8511fe06ff367ce48f15.js:1
remoteEntry.8511fe06ff367ce48f15.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/notebook (required ^3.0.11)
d @ remoteEntry.8511fe06ff367ce48f15.js:1
remoteEntry.8511fe06ff367ce48f15.js:1 Unsatisfied version 3.1.0-alpha.11 of shared singleton module @jupyterlab/rendermime (required ^3.0.10)
d @ remoteEntry.8511fe06ff367ce48f15.js:1
243.d9d134ad2ffdfb9205b3.js:2 Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. Error
    at https://jupyterlite.readthedocs.io/en/latest/_static/lab/extensions/jupyter-leaflet/static/243.d9d134ad2ffdfb9205b3.js:2:3143
    at Function.C.extend (https://jupyterlite.readthedocs.io/en/latest/_static/lab/extensions/jupyter-leaflet/static/243.d9d134ad2ffdfb9205b3.js:2:3162)
    at Object.665 (https://jupyterlite.readthedocs.io/en/latest/_static/lab/extensions/jupyter-leaflet/static/665.3328989849f89dbc115a.js:1:4763)
    at j (https://jupyterlite.readthedocs.io/en/latest/_static/lab/extensions/jupyter-leaflet/static/remoteEntry.8c5efb3516d04e6a5bb7.js:1:795)
    at https://jupyterlite.readthedocs.io/en/latest/_static/lab/extensions/jupyter-leaflet/static/remoteEntry.8c5efb3516d04e6a5bb7.js:1:3895
    at Object.w.<computed> (https://jupyterlite.readthedocs.io/en/latest/_static/lab/extensions/jupyter-leaflet/static/remoteEntry.8c5efb3516d04e6a5bb7.js:1:9878)
    at j (https://jupyterlite.readthedocs.io/en/latest/_static/lab/extensions/jupyter-leaflet/static/remoteEntry.8c5efb3516d04e6a5bb7.js:1:795)
    at Object.8197 (https://jupyterlite.readthedocs.io/en/latest/_static/lab/extensions/jupyter-leaflet/static/138.dd4ad020192640a8ffae.js:1:60072)
    at j (https://jupyterlite.readthedocs.io/en/latest/_static/lab/extensions/jupyter-leaflet/static/remoteEntry.8c5efb3516d04e6a5bb7.js:1:795)
    at Module.4795 (https://jupyterlite.readthedocs.io/en/latest/_static/lab/extensions/jupyter-leaflet/static/138.dd4ad020192640a8ffae.js:1:43948)
(anonymous) @ 243.d9d134ad2ffdfb9205b3.js:2
index.js:487 Starting app
index.js:489 JupyterLite started, waiting for restore
index.js:491 JupyterLite restored
pyodide.asm.js:9 Python initialization complete
pyodide.js:146 Loading matplotlib, cycler, six, kiwisolver, numpy, pillow, pyparsing, python-dateutil, pytz
pyodide.js:196 Loading matplotlib from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/matplotlib.js
pyodide.js:196 Loading cycler from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/cycler.js
pyodide.js:196 Loading six from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/six.js
pyodide.js:196 Loading kiwisolver from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/kiwisolver.js
pyodide.js:196 Loading numpy from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/numpy.js
pyodide.js:196 Loading pillow from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pillow.js
pyodide.js:196 Loading pyparsing from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pyparsing.js
pyodide.js:196 Loading python-dateutil from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/python-dateutil.js
pyodide.js:196 Loading pytz from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pytz.js
pyodide.js:252 Loaded matplotlib, cycler, six, kiwisolver, numpy, pillow, pyparsing, python-dateutil, pytz
pyodide.js:146 Loading micropip, pyparsing, packaging
pyodide.js:196 Loading micropip from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/micropip.js
pyodide.js:184 pyparsing already loaded from default channel
pyodide.js:196 Loading packaging from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/packaging.js
pyodide.js:252 Loaded micropip, pyparsing, packaging
pyodide.js:146 Loading pytest, atomicwrites, attrs, six, more-itertools, pluggy, py, setuptools, pyparsing
pyodide.js:196 Loading pytest from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pytest.js
pyodide.js:196 Loading atomicwrites from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/atomicwrites.js
pyodide.js:196 Loading attrs from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/attrs.js
pyodide.js:184 six already loaded from default channel
pyodide.js:196 Loading more-itertools from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/more-itertools.js
pyodide.js:196 Loading pluggy from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/pluggy.js
pyodide.js:196 Loading py from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/py.js
pyodide.js:196 Loading setuptools from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/setuptools.js
pyodide.js:184 pyparsing already loaded from default channel
pyodide.js:252 Loaded pytest, atomicwrites, attrs, six, more-itertools, pluggy, py, setuptools, pyparsing
pyodide.js:146 Loading setuptools, jedi, parso, decorator, nose, numpy
pyodide.js:184 setuptools already loaded from default channel
pyodide.js:196 Loading jedi from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/jedi.js
pyodide.js:196 Loading parso from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/parso.js
pyodide.js:196 Loading decorator from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/decorator.js
pyodide.js:196 Loading nose from https://cdn.jsdelivr.net/pyodide/v0.17.0/full/nose.js
pyodide.js:184 numpy already loaded from default channel
pyodide.js:252 Loaded setuptools, jedi, parso, decorator, nose, numpy
e1e4bd72-b6f8-4080-900f-9f962ae36eea:295 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 419, in eval_code_async
    return await CodeRunner(
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 272, in run_async
    await coro
  File "<exec>", line 14, in <module>
  File "/lib/python3.8/site-packages/pyolite/__init__.py", line 22, in <module>
    from .display import LiteStream
  File "/lib/python3.8/site-packages/pyolite/display.py", line 4, in <module>
    from IPython.core.displayhook import DisplayHook
  File "/lib/python3.8/site-packages/IPython/__init__.py", line 56, in <module>
    from .terminal.embed import embed
  File "/lib/python3.8/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 35, in <module>
    from .debugger import TerminalPdb, Pdb
  File "/lib/python3.8/site-packages/IPython/terminal/debugger.py", line 8, in <module>
    from IPython.core.completer import IPCompleter
  File "/lib/python3.8/site-packages/IPython/core/completer.py", line 146, in <module>
    import jedi
  File "/lib/python3.8/site-packages/jedi/__init__.py", line 32, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, preload_module
  File "/lib/python3.8/site-packages/jedi/api/__init__.py", line 22, in <module>
    from jedi.api import classes
  File "/lib/python3.8/site-packages/jedi/api/classes.py", line 24, in <module>
    from jedi.inference.utils import unite
  File "/lib/python3.8/site-packages/jedi/inference/__init__.py", line 70, in <module>
    from jedi.inference import imports
  File "/lib/python3.8/site-packages/jedi/inference/imports.py", line 29, in <module>
    from jedi.inference.gradual.typeshed import import_module_decorator, \
  File "/lib/python3.8/site-packages/jedi/inference/gradual/typeshed.py", line 13, in <module>
    from jedi.inference.gradual.stub_value import TypingModuleWrapper, StubModuleValue
  File "/lib/python3.8/site-packages/jedi/inference/gradual/stub_value.py", line 2, in <module>
    from jedi.inference.value.module import ModuleValue
  File "/lib/python3.8/site-packages/jedi/inference/value/__init__.py", line 5, in <module>
    from jedi.inference.value.klass import ClassValue
  File "/lib/python3.8/site-packages/jedi/inference/value/klass.py", line 48, in <module>
    from jedi.inference.arguments import unpack_arglist, ValuesArguments
  File "/lib/python3.8/site-packages/jedi/inference/arguments.py", line 13, in <module>
    from jedi.inference.value import iterable
  File "/lib/python3.8/site-packages/jedi/inference/value/iterable.py", line 19, in <module>
    from jedi.inference.value.dynamic_arrays import check_array_additions
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 915, in get_code
  File "<frozen importlib._bootstrap_external>", line 973, in get_data
RecursionError: maximum recursion depth exceeded while calling a Python object

    at new_error (pyodide.asm.js:9)
    at wrap_exception (pyodide.asm.wasm:0x1a6c94)
    at FutureDoneCallback_call (pyodide.asm.wasm:0x1aaab3)
    at byn$fpcast-emu$FutureDoneCallback_call (pyodide.asm.wasm:0x7a257c)
    at _PyObject_MakeTpCall (pyodide.asm.wasm:0x1cabed)
    at __static_1198 (pyodide.asm.wasm:0x2c54f1)
    at byn$fpcast-emu$__static_1198 (pyodide.asm.wasm:0x7bf866)
    at __static_678 (pyodide.asm.wasm:0x21220e)
    at byn$fpcast-emu$__static_678 (pyodide.asm.wasm:0x7bdce6)
    at PyVectorcall_Call (pyodide.asm.wasm:0x1cb006)
PythonError @ pyodide.asm.js:9
new_error @ pyodide.asm.js:9
wrap_exception @ pyodide.asm.wasm:0x1a6c94
FutureDoneCallback_call @ pyodide.asm.wasm:0x1aaab3
byn$fpcast-emu$FutureDoneCallback_call @ pyodide.asm.wasm:0x7a257c
_PyObject_MakeTpCall @ pyodide.asm.wasm:0x1cabed
__static_1198 @ pyodide.asm.wasm:0x2c54f1
byn$fpcast-emu$__static_1198 @ pyodide.asm.wasm:0x7bf866
__static_678 @ pyodide.asm.wasm:0x21220e
byn$fpcast-emu$__static_678 @ pyodide.asm.wasm:0x7bdce6
PyVectorcall_Call @ pyodide.asm.wasm:0x1cb006
PyCFunction_Call @ pyodide.asm.wasm:0x1cc509
_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x2a9cba
byn$fpcast-emu$_PyEval_EvalFrameDefault @ pyodide.asm.wasm:0x7a61f3
PyEval_EvalFrameEx @ pyodide.asm.wasm:0x2a4693
(anonymous) @ pyodide.asm.wasm:0x1cb77c
_PyFunction_Vectorcall @ pyodide.asm.wasm:0x1cb878
byn$fpcast-emu$_PyFunction_Vectorcall @ pyodide.asm.wasm:0x7a3736
__static_184 @ pyodide.asm.wasm:0x1ce34e
byn$fpcast-emu$__static_184 @ pyodide.asm.wasm:0x7bc354
PyVectorcall_Call @ pyodide.asm.wasm:0x1cb006
PyObject_Call @ pyodide.asm.wasm:0x1cb0c1
_pyproxy_apply @ pyodide.asm.wasm:0x1aa709
Module.callPyObject @ pyodide.asm.js:9
wrapper @ pyodide.asm.js:9
async function (async)
self.onmessage @ e1e4bd72-b6f8-4080-900f-9f962ae36eea:257
</pre>
</details>

**Comment by jtpio** [comment]
Thanks @davidbrochart for opening this.

For reference there is some logic in Pyodide to set the recusion limit: https://github.com/pyodide/pyodide/blob/7760ce7ab8fc8e9582ed73396a936e0455ed8b02/src/js/pyodide.js#L132-L154

We also define it here:

https://github.com/jupyterlite/jupyterlite/blob/1732344e565c0694b034a4de015231ea05d28e4b/packages/pyolite-kernel/py/pyolite/pyolite/__init__.py#L8-L10

**Comment by jtpio** [comment]
> Browser and version: Google Chrome version 91.0.4472.114 (Official Build) (64-bit)

Out of curiosity, does this also happen with Firefox?

**Comment by davidbrochart** [comment]
No, it works fine in Firefox.

**Comment by jtpio** [comment]
Ah, also seeing that with Brave (Version 1.26.67 Chromium: 91.0.4472.114 (Official Build) (64-bit)):

![image](https://user-images.githubusercontent.com/591645/125313447-863f4f80-e335-11eb-8de6-849245fdebff.png)

**Comment by jtpio** [comment]
> We also define it here:

Maybe we need to tweak that value, as mentioned in https://github.com/jupyterlite/jupyterlite/pull/113#issuecomment-851072065.

**Comment by jtpio** [comment]
Maybe it's related to this PR, which might add a couple more levels of depth: https://github.com/jupyterlite/jupyterlite/pull/239

**Comment by jtpio** [comment]
> Maybe it's related to this PR, which might add a couple more levels of depth: #239

Although seems to be fine on the RTD preview for that PR: 

![image](https://user-images.githubusercontent.com/591645/125321739-4bd9b080-e33d-11eb-9a90-1d8d09ad55ac.png)
