### ISSUE TITLE
Add back `importhook` for patches

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#254]
### Problem

#250 reverted the use of `importhook` as it seemed to be causing issues with the recursion limit in Chromium 91 (#248).

Ideally we should try to bring it back 

### Proposed Solution

We could try to open #239 again, and test against Chromium.

Have some end to end testing (#6) on multiple browsers (`firefox` and `chromium`) might also help catch such issues.

### Additional context

#239 #248 #250

cc @dsblank

**Comment by jtpio** [comment]
There might be some changes in the next Pyodide version regarding the recursion limit: https://github.com/pyodide/pyodide/pull/1733

**Comment by dsblank** [comment]
Yes, looks like the recursion limit is doubling. Let's try the PR again once we use the new version of pyodide.

**Comment by bollwyvl** [comment]
There's [a bunch](https://github.com/pyodide/pyodide/pull/1756) of additional changes landing, so I'm a bit hesitant to move forward on much on the pyolite wheel side of the house at present. 

So, yeah, not worth doing much of anything until 0.18 final... though there still appears to be a number of things on [the roadmap](https://github.com/pyodide/pyodide/milestone/5), though i think some of those are already done...

**Comment by bollwyvl** [comment]
#274 is in, so it's worth another look at this.

**Comment by bollwyvl** [comment]
@dsblank no pressure: did you find anything else? 

It would really help our performance/bandwidth posture on e.g. jupyter.org/try if we could get `matplotlib` and `numpy`, etc. off the critical path to starting kernels.

**Comment by dsblank** [comment]
@bollwyvl I haven't had a chance to revisit this. I'll see if I can catch up with recent development in jupyetrlite and pyodide and report back.

**Comment by bollwyvl** [comment]
Semi-related: at present, we only ship one version of the `widgetsnbextension` shim package, and [install it](https://github.com/jupyterlite/jupyterlite/blob/v0.1.0b3/packages/pyolite-kernel/src/worker.ts#L53) at startup.

However, on #563, it appears this version is incompatible with the `ipywdigets 7.7,0` that just came out:

```
ValueError: Requested 'widgetsnbextension~=3.6.0', but widgetsnbextension==3.5.0 is already installed
```

will look into it, as it _might_ be the case that we can just ship multiple versions...
