### ISSUE TITLE
Point readthedocs deployment to a stable branch?

### ISSUE THREAD

**Issue by martinRenou** [jupyterlite/jupyterlite#262]
### Problem

I was demoing jupyterlite during Scipy, and faced errors as master was broken (If I am correct it was due to [this issue](https://github.com/jupyterlite/jupyterlite/issues/248))

### Proposed Solution

It might be sensible to have the main readthedocs point to a "stable" branch that is known for working properly, in case master gets broken

**Comment by jtpio** [comment]
We could also point to the `demo` repo, which uses a released version of `jupyterlite`? (for example `jupyterlite==0.1.0a5`) https://jupyterlite.github.io/demo

(this was also briefly mentioned in https://github.com/jupyterlite/jupyterlite/pull/238#issuecomment-879218663)

**Comment by bollwyvl** [comment]
A quick win would be to "activate" all of the  tags:

![Screenshot from 2021-07-15 09-48-12](https://user-images.githubusercontent.com/45380/125798975-4f0aed57-237f-4aee-a2f8-113855c5ce3c.png)

I wouldn't necessarily stand behind a `stable` until we've gotten something we can actually start standing behind (which I won't do until i feel like I can actually ship "real" things with it). At this point, we basically need as many eyes on `latest` as possible, as even if we had pretty good coverage on #6, this environment is all about creating emergent systems with user code... and that can _always_ go wrong.

**Comment by bollwyvl** [comment]
A cute part of #149 would be to add a version picker that uses the same data.

**Comment by jtpio** [comment]
ReadTheDocs builds a `stable` now that we have a proper `0.1.0` release out:

![image](https://github.com/jupyterlite/jupyterlite/assets/591645/b4261d5d-5e0e-4ff3-b469-7c1e61a62fe1)

At the moment `stable` points to the latest `0.1.2` release: https://github.com/jupyterlite/jupyterlite/commit/e5ede1e85f6812ce8a94aa227be2ced8addd011f
