### ISSUE TITLE
All but "Download" Option Have Disappeared from Context Sensitive File List Pop-up Menu

### ISSUE THREAD

**Issue by psychemedia** [jupyterlite/jupyterlite#265]
Looking to delete a file by right-clicking on a file in the file listing, only a `Download` option appears rather than a full range of options.  

![image](https://user-images.githubusercontent.com/82988/125752166-ecf050bd-9b82-47f4-bfa5-f93c4f1c80a5.png)

JupyterLiteersion 0.1.0-alpha.5, Chrome (91.0.4472.114 x86_64), Mac OS/X 10.15.7

**Comment by jtpio** [comment]
Thanks @psychemedia for the report.

Probably this is related to the recent update to JupyterLab 3.1.0rc1 in #207.

This is reproducible on `main` (unreleased): https://jupyterlite.rtfd.io/en/latest/try/lab

But looks good with the latest release version: https://jupyterlite.github.io/demo/lab/

**Comment by jtpio** [comment]
Most likely related to this change upstream: https://github.com/jupyterlab/jupyterlab/pull/10373

**Comment by jtpio** [comment]
We can fix it upstream by moving this logic to a separate plugin:

https://github.com/jupyterlab/jupyterlab/blob/956d7e75cb2102ea24e461fef3202fdadefba86a/packages/application-extension/src/index.tsx#L393-L419

**Comment by jtpio** [comment]
Should be fixed by https://github.com/jupyterlab/jupyterlab/pull/10624.

**Comment by bollwyvl** [comment]
Awesome quick work!
