### ISSUE TITLE
Notebooks are not copied over in build

### ISSUE THREAD

**Issue by JohannesBuchner** [jupyterlite/jupyterlite#277]
Hi! This seems like a cool project. I'd like to use it for teaching a course.

## Description

Setting up a simple site with a simple prepared notebook does not show the notebook in lab/

## Background

I want to prepare a static web site based on a few python kernel notebooks, and with some python extensions pre-installed.
I find the documentation on how to get started a bit confusing; the examples/ directory does not explain how to build it and which configuration files are important. Here is what I did:

## Reproduce

1. Create and enter a empty directory
2. Create a jupyter notebook files/Untitled.ipynb with one cell: "import matplotlib"
3. run: jupyter lite init
4. run: jupyter lite build
5. run: jupyter lite serve
6. open http://127.0.0.1:8000/lab
7. be told "HTTP 403: Forbidden (lab is not a file)"
8. open http://127.0.0.1:8000/lab/ instead
9. file list (left panel) is empty
10. Go to the user doc at https://jupyterlite.readthedocs.io/en/latest/ -- it is pretty empty.
11. Go to the developer doc at https://jupyterlite.readthedocs.io/en/latest/configuring.html. 
   * It says "jupyter lite build" will copy all files in files/, but it did not (`find _output/ -iname '*.ipynb'` is empty)

## Expected behavior

1. run: jupyter lite init
2. create notebook files in files/
3. run: jupyter lite build
4. run: jupyter lite serve
5. on the quoted url, the notebooks are shown.

It would be helpful if the documentation answered the following questions:
 * How do I include a python packages so it comes with the static site?
 * How do I write the jupyter-lite.json, jupyter-lite.ipynb, index.html files? (beyond the schema and long unreadable example blurb)
 * How is the examples/ folder in the github repo built & delivered? Which config files are important?

## Context

- Operating System and version: Ubuntu Linux
- Browser and version: Firefox
- JupyterLite version: 0.1.0a5

**Comment by JohannesBuchner** [comment]
The same emptiness occurs when running the commands in the github repo `examples/` folder.

**Comment by bollwyvl** [comment]
Yeah, sorry the experience has not been great yet... _very_ alpha stuff here, thanks for trying. We also want to build a more visual experience, a la https://github.com/jupyterlite/jupyterlite/issues/165 so all of the plumbing stuff is a bit more hidden.

The current `main` branch (which does have a bit of a setup for a finicky environment) contains a number of things that didn't make the timeline `0.1.0alpha5`. This is no doubt confusing, something we've been looking into on #262. It'll be good to get those features out, though we might be waiting for JupyterLab `3.1rc2` to be released for some upstream fixes (that we discovered/made for ourselves).

Of note, the broken-by-default URL suggested by `serve` was updated in #260, and should be somewhat better after the next release... 

The docs in general are work-in-progress, both in 
  - content:
    - hoisting the "in-house" demo site to a literate/interactive tutorial 
  - workflow
    - eventually refactor into integration with more build tools e.g. sphinx #149 and nbconvert #41

Most likely, I think it's going to end up making sense to write out a `jupyter_config.json` (or, on `main`, `jupyter_lite_config.json`), which is [semi-documented](https://github.com/jupyterlite/jupyterlite/blob/v0.1.0a5/py/jupyterlite/src/jupyterlite/config.py).

**Comment by jtpio** [comment]
> we might be waiting for JupyterLab `3.1rc2` to be released for some upstream fixes (that we discovered/made for ourselves).

Yes, waiting for the next upstream rc before publishing a new jupyterlite release :+1:

**Comment by JohannesBuchner** [comment]
OK, I completely accept that it is alpha software, and am happy to put some tinkering effort in to get it to work. Or are you saying that 0.1.0a5 is not usable? If not, pointers that address the immediate problem are appreciated.

**Comment by jtpio** [comment]
`0.1.0a5` should work fine. It's just that it doesn't match the latest `main` on this repo.

The JupyterLite Demo repo has been using `0.1.0a5` for a couple of days already: https://github.com/jupyterlite/demo
