### ISSUE TITLE
FASTA example is failing

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlite/jupyterlite#284]
## Description

The fasta document viewer had been failing for a while, but as of #283, the mime renderer is also failing.

## Reproduce

- open the browser console
- open the [RTD build for #283](https://jupyterlite--283.org.readthedocs.build/en/283/_static/lab/index.html) 
- double click `fasta-example.fasta`
- see:
```
Uncaught TypeError: t.on is not a function
    resetSeqs 681.80b3439aec1db6dfd35f.js:2
    e 681.80b3439aec1db6dfd35f.js:2
    resetSeqs 681.80b3439aec1db6dfd35f.js:2
    i 681.80b3439aec1db6dfd35f.js:2
    _loadSeqs 681.80b3439aec1db6dfd35f.js:2
    initialize 681.80b3439aec1db6dfd35f.js:2
    a 681.80b3439aec1db6dfd35f.js:2
    i 681.80b3439aec1db6dfd35f.js:2
    i 681.80b3439aec1db6dfd35f.js:2
    l 568.761dbc3966ac7bd30a96.js:1
    createRenderer 568.761dbc3966ac7bd30a96.js:1
    createNewWidget mimedocument.js:204
    createNew default.js:349
    createWidget widgetmanager.js:62
    _createOrOpenDocument manager.js:465
    open manager.js:281
    openOrReveal manager.js:305
    handleOpen listing.js:862
    evtDblClick listing.js:943
    handleEvent listing.js:562
    onAfterAttach listing.js:606
    processMessage index.es6.js:1387
    c index.es6.js:442
    e index.es6.js:178
    attachWidget index.es6.js:2773
    insertWidget index.es6.js:2673
    addWidget index.es6.js:2642
    set useFuzzyFilter browser.js:146
    activate index.js:138
    promise callback*activate/< index.js:116
    promise callback*activate index.js:104
    promise index.es6.js:162
    promise callback*76219/a</e.prototype.activatePlugin index.es6.js:161
    i index.es6.js:281
    start index.es6.js:280
    60880 index.js:488
    60880 index.js:494
    Webpack 6
681.80b3439aec1db6dfd35f.js:2:238290
 ```

## Expected behavior

- See little colored squares and no error

## Options

- remove the example in the short term
- investigate upstream

**Comment by jtpio** [comment]
Thanks for catching this :+1: 

This looks like an issue upstream, as it seems to be failing with this gist:

- https://gist.github.com/jtpio/844ab4e85ae84f230cbcb0e56a59c88e
- https://mybinder.org/v2/gist/jtpio/844ab4e85ae84f230cbcb0e56a59c88e/master?urlpath=/lab

![image](https://user-images.githubusercontent.com/591645/126602114-340a8b2e-9256-42ac-99dd-5a2308f11fd3.png)

Will report upstream.

**Comment by jtpio** [comment]
> Will report upstream.

Opened https://github.com/jupyterlab/jupyterlab/issues/10675

**Comment by bollwyvl** [comment]
Weirdly it _worked at least once_:

![wtfasta](https://user-images.githubusercontent.com/45380/126669413-ceb5c933-2736-49b3-84ec-63bfa6a95cf3.png)

**Comment by bollwyvl** [comment]
Updated on conda-forge: worth a resolve in an hour or two, see if we get it back.
