### ISSUE TITLE
404 and "failed get jupyter-config-data" for /lab/jupyter-lite.ipynb

### ISSUE THREAD

**Issue by westurner** [jupyterlite/jupyterlite#298]
## Description

- This should probably be transferred to jupyterlite/demo issues.
- While this is relevant to the currently deployed version of jupyterlite/demo, I'm not sure whether this error is what's causing the whole app to fail to load.
- [ ] jupyterlite/jupyterlite: fail better when config 404s (if this is the actual showstopping issue and not just a logged error, haven't looked at the source)
- [ ] jupyterlite/demo: tag (date-based?) revisions for e.g. readthedocs
  - [ ] jupyterlite/demo: docs, .github-actions.yml: how to deploy with github actions (so that this doesn't change underneath a course)
  - [ ]  jupyterlite/demo: create an Action to verify that /latest/_static/lab/index.html loads and works (some sort of self-test?) regularly and/or after each relaease deploy to RTD and GH

## Reproduce

1. Go to https://jupyterlite.readthedocs.io/en/latest/_static/lab/index.html
4. See error '...'
5. Check to see whether there is a built tagged build on ReadTheDocs that probably worked before whichever change is to blame for this

## Expected behavior

JupyterLite works like it did a few days ago.

## Context

- JupyterLite version:
- Operating System and version:
- Browser and version:

Browser Output:

<pre>
config-utils.js:193 GET https://jupyterlite.readthedocs.io/en/latest/_static/lab/jupyter-lite.ipynb 404
config-utils.js:193 GET https://jupyterlite.readthedocs.io/en/latest/_static/jupyter-lite.ipynb 404
config-utils.js:200 failed get jupyter-config-data from https://jupyterlite.readthedocs.io/en/latest/_static/lab/jupyter-lite.ipynb
config-utils.js:200 failed get jupyter-config-data from https://jupyterlite.readthedocs.io/en/latest/_static/jupyter-lite.ipynb
</pre>

**Comment by westurner** [comment]
While this is relevant to the currently deployed version of jupyterlite/demo, I'm not sure whether this error is what's causing the whole app to fail to load.

- [ ] jupyterlite/jupyterlite: fail better when config 404s (if this is the actual showstopping issue and not just a logged error, haven't looked at the source)
- [ ] jupyterlite/demo: tag (date-based?) revisions for e.g. readthedocs
  - [ ] jupyterlite/demo: docs, .github-actions.yml: how to deploy with github actions (so that this doesn't change underneath a course)
  - [ ] jupyterlite/demo: create an Action to check that /latest/lab/index.html loads and works (some sort of self-test?)

**Comment by bollwyvl** [comment]
As to the 404s: we support both `jupyter-lite.json` and `jupyter-lite.ipynb` for configuration, and when either not present, the app will show these errors, but would not cause the app to fail... there is no way to avoid these with alternate HTTP requests.

A quick spin in private browsing sessions on Firefox 78 LTS, Chromium 90, and Chrome 92 the docs site currently works as expected. Please try clearing out your cache. If the issue persists, a screenshot of the network load and/or text of what appears in the developer console would allow us to help you.

As to your laundry list: please consider having a look at other open issues and PRs. Automated tests are planned in #6 and started in #258. The build already won't deploy if the expected files are not created during the build, but there is a good deal of reliance on CDN assets, especially for some of the kernels.

**Comment by jtpio** [comment]
@westurner mind splitting this into multiple issues if still relevant? Thanks!

For reference https://github.com/jupyterlite/jupyterlite/issues/466 should now help with the 404s logged in the dev tools console.

**Comment by jtpio** [comment]
Let's close this issue since the other bullet points mentioned above might be more related to the demo repo: https://github.com/jupyterlite/demo
