### ISSUE TITLE
ModuleNotFoundError: No module named 'ipython_genutils'

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#311]
## Description

Testing on the latest `main` with the widgets example notebook:

![image](https://user-images.githubusercontent.com/591645/131456088-22d0bcf5-7973-4c76-9da5-59e022d350f6.png)

## Reproduce

1. Go to https://jupyterlite.readthedocs.io/en/latest/_static/lab/index.html
2. Open the widgets example notebook
3. Run the first 2 cells

## Context

Explicitly installing `ipython_genutils` seems to do the trick:

![image](https://user-images.githubusercontent.com/591645/131456201-ada83b97-4c9e-4eb0-a95c-2a9b57984816.png)

So we should check what is happening as it seems unrelated to any recent change?

**Comment by martinRenou** [comment]
Seems related to https://github.com/ipython/ipykernel/pull/756 and https://github.com/ipython/ipykernel/issues/755.

Indeed, we should maybe install `ipython_genutils` before IPython

**Comment by martinRenou** [comment]
Although we are not using it directly, so should it be an ipywidgets dependency instead?

**Comment by jtpio** [comment]
> Although we are not using it directly, so should it be an ipywidgets dependency instead?

Yes this sounds like the best approach, just like in https://github.com/ipython/ipykernel/pull/756

**Comment by martinRenou** [comment]
As a temporary workaround, we could install `ipython_genutils`. Adding a comment `# TODO Remove this when it's an ipywidgets dependency`

**Comment by jtpio** [comment]
Sounds good :+1:

**Comment by jtpio** [comment]
Opened https://github.com/jupyter-widgets/ipywidgets/pull/3262

**Comment by bollwyvl** [comment]
Perhaps we just add here for now, as this is where it's presently landed in [ipykernel `6.3.1`](https://github.com/ipython/ipykernel/blob/master/setup.py#L65): https://github.com/jupyterlite/jupyterlite/blob/main/packages/pyolite-kernel/py/ipykernel/pyproject.toml

Probably worth assessing whatever else has changed in the shim in the ensuing time...
