### ISSUE TITLE
Update the examples to ipywidgets 8

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#312]
### Problem

The latest `ipywidgets` 7 depends on `ipython_genutils` in some places in the code. See https://github.com/jupyter-widgets/ipywidgets/pull/3262 and #311 for reference.

This doesn't seem to be the case with `ipywidgets` 8 anymore. So that could be a good time to start testing the latest ipywidgets 8 alpha releases.

But it's also nice to start testing this version to help with the final release.

### Proposed Solution

We can start updating the example notebooks to the latest 8 prereleases. That could be a draft PR for now.

We might need the prereleases to be published to a `ipywidgets` conda channel to fetch the lab prebuilt extension.

**Comment by bollwyvl** [comment]
Would certainly want to see a release out with the stable deps before jumping on another alpha train :stuck_out_tongue_closed_eyes:

**Comment by jtpio** [comment]
> Would certainly want to see a release out with the stable deps 

A JupyterLite release? Yes we should be able to cut a new one soon :+1:

**Comment by bollwyvl** [comment]
Very likely these don't all work yet... but we need to offer a no-op `widgetsnbextension@4` to explore further...

**Comment by bollwyvl** [comment]
It seems like it's possible to overload the `widgetsnbextension` mock package:

https://github.com/deathbeds/ipydrawio/pull/99 (very wip)

**Comment by bollwyvl** [comment]
There are two PRs that update all the demos (which appear to work) for ipywidgets 8:
- #795
- #793

The main difference is the latter will be slightly more performant, as widgetsnbextension only consists of js/css that we won't use.

**Comment by bollwyvl** [comment]
Some numbers:
- without shim: 30.9mb
  -  https://jupyterlite--795.org.readthedocs.build/en/795/_static/lab/index.html?path=pyolite/interactive-widgets.ipynb
- with shim: 28.8mb  
  - https://jupyterlite--793.org.readthedocs.build/en/793/_static/lab/index.html?path=pyolite/interactive-widgets.ipynb
