### ISSUE TITLE
Narrow down the `IKernel` interface?

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#314]
The current `IKernel` interface currently defines a couple of methods such as `executeRequest` and `completeRequest`:

https://github.com/jupyterlite/jupyterlite/blob/209d48100d598014df7e6c17993b3fdca279c984/packages/kernel/src/tokens.ts#L45

Which are then called in `BaseKernel` here:

https://github.com/jupyterlite/jupyterlite/blob/209d48100d598014df7e6c17993b3fdca279c984/packages/kernel/src/kernel.ts#L545

This made it convenient to implement the first JavaScript and Python kernels extending `BaseKernel`, as it required to implement just a couple of methods to get a basic kernel to work.

However in the case of [xeus](https://github.com/jupyter-xeus/xeus) based kernels, these are already handled and implemented. Having the TypeScript counterpart sounds redundant and not necessary.

We should then check whether we would like to narrow the `IKernel` down, for example to just the `handleMessage` method. And give full-control to kernel authors as to how they handle the messages.

cc @DerThorsten since we briefly discussed this

**Comment by martinRenou** [comment]
It will also be handy for cleaning the `pyodide` kernel as well, as the worker is responsible for dispatching the message to the right requests.

**Comment by martinRenou** [comment]
So you're not inheriting from the [base kernel](https://github.com/jupyterlite/jupyterlite/blob/main/packages/kernel/src/kernel.ts#L10)?

**Comment by DerThorsten** [comment]
nope..I just implement the IKernel interface directly.  this seems to be easier (at least for experimenting )

**Comment by jtpio** [comment]
`IKernel` is also what is expected here when registering a new kernel:

https://github.com/jupyterlite/jupyterlite/blob/209d48100d598014df7e6c17993b3fdca279c984/packages/kernel/src/kernelspecs.ts#L62-L80

Thinking that we could then keep `BaseKernel` with the convenient methods (handy for JS kernels), but remove them from the `IKernel` interface.

**Comment by jtpio** [comment]
Fixed by #355
