### ISSUE TITLE
How to create and publish(update) notebooks on gh-pages

### ISSUE THREAD

**Issue by voland62** [jupyterlite/jupyterlite#318]
Hi. I  want to ask about workflow (I can make dedicated issue for that, but it is maybe something wrong with me: I totally confused with docs...). Correct me please if I'm getting something wrong. 
So, the workflow, as I see it:

### Let's say, I want to create **math.ipynb**, and share it with my students... So I:
   1.  Use this "demo" template, for creation my own repo with **main** branch only. (At this stage there isn't gh-pages for default notebooks yet, so no any public site where I can create my new notebook exists yet...)
   2. git clone my/new/repo to get it locally
   3.      cd my/new/repo
             mamba create -n jupyterlite
             conda activate jupyterlite
             pip install -r requirements.txt
   4.      jupyter lite build --contents content
           jupyter lite serve
         open http://127.0.0.1:8000/index.html in a browser to test it locally.
   5. So now I can create **math.ipynb**. But, as I understand it, it exists only in the brower's local storage, so to get it on my file  system, I select "Download" from menu, and save it inside /contents/ folder of my repo. I have to do this on every edit...
   6. Than I do `git add/commit/push` as always.
   7. After the push, git Actions automation launches full build on github servers, and populate gh-pages branch of my repo. (It takes 4 min, btw... )
   8. At this point I can see/work with my new **math.ipynb** online.  To save it, I need to do Dowload/commit/push cycle again.. 
   9. I'm still not able to figure out how to get "shareable llink" (menu point doesn't work), so the best I can do is to send link to my.github.io/my-repo/lab/index.html, and ask her to open **math.ipynb** from iside..

### Questions:
Is this right workflow?
We still can't save on GitHub directly from the IDE (like in Google Colab), right?
We still can't get link to notebook/cell, right?
Can a collaboration be enabled in our case?(I can't understand docs, to be honest...)

Thanks.

**Comment by jtpio** [comment]
Thanks @voland62 for opening the issue!

>  2\. git clone my/new/repo to get it locally

For the demo template (https://github.com/jupyterlite/demo), it might not be necessary to clone the repo locally. Normally most of the workflow can be done on GitHub directly. One way to make changes is to open a new PR and wait for the check to be completed. Then download the built website from the GitHub Actions artifact:

![image](https://user-images.githubusercontent.com/591645/132302733-f20e3bb1-4c8a-4d9b-b0f4-1bc0eb76e244.png)

This corresponds to the archive that will be deployed to GitHub Pages when the changes are merged into the `main` branch. Locally the archive can be extracted and tested by running `python -m http.server` at the root folder.

> 5. So now I can create math.ipynb. But, as I understand it, it exists only in the brower's local storage, so to get it on my file system, I select "Download" from menu, and save it inside /contents/ folder of my repo. I have to do this on every edit...

You can also add `math.ipynb` to the `contents` directory, and it will be deployed with the website and served as a static file. When the users edit the file, a copy will be saved to the browser local storage (this is using a layering approach). To download to the local filesystem, one approach for now is to indeed use the download command.

> 9. I'm still not able to figure out how to get "shareable llink" (menu point doesn't work), so the best I can do is to send link to my.github.io/my-repo/lab/index.html, and ask her to open math.ipynb from iside.

Right this is not supported for now, but could be implemented. As an alternative you might want to use the RetroLab interface, which makes it possible to share direct links to single notebook files: https://jupyterlite.github.io/demo/retro/notebooks/?path=pyolite.ipynb

>  We still can't save on GitHub directly from the IDE (like in Google Colab), right?

Not yet. Ideally this can be implemented as a third-party plugin.

> Can a collaboration be enabled in our case?(I can't understand docs, to be honest...)

There is experimental support for real time collaboration. You might want to check this repo (generated from the demo template) which adds the needed configuration: https://github.com/jtpio/lit/blob/d65ee8adfbd400a70d4422f075937a25ac1ef86c/jupyter-lite.json#L5

**Comment by jtpio** [comment]
Maybe we could improve the docs (and include the details in the above comment) by having more detailed "User Guides" geared towards deploying a new JupyterLite website from scratch. Or at least make it more visible and accessible.

**Comment by jtpio** [comment]
@voland62 maybe you would like to check out the updated README over on the demo repo?

https://github.com/jupyterlite/demo/

@psychemedia added nice explanations and screenshots in https://github.com/jupyterlite/demo/pull/23, which should help clarify a couple of things.

**Comment by voland62** [comment]
Nice. Definitely it is much cleaner now.
   But, still one question that hurts me a lot... :

When I publish new/change my notebook inside content folder, we still do full rebuild.
What if our change in content folder, don't cause any rebuild, but just force app refresh it contents dynamically in the browser?
I understand rebuild neediness for adding extensions, but I don't see why we need it when just dealing with notebooks...

**Comment by jtpio** [comment]
Closing this issue as answered as the documentation has been improved quite a bit:

- https://jupyterlite.readthedocs.io/en/latest/quickstart/deploy.html
- https://jupyterlite.readthedocs.io/en/latest/howto/index.html

Don't hesitate to open a new issue or discussion if you have any question, thanks!
