### ISSUE TITLE
No module named 'ipywidgets'

### ISSUE THREAD

**Issue by cathalmccabe** [jupyterlite/jupyterlite#326]
## Reproduce
1. `jupyter lite init `
2. `jupyter lite build `

Note: @jupyter-widgets (and jupyterlab-plotly) exist in ./_output/lab/extensions

3. `jupyter lite serve`

4. In Jupyter Lite, create a new notebook and run:
`import ipywidgets`

## Results in:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-5a7c58814537> in <module>
----> 1 import ipywidgets

ModuleNotFoundError: No module named 'ipywidgets'

## Context

- JupyterLite version: 0.1.0a6
- Operating System and version: Win10
- Browser and version: Chrome  93.0.4577.63 
- Anaconda env:
 
jupyter labextension list
JupyterLab v3.0.14
C:\Users\username\Anaconda3\share\jupyter\labextensions
        jupyterlab-plotly v5.3.1 enabled ok
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled ok (python, jupyterlab_widgets)

**Comment by martinRenou** [comment]
You might need to install it with `micropip` in your first Notebook cell

```python
import micropip

await micropip.install('ipywidgets')
```

**Comment by cathalmccabe** [comment]
Thanks, this is resolved and I see the reason in #236 now.
