### ISSUE TITLE
Pyodide crash down

### ISSUE THREAD

**Issue by qqdaiyu55** [jupyterlite/jupyterlite#339]
## Description

![image](https://user-images.githubusercontent.com/9846706/133710231-5b408db3-d543-4731-96e4-c1d580893bd5.png)

![image](https://user-images.githubusercontent.com/9846706/133710255-6912ad26-70be-4f2a-b023-9dfb75453e6d.png)

## Reproduce

Jupyterlite randomly crashes down, thougth it's not frequent. I'm not sure if it's the same issue with [#158](https://github.com/jupyterlite/jupyterlite/issues/158).

## Context

- JupyterLite version: 0.1.0-alpha.6
- Operating System and version: Windows 21H1
- Browser and version: Chrome Version 93.0.4577.63 (Official Build) (32-bit)

<details><summary>Browser Output</summary>
<pre>
pyodide.asm.js:9 Uncaught (in promise) PythonError: Traceback (most recent call last):
  File "/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 419, in eval_code_async
    return await CodeRunner(
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 272, in run_async
    await coro
  File "<exec>", line 2, in <module>
  File "/lib/python3.8/site-packages/micropip.py", line 10, in <module>
    from packaging.requirements import Requirement
  File "/lib/python3.8/site-packages/packaging/requirements.py", line 10, in <module>
    from pyparsing import (  # noqa: N817
MemoryError

    at new_error (pyodide.asm.js:9)
    at pyodide.asm.wasm:0x1a6c94
    at pyodide.asm.wasm:0x1aaab3
    at pyodide.asm.wasm:0x7a257c
    at pyodide.asm.wasm:0x1cabed
    at pyodide.asm.wasm:0x2c54f1
    at pyodide.asm.wasm:0x7bf866
    at pyodide.asm.wasm:0x21220e
    at pyodide.asm.wasm:0x7bdce6
</pre>
</details>

**Comment by jtpio** [comment]
Thanks @qqdaiyu55 for reporting.

It it indeed similar to #158. Do you know if that happens with a specific example notebook?

Also, maybe you would like to try with the latest 0.18.1 which might have improved things: https://github.com/jupyterlite/jupyterlite/pull/338

**Comment by jtpio** [comment]
cc @qqdaiyu55 `jupyterlite==0.1.0a9` ships with Pyodide 0.18.1, which might help with this if you want to give it a try

**Comment by qqdaiyu55** [comment]
After upgrading to pyodide 0.18.1, the issue does not appear again thx!

**Comment by jtpio** [comment]
Nice, thanks for the heads-up!

**Comment by qqdaiyu55** [comment]
I'm afraid I have to reopen this issue, as the crash happended again,

![image](https://user-images.githubusercontent.com/9846706/136952522-c945db5e-6fb0-4e64-9862-ac2d72f74a52.png)

and when I refreshed the page, tried to reopen the notebook, the worker stops to load dependent python packages

(should load)
![image](https://user-images.githubusercontent.com/9846706/136953299-acfcd868-cebc-4d2a-b22e-6ab2cb5b47c6.png)

(however)
![image](https://user-images.githubusercontent.com/9846706/136953401-3212b6a2-2a65-4f60-8e82-2cb0b01ba450.png)

**Comment by qqdaiyu55** [comment]
@jtpio Yes, it also happened with Chrome 94.
When I opened multiple notebooks, this failure happened frequently, as each notebook will take a lot of memory

**Comment by rth** [comment]
> When I opened multiple notebooks, this failure happened frequently, as each notebook will take a lot of memory

Currently there is a limit of 2GB RAM for each Pyodide env (https://github.com/pyodide/pyodide/issues/1513#issuecomment-823841440) due to WASM limitations. If you have many notebooks (each in their own webworker?) I'm not sure if this limit would remain the same, or if would be per web-worker -- the latter I imagine?

> and when I refreshed the page

Also there is a related browser issue that reloading the tab doesn't necessarily free the memory  https://github.com/pyodide/pyodide/issues/1333

**Comment by bollwyvl** [comment]
> each in their own webworker

yep, at present, each kernel is its own worker, which in turn launches pyodide. The line between worker/kernel/shell is somewhat vague at present, and we probably need to clean up some of the language/layers.

we've discussed a couple different kernel deployment options, and each has its own opportunities and limitations:
- running in the host scope (worst of all possible worlds, except for the fun DOM proxies until everything crashes)
- figure out how to run multiple `pyodide` instances (or even _other_ kernels, eventually) in the same wasm (will _globally_ use less RAM, but would be easier to exhaust 2gb)
- going back to the old iframe approach

>  reloading the tab doesn't necessarily free the memory 

That's a good one... even if it's a placebo under some conditions, at least we can try! 

But we really won't _know_ much from inside the JS environment, so it might just be "hey, watch yourself with multiple complex/long-running notebooks!" Even on a "real" (as in, fake) computer in a docker container (e.g. on binder), these things happen.

**Comment by bollwyvl** [comment]
There isn't much more to say about this one: worker kernels are expensive, but we're unlikely to move away from them.
