### ISSUE TITLE
Seeing max call stack size exceeded on initial Jupyterlite instance

### ISSUE THREAD

**Issue by mvbrock-ae** [jupyterlite/jupyterlite#341]
Seeing the following console error after running `jupyter-lite build` and then `jupyter-lite serve`:

Chrome
```
Uncaught RangeError: Maximum call stack size exceeded
    at pyodide.asm.wasm:0x7bded4
    at pyodide.asm.wasm:0x21cf80
    at pyodide.asm.wasm:0x1f3c8b
    at pyodide.asm.wasm:0x1fba81
    at pyodide.asm.wasm:0x1fb935
    at pyodide.asm.wasm:0x7bd569
    at pyodide.asm.wasm:0x1b4803
    at pyodide.asm.wasm:0x1b4dee
    at pyodide.asm.wasm:0x3fa4c2
    at pyodide.asm.wasm:0x3f7b84
```

Safari:
```
RecursionError: maximum recursion depth exceeded in __instancecheck__
```

I've cleared out all local browser DBs, cookies, etc. and am still seeing this.

## Reproduce

1. Run `jupyter-lite build`
2. Run `jupyter-lite serve`
3. Open browser console
4. Create a new notebook
4. See stack size error in browser console

## Context

- JupyterLite version: 0.1.0
- Operating System and version: macOS 11.5.2
- Browser and version: Chrome 93.0.4577.63, Safari 14.1.2

**Comment by jtpio** [comment]
Thanks @mvbrock-ae.

The max call stack size error seems to be a recurring issue.

> JupyterLite version: 0.1.0

The demo repo (https://jupyterlite.github.io/demo/lab/index.html) seems to working fine with `0.1.0-alpha.8` and the `altair` example with my setup (Chromium 93 on Ubuntu). 

Which alpha version of `jupyterlite` is it exactly?

**Comment by mvbrock-ae** [comment]
Ah, yes, I was on `0.1.0-alpha.6`. I just upgraded to `alpha.8` and things seem to be working now. Thanks!
