### ISSUE TITLE
Save as event will always trigger overwrite

### ISSUE THREAD

**Issue by qqdaiyu55** [jupyterlite/jupyterlite#370]
## Description

When I try to save a file as a new one, jupyterlite will always prompt that "the file is already exists" even though it does not exist.
![image](https://user-images.githubusercontent.com/9846706/135816708-71c2fcf5-3cb5-4195-82b7-1e94888a8cb2.png)

## Reproduce

File > Save Notebook As

**Comment by jtpio** [comment]
Thanks @qqdaiyu55 for reporting.

I can confirm this is an issue when testing on the latest: https://jupyterlite.rtfd.io/en/latest/try/lab
