### ISSUE TITLE
Read the docs demo are broken

### ISSUE THREAD

**Issue by fcollonval** [jupyterlite/jupyterlite#373]
## Description

Both JupyterLab and RetroLab try buttons on the documentation are failing to load an application 

Some resources are not loaded.

## Reproduce

1. Go to https://jupyterlite.readthedocs.io/en/latest/index.html
2. Click on one of the two try buttons

## Expected behavior

It works

## Context

- JupyterLite version: latest
- Operating System and version: Debian 11
- Browser and version: Firefox 88

<details><summary>Browser Output</summary>
<pre>
failed get jupyter-config-data from https://jupyterlite.readthedocs.io/en/latest/_static/retro/tree/jupyter-lite.ipynb config-utils.js:200:13
failed get jupyter-config-data from https://jupyterlite.readthedocs.io/en/latest/_static/retro/jupyter-lite.ipynb config-utils.js:200:13
failed get jupyter-config-data from https://jupyterlite.readthedocs.io/en/latest/_static/jupyter-lite.ipynb config-utils.js:200:13
Unsatisfied version 5.1.12 of shared singleton module @jupyterlab/coreutils (required ^5.1.13) consumes:40
Failed to create module: package: @jupyter-widgets/jupyterlab-manager; module: ./extension index.js:28:12
Failed to create module: package: bqplot; module: ./extension index.js:28:12
Failed to create module: package: ipycanvas; module: ./extension index.js:28:12
Uncaught (in promise) ChunkLoadError: Loading chunk 638 failed.
(missing: https://jupyterlite.readthedocs.io/en/latest/_static/lab/ext…idgets/jupyterlab-manager/static/638.f3e5e34a28f3334d4f08.js)
    j remoteEntry.f6574b55a223d23e7a04.js:1
    e remoteEntry.f6574b55a223d23e7a04.js:1
    e remoteEntry.f6574b55a223d23e7a04.js:1
    I remoteEntry.f6574b55a223d23e7a04.js:1
    h remoteEntry.f6574b55a223d23e7a04.js:1
    y remoteEntry.f6574b55a223d23e7a04.js:1
    b remoteEntry.f6574b55a223d23e7a04.js:1
    1524 remoteEntry.f6574b55a223d23e7a04.js:1
    consumes remoteEntry.f6574b55a223d23e7a04.js:1
    consumes remoteEntry.f6574b55a223d23e7a04.js:1
    e remoteEntry.f6574b55a223d23e7a04.js:1
    e remoteEntry.f6574b55a223d23e7a04.js:1
    extension remoteEntry.f6574b55a223d23e7a04.js:1
    n remoteEntry.f6574b55a223d23e7a04.js:1
    a index.js:25
    60880 index.js:192
    60880 index.js:185
</pre>
</details>

**Comment by jtpio** [comment]
Normally there should at least be an error logged in the dev tools console.
