### ISSUE TITLE
Move `pyolite` to a different repository

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#386]
### Problem

At the moment the Python kernel is part of the monorepo: 

- https://github.com/jupyterlite/jupyterlite/tree/main/packages/pyolite-kernel
- https://github.com/jupyterlite/jupyterlite/tree/main/packages/pyolite-kernel-extension

This has been convenient so far as it allowed for faster iterations until we implemented most of the Jupyter protocol (including comms for widgets).

However there are now a couple of reasons to start thinking moving it to a different repo:

- it is now growing in size and complexity
- it also depends on a couple of shims (`ipykernel`, `widgetsnbextension`...)
- all of this adds some weight to the `jupyterlite` dev workflow
- there might be alternative implementations for a Python kernel in the future (for example based on `xeus-python`)
- other JupyterLite distributions like the p5 notebook don't need it and have to disable the extension: https://github.com/jtpio/p5-notebook

With support for [federated server extensions](https://jupyterlite.readthedocs.io/en/latest/extensions.html), we can imagine having that kernel living outside of the main repo, for example in https://github.com/jupyterlite/pyolite-kernel or https://github.com/jupyterlite/ipylite-kernel.

### Proposed Solution

We move the kernel to https://github.com/jupyterlite/pyolite-kernel and make it a federated server extension.

### Additional context

This was also mentioned by @bollwyvl in https://github.com/jupyterlite/jupyterlite/issues/383#issuecomment-940112826

This might also simplify things like https://github.com/jupyterlite/jupyterlite/pull/310, but raises new issues:

#### config junk
- move the schema description of `pyodideUrls` and `micropipUrls` to a file pointed to by `package.json#/jupyterlite/schemaDir`
  - does this need to be disjoint from `jupyterlab/schemaDir`
- in `jupyterlite.schema.v0.json` (or maybe this is finally a `v1`?), add a new field, `extensionConfiguration`, which allows per-extension configuration (akin to `jupyter_(notebook|server)_config.json`

#### lite wheels
- serve from `lab/extensions/@jupyterlite/pyolite-extension/static/wheels` via webpack `assets`
  - need some CLI, e.g. `jupyter ipylite index` to generate the business for complex packages

#### CLI build stuff
  - move `entry_point` (hooray! _one_ thing is easy!)
  - add a way to extend `flags` and `aliases`?

**Comment by jtpio** [comment]
Thinking about moving that one to `0.2.0` so we can soon release a `0.1.0`.

This would give us more time to iterate on the interface for web worker kernels: https://github.com/jupyterlite/jupyterlite/issues/463. And having the Python kernel still in the monorepo would probably make that easier for the time being.

**Comment by bollwyvl** [comment]
Sure, that's fine: then in the near term, i think we either need to look at making a federated extension in this repo, or otherwise hoisting it to be shared: i was unable to extend it by subclass over on [pidgy](https://github.com/deathbeds/pidgy/tree/main/lite/jupyterlite-pidgy), as some things we're exposed properly, and had to just copy-pasta the whole thing.

**Comment by jtpio** [comment]
> : i was unable to extend it by subclass over on [pidgy](https://github.com/deathbeds/pidgy/tree/main/lite/jupyterlite-pidgy), as some things we're exposed properly, and had to just copy-pasta the whole thing.

Right, https://github.com/jupyterlite/jupyterlite/issues/463 should make it easier hopefully.
