### ISSUE TITLE
Adding new server routes in a serverlite extension

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#390]
### Problem

For now the server implementation doesn't allow adding new routes: https://github.com/jupyterlite/jupyterlite/tree/main/packages/server/src

### Proposed Solution

There should be an extension point so serverlite plugins can add new routes.

One way would be to just expose the router to the public interface:

```typescript
app.server.router.get(
  '/voila/render/(.+)',
  async (req: Router.IRequest, path: string) => {
    // handle the request
  }
);
```

That would be for requests going through `ServerConnection.ISettings`. In the case of voila that would be a bit more complicated and probably require a new app / endpoint that would also leave on the server.

### Additional context

For reference the default routes are defined here:

https://github.com/jupyterlite/jupyterlite/blob/6fdcbbe38616fced8ca59ee5b0d1ce6530765c4f/packages/server/src/server.ts#L52-L218

**Comment by bollwyvl** [comment]
Ha, thought it already did that! We'll want new routes for sure!

As might be guessed, i'd see value in (optionally?) allowing registration
of a (couple) routes with an openapi spec.

I don't understand the voila issue, but that's probably okay.

**Comment by bollwyvl** [comment]
Ha, i thought we had already done this!

**Comment by jtpio** [comment]
Still one "major" change to do before 0.1.0 beta since this is probably going to break the API.
