### ISSUE TITLE
Share a link to a file from the Notebook interface

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#398]
### Problem

#384 added a way to share a link to multiple files in lab:

![image](https://user-images.githubusercontent.com/591645/137783800-2af23de8-5052-4da5-966b-5858b8968db0.png)

"Copy Shareable Link" is also available from the retro file browser: 

![image](https://user-images.githubusercontent.com/591645/137784125-10150d04-5ce9-4f95-b568-cc21c07f5abe.png)

But it generates a link that redirects to `/lab`. Ideally the link generated from the RetroLab interfaces should redirect to `/retro`.

### Proposed Solution

Probably it would be enough to iterate on the existing plugin for now:

https://github.com/jupyterlite/jupyterlite/blob/52944e9cd21785291d0975a63f6723038efa9525/packages/application-extension/src/index.tsx#L445-L494

This is where `lab` is hardcoded in the URL: https://github.com/jupyterlite/jupyterlite/blob/52944e9cd21785291d0975a63f6723038efa9525/packages/application-extension/src/index.tsx#L475

### Additional context

As mentioned in related issues and PRs, it would be great to have a more advanced way for sharing files / workspaces (some of it could be done upstream).

**Comment by bollwyvl** [comment]
Some discussion over on https://github.com/jupyterlite/jupyterlite/pull/457#issuecomment-1017079021

**Comment by bollwyvl** [comment]
> This is where `lab` is hardcoded in the URL: 

In retro, does `appUrl` point at `/retro`?

**Comment by jtpio** [comment]
> In retro, does `appUrl` point at `/retro`?

I think it's still `/lab` at the moment:

![image](https://user-images.githubusercontent.com/591645/152402354-1c407014-d237-4bc2-afa9-b770a05ebb82.png)

**Comment by bollwyvl** [comment]
Hm... well it looks like upstream in lab, it drives `workspaces` (which we don't have) and `settings` (which we do... but implement quite differently)... and is _not_ used for the share link. So i guess `app` means "the host web server app," not "this in-browser app".

Also, semi-related: 
https://github.com/jupyterlab/retrolab/issues/344
