### ISSUE TITLE
Open a local folder with the FileSystem API

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#403]
### Problem

It would be great if we could just mount a local folder intro JupyterLite using the Filesystem API.

This would avoid having to manually upload / download notebooks.

Or still being able to persist changes when editing notebooks and files in a private browser window.

### Proposed Solution

For now the contents is managed in https://github.com/jupyterlite/jupyterlite/blob/main/packages/contents/src/contents.ts

With the assumption that files are persisted to IndexedDB / localStorage. Maybe that part would have to modified or extended.

Or maybe this could even be a normal JupyterLab extension, so that it could also be used on Binder and other ephemeral sessions. By adding additional drives: https://github.com/jupyterlab/jupyterlab/blob/997f3af68396539136ab0cb8512c73c07e021e4a/packages/services/src/contents/index.ts#L229-L232

### Additional context

This would be a Chrome / Edge / Opera only feature:

![image](https://user-images.githubusercontent.com/591645/138412455-cd506432-dceb-4ab3-b054-57d31b958ffa.png)

So it should not affect uses of other browsers like Firefox. We should also not advertise using Chrome, maybe just a quick mention in the docs would be enough.

More info: https://web.dev/file-system-access/

**Comment by jtpio** [comment]
As a heads-up I've started looking into implementing a JupyterLab extension to give access to the local file system using the FileSystem API, implementing a custom drive using the `Contents.IDrive` interface:

https://user-images.githubusercontent.com/591645/160241594-6b363b06-2103-445a-ac68-9ecc6104e0c4.mp4

This should then also be compatible with JupyterLite, so folks could include it in their deployment just like other lab extensions.

Will try to push the code and publish the package over the coming days...

**Comment by bollwyvl** [comment]
An IDrive is a great interim solution: it looks like there's some polyfills
for non-chrome stuff.

I haven't looked but maybe there's a localForage adapter for this api...
But for certain configurations that cold be ideal.

**Comment by datakurre** [comment]
@jtpio Does this allow also kernels to see all the files from chosen local folder?

**Comment by jtpio** [comment]
@datakurre unfortunately not. This has the same limitations as the default contents manager.

Hopefully this will be improved by https://github.com/jupyterlite/jupyterlite/issues/315.

**Comment by Ciantic** [comment]
Sorry to bother you, but I can't see "Open local folder" option in https://jupyterlite.readthedocs.io/en/stable/_static/lab/index.html

Maybe it's not on the sidebar like in that video, or maybe the implementation is still not done?

<img src="https://github.com/jupyterlite/jupyterlite/assets/64731/646d16fe-3dbb-46c5-b65d-698a916911f1" width="350" />

I have just these four buttons, and in that video there is fifth for opening from file system.
