### ISSUE TITLE
Support for https in requests

### ISSUE THREAD

**Issue by andeplane** [jupyterlite/jupyterlite#413]
### Problem
I want to authenticate with Microsoft Azure with https url. Can be reproduced with 

`requests.get("https://login.microsoftonline.com/5409fe5e-39ad-4448-90ad-6688455011bf/oauth2/v2.0/token")`

but when I run it, I get error 

`HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /5409fe5e-39ad-4448-90ad-6688455011bf/oauth2/v2.0/token (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))`

which seems to me is a problem with the installed packages. If I have this on a linux machine, I would install OpenSSL or something like that, but here I don't really know.

### Proposed Solution
I am not sure, and this may be pyodide more than jupyterlite, but trying here first :)

**Comment by andeplane** [comment]
I realized that this really is a pyodide issue, not jupyterlite. Closing!

**Comment by jtpio** [comment]
Thanks @andeplane for opening the issue.

Yes it's more related to Pyodide.

For reference there was a recent discussion about this in https://github.com/jupyterlite/jupyterlite/discussions/412

With using `fetch` as an alternative to `requests`.
