### ISSUE TITLE
`import ssl` fails → can't fetch HTTPS content

### ISSUE THREAD

**Issue by ryan-williams** [jupyterlite/jupyterlite#415]
## Solution/Summary
- Use `js.fetch` instead of e.g. `urlretrieve` (cf. https://github.com/pyodide/pyodide/issues/529)
- For some functions, like `pandas.read_html`, use unsupported `urllib` functions under the hood.
  - In these cases, you'll need to `fetch` the URL yourself, save it to a file, and point `pd.read_html` at that file
  - [Example code](https://github.com/jupyterlite/jupyterlite/issues/415#issuecomment-963323676)
- Some sites, like Wikipedia, don't return CORS headers that would allow `fetch` to work.
  - I'm not sure what to do about that, or whether it makes sense that e.g. GitHub provides the required CORS headers while Wikipedia doesn't.
  - One workaround is to download the HTML yourself (either via a system Python install, `wget`, or "View Page Source" / "Save Page" in the browser), upload it to somewhere `fetch`able (like a GitHub repo or gist), and point your Jupyterlite notebook at that URL.

## Description

`import ssl` fails in Jupyterlite (Pyolite kernel on [the demo site](https://jupyterlite.readthedocs.io/en/latest/_static/lab/index.html)):

![image](https://user-images.githubusercontent.com/465045/140762636-39b4ac1f-9a9e-4116-8f47-a4938384f502.png)

This affects [this block in `http/client.py`](https://github.com/python/cpython/blob/v3.9.6/Lib/http/client.py#L1368-L1376):
```python
try:
    import ssl
except ImportError:
    pass
else:
    class HTTPSConnection(HTTPConnection):
        "This class allows communication via SSL."
        …
```

which causes `HTTPSConnection` to never be defined, so [there's no `https` protocol handler available](https://github.com/python/cpython/blob/v3.9.6/Lib/urllib/request.py#L581-L582).

This results in various attempts to fetch `https` URLs hitting `URLError: <urlopen error unknown url type: https>`:
- `urlretrieve`
- `pandas.read_html`

(Note that `pandas.read_html` requires `import lxml` before `import pandas` to even get this far, otherwise it fails with `ImportError: lxml not found, please install it` before even attempting to fetch the URL.)

## Reproduce

[Here is a notebook](https://gist.github.com/ryan-williams/2a026b16ac531aad0b196fe610c9a607) I created on [the jupyterlite demo "server"](https://jupyterlite.readthedocs.io/en/latest/_static/lab/index.html) that shows these end results of this issue: (`urlretrieve` and `pd.read_html` failing to fetch an `https` URL).

The full source is
```python
import ssl          # ❌ fails: ModuleNotFoundError: No module named '_ssl'

from urllib.request import urlretrieve
url = 'https://en.wikipedia.org/wiki/Project_Jupyter'
urlretrieve(url)    # ❌ fails: `URLError: <urlopen error unknown url type: https>`

import lxml
import pandas as pd
pd.read_html(url)   # ❌ fails: `URLError: <urlopen error unknown url type: https>`
```

#### `import ssl`
![image](https://user-images.githubusercontent.com/465045/140767455-d06ac034-67a4-4c21-9074-fa67742dfe01.png)

#### `urlretrieve`
![image](https://user-images.githubusercontent.com/465045/140767520-cd20ec94-cd61-4b68-ba0a-0be5fc9bedc1.png)

#### `import lxml.etree` → `pd.read_html`
![image](https://user-images.githubusercontent.com/465045/140767570-5a10c2df-44b9-4238-9676-a1b8c0bb72fd.png)

Continued:

![image](https://user-images.githubusercontent.com/465045/140767613-92b3d633-77d1-41e7-8429-badebe406745.png)

## Expected behavior

Expect `urlretrieve`/`pd.read_html` to be able to fetch HTTPS URLs.

## Context

- JupyterLite version: Version 0.1.0-alpha.16 (https://jupyterlite.readthedocs.io/en/latest/_static/lab/index.html)
- Operating System and version: macOS Big Sur 11.6
- Browser and version: Chrome, Version 95.0.4638.69 (Official Build) (arm64)

<details><summary>Browser Output</summary>
<pre>
Dispose worker for kernel 0f962d82-1560-48a8-8dd4-d91b6e22bac6
react_devtools_backend.js:2540 Connection lost, reconnecting in 0 seconds.
overrideMethod @ react_devtools_backend.js:2540
_reconnect @ default.js:1245
reconnect @ default.js:526
restart @ default.js:496
async function (async)
restart @ default.js:493
restartKernel @ sessioncontext.js:319
restart @ sessioncontext.js:788
async function (async)
restart @ sessioncontext.js:763
restartKernel @ index.js:1972
(anonymous) @ index.js:559
e.execute @ index.es6.js:371
e._executeKeyBinding @ index.es6.js:531
e.processKeydownEvent @ index.es6.js:470
e.evtKeydown @ index.es6.js:356
e.handleEvent @ index.es6.js:312
pyodide.asm.js:14 Python initialization complete
load-pyodide.js:172 Loading distutils
load-pyodide.js:198 Loading distutils from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/distutils.js
load-pyodide.js:252 Loaded distutils
load-pyodide.js:172 Loading micropip, pyparsing, packaging, distutils
load-pyodide.js:198 Loading micropip from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/micropip.js
load-pyodide.js:198 Loading pyparsing from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/pyparsing.js
load-pyodide.js:198 Loading packaging from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/packaging.js
load-pyodide.js:185 distutils already loaded from default channel
load-pyodide.js:252 Loaded micropip, pyparsing, packaging, distutils
load-pyodide.js:172 Loading matplotlib, distutils, cycler, six, kiwisolver, numpy, pillow, pyparsing, python-dateutil, pytz
load-pyodide.js:198 Loading matplotlib from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/matplotlib.js
load-pyodide.js:185 distutils already loaded from default channel
load-pyodide.js:198 Loading cycler from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/cycler.js
load-pyodide.js:198 Loading six from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/six.js
load-pyodide.js:198 Loading kiwisolver from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/kiwisolver.js
load-pyodide.js:198 Loading numpy from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/numpy.js
load-pyodide.js:198 Loading pillow from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/pillow.js
load-pyodide.js:185 pyparsing already loaded from default channel
load-pyodide.js:198 Loading python-dateutil from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/python-dateutil.js
load-pyodide.js:198 Loading pytz from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/pytz.js
load-pyodide.js:252 Loaded matplotlib, distutils, cycler, six, kiwisolver, numpy, pillow, pyparsing, python-dateutil, pytz
load-pyodide.js:172 Loading jedi, parso, pygments, decorator, setuptools, distutils, pyparsing
load-pyodide.js:198 Loading jedi from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/jedi.js
load-pyodide.js:198 Loading parso from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/parso.js
load-pyodide.js:198 Loading pygments from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/Pygments.js
load-pyodide.js:198 Loading decorator from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/decorator.js
load-pyodide.js:198 Loading setuptools from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/setuptools.js
load-pyodide.js:185 distutils already loaded from default channel
load-pyodide.js:185 pyparsing already loaded from default channel
load-pyodide.js:252 Loaded jedi, parso, pygments, decorator, setuptools, distutils, pyparsing
7f57e2c3-8b14-444f-ab6f-bc93221bdc02:58 Pyolite kernel initialized, version 0.1.0a16
7f57e2c3-8b14-444f-ab6f-bc93221bdc02:320 Perform execution inside worker {type: 'execute-request', data: {…}, parent: {…}}
7f57e2c3-8b14-444f-ab6f-bc93221bdc02:320 Perform execution inside worker {type: 'execute-request', data: {…}, parent: {…}}
7f57e2c3-8b14-444f-ab6f-bc93221bdc02:320 Perform execution inside worker {type: 'execute-request', data: {…}, parent: {…}}
load-pyodide.js:172 Loading lxml, beautifulsoup4, soupsieve, cssselect, html5lib, webencodings, six, pandas, distutils, numpy, python-dateutil, pytz
load-pyodide.js:198 Loading lxml from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/lxml.js
load-pyodide.js:198 Loading beautifulsoup4 from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/beautifulsoup4.js
load-pyodide.js:198 Loading soupsieve from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/soupsieve.js
load-pyodide.js:198 Loading cssselect from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/cssselect.js
load-pyodide.js:198 Loading html5lib from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/html5lib.js
load-pyodide.js:198 Loading webencodings from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/webencodings.js
load-pyodide.js:185 six already loaded from default channel
load-pyodide.js:198 Loading pandas from https://cdn.jsdelivr.net/pyodide/v0.18.1/full/pandas.js
load-pyodide.js:185 distutils already loaded from default channel
load-pyodide.js:185 numpy already loaded from default channel
load-pyodide.js:185 python-dateutil already loaded from default channel
load-pyodide.js:185 pytz already loaded from default channel
load-pyodide.js:252 Loaded lxml, beautifulsoup4, soupsieve, cssselect, html5lib, webencodings, six, pandas, distutils, numpy, python-dateutil, pytz
</pre>
</details>

**Comment by jtpio** [comment]
Thanks @ryan-williams for the detailed report :+1: 

This is probably more of a limitation of Pyodide.

An alternative is to use the browser `fetch`, for example:

```python
from js import fetch

URL = "https://eu.httpbin.org"

res = await fetch(URL)
text = await res.text()
print(text)
```

![image](https://user-images.githubusercontent.com/591645/140771370-cbcd69f1-eb85-4a49-9778-fd2db328e867.png)

**Comment by bollwyvl** [comment]
Woof, yeah: there's a couple key parts of stdlib that just aren't going to
work without _substantial_ patching upstream... Potentially even to import.
We kind of have our hands full getting the jupyter/ipython layer of stuff
working, and are trying to stay out of lower level this when we possibly
can.

In addition to networking, I'd imagine anything related to displays,
processes, pipes, resources will be "off" and things that sniff
platform/implementation-specific stuff will likely be wrong.

The examples posted (and those on the documentation and demos) are the best
we have for now, but would be happy to accept more content for
organizing/surfacing these kinds of knowledge. For example, we've discussed
adding message filtering and reporting (which we can do at the
any-kernel-message level) and could show links in the status bar etc. when
certain errors are encountered. This feature wouldn't even be stuff to
lite, but we'd have our own set of "gotchas," as would other harsh
environments like "windows".

Good luck!

**Comment by ryan-williams** [comment]
Cool, yea this looks like a somewhat canonical discussion of it on the pyodide end https://github.com/pyodide/pyodide/issues/529.

I think I'd tried the `js.fetch` version previously but it was before I'd learned the "`import lxml` before `import pandas`" thing, and I got the wires crossed debugging the two.

So, I seem to be able to do what I want like this:

```python
from contextlib import nullcontext
from js import fetch
import lxml  # must precede `import pandas`, for `pd.read_html` to work
from os.path import basename, exists
import pandas as pd

async def urlretrieve(url, path, use_cache=True):
    if use_cache and exists(path):
        print(f'Found existing {path}; returning')
        return path
    print(f'Saving {url} to {path}')
    res = await fetch(url)
    text = await res.text()
    with open(path, 'w') as f:
        f.write(text)
    return path

async def read_html(url, path=None):
    if path is False:
        ctx = TemporaryDirectory()
        path = join(ctx.name, basename(url))
    else:
        ctx = nullcontext()
        if path is None:
            path = basename(url)
    
    with ctx:
        await urlretrieve(url, path)
        return pd.read_html(path)
```

`read_html` is essentially a replacement for `pd.read_html` that uses `js.fetch` to download the HTML to a local file first (and caches that by default). So then something like this works:

```python
url = 'https://raw.githubusercontent.com/CarsDontFit/car-wars/8c802f978a4b83e165122138d9a896a9010b5ef6/Motor_vehicle_fatality_rate_in_U.S._by_year.html'
dfs = await read_html(url)
dfs[0]
```

A related issue I hit is that Wikipedia apparently doesn't serve CORS headers that allow `js.fetch` to work; you get the error #347, `JsException: TypeError: Failed to fetch`.

```python
url = 'https://en.wikipedia.org/wiki/Motor_vehicle_fatality_rate_in_U.S._by_year'
dfs = await read_html(url)
```
<details><summary>Output</summary>

```
---------------------------------------------------------------------------
JsException                               Traceback (most recent call last)
<ipython-input-19-d32ab0355a25> in <module>
      1 url = 'https://en.wikipedia.org/wiki/Motor_vehicle_fatality_rate_in_U.S._by_year'
----> 2 dfs = await read_html(url)
      3 dfs[0]

<ipython-input-3-4fcb0e9774e5> in read_html(url, path)
     20 
     21     with ctx:
---> 22         await urlretrieve(url, path)
     23         return pd.read_html(path)

<ipython-input-3-4fcb0e9774e5> in urlretrieve(url, path, use_cache)
      4         return path
      5     print(f'Saving {url} to {path}')
----> 6     res = await fetch(url)
      7     text = await res.text()
      8     with open(path, 'w') as f:

/lib/python3.9/asyncio/futures.py in __await__(self)
    282         if not self.done():
    283             self._asyncio_future_blocking = True
--> 284             yield self  # This tells Task to wait for completion.
    285         if not self.done():
    286             raise RuntimeError("await wasn't used with future")

/lib/python3.9/asyncio/tasks.py in __wakeup(self, future)
    326     def __wakeup(self, future):
    327         try:
--> 328             future.result()
    329         except BaseException as exc:
    330             # This may also be a cancellation.

/lib/python3.9/asyncio/futures.py in result(self)
    199         self.__log_traceback = False
    200         if self._exception is not None:
--> 201             raise self._exception
    202         return self._result
    203 

JsException: TypeError: Failed to fetch
```
</details>

![image](https://user-images.githubusercontent.com/465045/140778425-65c58b82-ecef-45dd-848e-601500ad1954.png)

In #347, the person was `fetch`ing from their own server, so they could presumably just fix the CORS headers on that side. I'm not sure could/should be done about Wikipedia. Is it weird that GitHub allows these fetches and Wikipedia doesn't?

For now, my workaround is saving the Wikipedia pages to GitHub (once per page), and then having my Jupyterlite notebooks `js.fetch` from GitHub. Whew!

**Comment by ryan-williams** [comment]
I summarized things at the top of the issue. Happy to keep discussing, but will close for now.

**Comment by jtpio** [comment]
Thanks @ryan-williams for writing that summary.

Since this has come up several times recently, we should add that to the documentation. A good place to start with could be the FAQ: https://github.com/jupyterlab/jupyterlab/pull/9439. Or a new section in the User Guide: https://jupyterlite.readthedocs.io/en/latest/user-guide.html#contents

@ryan-williams would you like to open a PR to improve the documentation? Thanks!
