### ISSUE TITLE
[wip] pyodide 0.19 notes

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlite/jupyterlite#429]
I'm having a look at some stuff that is landing as it looks like pyodide 0.19.0 might be winding up

- https://github.com/pyodide/pyodide/pull/2008
  - this means we can drop the [nbformat mock](https://github.com/jupyterlite/jupyterlite/tree/main/packages/pyolite-kernel/py/nbformat)
- https://github.com/pyodide/pyodide/pull/1976
  - will be useful for more confidently evaluating the feasibility of an early demo, e.g.:
    - one or two `pip wheel` repackaings? no prob!
    - need a whole new binary stack? no thanks!

There will probably be some more stuff... i've been preferring to use local pyodide stuff for testing, but i haven't figured out how to get the dev artifact out easily...

**Comment by bollwyvl** [comment]
:santa:  https://github.com/pyodide/pyodide/releases/tag/0.19.0a1

**Comment by rth** [comment]
Yeah, if you have a chance to test it, feedback would be very welcome. The final release will happen next week.

**Comment by bollwyvl** [comment]
> a chance to test it

I hope to! I'm most concerned about our `(micro)pip(lite)` hacks, but really looking forward to some of the other stuff. Also, of note, `lite` (and by extension `pyoidide`) [might end up](https://github.com/jupyter/jupyter.github.io/issues/513) as an above-the-fold link on `try.jupyter.org` to take some load of `mybinder.org`.

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlite/jupyterlite/pull/433 and released in `0.1.0a19`: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0a19
