### ISSUE TITLE
Verify behavior with IPython 8.0.0

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlite/jupyterlite#444]
### Problem

While our docs site ships its own ipython wheel, a "naive" `jupyter lite build` is going to start pulling ipython 8.0.0 hot from pypi. We have no idea what this is going to do, either for our relatively involved uses of the API or for downstreams. Some of the demo pieces might already have ipython pins, as well.

### Proposed Solution

- Investigate all of our examples vs IPython 8.
- adjust pyolite to work with IPython 7 or 8 (e.g. compat flags)
- offer an `ipython-version` setting in the pyolite kernel 

### Additional context

...

**Comment by jtpio** [comment]
> adjust pyolite to work with IPython 7 or 8 (e.g. compat flags)

If focusing on IPython 8 exclusively by default can help reduce maintenance efforts in lite, that would be great.

**Comment by martinRenou** [comment]
I've just tried xeus-python with IPython 8. There seem to be no issue (completion, inspection, widgets, display publishing, etc works nicely).

As the Pyolite/IPython interface implementation was quite close to the one in xeus-python, I guess there is a change that no issue arises from updating.

**Comment by bollwyvl** [comment]
Yeah, if we don't have to specify, that would be _wonderful_. :star_struck: I guess we'll see!

**Comment by jtpio** [comment]
Seems to be running well with IPython 8 on https://jupyterlite.github.io/demo:

![image](https://user-images.githubusercontent.com/591645/149228864-3c69f379-0c4b-4013-910b-8eac6d31b96d.png)

**Comment by bollwyvl** [comment]
In that I haven't observed a single issue, i think we just close this one out.
