### ISSUE TITLE
How do I use a different CDN for pyodide?

### ISSUE THREAD

**Issue by vrthra** [jupyterlite/jupyterlite#451]
### Problem

In the documentation on [configuration](https://jupyterlite.readthedocs.io/en/latest/configuring.html), I see that we can provide a pyodide URL which is then downloaded. I want instead to provide a CDN URL for pyodide that is then used like the original CDN?

**Comment by bollwyvl** [comment]
Yeah, that's what [`pyodideUrl`](https://jupyterlite.readthedocs.io/en/latest/configuring.html#pyodide) does: it doesn't download anything to your server, but rather tells your users' web browser to.

The build-time downloading behavior is only triggered by the [CLI option](https://jupyterlite.readthedocs.io/en/latest/cli.html#common-parameters) `--pydodide`.

**Comment by vrthra** [comment]
Thanks, Is there a corresponding CLI option? or do I have to modify `$YOUR_JUPYTERLITE/{app}/jupyter-lite.json` for that?

**Comment by bollwyvl** [comment]
There is no CLI setting for a large number of the config options: those are generally reserved for when things are... hard.

I _guess_ you could use `cat` to write the file out... but it's _really_ verbose JSON, and probably better off just checked in/generated at build time.

By default, this layout:

```
your_jupyter_lite/  # cd into this folder
  jupyter-lite.json  # include `pyodideUrl`
```

running:

```
cd your_jupyter_lite
jupyter lite build
```

would yield:

```
your_jupyter_lite/
  jupyter-lite.json
  _output/
    index.html
    jupyter-lite.json  # an updated copy of `../jupyter-lite.json` with pyodideUrl
    apps/
      lab/
        index.html
        jupyter-lite.json
        # ... lots of other stuff
```

The `jupyter-lite.json` files get merged, so you would _not_ need to customize the app unless you want to.

An alternative would be to us jq or something after the fact to update the output.

**Comment by vrthra** [comment]
Ah thank you! much appreciated.

**Comment by bollwyvl** [comment]
Closing as apparently resolved.
