### ISSUE TITLE
asyncio, without await

### ISSUE THREAD

**Issue by psychemedia** [jupyterlite/jupyterlite#455]
One of the issues of working in JupyterLite is that certain functions must be called as `await`ed async functions.

It would be useful if there were a way of decorating functions so that `asyncio` functions could be treated as non-async functions, without the `await` requirement.

The https://github.com/davidbrochart/syncio package attempts to create a decorator for this, although I don't think it works in a notebook context, let alone `jupyterlite` context. But I don't understand enough of `asyncio` to know what the blockers are on making it work in such contexts, if it is possible.

Such a decorator would allow the creation of simple wrapper functions to remove the explicit `await` requirement, and simplify notebook usage. This would be particularly useful in cases where async function hacks are required, such as when trying to load load data files into `pandas` from browser storage, eg as per  https://github.com/jupyterlite/jupyterlite/issues/119 .

**Comment by bollwyvl** [comment]
This is mostly an upstream issue: pyolite is bound by pyodide, which is in
turn bound by emscripten, which is in turn bound by the browsers.

There are some tools like asyncify that work at the emscripten level, but
there is really quite a bit at the network plumbing level that would need
porting before it made a difference to user code.

PRs welcome, but if this _can_ be solved unobtrusively (i.e. without
rewriting user source on the fly), the fix belongs in pyodide, which
already ships e.g. pandas.

**Comment by psychemedia** [comment]
Just as a way of tracking this: https://github.com/pyodide/pyodide/issues/1545
