### ISSUE TITLE
ENH: jupyterlab-google-drive support

### ISSUE THREAD

**Issue by westurner** [jupyterlite/jupyterlite#465]
### Problem

JupyterLite users need a way to save their notebooks to their Google Drive because otherwise their locally-saved notebooks are lost upon {browser cache reset is it?,}?

### Proposed Solution

- [x] https://github.com/jupyterlite/jupyterlite/issues/464
- [ ] From https://github.com/jupyterlab/jupyterlab-google-drive/issues/203 : 
  > - Determine whether jupyterlab-google-drive already works in a jupyter lite build
  > - BLD,ENH,REF: Integrate the components with minimal maintenance overhead

**Comment by bollwyvl** [comment]
The best play in this case is to keep pushing upstream on `jupyterlab-google-drive`, as it theoretically would work out of the box, containing no server component. However: you will note that project is dormant, and unlikely to be warmed up until https://github.com/jupyterlab/jupyterlab-google-drive/issues/108 is resolved. Please feel free to reopen this issue at that point.
