### ISSUE TITLE
Disable fetching `jupyter-lite.ipynb`

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#466]
### Problem

Site deployers sometimes want a clean dev tools console with no error.

At the moment JupyterLite tries to fetch configuration files from well-known places, such as `jupyter-lite.ipynb`. This often leads to 404s, for example:

![image](https://user-images.githubusercontent.com/591645/152304236-e0bc959f-2d95-47d9-8677-c15a2ae4fe8e.png)

### Proposed Solution

Either a default `jupyter-lite.ipynb` is created on build, or fetching `jupyter-lite.ipynb` is made configurable.

**Comment by bollwyvl** [comment]
I guess i'd be inclined to ship all-but-empty notebooks, as I still look forward to when we can start authoring sites in lab... or lite itself.

**Comment by bollwyvl** [comment]
By extension, perhaps we should consider reducing our `console.log` output even further.

Some notably chatty places where we've done this to ourselves:
- app startup (`Starting app`, `JupyterLite Examples started, waiting for restore`, `JupyterLite Examples restored`)
- kernel messages


I guess, ideally, we'd run silent except for errors, and have the linter fail on new `console.log` entries. If we did want configurable, discretionary logging, maybe add an ability to increase it either by:
- changing `jupyter-lite.json#/jupyter-config-data/logLevel: DEBUG`
- a plugin which will look for a URL param (e.g. `?LOG_LEVEL=DEBUG`)
