### ISSUE TITLE
bqplot in gitlab page deployment

### ISSUE THREAD

**Issue by djangoliv** [jupyterlite/jupyterlite#471]
## Description

On gitlab page bqplot doesn't display the Map.
It is stuck on "Loading Widget ..." .
You can se the problem here: https://benabel.gitlab.io/jupyterlite-template/lab/index.html with ipyleaflet.ipynb.
I reproduce this problem on my own instance (with ipyleaflet.ipynb and bqplot.ipynb).

## Expected behavior
The map is displayed like on readthedoc deployement.

## Context

firefox
Jupyterlite 0.1.0a21

Regards

**Comment by bollwyvl** [comment]
Take a look in your browser console:

```
523.cf94b68f6edde7eefd61.js:1 Uncaught (in promise) Error: Module bqplot, semver range ^0.5.33 is not registered as a widget module
```

This means: the labextension (which must be shipped unpacked in `lab/extensions/bqplot`) and the `bqplot` in the pyodide kernel (which must be shipped as a wheel) are not compatible.

You have a few options:
- pin labextensions and [versions in notebooks](https://github.com/jupyterlite/jupyterlite/blob/main/examples/pyolite/ipyleaflet.ipynb)
- automate pinning the versions with e.g. a `requirements.txt` 
  - `pip download` them into `my-lite-dir/pypi`

**Comment by djangoliv** [comment]
Thanks @bollwyvl . It works for me now.
