### ISSUE TITLE
Document in-app keyboard shortcuts

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlite/jupyterlite#509]
### Problem

Rather a lot of useful keyboard-driven features are enabled in the various app, but there is no way (or _no easy way_ ) to discover what they are... especially if further customized by extensions, etc.

### Proposed Solution

- for `lab`: 
  - just wait for 3.3.0 to have the settings editor, which will at least be _better_
- for `repl`
  -  add a "Keyboard Shortcuts" button to the toolbar (by default?)
    - i guess this would show a popup?
  - ensure the buttons also show their keyboard shortcuts?
- for `retro`
  - similar popup as above, probably

### Additional context

Unless it goes in lab core, this probably should be a third-party extension a la [jupyterlab-keycaps](https://github.com/deathbeds/jupyterlab-keycaps), though it probably _wouldn't_ add it to the console toolbar by default.

**Comment by jtpio** [comment]
For `lab` this is indeed available now:

![image](https://user-images.githubusercontent.com/591645/208981951-f764cdc5-2778-47ba-ad93-de84599fc834.png)


For the other apps probably something could be consumed from upstream directly, as proposed in this PR: https://github.com/jupyterlab/jupyterlab/pull/11960

**Comment by jtpio** [comment]
For reference this might be fixed by https://github.com/jupyterlab/jupyterlab/pull/14053 after updating to the lab 4 packages: https://github.com/jupyterlite/jupyterlite/pull/1019
