### ISSUE TITLE
Upgrade to pyodide 0.19.1

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlite/jupyterlite#518]
### Problem

- https://github.com/pyodide/pyodide/releases/tag/0.19.1
- https://pyodide.org/en/stable/project/changelog.html#version-0-19-1

### Proposed Solution

- bump some 0's to 1's

### Additional context

- n/a

**Comment by jtpio** [comment]
Neat!

**Comment by jtpio** [comment]
PR opened: https://github.com/jupyterlite/jupyterlite/pull/519
