### ISSUE TITLE
Disabled toolbar items in RetroLab

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#537]
## Description

This seems to be happening in RetroLab and is related to the `app.commands.notifyCommandChanged();` trick added in https://github.com/jupyterlite/jupyterlite/pull/528.

It's not reproducible on all page reloads.

## Reproduce

Go to a JupyterLite website running `0.1.0b1` and open a notebook with RetroLab.

![image](https://user-images.githubusercontent.com/591645/156988515-83ee5cb0-84ab-4249-ba23-c4843ef06c5f.png)

## Context

Follow-up to https://github.com/jupyterlite/jupyterlite/pull/528

**Comment by jtpio** [comment]
Stock JupyterLab? Or the lab app in JupyterLite?

**Comment by bollwyvl** [comment]
Ha. Lablite. Will do some more digging but might be a tick...

**Comment by bollwyvl** [comment]
Didn't have a chance to look into this further, but do we think this would be fixed by revving to 3.3.1?

**Comment by jtpio** [comment]
Closing as this does not seem to be happening anymore with the latest JupyterLite 0.2.x releases, based on Notebook 7.

Although the issue might still be there, and happening randomly.

Linking to the following issues for reference, in case this needs to be re-opened:

- https://github.com/jupyter/notebook/issues/6553
- https://github.com/jupyterlab/jupyterlab/pull/15553
