### ISSUE TITLE
Binder Link doesn't work

### ISSUE THREAD

**Issue by larsbonczek** [jupyterlite/jupyterlite#540]
## Description

mybinder.org errors out with the following message when building this repository:

```
[...]
$ yarn-deduplicate -s fewer --fail
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
TaskFailed - taskid:setup:js
Command failed: '['/srv/conda/envs/notebook/bin/yarn', 'deduplicate']' returned 1

Removing intermediate container 264d6b87bb3a
The command '/bin/sh -c ./.binder/postBuild' returned a non-zero code: 1Built image, launching...
Failed to connect to event stream
```

## Reproduce

1. Click the Binder link in the ReadMe: https://mybinder.org/v2/gh/jupyterlite/jupyterlite/main?urlpath=lab
2. Wait
3. See error above

**Comment by bollwyvl** [comment]
Thanks for the report. In an attempt to start managing our nodejs build/download sizes some, we've been trying some approach like `yarn-deduplicate`. Simultaneously, we've added more automation around releases, and the version bumping script gets out of sync.

While fixing the whole problem is a bit tricky, we can adjust it to not break binder.

**Comment by jtpio** [comment]
I've seen this one also happen locally after doing a `git clean` followed by the full setup (`doit`).

The `yarn-deduplicate` command is not run on CI and RTD at the moment: 

https://github.com/jupyterlite/jupyterlite/blob/0bf8f3b64b611f622d6b477a38054a0d7b79f0bf/dodo.py#L104-L105
