### ISSUE TITLE
ipympl buttons not properly rendered

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlite/jupyterlite#550]
## Description

When displaying a matplitlib figure using `ipympl`, the buttons are not properly rendered:
![image](https://user-images.githubusercontent.com/4711805/158257497-86ae0f0c-8501-445d-b832-ef855258b2f2.png)

## Reproduce

Open and execute [this notebook](https://jupyterlite.readthedocs.io/en/latest/_static/lab?path=pyolite%2Fipympl.ipynb).

**Comment by jtpio** [comment]
Thanks @davidbrochart for reporting.

A quick check in the dev tools console indicates this is an issue with font awesome:

![image](https://user-images.githubusercontent.com/591645/158258933-79bfdb15-e32e-4080-9b1a-c96451d903a2.png)

```
downloadable font: rejected by sanitizer (font-family: "Font Awesome 5 Free" style:normal weight:400 stretch:100 src index:1) source: https://jupyterlite.readthedocs.io/en/latest/_static/build/fa-regular-400.woff2
```

**Comment by jtpio** [comment]
This appears to be the case with other extensions too, for example with `stickyland`: https://github.com/xiaohk/stickyland/issues/4

**Comment by jtpio** [comment]
For reference this seems to be working with `0.1.0a22`:

![image](https://user-images.githubusercontent.com/591645/158262265-52132366-81ff-413a-a089-884cb4195654.png)

Looks like https://github.com/jupyterlite/jupyterlite/pull/477 might be related (cc @bollwyvl)

**Comment by martinRenou** [comment]
IIRC ipympl as well as ipywidgets assumes fontawesome is in the page

**Comment by jtpio** [comment]
I think it comes from `@jupyterlab/application` here and should be available on the page in lab / lite:

https://github.com/jupyterlab/jupyterlab/blob/7af65dd2fdfb443e13aaf1e03a7951ea98be7f1d/packages/application/package.json#L44

**Comment by bollwyvl** [comment]
i took a bit of a look yesterday and didn't come up with much.

the `woff2` assets are getting copied all the way through on build (e.g. are listed in the [hashsums](https://jupyterlite.readthedocs.io/en/latest/_static/SHA256SUMS) file), but the woff2 files have a `js` wrapper around them. We either need to figure out how to do one/more/something other than:

- make the chunk renaming dynamic to special case font-awesome
- use the base64 loader on them, so the file path resolution doesn't have to be perfect
- move them to an (installed/activated by default) federated extension
- muck around with the upstream [rules](https://github.com/jupyterlab/jupyterlab/blob/3.3.x/builder/src/webpack.config.base.ts#L19-L22) 

...but have made no headway yet.

**Comment by bollwyvl** [comment]
Going to see if #554 helps...

**Comment by bollwyvl** [comment]
Yep, between #554 and hacking more upstream rules to be `asset/resource`, things are much better:

![Screenshot from 2022-03-15 19-49-37](https://user-images.githubusercontent.com/45380/158495416-a9d9b794-22c4-4fa8-abc4-991cf85f3c6b.png)
