### ISSUE TITLE
mock-socket WebSocketServer should use the mock: false flag to not stub out the global WebSocket 

### ISSUE THREAD

**Issue by shibbas** [jupyterlite/jupyterlite#559]
### Problem

The latest version of mock-socket now provides a way to specify that the global WebSocket should not be stubbed out. Currently any following Websocket operations after starting a kernel also end up using mock-socket unless you set it back. It's best to set this option to false to avoid this. 

### Proposed Solution

Solution provided here: https://github.com/thoov/mock-socket/issues/308

**Comment by jtpio** [comment]
Thanks @shibbas for the heads up :+1: 

Looks like the relevant code is here: 

https://github.com/jupyterlite/jupyterlite/blob/fa985055885cb1d53cccbf6e46ced7d14d38ea06/packages/kernel/src/kernels.ts#L152

Would you like to submit a PR to add the new flag? Thanks!

**Comment by oeway** [comment]
Would be really useful if we can fix this, the current mock-socket used in the jupyterlite kernel is problematic when I try to use it with the native websocket.
