### ISSUE TITLE
Better integration with the "Open from a URL" command

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#561]
### Problem

In https://github.com/jupyterlite/jupyterlite/pull/528 we updated to the latest JupyterLab 3.3.

This brought the "Open from URL" feature added in https://github.com/jupyterlab/jupyterlab/pull/11387.

This is already functional in the latest `0.1.0b3` release:

https://user-images.githubusercontent.com/591645/158786569-20a84697-ca50-4868-bd66-3b5f4893b893.mp4

JupyterLite also already supports opening a given file on startup:

https://jupyterlite.readthedocs.io/en/latest/user-guide.html#how-can-i-share-a-link-to-a-file

### Proposed Solution

Maybe `?path=` should also be able to open from URL, if the command is available?
 
This could be implemented as a third-party extension first.

### Additional context

cc @psychemedia since you brought that point in https://blog.ouseful.info/2022/03/16/my-personal-blockers-to-adopting-jupyterlite-for-distance-and-open-educational-use/

**Comment by psychemedia** [comment]
As an alternative to complicating `path=` handling, a `url=` parameter could take the URL (which is reminiscent of the "Open from URL".

This would then provide a way for eg launching notebooks from Github repos or gists into an arbitrary JupyterLite environment from a simple link. Cf Binderhub etc.

**Comment by psychemedia** [comment]
Ah, I see this has already been discussed in https://github.com/jupyterlite/jupyterlite/issues/430

**Comment by jtpio** [comment]
Right, closing in favor of https://github.com/jupyterlite/jupyterlite/issues/430
