### ISSUE TITLE
ipywidgets installation

### ISSUE THREAD

**Issue by ams1** [jupyterlite/jupyterlite#571]
## Description

**The problem:**
I'm trying to install `ipywidgets` using micropip as described at #326 and #236 but i get a ValueError

## Reproduce

1. given a locally served jupyterlite OR https://jupyterlite.github.io/demo/lab/index.html, when running:
    ```py
    import micropip
    await micropip.install('ipywidgets')
    ```
    I get:
        ```
        ValueError: Requested 'widgetsnbextension~=3.6.0', but widgetsnbextension==3.5.0 is already installed
        ```

## Expected behavior

ipywidgets should install

## Context

- JupyterLite version: Version 0.1.0-beta.3
- Operating System and version: Windows 10
- Browser and version: Chrome Version 98.0.4758.102 (Official Build) (64-bit)

**Comment by martinRenou** [comment]
This should be fixed in the next release, see https://github.com/jupyterlite/jupyterlite/issues/565 and https://github.com/jupyterlite/jupyterlite/pull/566, in the meantime you can probably do:

```python
import micropip
await micropip.install('ipywidgets==7.6.5')
```

**Comment by jtpio** [comment]
FYI @ams1 `0.1.0b4` has been released with the fixes mentioned above: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0b4

**Comment by ams1** [comment]
Thank you! - sorry i missed #565 - i'll try to do a better job searching next time :-)
