### ISSUE TITLE
Provide an easier way to manager `piplite` wheels

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#574]
### Problem

At the moment the docs suggest:

> Extra wheels that can be installed via piplite in a running kernel can be added via the --piplite-urls CLI flag or LiteBuildConfig/piplite_urls config value, or simply left in-place in lite_dir/pypi.

https://jupyterlite.readthedocs.io/en/latest/configuring.html#adding-pyolite-wheels

This requires manual crafting of URLs and can be tedious and error-prone.

### Proposed Solution

There is some logic in the main `dodo.py` to manage that list for the demo site of the repo:

https://github.com/jupyterlite/jupyterlite/blob/41da1cb7ba64708284a07ac381d296466d0f0fdd/dodo.py#L1272-L1316

Maybe this could be moved to the `piplite` addon of the `jupyterlite` CLI so it can be reused outside of the repo?

https://github.com/jupyterlite/jupyterlite/blob/main/py/jupyterlite/src/jupyterlite/addons/piplite.py

### Additional context

This would be useful to other JupyterLite website that want to prefetch the wheels to increase stability (for example to avoid recent breakage related to the new ipywidgets version).

**Comment by bollwyvl** [comment]
>  requires manual crafting of URLs

The reason for the complex URL-crafting on this repo is just that we don't want to check in all the wheels, but _do_ want to maintain a robust history of what wheels we had... if only so we can roll back to working ones.

> simply left in-place in `lite_dir/pypi`

If anything, we should push the well-known paths more, as they are the least prescriptive: as long as you get the right files to a place, it's good to go, and can be driven by a robust locking mechanism. The issue with "magically" downloading wheels there are _so_ many ways to describe and get them. Our demo needs are met by "Big PyPI," but...

- What about my corporate proxy server?
- What about poetry?
- What about pipenv?
- What about if i only use conda? mamba?

By delegating the getting of wheels to a place to a separate step, e.g. `wheel download` one maintains a lot of power without the creep. We _really_ don't want to be a package manager.

So i guess I'd rather wait to do anything too specific until we've split the python component out entirely, and can think about how best to encapsulate some more magical behavior.

**Comment by jtpio** [comment]
> We really don't want to be a package manager.

For sure existing package managers should just be leveraged. I think the use case here is more about the generation of the list of wheels, which can then be stored in `jupyter_lite_config.json` and versioned. And then explicitly be updated when doing updates.

**Comment by bollwyvl** [comment]
>  just be leveraged

yeah, well... if it was possible to  `--dry-run` one of the existing ones from a stable API I'd be all for it... but the upstreams aren't super keen to make any commitments to getting this information more directly than "install full environment, read off versions." It's pretty frustrating. as it is in `dodo`, it's pretty ugly, and makes a number of assumptions that I'm not sure are even sound...

**Comment by bollwyvl** [comment]
Sigh. Started having to do more shenanigans for this over on #578  because `fastjsonschema` doesn't have "predictable" URLs. It's really hard to get excited about supporting this.

**Comment by jtpio** [comment]
Closing as this indeed looks like a lot of troubles to try to provide (and maintain) some helpers in core.
