### ISSUE TITLE
Support pyodide 0.20.0

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlite/jupyterlite#577]
### Problem

pyodide 0.20 is Kind Of A Big Deal, as it bumps up to python 3.10, drops a number of packages, favoring pure python wheels.

### Proposed Solution

 [0.20.0a1](https://github.com/pyodide/pyodide/releases/tag/0.20.0a1) is out, and we could start testing now.

### Additional context

Previous alphas had been about a week, so we could just wait, but if we found any real issues, it might be better to do early.

**Comment by bollwyvl** [comment]
Of note, it looks like `depfinder` doesn't work with python 3.10 yet :(

**Comment by bollwyvl** [comment]
Looks like newer IPython needs mock `pexpect`...

**Comment by datakurre** [comment]
@bollwyvl Do you mean that this would make jupyterlite somewhat independent from https://cdn.jsdelivr.net/pyodide/?

**Comment by bollwyvl** [comment]
>  jupyterlite somewhat independent 

it is already entirely independent, if you so desire, with the [`--pyodide` CLI option](https://jupyterlite.readthedocs.io/en/latest/cli.html#pyodide). You're signing up for serving 150mb of files, though!

**Comment by richardotis** [comment]
Can you comment on how pyodide's recently adopted binary wheel format (https://github.com/pyodide/pyodide/pull/2027 ) might work with JupyterLite? All the existing documentation and issues for both pyodide and JupyterLite seem to assume all wheels are pure Python noarch wheels, but that is no longer the case.

I've been playing with pyodide 0.20.0 and have managed to successfully import packages built as binary wheels from the test REPL console generated by `pyodide-build serve`, but I haven't had luck with this on the JupyterLite side yet, even with a built local version of https://github.com/jupyterlite/jupyterlite/pull/578 . Advice and/or a minimal example would be greatly appreciated.

**Comment by bollwyvl** [comment]
I'd wager you could force it to work now by manually patching pypi/all.json
after the build... I think the runtime code assumes you gave it good stuff.

Otherwise: we're still just trying to get it working. If you have a more
concrete reproducer, feel free to post as a dedicated issue...
