### ISSUE TITLE
File not found, but clearly uploaded. Openpyxl cannot be installed?

### ISSUE THREAD

**Issue by Hunteriwi** [jupyterlite/jupyterlite#579]
## Description

Tried to use jupyter on browser, since now it's lite, it changed and now throws this error:

![image](https://user-images.githubusercontent.com/45808925/160261692-223b78d3-1b70-4d34-b77d-39fd6d5533c1.png)

I already uploaded my file and still cannot get past this error. I needed openpyxl before, but I cannot pip install it anymore.

![image](https://user-images.githubusercontent.com/45808925/160261705-31178eaf-cae7-4141-bea1-f0640475ba27.png)

## Reproduce
I have this block of code that caused the problem:

    import numpy as np
    import matplotlib.pyplot as plt
    import pandas as pd
    from sklearn.linear_model import LinearRegression

    xls = pd.ExcelFile('Degradacion_de_azucares_en_medio_de_orujo_LB400.xlsx')

and when I tried to install openpyxl like this:

    import sys
    !{sys.executable} -m pip install openpyxl

![image](https://user-images.githubusercontent.com/45808925/160261684-38bdc07f-bb47-4f06-a28a-a28468a17db2.png)

Using last version of Google Chrome, and jupyterLite lab on it.

**Comment by bollwyvl** [comment]
Please have a look at some of the example documents, issues, and
discussions, where some of these topics are discussed:

- use "import piplite; await piplite install ('openpyxl')"
  - but many packages don't work, such as any that use processes, threads,
or networking
- at present, files uploaded to your browser are not trivially available in
the kernel
  - but loading files from elsewhere on the internet is actually far easier
  - look for "import js; await js.fetch"

**Comment by tomthe** [comment]
It would be nice to make it clearer in the guides that it is not trivial to access uploaded files from the kernel. I had the impression it would be easy and only after 2 hours of trying and searching I found this answer.

**Comment by jtpio** [comment]
> It would be nice to make it clearer in the guides that it is not trivial to access uploaded files from the kernel.

Opened https://github.com/jupyterlite/jupyterlite/pull/601 to address this.
