### ISSUE TITLE
Clear current state

### ISSUE THREAD

**Issue by sapristi** [jupyterlite/jupyterlite#582]
Hello, I have started playing with jupyterlite, and would like to thank all maintainers for this awsome tool !

### Problem

It seems that when updating content on the server, the clients will need to clear all their local data to pick up the new content / updated notebooks.

I would like a more "user friendly" way to do this.

--- 

Sorry if this has been discussed somewhere else, but I couldn't find an issue or documentation about this.

**Comment by bollwyvl** [comment]
Perhaps a duplicate of https://github.com/jupyterlite/jupyterlite/issues/407 ?

**Comment by sapristi** [comment]
Indeed, closing :)
