### ISSUE TITLE
How to use phat old Jupyter online?

### ISSUE THREAD

**Issue by Paw-El-Cow** [jupyterlite/jupyterlite#584]
JupyterLite is so raw it hasn't been born yet. It doesn't support too many vital features of the old one.

**Comment by martinRenou** [comment]
Thanks for opening an issue. 

> It doesn't support too many vital features of the old one.

Can you be more specific about your comment? Which Jupyter front-end are you referencing to with "the old one" (Jupyter Notebook/JupyterLab)? Which are the features you see missing and would like to see added in JupyterLite?

**Comment by martinRenou** [comment]
Are you saying you would prefer to have back a real JupyterLab deployment on try.jupyter.org instead of JupyterLite?

**Comment by Paw-El-Cow** [comment]
Yes, or JupyterNotebook. JupyterLite in the current state is useless for me.

**Comment by martinRenou** [comment]
try.jupyter.org has moved to using JupyterLite for reducing costs. You can always install JupyterLab on your machine :)

If you don't have a specific feature request/issue, I'm closing this issue.

**Comment by Paw-El-Cow** [comment]
> You can always install JupyterLab on your machine :)

I don't have one (:
