### ISSUE TITLE
Cannot add local pyolite wheels but with explicit url - feature or bug ?

### ISSUE THREAD

**Issue by oscar6echo** [jupyterlite/jupyterlite#588]
## Description

I have created a small wheel and placed it in folder `pypi/` as explained in the doc [here](https://jupyterlite.readthedocs.io/en/latest/configuring.html#adding-pyolite-wheels).

The build step works as expected: The wheel is copied into `_output/pypi`, referenced in `_output/pypi/all.json`, and `_output/jupyter-lite.json` contains the relevant ref:

```json
"litePluginSettings": {
      "@jupyterlite/pyolite-kernel-extension:kernel": {
        "pipliteUrls": [
          "./pypi/all.json?sha256=7766266d3969726da988fc7517e11d76897009bb9e38b29bac3bab346e977afd"
        ]
      }
    },
```
Now to use in a notebook this package I tried:

+ with micropir
```py
import micropip
await micropip.install('jupyterlite_utils')
# it fails as the url fetched is https://pypi.org/pypi/jupyterlite_utils/json
```

+ with piplite
```py
import piplite
await piplite.install('jupyterlite_utils')
# it fails as the url fetched is https://pypi.org/pypi/jupyterlite_utils/json
```

+ with explicit url
```py
import micropip
base_url = 'http://localhost:3000'
whl_name = 'jupyterlite_utils-0.1.0-py3-none-any.whl'
await micropip.install(f'{base_url}/pypi/{whl_name}')
# it works as the wheel is indeed served at this url
```

## Question

Is is the expected behavior ?
Is there was a simpler way to reference the wheels served ?
Where to look in the doc or in the code to find out ?

Note this is not blocking. I'm just trying to avoid going unnecessarily manual.

**Comment by bollwyvl** [comment]
right, `micropip` won't look at all for it, but `piplite` should. what's the actual content of `pypi/all.json`? there might be some normalization issue: if the distribution `name` is actually `jupyterlite-utils`, it might need to be the argument to `install`, even if the wheel uses an underscore.

**Comment by oscar6echo** [comment]
Ok, right ! This is the solution.  
This does work:

```py
import piplite
await piplite.install('jupyterlite-utils')
# it works
```
---

More details for future readers:

The content of `/pypi/all.json` is:
```json
{
  "jupyterlite-utils": {
    "releases": {
      "0.1.0": [
        {
          "comment_text": "",
          "digests": {
            "md5": "875e3e99a40931d0837bffa528f03854",
            "sha256": "b490da461806ef18f9975819ca351fa930c6005005f958af13a41580b24c07fc"
          },
          "downloads": -1,
          "filename": "jupyterlite_utils-0.1.0-py3-none-any.whl",
          "has_sig": false,
          "md5_digest": "875e3e99a40931d0837bffa528f03854",
          "packagetype": "bdist_wheel",
          "python_version": "py3",
          "requires_python": null,
          "size": 4726,
          "upload_time": "2022-04-03T11:17:38.660746Z",
          "upload_time_iso_8601": "2022-04-03T11:17:38.660746Z",
          "url": "./jupyterlite_utils-0.1.0-py3-none-any.whl",
          "yanked": false,
          "yanked_reason": null
        }
      ]
    }
  }
}
```
The reason the key is `jupyterlite-utils` is that it is the name of the folder containing the `setup.py` creating the wheel.  
Another way to see it is the wheel dist-info/METADATA#Name is `jupyterlite-utils`.

Then if I use a key in `/pypi/all.json`, `jupyterlite-utils` in this case, then I can `await piplite.install(<key>)`.  
Under the hood it builds the wheel full url and do the equivalent of `await micropip.install(f'{base_url}/pypi/{whl_name}')`.
