### ISSUE TITLE
Start kernel in extension with `jupyterlite` 

### ISSUE THREAD

**Issue by trungleduc** [jupyterlite/jupyterlite#607]
Hello,
 I'm creating a `jupyterlab` extension that needs to interact with a python kernel (something along the lines of this example https://github.com/jupyterlab/extension-examples/tree/master/kernel-messaging )
For now, it works well with `jupyterlab` but when I start my extension in `jupyterlite`, I got the following errors:

![kernel](https://user-images.githubusercontent.com/4451292/164104652-8f339e56-9140-4f0b-a606-eedc391e2518.png)

The relevant part of my extension is the following function:

```javascript
async  startKernel(): Promise<void> {
  const sessionManager: SessionManager  = this.options.manager.sessions;
  await sessionManager.ready;
  await sessionManager.refreshRunning();

  this._sessionConnection = await sessionManager.startNew({
    name: KERNEL_NAME,
    path: UUID.uuid4(),
    type: '',
  });
  const kernelSpecs: KernelSpecManager = this.options.manager.kernelspecs
  await kernelSpecs.ready;
  const specs = this.options.manager.kernelspecs.specs!;
  const kernelModel = {
    name: specs.kernelspecs[specs.default]!.name,
  } as Kernel.IModel;
  await this._sessionConnection.changeKernel(kernelModel);
}

```
Do you have any pointer to solve this issue? Thanks!

**Comment by jtpio** [comment]
Thanks @trungleduc for reporting this.

```ts
const sessionManager: SessionManager  = this.options.manager.sessions;
```

Does the `manager` come from `app.serviceManager` in the extension? The stack trace shows `mock-socket` so it's probably the case.

Would you mind posting the JupyterLite version and browser you're using? (it's part of the issue template normally)

**Comment by trungleduc** [comment]
Hello @jtpio, sorry for the missing info. Indeed I get the `manager` from the `app.serviceManager` 
- `jupyterlite` version 0.1.0b5
- `Chrome` version 100.0.4896.127

**Comment by trungleduc** [comment]
Fixed by https://github.com/jupyterlite/jupyterlite/pull/657

**Comment by jtpio** [comment]
Nice, thanks @trungleduc for following up here!
