### ISSUE TITLE
input function  return asyncio.futures.Future

### ISSUE THREAD

**Issue by glapcio** [jupyterlite/jupyterlite#609]
Hi
In the Jupyter online version(Jupyter lab) function import return asyncio.futures.Future (expected string)
![image](https://user-images.githubusercontent.com/50668454/164410971-8ccfe4f8-e678-4c5c-af3a-257f344e2e9a.png)
I tried it few days ago and worked but currently is different.

**Comment by jtpio** [comment]
@glapcio for now you need to use the `await` keyword:

```py
await input("test")
```
Also it looks like combining the print in one statement doesn't output anything (this might be a different issue).

In the meantime you can do something like the following:

![image](https://user-images.githubusercontent.com/591645/164415327-2c3c4917-6f2d-4d48-9157-22c6680f8eb0.png)

**Comment by glapcio** [comment]
Thank You. I'm wondering why input return asynch task ?
And the second after await the code is not processed further :
![image](https://user-images.githubusercontent.com/50668454/164426493-3ccd7195-bc10-426c-b20b-0ce6efae9ef3.png)

**Comment by martinRenou** [comment]
This is a duplicate of https://github.com/jupyterlite/jupyterlite/issues/275

We did not find a way around this for now. But if you have ideas please share them in the issue I just mentioned :)

**Comment by glapcio** [comment]
Thank You.
