### ISSUE TITLE
Hide or remove Javascript kernel 

### ISSUE THREAD

**Issue by rafpyprog** [jupyterlite/jupyterlite#612]
Is it possible to build or customize a JupyterLite instance removing the Javascript kernel?

**Comment by jtpio** [comment]
@rafpyprog yes you can use a custom `jupyter-lite.json` with the following content:

```json
{
  "jupyter-lite-schema-version": 0,
  "jupyter-config-data": {
    "disabledExtensions": [
      "@jupyterlite/javascript-kernel-extension"
    ]
  }
}
```

Some more info about this file in https://jupyterlite.readthedocs.io/en/latest/configuring.html#runtime-configuration-files
