### ISSUE TITLE
Make shareable links open subdirectories

### ISSUE THREAD

**Issue by HighDiceRoller** [jupyterlite/jupyterlite#613]
### Problem

I go to a file in a subdirectory and select "Copy Shareable Link":

![image](https://user-images.githubusercontent.com/98680644/164614587-b8f9cb83-cb74-4cd0-9e6a-0cb8b2dc5342.png)

Using the link opens the correct file. However, the File Browser is opened to the root directory rather than the subdirectory:

![image](https://user-images.githubusercontent.com/98680644/164614746-035d0bf7-1e68-4fe0-903f-ada2c8bb09d8.png)

[The actual link in this example.](https://highdiceroller.github.io/icepool/notebooks/lab?path=ability_scores%2Fcompletely_unfair.ipynb)

### Proposed solution

I would have expected the link to open the File Browser to the subdirectory that the linked file is in (e.g. `/ability_scores/` in this case).

**Comment by jtpio** [comment]
Thanks @HighDiceRoller for reporting.

Probably the "Show in File Browser" command could be triggered automatically after opening the documents:

![image](https://user-images.githubusercontent.com/591645/164624672-5d19aa46-7aa5-4c0c-9af1-b9c2756ec4de.png)

**Comment by jtpio** [comment]
Actually this can also be achieved by enabling the "Navigate to current drectory" option in the settings editor:

https://user-images.githubusercontent.com/591645/164706967-5bd54ca9-569c-4ef4-9058-bbd6d3505ccd.mp4
