### ISSUE TITLE
Ipywidgets no longer works in default installation

### ISSUE THREAD

**Issue by deeplook** [jupyterlite/jupyterlite#620]
## Description

Using the "default" [JupyterLite Lab installation](https://jupyterlite.readthedocs.io/en/latest/_static/lab/index.html) on [readthedocs.io](https://readthedocs.io) I was able before (some weeks) to import/use e.g. `ipywidgets` like this, but now I'm getting the error below:

```python
>>> import micropip
>>> await micropip.install("ipywidgets")
[...]
ValueError: Couldn't find a pure Python 3 wheel for 'tornado>=4'. You can use
`micropip.install(..., keep_going=True)` to get a list of all packages with missing wheels.

>>> await micropip.install("ipywidgets", keep_going=True)
[...]
ValueError: Couldn't find a pure Python 3 wheel for: 'pyzmq>=22.3', 'tornado>=6.0',
'tornado>=4', 'tornado>=6.1', 'argon2-cffi-bindings', 'pyzmq>=17'
```

- JupyterLite as installed on readthedocs.io.
- Browser and version: Firefox 99.0 (should not matter)

**Comment by martinRenou** [comment]
Does it behave differently with piplite?

```python
import piplite

await piplite.install('ipywidgets')
```

**Comment by deeplook** [comment]
Yes, it does, thanks! Maybe worth deprecating micropip in the docs?

**Comment by bollwyvl** [comment]
We _only_ mention piplite in the docs/examples, and describe the
relationship to micropip.
