### ISSUE TITLE
Behavior when downloading files with unsaved edits

### ISSUE THREAD

**Issue by HighDiceRoller** [jupyterlite/jupyterlite#628]
### Problem

When downloading a file that has unsaved edits, the unedited version of the file is downloaded. I've been surprised by this behavior on a few occasions; my natural expectation is that the file would be saved before downloading.

### Proposed Solution

A (non-exhaustive) list of possible alternative behaviors for this case:

1. Automatically save the file before downloading, with the context menu option being named something like "Save and Download".
2. Add separate context menu options for "Download Without Saving" and "Save and Download".
3. After selecting "Download", prompt the user whether they would like to save before downloading.
4. Automatically save the file before downloading if the "Autosave Documents" user setting is checked. (Actually, I'm not sure what this setting currently does?)
5. Add a new user setting to determine whether files are automatically saved before downloading.

If I had to pick one I'd go with option 4, but I welcome any other opinions even if they are for the status quo.

As always, thanks for this phenomenal project!

**Comment by jtpio** [comment]
Thanks @HighDiceRoller.

> Automatically save the file before downloading, with the context menu option being named something like "Save and Download".

Since JupyterLite defines its own commands for downloading the content, probably the context could first be saved with `await context.save()` before triggering the download. 

The relevant code is here:

https://github.com/jupyterlite/jupyterlite/blob/7a7a8a92d98b5b3700ef8ad51c8e2306efcbea23/packages/application-extension/src/index.tsx#L204-L298

**Comment by jtpio** [comment]
@HighDiceRoller would you like to give this a try and open a PR?

My guess would be that we could add `await context.save()` here:

https://github.com/jupyterlite/jupyterlite/blob/7a7a8a92d98b5b3700ef8ad51c8e2306efcbea23/packages/application-extension/src/index.tsx#L263

And here:

https://github.com/jupyterlite/jupyterlite/blob/7a7a8a92d98b5b3700ef8ad51c8e2306efcbea23/packages/application-extension/src/index.tsx#L289

Then we could check the behavior on the ReadTheDocs preview for the PR.

**Comment by HighDiceRoller** [comment]
Gave it a try, see what you think.
