### ISSUE TITLE
Error: Shared module @jupyter-widgets/base doesn't exist in shared scope default

### ISSUE THREAD

**Issue by ivanistheone** [jupyterlite/jupyterlite#635]
## Description

Console error when when testing the new SymPy Live shell.

<img width="604" alt="Screen Shot 2022-05-08 at 8 59 07 AM" src="https://user-images.githubusercontent.com/163966/167297450-cceec120-8856-4d55-b380-ed8cbc5f7caa.png">

## Reproduce
- visit [this url](https://sympy.github.io/live/repl/?toolbar=1&kernel=python) 
- open JS console
- 

## Expected behavior

No errors in console.

## Context

- JupyterLite version: [this build](https://github.com/sympy/live/commit/3cd4fd0083eb3da89b3fc325da113f033b7422b0)
- Operating System and version: Mac OS 11.6
- Browser and version: Firefox 100.0 (64-bit)

**Comment by jtpio** [comment]
Thanks @ivanistheone.

I opened https://github.com/sympy/live/pull/8, which should prevent that error message from being logged in the dev tools console.

**Comment by ivanistheone** [comment]
confirmed after merging #8 (and pushing https://github.com/sympy/live/commit/86b6acbe1ed5bc2ee10337345c3b97476c5c2dd0 directly to main), the js console is now clean:

<img width="593" alt="Screen Shot 2022-05-08 at 4 41 57 PM" src="https://user-images.githubusercontent.com/163966/167315105-24ea3796-aa7c-4bb6-86c2-00a3572b4235.png">

<img width="575" alt="Screen Shot 2022-05-08 at 4 42 13 PM" src="https://user-images.githubusercontent.com/163966/167315108-4df134d7-2758-4e3f-ae36-1ecdf57b2ffb.png">
