### ISSUE TITLE
Might have accidentally edited the official docs?? Really, really confused, sorry.

### ISSUE THREAD

**Issue by nathanielvirgo** [jupyterlite/jupyterlite#637]
I would like to make a simple iPython notebook to share with students in a class, who might not have Python installed.

I found the documents at https://jupyterlite.readthedocs.io/en/latest/_static/retro/tree/ and thought "oh, I didn't know about this project, let's try it out." So I created a new file and put some teaching content in it with the intention of sharing the link with the students.

But now I'm really confused - it seems like somehow the file I created is in the same folder as the official documentation. Did I somehow accidentally edit the official docs? Or does the file only exist on my machine but just appears to be in the repository at readthedocs? If I share the link, will other people be able to access it?

The file I created is at https://jupyterlite.readthedocs.io/en/latest/_static/retro/notebooks/?path=Population%20dynamics.ipynb . Many apologies if I've accidentally vandalised the official docs - feel free to remove the file as I have a local copy.

If it is possible for random noobs to accidentally edit the official docs, I would suggest changing that. Either way, I strongly suggest making the documentation **much** clearer regarding how to make shareable links. At the moment it is not even clear to me whether this is a web-based service that anyone can use, or whether I'm supposed to set up my own web server.

**Comment by jobovy** [comment]
You haven't edited the official docs. The file you've created is in your browser's cache, so it shows up for you, but not for others (I don't see it). So don't worry! While you can technically create a 'shareable link' to your file, it isn't actually shareable, because the notebook doesn't exist for anybody else.

If you want to share your own notebook(s) with other users, you have to build your own deployment with the notebook(s) that you want to share and then you could use the 'shareable link' feature to share links to them. The easiest way to do this is using the demo site repository here: https://github.com/jupyterlite/demo. The README there has detailed instructions on how to use the demo repository to build your own deployment with custom notebooks.

**Comment by nathanielvirgo** [comment]
Thanks, that's very helpful.

I would still suggest some improvements to the documentation are in order, since I wasn't able to discover the page you linked to from the main demo site. Since I got there by searching how to share a notebook online, it was reasonable to think that creating a new file would create a shareable page and not just a local one in my browser's cache - that should be made clear to new users to avoid confusion.

Now I'm trying to follow the instructions you linked to. I guess there are reasons for this being the way it is, but it all seems incredibly weird. I have to make a pull request against the original repository in order to publish something locally on my own account? In any case it's telling me I need approval in order to do that, so no success so far.

**Comment by nathanielvirgo** [comment]
This is what I mean about "approval"

<img width="801" alt="image" src="https://user-images.githubusercontent.com/6964676/167764386-ae8b2c80-583f-4bfd-9de3-250d4bee506f.png">

**Comment by jobovy** [comment]
Yes, I agree that this is weird. I think the maintainers of the demo repository (@jtpio?) should turn off the requirement for approval of workflow runs for first-time contributors. Then your site would be built automatically.

However, note that this only builds the website, you would then still have to deploy it somewhere (i.e., copy it to a web server). Alternatively, you can follow the [instructions for publishing to GitHub Pages](https://github.com/jupyterlite/demo#using-your-own-repository-to-build-a-release-and-deploy-it-to-github-pages), which would automatically deploy your website and update it whenever you make changes. It does require a certain familiarity with GitHub Pages....

**Comment by jobovy** [comment]
Note that if you just want to build your site like you are trying with the PR, you should also be able to just enable workflows to run on your fork, which will then do the same build as should be done by the PR, but in your fork's Actions tab.

To do this, go to your fork's Actions tab where you should see this:

<img width="1137" alt="Screen Shot 2022-05-10 at 11 55 02 PM" src="https://user-images.githubusercontent.com/1044876/167766133-6bd2229a-ba90-4fe5-88d8-0ab0f1598827.png">

then click the green button. To run the workflow, I think you'll then have to push another change to the `main` branch.

**Comment by nathanielvirgo** [comment]
Thanks very much! I'm trying to follow the instructions for deploying to github pages. It mostly seems very straightforward, but I'm stuck where it says 

> from your repository [Settings](https://github.com/jupyterlite/demo/blob/main/settings) tab, select the [Pages](https://github.com/jupyterlite/demo/blob/main/settings/pages) menu item and ensure that the source is set to gh-pages.

This is what I see on that page:

<img width="692" alt="image" src="https://user-images.githubusercontent.com/6964676/167766706-96698f0c-f763-4b0a-a680-abbdafadcdbf.png">

There is only an option to select the brach (I have only main) and then the folders `/` or `/docs`. There's no option to set it to "`gh-pages`" anywhere. If I set it to `/` or `/docs` I only see the readme.md file, not the notebook I uploaded.

**Comment by jobovy** [comment]
Once the workflow runs, it will deploy to the `gh-pages` branch, so it should exist once you push another change that will run the workflow. Then you can select it. I believe you will have to choose the `dist/` folder in that branch then.

**Comment by nathanielvirgo** [comment]
Ah, I think this must be why: the `Build and Deploy` action is failing with this error message:

> The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128

It seems this was happening since my initial commit, so I guess it's not a problem with the notebook I uploaded.

**Comment by jobovy** [comment]
Looks like the deploy action runs into a permissions issue with your repository; this seems helpful: https://github.com/marketplace/actions/deploy-to-github-pages#security-settings-%EF%B8%8F, although I'm not sure what they mean by 'the provided GITHUB_TOKEN'. Maybe it will be obvious in your settings..

**Comment by nathanielvirgo** [comment]
Many thanks! I found it in Settings -> Actions -> general, towards the bottom:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/6964676/167770286-b20b6bc3-dab5-4446-9092-c95b4613f09c.png">

It looks like building and deploying is working now, which is great! I can't seem to get plots to show up, but that must be a separate issue.

**Comment by jobovy** [comment]
Great! Plots show up for me, but if you're having problems, you can try adding `%matplotlib inline` to the top cell.

**Comment by jtpio** [comment]
Thanks @nathanielvirgo for the feedback and @jobovy for the help.

Looks like this is the confusing part in the `jupyterlite/demo` README:

![image](https://user-images.githubusercontent.com/591645/167798356-1e8204da-b4a7-4e27-818d-80ac5404dc26.png)

Which an explain why some other folks also opened similar PRs in the past: https://github.com/jupyterlite/demo/pulls?q=is%3Apr+is%3Aclosed

Just opened https://github.com/jupyterlite/demo/pull/77 as an attempt to simplify this.
