### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by oeway** [jupyterlite/jupyterlite#642]
## Description
I am trying to run the plotly example with the latest jupyterlite but it give me the "ReferenceError: require is not defined" error in the browser console, and the plot didn't show.

## Reproduce
```
pip install -U --pre jupyterlite

jupyter lite serve
```
Open a new notebook and  run the following code:
```
import micropip
await micropip.install(['nbformat>=4.2.0', 'plotly'])

import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(y=[2, 1, 4, 3]))
fig.add_trace(go.Bar(y=[1, 4, 3, 2]))
fig.update_layout(title = 'Hello Figure')
fig.show()
```

## Expected behavior

The plot should show.

## Context

- JupyterLite version: 0.1.0-beta.7
- Operating System and version: MacOS
- Browser and version: Chrome 101.0.4951.54 

<details><summary>Browser Output</summary>
<pre>
VM623:1 Uncaught ReferenceError: require is not defined
    at <anonymous>:1:17
    at t.attachWidget (index.es6.js:2831:26)
    at t.insertWidget (index.es6.js:2734:22)
    at O._insertOutput (widget.js:434:20)
    at O.onModelChanged (widget.js:225:22)
    at l (index.es6.js:461:18)
    at Object.n.emit (index.es6.js:416:17)
    at n.emit (index.es6.js:99:17)
    at h._onListChanged (model.js:231:23)
    at l (index.es6.js:461:18)
</pre>
</details>

**Comment by bollwyvl** [comment]
I believe plotly requires (ha!) the labextension to be installed.

With the other configuration defaults, the simplest way to get this is by
installing  plotly in the same environment as jupyterlite before building.

During the build, it will copy the plotly assets, and tell the app where to
find them (probably something like _output/extensions/jupyterlab-plotly)

For the long-term health of a deployment, it is (probably) important to
match the extension and kernel versions, so it may be worth capturing the
desired version in one of:
- your build environment: this is what we do in the jupyterlite examples in
this repo, with piplite_wheels.
- your user-facing code, e.g. piplite.install('plotly==x.x.x')
