### ISSUE TITLE
Python wheel for `cryptography`

### ISSUE THREAD

**Issue by ineiti** [jupyterlite/jupyterlite#648]
### Problem

I'd like to use JupyterLite in a cryptography course, and found the following code:

```
import micropip
await micropip.install('pyOpenSSL')
```

Unfortunately, when I run this, I get the following error:

```
Couldn't find a pure Python 3 wheel for: 'cryptography>=35.0'
```

### Proposed Solution

It would be nice to have a wheel for this package, but I have no idea how I can
accomplish this. And it's probably not JupyterLite's fault, neither...

**Comment by bollwyvl** [comment]
Yeah, have marked this upstream, as there is not much more we can do at present.

Pre-rust `cryptography` (single digit major version) will be coming along with `pyodide==0.20.1`, which we have currently started on bringing in on #625. We're hoping a few other things (like install name normalization) will also make it in.

Of note: it's all but certain anything that touches the network for _anything_ will probably not work without significant shimming.

You could try some basics out on the _temporary preview_ deployment of that PR, where the following does work:

```py
import piplite
await piplite.install("pyopenssl<22")
import OpenSSL
```

As for `pypopenssl>=22`: that has a hard dependency on the more modern `cryptography`, which requires the `rust` tool chain. At present, there have been some demonstrations of such a thing for pyodide, but it might be a bit longer before more kinds of native extensions are widely distributed: I'm personally hoping we see that come through the conda(-forge) ecosystem, as it would be _far_ more scalable.

**Comment by ineiti** [comment]
OK, thanks a lot. I think I won't play around with it today, as I would need it for tomorrow's course :)
