### ISSUE TITLE
Renderer Failure

### ISSUE THREAD

**Issue by xtawfeeq7k** [jupyterlite/jupyterlite#649]
I can't render `data/fasta-example.fasta` with message : `Cannot read properties of undefined (reading 'seq')`
![image](https://user-images.githubusercontent.com/87164562/169655507-24e29b19-ecab-4e2f-bc8c-13a578bae52e.png)

**Comment by jtpio** [comment]
Thanks @xtawfeeq7k for reporting.

Yes this seems like an issue and has been the case for a while.

**Comment by bollwyvl** [comment]
this appears to be fixed once again as of #670, release as part of `0.1.0b9`. please reopen if you encounter further issues.
