### ISSUE TITLE
Opening csv files

### ISSUE THREAD

**Issue by annawawrzynczak** [jupyterlite/jupyterlite#665]
Opening a csv file with pandas doesn't work. I uploeaded the file in the same folder as the notebook yet still it cannot be found

**Comment by jtpio** [comment]
Thanks @annawawrzynczak for reporting.

This will likely be fixed by https://github.com/jupyterlite/jupyterlite/pull/655

**Comment by martinRenou** [comment]
JupyterLite seems to fail at uploading CSV files as well. The uploaded file is a base64 representation of the file.

![base64](https://user-images.githubusercontent.com/21197331/173299605-7a184b36-f89c-4e24-922f-a2021b9455ab.png)

**Comment by martinRenou** [comment]
#666 and #655 will respectively fix the upload issue and allow the kernel to load the file

![csv](https://user-images.githubusercontent.com/21197331/173301875-4d2685b2-9726-426d-afc4-175bb59b5b1d.png)

**Comment by bollwyvl** [comment]
See #91 for the long running discussion about this. In short: today it's
easier to download files from elsewhere on the Internet then inside the
same browser session.

You can also use ipywidgets:
https://ipywidgets.readthedocs.io/en/7.7.0/examples/Widget%20List.html#File-Upload

Longer term: #655 is the current effort towards unifying contents and the
kernel file system: we're still determining what the limits are of this
approach, but you can already try it out on the ReadTheDocs preview there.
The end goal is for all emscripten-based kernels to have near-transparent
read/write access to a consistent set of files.
