### ISSUE TITLE
More configurable mime types for serving, contents

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlite/jupyterlite#667]
### Problem

At present we hard-code an understanding of some known MIME types. This creates problems when:
- #569 serving files in development where the os/python/browser are misconfigured by a third-party tool
- #665 uploading files where user files which a renderer can show, but the lite contents manager misidentifes

### Proposed Solution

Not mutually exclusive, but roughly in order of impact:

- add some build-time `file_types` configuration options
  - probably reuse [IFileType](https://github.com/jupyterlab/jupyterlab/blob/v3.4.3/packages/rendermime-interfaces/src/index.ts#L167)
  - use this extended knowledge
    - in the browser contents manager
    - in the server, use these to overload the served types (#569)
- do more robust in-browser guessing of well-known types
  - extension-based with [`mime-types`](https://github.com/jshttp/mime-types)
  - extension- and content-based [`@npcz/magic`](https://github.com/npcz/magic)... but doesn't work in browser yet 
- cheat and use the registered file types from the [document registry](https://github.com/jupyterlab/jupyterlab/blob/v3.4.3/packages/docregistry/src/registry.ts#L292)
  - in the browser
  - this is not available at build time, because those JS values aren't available
- add user settings for registering file types
 - this would let someone overcome any build time problems if they _really_ knew what they needed
 - would work well with the above, probably

### Additional context

- might address #534
  - already fixed by #655?
- continues work from #541, #666
- sensible defaults should include e.g #570

**Comment by psychemedia** [comment]
Reading and writing sqlite databases using sqlite throws disk i/o errors in notebook. Could this be related to a mime type issue, eg against `.db` and `.sqlite` filetypes, or does it represent something more fundamental in the way that sqlite3 handlings I/O?
