### ISSUE TITLE
Custom build with 0.1.0b9 does not allow kernel access to GUI content

### ISSUE THREAD

**Issue by oscar6echo** [jupyterlite/jupyterlite#678]
On https://jupyterlite.readthedocs.io/en/latest/_static/lab/ I see:

````py
import pyolite
pyolite.__version__
# '0.1.0b9'

import os
os.getcwd()
# '/drive'

os.listdir('/drive')
# list GUI contents

with open('/drive/coucou.txt', 'w') as f:
    f.write('i am coucou')
# creates file coucou.txt in GUI
````

If I build a custom jupyterlite after pip install `jupyterlite==0.1.0b9` I see:

````py
import pyolite
pyolite.__version__
# '0.1.0b9'

import os
os.getcwd()
# '/home/pyodide' ----> like in 0.1.0b8 ?!?

os.listdir('/drive')
# ['.matplotlib', '.ipython']

with open('/drive/coucou.txt', 'w') as f:
    f.write('i am coucou')
# does not creates file coucou.txt in GUI
````

And menu Help/About Jupyter lite shows: `Version 0.1.0-beta.9` as expected.

How come ?
How can get the same version as RTD ?

**Comment by jtpio** [comment]
@oscar6echo I just checked locally with the built assets from https://github.com/jupyterlite/demo/pull/86 (which can be downloaded [here](https://github.com/jupyterlite/demo/actions/runs/2514924514)) and it looks fine:

![image](https://user-images.githubusercontent.com/591645/174552905-4c21e772-931b-4201-bc24-1ac6b4318bfb.png)

Are you using Firefox in a private window? Otherwise maybe it's a cache issue?

**Comment by oscar6echo** [comment]
@jtpio Thx to the fast reply.  

Unfortunately the error persists on several chromium browsers Chrome, Brave, Opera, not in a private window, and with cache disabled:
![Screenshot from 2022-06-20 10-26-51](https://user-images.githubusercontent.com/2219383/174558927-7278526f-1e81-443e-aebc-95220410076b.png)


I get the same seemingly **inconsistent** result:
+ version '0.1.0b9' displayed in the GUI and in a notebook cell
+ home dir `/home/pyodide`

See below:

![Screenshot from 2022-06-20 10-23-07](https://user-images.githubusercontent.com/2219383/174558216-6f9c03c4-01e5-4576-96dd-f68d26f1f9d0.png)

To create this custom jupyterlite deployment I did:

```bash
pip install `jupyterlite==0.1.0b9`
jupyter lite build -- config jupyter_lite_config.json
```
This is really perplexing...

Could it be that a pip install jupyterlite does not download the exact same assets as the ones you use for the RTD jupyterlite ?

**Comment by jtpio** [comment]
> Could it be that a pip install jupyterlite does not download the exact same assets as the ones you use for the RTD jupyterlite ?

`pip install` will download from PyPI, and the `jupyterlite` bundles the static assets in the wheel. We could check everything looks good by downloading the assets and check the proper files (for the example the service worker) are there: https://pypi.org/project/jupyterlite/0.1.0b9/#files

Also this JupyterLite deployment was updated to `0.1.0b9` and seems to be working fine: https://jupyter.org/try-jupyter/

**Comment by jtpio** [comment]
Does the dev tools console mention something about the service worker failing to activate?

It could also be related to browsers with stricter restrictions: https://github.com/jupyterlite/jupyterlite/issues/679.

**Comment by oscar6echo** [comment]
@jtpio  Your second guess is correct. 

I'll develop a bit to maybe help other people avoid losing time on this problem.

After  investigation it was **not**:
+ a problem with the assets of version `0.1.0b9`
+ a browser cache issue
+ a private window issue

It is **just** that if you serve your jupyterlite site over `http`, **EXCEPT localhost**, then the browser will forbid the service worker activation:

![Screenshot from 2022-06-21 00-20-13](https://user-images.githubusercontent.com/2219383/174684224-d4564b04-0ce3-4db3-b7d4-67cee6e161ba.png)

Why would I need a hostname different from `localhost` ?  (setting file `/etc/hosts`)
Because in my case, the corporate OAuth2 redirect will only work on a specific corporate domain.  
(The OAuth2 is added through a handcrafted custom index.html built from the jupyterlite index.html).  

![Screenshot from 2022-06-21 00-21-51](https://user-images.githubusercontent.com/2219383/174684324-95178542-5e59-4329-99f4-defeb4135371.png)

In this unfortunate case the new `/drive` feature in `0.1.0b9` silently fails - I mean except for the console msg.  
And a user sees:
```py
import os
os.getcwd()
# /home/pyodide
```

This has been disconcerting.  
Maybe a clearer msg could appear in the notebook ?

So to fix the issue:
+ Create a dev certificate (seen as valid by the browser) with [mkcert](https://github.com/FiloSottile/mkcert)
+ serve the jupyterlite static assets with fastapi:

  ```bash
  #! /bin/bash
  
  uvicorn serve:app \
      --host 0.0.0.0 \
      --port 3000 \
      --reload \
      --ssl-certfile tls-localhost-sg.crt \
      --ssl-keyfile tls-localhost-sg.key
  ```
  
  ```py
  # serve.py
  
  from pathlib import Path
  from fastapi import FastAPI
  from fastapi.staticfiles import StaticFiles
  
  app = FastAPI()
  HERE = Path(__file__).parent.resolve()
  dir_jlite = HERE / ".." / "public"
  app.mount("/", StaticFiles(directory=dir_jlite, html=True), name="public")
  ```
   
Then no problem you get the expected:
```py
import os
os.getcwd()
# /drive
```

**Comment by jtpio** [comment]
> It is just that if you serve your jupyterlite site over http, EXCEPT localhost, then the browser will forbid the service worker activation:

Yes this is because service workers are only available in secure contexts: https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#when_is_a_context_considered_secure

>  Maybe a clearer msg could appear in the notebook ?

Agree :+1: As noted in https://github.com/jupyterlite/jupyterlite/issues/679, it would be nice to improve the error handing when the service workers are not supported. For example there could be a small cue in the UI, instead of having to look at the browser dev tools console.
