### ISSUE TITLE
Add empty file `.nojekyll` in build process to avoid problem in github pages deployment

### ISSUE THREAD

**Issue by oscar6echo** [jupyterlite/jupyterlite#687]
If you:
+ deploy a custom jupyterlite instance on [github pages](https://pages.github.com/)
+ happen to have files starting with `_`
  + Always the case if you ship any Python package in folder `/contents`

Then the files with a name starting with `_` will not be served by gh-pages **unless** you add an empty `.nojekyll` file at the root of the `/_output` folder. See [Bypassing Jekyll on GitHub Pages](https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/).  
This strange behavior, not linked to jupyterlite, is disconcerting.  

Maybe `jupyter lite build` could do it by default ? with a warning in the relevant [doc page](https://jupyterlite.readthedocs.io/en/latest/quickstart/deploy.html#) ?

This would probably save some people (like me) time.

**Comment by jtpio** [comment]
Thanks @oscar6echo.

> Maybe `jupyter lite build` could do it by default ? with a warning in the relevant [doc page](https://jupyterlite.readthedocs.io/en/latest/quickstart/deploy.html#) ?

Since this is provider related, this could indeed be added as a note in the documentation. 

And also added by default to the demo repo since it's meant to be deployed on GitHub Pages: https://github.com/jupyterlite/demo

**Comment by jtpio** [comment]
> with a warning in the relevant [doc page](https://jupyterlite.readthedocs.io/en/latest/quickstart/deploy.html#) ?

Opened https://github.com/jupyterlite/jupyterlite/pull/689
