### ISSUE TITLE
SyntaxError after version 0.1.0b6

### ISSUE THREAD

**Issue by rafpyprog** [jupyterlite/jupyterlite#696]
## Description

After version 0.1.0b6  JupyterLab won't work on Firefox 78.9.0esr.

![image](https://user-images.githubusercontent.com/17583740/176001444-3a9e4aaa-5199-4559-be97-aa4096dd6618.png)

## Reproduce

1. Install jupyerlite 0.1.0b6 or greater version
2. run jupyter lite serve
3. try to open jupyterlab

## Expected behavior

Jupyterlab open

## Context

- JupyterLite version: 0.1.0b6 until 0.1.0b10
- Operating System and version: Linux
- Browser and version: Firefox 78.9.0esr

![image](https://user-images.githubusercontent.com/17583740/176001444-3a9e4aaa-5199-4559-be97-aa4096dd6618.png)

**Comment by jtpio** [comment]
@rafpyprog Probably the easiest (and safest) would be to update to Firefox 89+:

![image](https://user-images.githubusercontent.com/591645/176015575-20115aff-0b8d-439b-a180-a4a68dcf8605.png)

**Comment by rafpyprog** [comment]
Thank you guys !@jtpio  @bollwyvl
