### ISSUE TITLE
IPython display failure (caused by service worker)

### ISSUE THREAD

**Issue by qqdaiyu55** [jupyterlite/jupyterlite#701]
## Description

Jupyterlite is stuck on below codes. I inspected the request, it was pending on `https://jupyterlite.readthedocs.io/en/latest/_static/api/drive//%3Cspan%20style=%22color`. Looks like service worker somehow truncates string after `#`.

code snippet
```python
from IPython.display import display, HTML

display(HTML('<span style="color#6c5ce7">debug</span>'))
```

**Comment by martinRenou** [comment]
This is odd. The service worker should not be involved in this, in any way.
