### ISSUE TITLE
pypy CI jobs failing

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlite/jupyterlite#703]
## Description

It looks like pypy jobs are failing. It appears related to a transient dependency from `requests_cache`.

## Reproduce

See current CI jobs

## Expected behavior

At least _some_ pypy CI should be working.

## Context

- noticed (and trying some fixes) on https://github.com/jupyterlite/jupyterlite/pull/702

**Comment by JWCook** [comment]
@bollwyvl Do you happen to remember what the problem was here? Looks like the CI logs related to this aren't available anymore. Just wondering if it's something that could be fixed in requests-cache.

**Comment by bollwyvl** [comment]
Maybe one of the backends? Mongo?

**Comment by JWCook** [comment]
Ah, well there's a chance it was something related to handling optional dependencies that has already been fixed. Either way, I'll add testing with pypy to my todo list.

**Comment by JWCook** [comment]
For reference, I tested requests-cache with pypy, and the only issue I found was related to multithreading with SQLite (some notes on that here: https://github.com/requests-cache/requests-cache/issues/733).

The dependency issue may have been something that was already fixed. If you run into it again, feel free to create a bug report on the requests-cache repo.
