### ISSUE TITLE
The "Build your own JupyterLite" section of the RTD home page links to itself

### ISSUE THREAD

**Issue by manics** [jupyterlite/jupyterlite#706]
### Problem

If you go to the JupyterLite RTD home page and scroll down to [`🏗️ Build your own JupyterLite 🏗️`](https://jupyterlite.readthedocs.io/en/latest/#build-your-own-jupyterlite) you're told to
`See the [documentation](https://jupyterlite.rtfd.io/) for more details.`
i.e. it links back to itself. This is because it's a [copy of the repository README](https://github.com/jupyterlite/jupyterlite/blob/b0ad262b84b7ab11bb7bc89112167bb0d7a27627/docs/index.md?plain=1#L5).

### Suggested Improvement

Easy option: Modify the README to link to a relevant page in RTD, e.g. the [Quick-Start](https://jupyterlite.readthedocs.io/en/latest/quickstart/) guide.
Hard option: Use separate content for the repository README and the RTD home page.

**Comment by epugh** [comment]
I was just about to open this same issue ;-)

**Comment by jtpio** [comment]
Thanks both for reporting.

Probably the README could be updated to point to a different page, for example: https://jupyterlite.readthedocs.io/en/latest/quickstart/deploy.html

Maybe this could also be a good opportunity to simplify or rework the README a little bit.
