### ISSUE TITLE
How to trust HTLM files by default ?

### ISSUE THREAD

**Issue by oscar6echo** [jupyterlite/jupyterlite#708]
Currently to open and render an `.html` file I must:
+ double click on it or right click on HTML viewer
+ click button `Trust HTML`

Is there a way to configure Jupyterlite/lab to **automatically trust `.html` files** ?  
Or a least some of them ?
Or at least those which are present in folder `/files` ?

_CONTEXT_:  
I am well aware of the risks of running arbitrary `html/js/css`.  
The context is that I build pure JS custom data viz, wrapped into standalone template `html` files with a placeholder to be replaced by custom json.  
Sample: https://github.com/oscar6echo/vite-single-file-apps/tree/main/svg-graph.  
The custom json can then be generated in a Python notebook, inserted in the template to produce a result `viz.html` file. The operation is simple for regular Python users. It would be nice if they would not have to click that `Trust HTML` button every time. This is all the more true if the `viz.html` would be in `/files` and shareable via a link.

If it is not possible by standard configuration, is there a way to hack it ?

**Comment by jtpio** [comment]
The command to trust the HTML is defined here in JupyterLab: https://github.com/jupyterlab/jupyterlab/blob/22bc71d1c8481bf847e33d2e1603f10e5b510f11/packages/htmlviewer-extension/src/index.tsx#L155

One way could be to write a small plugin using the `IHTMLViewerTracker` tracker and set the `trusted` to `true` when a new widget is added.

Otherwise maybe it could make sense to add a new setting (defaulting to `false`) to the `html-extension` to allow automatically trusting html files.

**Comment by oscar6echo** [comment]
@jtpio thx for the very precise pointer.  
With the help of [jupyterlab/extension-examples/completer example](https://github.com/jupyterlab/extension-examples/blob/master/completer/src/index.ts) I could see how to apply the change after the `widgetAdded` event.

Result: https://github.com/oscar6echo/jupyterlab-trust-html
This is a big repo for such a tiny modification.  

I believe it would be a useful setting to Jupyterlab in particular in the context of Jupyterlite.  
But I would not know how/where to do that.

**Comment by jtpio** [comment]
@oscar6echo thanks for sharing this :+1: 

Maybe a good start would be to open a new issue in the JupyterLab repo ? https://github.com/jupyterlab/jupyterlab

The relevant code would be placed in the `activate` function of the plugin: https://github.com/jupyterlab/jupyterlab/blob/b4bc105f1b53a1a40b7b8faaca8ca65a1fa01e6f/packages/htmlviewer-extension/src/index.tsx#L65
And added to the schema here: https://github.com/jupyterlab/jupyterlab/blob/b4bc105f1b53a1a40b7b8faaca8ca65a1fa01e6f/packages/htmlviewer-extension/schema/plugin.json#L11

**Comment by jtpio** [comment]
And also @oscar6echo what do you think about closing this issue in favor of https://github.com/jupyterlab/jupyterlab/issues/12792 now that it is tracked upstream in JupyterLab?

**Comment by oscar6echo** [comment]
Closing as suggested by @jtpio
