### ISSUE TITLE
Option to Import pyodide as module 

### ISSUE THREAD

**Issue by joemarshall** [jupyterlite/jupyterlite#710]
Just checking before I make a pr, but in pyolite kernel worker, we call importscripts to load pyodide. This means that if you build as es module with webpack, it breaks, because that assumes all workers are modules (and importscripts doesn't work in modules). It would be nice if that method looked at the extension of the pyodide.js and if it was pointed at pyodide.mjs it could use await import instead of importscripts. This is the only blocker right now to making my jupyterlite based bare notebook build be an es module (makes it easier to use in svelte which is where I'm aiming to use it, and in theory should aid code size too I think.

This file is where the importscripts is. I think it could just be roughly 

'''
 if(pyodideurl.endswith('.mjs')){
   await import
 }else{
   importscripts
 }.
 '''

https://github.com/jupyterlite/jupyterlite/blob/main/packages/pyolite-kernel/src/worker.ts

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlite/jupyterlite/pull/715, thanks!
