### ISSUE TITLE
Writing json to/from files not working - apparent double JSON.stringify()

### ISSUE THREAD

**Issue by oscar6echo** [jupyterlite/jupyterlite#712]
In the following sequence I would expect `dic2` to be the same as `dic1`.  
It is in jupyterlab, not in jupyterlite.

It seems there is an extra `JSON.stringify` when writing to a `.json` file.  
This is a bit crippling if you want to generate, edit, parse such a file.  

Is it easy to fix ?

```py
# Run this code in https://jupyterlite.readthedocs.io/en/latest/_static/lab/
# version Version 0.1.0-beta.10

from pathlib import Path
import json

path = Path('/drive/toto.json')

dic = {'a': 11, 'b': 'qwerty', 'c': [22, 'azerty']}
dic
# {'a': 11, 'b': 'qwerty', 'c': [22, 'azerty']}

txt = json.dumps(dic)
txt
# '{"a": 11, "b": "qwerty", "c": [22, "azerty"]}'

with path.open('w') as f:
    f.write(txt)

with path.open('r') as f:
    txt2 = f.read()
txt2
# '"{\\"a\\": 11, \\"b\\": \\"qwerty\\", \\"c\\": [22, \\"azerty\\"]}"'

dic2 = json.loads(txt2)
dic2
# '{"a": 11, "b": "qwerty", "c": [22, "azerty"]}'

dic2['a']
# error

json.loads(dic2)
# {'a': 11, 'b': 'qwerty', 'c': [22, 'azerty']}
# OK then but surely not what is meant
```

**Comment by jtpio** [comment]
Thanks @oscar6echo for the report and the steps to reproduce.

This probably explains why some of the pandas read / write methods are also not behaving properly: https://github.com/jupyterlite/jupyterlite/issues/682
