### ISSUE TITLE
doit serve:core:py defaults to Nodejs

### ISSUE THREAD

**Issue by Enforcer007** [jupyterlite/jupyterlite#723]
## Description

`doit serve:core:py` uses Nodejs to serve the App, instead of Python.

## Reproduce

Run `doit serve:core:py`. Node will be run.
![image](https://user-images.githubusercontent.com/6951100/178043238-8b217248-90a9-48da-b76b-22195334e928.png)

## Expected behavior

Python script / Server based on Python should run.

- JupyterLite version: 0.1.0b11
- Operating System and version: Ubuntu 20.4
- Browser and version: Firefox 101.01

**Comment by Enforcer007** [comment]
In `dodo.py` the task for serving the app from python has same set of commands as of Nodejs.

```python
   yield dict(
        name="core:py",
        doc="serve the core app (no extensions) with python",
        uptodate=[lambda: False],
        actions=[U.do("yarn", "serve")], # It should be actions=[U.do("yarn", "serve:py")]
        file_dep=app_indexes,
    )
```

**Comment by jtpio** [comment]
Fixed by https://github.com/jupyterlite/jupyterlite/pull/724
