### ISSUE TITLE
Using a local bz2 compressed pyodide distribution

### ISSUE THREAD

**Issue by rickwierenga** [jupyterlite/jupyterlite#727]
## Description

Using a local `.bz2` archive is not supported, `UnboundLocalError: local variable 'will_fetch' referenced before assignment` will always be raised, even when it shouldn't.

## Reproduce

`jupyter lite build --pyodide /path/to/somewhere/pyodide.tar.bz2`

## Expected behavior

\-

## Context

- JupyterLite version: latest
- Operating System and version: macOS 12.3.1 
- Browser and version: n/a

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlite/jupyterlite/pull/728, thanks @rickwierenga!
