### ISSUE TITLE
BEWARE https://jupyterlite.readthedocs.io is down

### ISSUE THREAD

**Issue by oscar6echo** [jupyterlite/jupyterlite#732]
![Screenshot from 2022-07-11 14-22-43](https://user-images.githubusercontent.com/2219383/178263280-d75e2eb3-3d34-4c5d-918c-edabfedf2dde.png)

**Comment by jtpio** [comment]
Thanks @oscar6echo for reporting.

This looks strange, the last build passed just fine: https://readthedocs.org/projects/jupyterlite/builds/17406157/

I just started a new build just to double check.

**Comment by jtpio** [comment]
This seems to be back now:

![image](https://user-images.githubusercontent.com/591645/178272793-b34a6d00-b903-4c36-9356-7e78d21b2fc0.png)

@oscar6echo mind having a second look to double check?

**Comment by oscar6echo** [comment]
Working on my side now.  
Thx for the fast reply.

Closing.
