### ISSUE TITLE
Publish services.js on npm somewhere?

### ISSUE THREAD

**Issue by joemarshall** [jupyterlite/jupyterlite#736]
services.json lives in the app folder which isn't published on npm (or I can't find it?). This means if you're building something based on jupyterlite node modules, you have to manually copy that across from github, and can't install as a dependency easily.

It would be nice if either a)the app folder was published to npm, or b) the services.json lived in the build under packages somehow.

That way those of us who are using a subset of jupyterlite node packages for out of build trees don't have to hack this file in if we want service worker caching etc.

**Comment by jtpio** [comment]
Thanks @joemarshall for the suggestion.

Maybe we could indeed move that to a separate package (for example `@jupyterlite/server` or `@jupyterlite/serviceworker`) and make sure it's still placed under `app/services.js` at build time.

**Comment by jtpio** [comment]
Closing as the `ServiceWorker` should now be distributed via the `@jupyterlite/server` package:

https://github.com/jupyterlite/jupyterlite/blob/main/packages/server/src/service-worker.ts
