### ISSUE TITLE
`pd.read_csv` can't read in https URLs from GitHub

### ISSUE THREAD

**Issue by palewire** [jupyterlite/jupyterlite#744]
Run this:

```python
import pandas as pd
pd.read_csv("https://raw.githubusercontent.com/palewire/news-homepages/main/extracts/csv/sites.csv")
```

And I get this:

```
ile /lib/python3.10/urllib/request.py:1419, in UnknownHandler.unknown_open(self, req)
   1417 def unknown_open(self, req):
   1418     type = req.type
-> 1419     raise URLError('unknown url type: %s' % type)

URLError: <urlopen error unknown url type: https>
```

**Comment by psychemedia** [comment]
Currenyly requires a workaround, eg:

```python
import pandas, pyodide

pandas.read_csv(pyodide.open_url(URL))
```

**Comment by palewire** [comment]
Thank you!

This morning at 10 a.m. I will be hosting a two-hour Jupyter training for a group of fellows at Stanford. It will be the debut of a shorter variation on a six-hour "First Python Notebook" class I teach at journalism conferences. My draft is scripted [here](https://github.com/palewire/first-python-notebook/blob/master/notebooks/faster-python-notebook.ipynb).

If all goes well today, I plan on making any necessary revisions and following up with a repeat performance next week that's open to all comers on Zoom. The coolest thing I learned during the preparation is that the class materials can work JupyterLite. The trick here is the only workaround.

That means a student would take the class and run all of the code without installing anything at all. We're not Mars yet but how cool is that?!

**Comment by jtpio** [comment]
Thanks @palewire for sharing this sounds cool!

An alternative would be to ship the `.csv` file together with the rest of the notebooks. With https://github.com/jupyterlite/jupyterlite/pull/655 now in and released, you should be able to load it with:

```py
import pandas as pd

pd.read_csv('sites.csv')
```

Some more examples in: https://github.com/jupyterlite/jupyterlite/blob/main/examples/pyolite/virtual_drive.ipynb

**Comment by psychemedia** [comment]
In my experience of educational contexts, you often want to start off with a very controlled environment, eg a shipped CSV file in the published repo, but you very quickly then want to move to generality and let students load in their own files. If students try to load in their own files and they fail to load, you can lose them really quickly ("this is pointless" etc.).

Similarly, the need to modify JupyterLite/pyodide executed statements via `await` calls are similarly blocking for many educational use cases, where  you need to be able to use *exactly* the same statements in differently back-ended environments.

**Comment by psychemedia** [comment]
To ship CSVs, pop them in eg a `content` directory in the repo along with your notebooks, and then copy that directory into the distribution: `jupyter lite build --contents content`

**Comment by palewire** [comment]
Inspired by the group here, I've drafted and published a revised class with packaged. Give it a look and let me know what you think.

https://palewi.re/docs/first-python-notebook/_extra/fast-python-notebook/lab/index.html

**Comment by augusto-herrmann** [comment]
For anyone else wondering, who tried `pyodide.open_url()` and it didn't work.

Nowadays the correct call is `pyodide.http.open_url()`. You can also use `pyodide.http.pyfetch()` to fetch network resources. More info in [pyodide.http](https://pyodide.org/en/stable/usage/api/python-api/http.html#module-pyodide.http) documentation.

Note: in any case, the network resource (e.g. csv file) **must** be served by the server with `Access-Control-Allow-Origin: *` in the headers, or the request will be blocked by the browser due to [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) rules.
