### ISSUE TITLE
Xarray HTML repr

### ISSUE THREAD

**Issue by davidbrochart** [jupyterlite/jupyterlite#760]
## Description

The HTML repr of an `xarray.DataArray` cannot be shown.

## Reproduce

1. `pip install jupyterlite jupyterlite-xeus-python`
2. `jupyter lite build --XeusPythonEnv.packages=xarray`
3. `jupyter lite serve`
4. Open a browser at http://127.0.0.1:8000
5. Create a notebook and execute:
```py
import numpy as np
import xarray as xr

data = np.random.rand(4, 3)
da = xr.DataArray(data)
da
```
6. See the error:
```
FileNotFoundError: [Errno 44] No such file or directory: '/tmp/xeus-python-kernel/envs/xeus-python-kernel/lib/python3.10/site-packages/xarray/static/html/icons-svg-inline.html'
```
![image](https://user-images.githubusercontent.com/4711805/183249114-ef3d1b58-42b7-4be6-b7bf-ec88ceff0374.png)

## Expected behavior

It should show the HTML repr, as in JupyterLab:
![image](https://user-images.githubusercontent.com/4711805/183249416-162dfa5b-01a4-4dde-bf74-a3cd6b3da931.png)

## Context

- JupyterLite version: 0.1.0-beta.11
- Operating System and version: Linux Ubuntu 21.04
- Browser and version: Google-Chrome 104.0.5112.79

**Comment by martinRenou** [comment]
I believe this is an issue for https://github.com/emscripten-forge/recipes. It looks like the xarray package-data are being filtered out. Maybe xarray needs an entry in https://github.com/emscripten-forge/recipes/blob/main/empack_config.yaml.

**Comment by martinRenou** [comment]
Normally you should be able to test a local config with `jupyter lite build --XeusPythonEnv.empack_config=/home/david/path/to/local/empack_config.yaml`

**Comment by davidbrochart** [comment]
Thanks, https://github.com/emscripten-forge/recipes/pull/160 should fix it.
