### ISSUE TITLE
can't import meep

### ISSUE THREAD

**Issue by ljsandstrom** [jupyterlite/jupyterlite#764]
## Description

"import meep as mp" fails, giving the error: ModuleNotFoundError: No module named 'meep'

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- JupyterLite version:
- Operating System and version:
- Browser and version:

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by bollwyvl** [comment]
You'll need to use [`piplite`](https://jupyterlite.readthedocs.io/en/latest/howto/python/packages.html)
```
import piplite
await piplite.install("meep")
```

However, you'll find that a number of `meep`'s dependencies are not yet compatible with `pyodide`:

![Screenshot from 2022-08-10 15-39-57](https://user-images.githubusercontent.com/45380/184015928-ad5b393a-a3a4-4659-911c-b1611db8325a.png)

[`gitapi`](https://pypi.org/project/gitapi/#files) and [`hgapi`](https://pypi.org/project/hgapi/#files) only distribute source distributions (e.g. `.tar.gz`)
  - you could request that the upstreams publish `noarch` wheels
  - or build yourself and include it them via the [instructions in the docs](https://jupyterlite.readthedocs.io/en/latest/howto/python/wheels.html#adding-pyolite-wheels)

There really isn't much else we can do at this point, so closing this out!
