### ISSUE TITLE
App freezes when using help

### ISSUE THREAD

**Issue by Gal-Peled** [jupyterlite/jupyterlite#767]
## Description

Jupyterlite freezes when going to help menu 

## Reproduce

Open Jupyterlite in chrome  
1. Go to 'help menu'
2. Click on 'markdown reference'
3. Go back to  'previous tab'
4. See error 'the app freeze'

## Expected behavior

app should work 

## Context

- JupyterLite version: 0.1.0 beta
- Operating System and version: Windows 10 Enterprise N 21H1
- Browser and version: Chrome  104.0.5112.81 (Official Build) (64-bit)

<details><summary>Browser Output</summary>
<pre>
Paste the output from your browser Javascript console here.
</pre>
</details>
![Slide1](https://user-images.githubusercontent.com/91271356/185054070-ccabebe8-f2fe-4e37-bd9e-d2a8b1149b48.PNG)

**Comment by Gal-Peled** [comment]
Just checked it on:
1.  Jupyterlab installed on my local machine and it has the same issue 
2.  Jupyterlite on MS EDGE browser and it behaves the same (EDGE Version 104.0.1293.54 on 64bit window 10 21H1)

**Comment by jtpio** [comment]
Closing in favor of https://github.com/jupyterlab/jupyterlab/issues/13039
