### ISSUE TITLE
What is the difference between an overrides.json and a jupyter-lite.json?

### ISSUE THREAD

**Issue by savakarrohan** [jupyterlite/jupyterlite#784]
## Description

I am trying to create a site and configure a few items such as 
- the icon in the browser `favicon`
- The app name under the help tab `appName`

I used the word configure, so it makes sense to have it under the jupyter-lite.json but what does an overrides.json do too?
## Reproduce

1. Init a fresh repository using jupyter lite init
2. Have some notebooks in a folder files (helloWorld.ipynb would be perfect)
3. Run the CLI command `jupyter lite build`
4. Check if the output site has built with your notebook.
5. Copy contents under `_output/jupyter-lite.json`
6. Paste contents to `jupyter-lite.json` in the root directory.  (root jupyter-lite.json)
7. copy paste your favourite icon to a folder under root
    - I have copied a file called `favicon.ico` under `/toCopy/Icon`
8. In the root jupyter-lite.json change the `faviconUrl` value to `/toCopy/Icon/favicon.ico`

I have attempted several combinations of the following
- Write an overrides.json with appropriate values for favicon, appName
- copy the folder `toCopy` to `_output` with overrides.json
- a `jupyter-lite.json` file under `{apps?}` directories 
and combinations of these and inbetween

### What worked
copying the `toCopy` file to `_output` with a `jupyter-lite.json` file in root directory.

This now makes sense as I am trying to "configure"(and thus the jupyter-lite.json over an overrides.json) a site.
 
## Expected behavior

I expect jupyter-lite to copy the respective file or path to output and merge with the static files. 

## Context

- JupyterLite version: 0.1.0b12
- Operating System and version: Ubuntu 22.04.1 LTS
- Browser and version: Brave v 1.42.97

**Comment by vasiljevic** [comment]
@savakarrohan Have you tried to delete `.jupyterlite.doit.db` ?

BTW, you don't need steps 5 and 6 sice configuration files will be merged.

**Comment by savakarrohan** [comment]
So here's the weird part,
It worked initially,
- I deleted the `.db` file and the Icon was updated as expected,
   - Here the icon updated and I was able to play around with other settings such as `appName`
- In a new try, I deleted `_output` folder and `.db` file and ran the command `jupyter lite build` 
   - Here I ran a server and now the icon has not been updating.
      - I have tried all types of relative URL's for the `toCopy/Icon/favicon.ico` 

On a side note, I just noticed that the config files are getting merged thank you!

**Comment by jtpio** [comment]
Thanks @savakarrohan for reporting.

Probably there could be some more information in the documentation to make the distinction clearer.
