### ISSUE TITLE
Pyodide 0.21.2 needed for Safari support!

### ISSUE THREAD

**Issue by henryiii** [jupyterlite/jupyterlite#798]
I'd really like a JupyterLite release with 0.21.2. Specifically, 0.21.1 fixed a bug that causes Safari to hang when doing almost anything. It seems to have already been updated, but no JupyterLite release has been made. This is causing a vanilla install to make secretly-broken-on-Safari output.

I'm currently manually adding this hackary to my noxfiles, which does fix the problem:

```python
import nox
from pathlib import Path

nox.needs_version = ">=2022.1.7"
DIR = Path(__file__).parent.resolve()


@nox.session
def pyodide(session: nox.Session) -> None:
    session.install("jupyterlite[lab]")
    session.run("jupyter", "lite", "init")
    session.run("jupyter", "lite", "build", "--contents=notebooks")

    avoid_pyodide_bug()

    if "--serve" in session.posargs:
        session.run("jupyter", "lite", "serve")


# Required for JupyterLite 0.1.0b12
def avoid_pyodide_bug():
    output = DIR / "_output"
    build = output / "build"
    paths = [
        output / "jupyterlite.schema.v0.json",
        *build.glob("*.js"),
        *build.glob("*.js.map"),
    ]
    for path in paths:
        txt = path.read_text()
        txt = txt.replace(
            "https://cdn.jsdelivr.net/pyodide/v0.21.0",
            "https://cdn.jsdelivr.net/pyodide/v0.21.2",
        )
        path.write_text(txt)
```

If development has continued on a bit, could at least a quick branch of 0.1.0b10 be made with this single patch be made then released as 0.1.0b11?

(PS: I don't think `--pyodide` is intended for this, and it will still expect 0.21.0 if used? The output files don't seem to change when it's used.)

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0b13 and https://github.com/jupyterlite/jupyterlite/pull/782.
