### ISSUE TITLE
Update to pyodide 0.12.3

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlite/jupyterlite#803]
### Problem

Pyodide [0.12.3](https://pyodide.org/en/stable/project/changelog.html#version-0-21-3) is out, with a bunch of bug fixes. Cruically, source maps are restored, which provide a _much_ nicer experience when debugging.

### Proposed Solution

- bump the couple places where it occurs

### Additional context

Could already be started, but should make a decision on #795 vs #793.

**Comment by Jirkuwiwan** [comment]
Hi!
Am having issue in Jupyter-try!
Auto completion not working now!
