### ISSUE TITLE
Malformed links

### ISSUE THREAD

**Issue by palewire** [jupyterlite/jupyterlite#804]
The hyperlinks in the Jupyter Lite notebook [here](https://palewi.re/docs/first-python-notebook/_extra/fast-python-notebook/lab/index.html) are sometimes coming out wrong. Am I doing something wrong with my Markdown?

![Screenshot from 2022-09-16 14-18-13](https://user-images.githubusercontent.com/9993/190770242-f1fa7c79-8bbe-4f68-85f0-1f3c6d849e88.png)

![Screenshot from 2022-09-16 14-18-21](https://user-images.githubusercontent.com/9993/190769925-54a24dda-7cab-4e8c-a704-206b2ec60ea9.png)

**Comment by bollwyvl** [comment]
Does it happen in stock jupyterlab?

**Comment by palewire** [comment]
Sorry. DOES NOT happen in stock.

**Comment by palewire** [comment]
It does happen in Jupyter Lab, where I authored the notebook. You can find the source here: 

https://github.com/palewire/first-python-notebook/blob/master/jupyterlite/fast-python-notebook/notebook.ipynb

**Comment by palewire** [comment]
I see the error on my production URL here:

https://palewi.re/docs/first-python-notebook/_extra/fast-python-notebook/lab?path=notebook.ipynb

But not in the direct S3 bucket URL here:

https://palewire-docs.s3.amazonaws.com/first-python-notebook/_extra/fast-python-notebook/lab?path=notebook.ipynb

I suspect this means the bug must be in my CDN layer at Cloudflare, where a reverse proxy is serving the https://palewi.re/docs/first-python-notebook/ URL prefix from the S3 origin.

If that's right, I think the bug must be in my reverse proxy layer, not Jupyter Lite. I'm using a generic Cloudflare worker install that probably has a hyperlink rewrite function. I bet that's the culprit.

```javascript
const OLD_URL = "http://palewire-docs.s3-website-us-east-1.amazonaws.com"
const NEW_URL = "https://palewi.re/docs"


async function handleRewrite(req) {
  const res = await fetch(req)
  return rewriter.transform(res)
}

class AttributeRewriter {
  constructor(attributeName) {
    this.attributeName = attributeName
  }
  element(element) {
    const attribute = element.getAttribute(this.attributeName)
    if (attribute) {
      element.setAttribute(
        this.attributeName,
        attribute.replace(OLD_URL, NEW_URL)
      )
    }
  }
}


const rewriter = new HTMLRewriter()
  .on("a", new AttributeRewriter("href"))
  .on("img", new AttributeRewriter("src"))
  .on("link", new AttributeRewriter("href"))
  .on("meta", new AttributeRewriter("content"))


addEventListener("fetch", event => {
  let url = event.request.url;
  let rewriteUrl = OLD_URL + url.split("/docs")[1];
  event.respondWith(
    handleRewrite(rewriteUrl)
      .catch(err => new Response(err.toString(), {status:500}))
  );
})
```

**Comment by palewire** [comment]
I commented out the HTML rewriter function above the error disappeared. That's the problem.
