### ISSUE TITLE
Importing scipy from module fails (but from notebook it works)

### ISSUE THREAD

**Issue by kolibril13** [jupyterlite/jupyterlite#806]
While creating a [minimal example](https://gitlab.gwdg.de/crc1456/livedocs/jupyterlite-minimal-example/) for JupyterLite I found the following bug.

## Description
Importing numpy from a module works fine, however importing scipy from a module does not work.
It only works when scipy is first imported from the notebook, see the following screenshot: 
<img width="662" alt="image" src="https://user-images.githubusercontent.com/44469195/190871053-bdf1dfd1-25b4-4d79-9f33-1887cba0b015.png">

## Reproduce

1. Go to https://crc1456.pages.gwdg.de/livedocs/jupyterlite-minimal-example/lab/index.html
2. Click on 'numpy_scipy_bug_notebook.ipynb'
3. Run all cells
4. Installed requirements are [here](https://gitlab.gwdg.de/crc1456/livedocs/jupyterlite-minimal-example/-/blob/main/gitlab-demo/requirements.txt). See also the files [numpytest.py](https://gitlab.gwdg.de/crc1456/livedocs/jupyterlite-minimal-example/-/blob/main/gitlab-demo/content/numpytest.py) and [scipytest.py](https://gitlab.gwdg.de/crc1456/livedocs/jupyterlite-minimal-example/-/blob/main/gitlab-demo/content/scipytest.py)

**Comment by bollwyvl** [comment]
Please see if you can reproduce this upstream in the [pyodide console](https://pyodide.org/en/stable/console.html).

If so, this is likely an upstream [pyodide issue](https://github.com/pyodide/pyodide/issues) and may already have been reported, or even fixed, in a version we haven't yet tested with jupyterlite's `pyolite` kernel (#803).

**Comment by kolibril13** [comment]
I've just tested this in the [pyodide console](https://pyodide.org/en/stable/console.html) and the scipy bug also occurs there.
In addition, there is also the same bug with numpy.
It's interesting that this numpy bug does not occur in JupyterLite!

I could not find a reported issue in the pyodide repo, so I can write one tomorrow. 
Here is my testing code:

```console
Welcome to the Pyodide terminal emulator 🐍
Python 3.10.2 (main, Sep 15 2022 23:28:12) on WebAssembly/Emscripten
Type "help", "copyright", "credits" or "license" for more information.
>>> filename = "numpytest.py"
code = """
print("Hello Numpy")
import numpy
print(f"{numpy.euler_gamma = }")
"""
with open(filename, "w") as f:
    f.write(code)
... 
68
>>> filename = "scipytest.py"
code = """
print("Hello Scipy")
import scipy
print(f"{scipy.pi = }")
"""
with open(filename, "w") as f:
    f.write(code)
... 
59
>>> from numpytest import *
Hello Numpy
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/pyodide/numpytest.py", line 3, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
>>> from scipytest import *
Hello Scipy
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/pyodide/scipytest.py", line 3, in <module>
    import scipy
ModuleNotFoundError: No module named 'scipy'
>>> import scipy
>>> from scipytest import *
Hello Scipy
scipy.pi = 3.141592653589793
>>> 
>>> import numpy
>>> from numpytest import *
Hello Numpy
numpy.euler_gamma = 0.5772156649015329
>>> 
 
 ```

**Comment by bollwyvl** [comment]
As this has been identified as a _hard_ upstream issue, going to close this out here.
