### ISSUE TITLE
Half baked release 0.1.0b13

### ISSUE THREAD

**Issue by martinRenou** [jupyterlite/jupyterlite#814]
cc. @jtpio @bollwyvl 

## Description

Looks like we reached some kind of account limit

https://github.com/martinRenou/jupyter_releaser/actions/runs/3113592500/jobs/5048416547

The release is not finished and still on draft. I will try later today, or another day.

**Comment by vasiljevic** [comment]
Looks like this is a GitHub issue, not a limit of any specific GitHub account:
https://github.com/community/community/discussions/8535

**Comment by jtpio** [comment]
Thanks @martinRenou for the heads up and doing the release.

Looks like https://github.com/orgs/community/discussions/8535 has been marked as answered, so maybe resuming the release with the "Publish Release" workflow will complete it this time.

**Comment by martinRenou** [comment]
Thanks both, I'll try to resume the release

**Comment by martinRenou** [comment]
The pypi release is out (https://pypi.org/project/jupyterlite) but the Publish Release workflow still fails with:

```
COMMAND: npm publish jupyterlite-application-0.1.0-beta.13.tgz
npm notice
npm notice 📦  @jupyterlite/application@0.1.0-beta.13
npm notice === Tarball Contents ===
npm notice 72B   lib/index.d.ts
npm notice 175B  lib/index.js
npm notice 2.3kB lib/singleWidgetApp.d.ts
npm notice 4.0kB lib/singleWidgetApp.js
npm notice 1.8kB lib/singleWidgetShell.d.ts
npm notice 2.4kB lib/singleWidgetShell.js
npm notice 1.6kB package.json
npm notice 458B  style/base.css
npm notice 347B  style/index.css
npm notice 333B  style/index.js
npm notice === Tarball Details ===
npm notice name:          @jupyterlite/application
npm notice version:       0.1.0-beta.13
npm notice filename:      @jupyterlite/application-0.1.0-beta.13.tgz
npm notice package size:  3.5 kB
npm notice unpacked size: 13.6 kB
npm notice shasum:        12c8bfd0687d39ea61c63d2a552ffc77de84a9bc
npm notice integrity:     sha512-4qS7smGYZpCNp[...]ITT0GnoojKzhg==
npm notice total files:   10
npm notice
npm notice Publishing to https://registry.npmjs.org/
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/@jupyterlite%2fapplication - Not found
npm ERR! 404
npm ERR! 404  '@jupyterlite/application@0.1.0-beta.13' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

This does not look like an authorization issue? I'm not sure I understand the error message. Of course `@jupyterlite/application@0.1.0-beta.13` is not in the registry I'm trying to publish it...

**Comment by vasiljevic** [comment]
I've found similar issue:
https://github.com/expo/expo-cli/issues/4099#issuecomment-1005142428

**Comment by jtpio** [comment]
For reference I also tried resuming the release with the Publish Release workflow but got the following issue before uploading the npm packages: https://github.com/jupyter-server/jupyter_releaser/issues/406

**Comment by jtpio** [comment]
> For reference I also tried resuming the release with the Publish Release workflow but got the following issue before uploading the npm packages: [jupyter-server/jupyter_releaser#406](https://github.com/jupyter-server/jupyter_releaser/issues/406)

Just did another try with the new 0.25.0 release of the releaser (https://github.com/jupyter-server/jupyter_releaser/releases/tag/v0.25.0) and it passed this time: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0b13

Closing as fixed.

**Comment by martinRenou** [comment]
Thanks!!
