### ISSUE TITLE
Making notebooks ready for both JupyterLab and JupyterLite

### ISSUE THREAD

**Issue by kolibril13** [jupyterlite/jupyterlite#816]
Firstly, thanks for making JupyterLite! This tool is great for creating Jupyter demos and teaching science.

I was recently preparing notebooks that should execute in both JupyterLab and JupyterLite, and I run into some adjustments that had to be made and are listed below.
While these points can guide people who want to do the same, the below list can also be seen as feature ideas for JupyterLite to make working with JupyterLab and JupyterLite even more seamless.

1. When a python file is imported into a notebook, module imports that are present in that python file are not reflected to the JupyterLite notebook. Therefore, these modules have to be imported in JupyterLite separately (reference: https://github.com/jupyterlite/jupyterlite/issues/806). 
This is a not-yet implemented feature in Pyodide. If you like this feature idea, feel free join the discussion in the feature request issue: https://github.com/pyodide/pyodide/issues/3155. 

2. When importing data in JupyterLite, equal signs in file names have to be removed otherwise this error is thrown: 
```
Task 'build:contents:copy:data/s=3.dat': name must not use the char '=' (equal sign).
```
In JupyterLab, equal signs are allowed.

3. Some moduls (e.g. `ipywidgets`) have to be installed via piplite. But piplite will throws an error in JupyterLab, therefore this `if`-condition can be used to support both JupyterLab+JupyterLite:

```
import sys
if "pyodide" in sys.modules:
    import piplite
    await piplite.install('ipywidgets')
```

4. The folder with the name `lib` does not show up in the JupyterLite explorer, so it has to be renamed from lib to another name (see [jupterlite demo](https://crc1456.pages.gwdg.de/livedocs/jupyterlite-minimal-example/lab/index.html) and  [corresponding repo](https://gitlab.gwdg.de/crc1456/livedocs/jupyterlite-minimal-example/-/tree/98f548f8083f2f86beeb3ee91780e3b9f14768fc/gitlab-demo/content).)

5. In JupyterLab matplotlib figures are shown automatically in the cell output, in JupyterLite they have to be called with `plt.show()`.

Hope these findings might be useful for someone.

**Comment by bollwyvl** [comment]
Laundry list issues aren't particularly helpful... here is a another collection of random thoughts in reply.

Upstream issues are precisely that: we attempt to get pyodide releases out the door as quickly as possible, but there's always a chance we have to deal with new API changes. The goal is to move the pyodide-specific behavior to another repo (#386).

The task file names are probably mungeable by replacing non-standard characters when [initializing the task](https://github.com/jupyterlite/jupyterlite/blob/main/py/jupyterlite/src/jupyterlite/addons/contents.py#L73).

The docs describe how to [ignore contents](https://jupyterlite.readthedocs.io/en/latest/reference/cli.html#common-parameters).

At some point we'll figure out how to enable the `%pip` magic to normalize the import process #237.

**Comment by kolibril13** [comment]
Thanks for these thoughts, next time I will report findings in separate issues. I'll then close this issue and make a new issue about non-standard characters in file names.
It's great to see that other points are already addressed.

**Comment by jtpio** [comment]
> Some moduls (e.g. ipywidgets) have to be installed via piplite. But piplite will throws an error in JupyterLab, therefore this if-condition can be used to support both JupyterLab+JupyterLite:

As an alternative, you could also use the `xeus-python` kernel for JupyterLite, which allows for preinstalling packages and avoid installing with `piplite`: https://xeus-python-kernel.readthedocs.io/en/latest/
