### ISSUE TITLE
Build custom jupyterlite with xeus-python kernel only ?

### ISSUE THREAD

**Issue by oscar6echo** [jupyterlite/jupyterlite#825]
### Problem

I build a custom jupyterlite with:

```sh
jupyter lite build --config jupyter_lite_config.json
```

```json
// jupyter_lite_config.json
{
    "LiteBuildConfig": {
        "lite_dir": "lite",
        "contents": [
            "contents"
        ],
        "federated_extensions": [ ],
        "ignore_sys_prefix": true,
        "output_dir": "public",
        "base_url": "./",
        "XeusPythonEnv": {
            "packages": [ "numpy", "matplotlib", "ipyleaflet" ]
        }
    }
}
```
I get the following launcher:

![image](https://user-images.githubusercontent.com/2219383/193473417-a066b20a-b45c-4444-9e90-af429fe89cfd.png)

However my intention is to use the xeus-python kernel **only**.  
Because:
1/ The xeus-python kernel is faster to run initial imports in the notebook
2/ A user gets to choose between 2 kernels which is not the experience I would like to offer:

![image](https://user-images.githubusercontent.com/2219383/193473774-273299cd-927c-4eb8-a169-de4069bc3fe7.png)

Hence the question:  
Is there a way to **not ship** the default pyodide kernel, but **only** the xeus-python kernel ?

**Comment by martinRenou** [comment]
You can create a `jupyter-lite.json` file with the following content: https://github.com/jupyterlite/xeus-python-kernel/blob/main/docs/jupyter-lite.json

**Comment by jtpio** [comment]
The Pyodide kernel will also move to a different repo at some point, which should make it easier to use the xeus-python kernel only: https://github.com/jupyterlite/jupyterlite/issues/386

**Comment by oscar6echo** [comment]
Indeed @jtpio  
I woud think that for custom jupyterlite deployments, the cherry picking enabled by xeus-python will soon make it preferable to the full but bulky pyodide.

Thx @martinRenou  
I can confirm it does work:

```sh
jupyter lite build --config jupyterlite_config.json --lite-dir .
```

```json
// ./jupyterlite_config.json
{
    "LiteBuildConfig": {
        "lite_dir": "lite",
        "contents": [
            "contents"
        ],
        "federated_extensions": [ ],
        "ignore_sys_prefix": true,
        "output_dir": "public",
        "base_url": "./",
        "XeusPythonEnv": {
            "packages": [ "numpy", "matplotlib", "ipyleaflet" ]
        }
    }
}
```

```json
// ./jupyter-lite.json
{
    "jupyter-lite-schema-version": 0,
    "jupyter-config-data": {
        "disabledExtensions": [
            "@jupyterlite/javascript-kernel-extension",
            "@jupyterlite/pyolite-kernel-extension"
        ]
    }
}
```

Then I get:

![image](https://user-images.githubusercontent.com/2219383/193673761-eee3a354-3b88-4dfd-86a8-100cccf0fc00.png)

Perfect !
