### ISSUE TITLE
Replace the p5 kernel by the echo kernel on the RTD demo site?

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#836]
### Problem

The p5 kernel was added to the demo site mostly for demo purposes and to test the federated kernels.

### Suggested Improvement

To reduce maintenance, we could replace it by the simple [echo-kernel](https://github.com/jupyterlite/echo-kernel), and remove the p5 example notebook.

There is already a demo site using a released version of JupyterLite with more kernels: https://jupyterlite.github.io/demo.

Once https://github.com/jupyterlite/jupyterlite/issues/386 is done and Pyolite becomes a federated kernel, we can still keep it as part of the demo site (and remove `echo-kernel`).

**Comment by bollwyvl** [comment]
Until we get to a second row of kernels, I don't see a big UX problem to keeping more kernels in the docs demo, as it helps track when we inadvertently introduce a breaking change... I always try to remember to review it especially when doing a big update (e.g. lab upstream). Is there something else you don't like about it keeping it around?

echo kernel seems like it would actually be _confusing_ to expose on the regular site.

**Comment by jtpio** [comment]
Agree the echo kernel is not the most interesting kernel.

Depends what we want to test on the demo site. I think p5 was added to test the federated extensions initially for which echo would also work.

Maybe we'll want to add more kernels to the RTD site later then (xeus python, xeus lua...), to test for breaking changes downstream (after https://github.com/jupyterlite/jupyterlite/issues/386).

**Comment by jtpio** [comment]
https://github.com/jupyterlite/jupyterlite/pull/711 is an example of a PR making significant changes to the JavaScript kernel, removing some methods the p5 kernel was relying.

In that case the downstream p5 kernel will need the new `@jupyterlite` packages to be published to update itself, and then be released. I guess it would be fine to leave that kernel "broken" on the demo site during that time.

**Comment by jtpio** [comment]
Closing the issue for now, since the `p5` kernel does not depend on the JavaScript kernel anymore. The JS kernel is now backed by a Web Worker, but p5 sticks to an IFrame since it needs access to `window` and `document` in quite a few places.

We can keep it around as a federated kernel on the demo site: https://github.com/jupyterlite/jupyterlite/pull/955
