### ISSUE TITLE
Pyolite `sqlite3` doesn't work inside the serviceworker-provided FS

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlite/jupyterlite#840]
## References

- more of a reproducer in #839
- refines #671

## Description

Some c-level libraries are still not happy with files served by the virtual drive, namely the ubiquitous `sqlite3`. We can be _pretty sure_ the problem is **not** in `sqlite3`!

## Reproduce

1. Go to https://jupyterlite.rtfd.io/_static
2. Start a pyolite notebook
3. Create a code cell
```py
import sqlite3
con = sqlite3.connect("/tmp/example.db")
cur = con.cursor()
cur.execute("CREATE TABLE movie(title, year, score)")
```
7. see that it works
6. change the path to `./example.db`
5. See error `sqlite3.OperationalError: disk I/O error`

## Expected behavior

- `sqlite3` should work the same way when used in the mounted filesystem as it does in the base `MEMFS`

## Context

- JupyterLite version: any beyond 0.1.0b11 or thereabouts
- Operating System and version: Ubuntu Linux 20.1
- Browser and version: Chrome/FF latest (but not FF in Private Browsing, because no serviceworker)

<details><summary>Browser Output</summary>
<pre>
just the usual, no emscripten stack trace
</pre>
</details>

Turning on `Show hidden files` from settings, one _briefly_ sees a `-journal` file flash in the file tree, and occasionally a different error, `malformed disk image`. So perhaps a race condition?

**Comment by psychemedia** [comment]
Does this also relate to https://github.com/jupyterlite/jupyterlite/issues/682 , eg in the context of providing a set of tests regarding read/writes from common packages (`sqlite`, `pandas`, etc.)?

**Comment by bollwyvl** [comment]
Partial fix here:

https://github.com/jupyterlite/jupyterlite/commit/c7c29078edf28f1828023385fde8e4d130a4630a#r89808665

This gets past `disk i/io error`... revealing `database disk image is malformed`.

**Comment by jtpio** [comment]
Closing as it looks like the conversation has now moved to https://github.com/jupyterlite/pyodide-kernel/issues/35
