### ISSUE TITLE
matplotib margins/padding are not consistent with (and sometimes radically different from) Jupyter Lab

### ISSUE THREAD

**Issue by posita** [jupyterlite/jupyterlite#850]
``` python
import matplotlib.pyplot
from fractions import Fraction
from itertools import chain

data = {
"3d6": {3: Fraction(1, 216), 4: Fraction(1, 72), 5: Fraction(1, 36), 6: Fraction(5, 108), 7: Fraction(5, 72), 8: Fraction(7, 72), 9: Fraction(25, 216), 10: Fraction(1, 8), 11: Fraction(1, 8), 12: Fraction(25, 216), 13: Fraction(7, 72), 14: Fraction(5, 72), 15: Fraction(5, 108), 16: Fraction(1, 36), 17: Fraction(1, 72), 18: Fraction(1, 216)},
"2d10": {2: Fraction(1, 100), 3: Fraction(1, 50), 4: Fraction(3, 100), 5: Fraction(1, 25), 6: Fraction(1, 20), 7: Fraction(3, 50), 8: Fraction(7, 100), 9: Fraction(2, 25), 10: Fraction(9, 100), 11: Fraction(1, 10), 12: Fraction(9, 100), 13: Fraction(2, 25), 14: Fraction(7, 100), 15: Fraction(3, 50), 16: Fraction(1, 20), 17: Fraction(1, 25), 18: Fraction(3, 100), 19: Fraction(1, 50), 20: Fraction(1, 100)},
"d8d12": {2: Fraction(1, 96), 3: Fraction(1, 48), 4: Fraction(1, 32), 5: Fraction(1, 24), 6: Fraction(5, 96), 7: Fraction(1, 16), 8: Fraction(7, 96), 9: Fraction(1, 12), 10: Fraction(1, 12), 11: Fraction(1, 12), 12: Fraction(1, 12), 13: Fraction(1, 12), 14: Fraction(7, 96), 15: Fraction(1, 16), 16: Fraction(5, 96), 17: Fraction(1, 24), 18: Fraction(1, 32), 19: Fraction(1, 48), 20: Fraction(1, 96)}
}

with matplotlib.style.context("bmh"):
    fig = matplotlib.pyplot.figure()
    xmin, ymin, dx, dy = 0.0, 0.0, 1.0, 1.0  # 0.1, 0.1, 0.9, 0.9
    ax = fig.add_axes((xmin, ymin, dx, dy))
    ax.yaxis.set_major_formatter(matplotlib.ticker.PercentFormatter(xmax=1))
    unique_outcomes = sorted(set(chain.from_iterable(data.values())))
    ax.set_xticks(unique_outcomes)
    ax.set_xlim((min(unique_outcomes) - 0.5, max(unique_outcomes) + 0.5))
    for label, d in data.items():
        outcomes, values = zip(*((outcome, float(value)) for outcome, value in d.items()))
        ax.plot(
            outcomes, values,
            label=label,
            marker="o",
        )
    matplotlib.pyplot.show()

print(matplotlib.__version__)
```

Jupyter Lab (using `matplotlib` 3.5.2):
![lab](https://user-images.githubusercontent.com/222581/198044498-828d5941-9b13-4e17-bbc3-2024a3363f42.png)

Jupyter Lite (0.1.0b14 using `matplotlib` 3.5.2):
![lite](https://user-images.githubusercontent.com/222581/198044531-b5fd3414-b29d-4784-812c-023b3779285c.png)

In this particular case, you can achieve a much closer (but still different) result by doing this instead:

``` python
xmin, ymin, dx, dy = 0.1, 0.1, 0.9, 0.9
```

However, this isn't universally true. Subplots for example are _radically_ different  with Jupyter Lite's rendering tending to pad with whitespace proportionate to the number of subplots, which is weird. Here's one example of the same code being rendered by the two platforms:

Lab:
[![lab-subplots](https://user-images.githubusercontent.com/222581/198046339-eb00f64a-2434-4b3f-a303-2272b5c17b99.png)](https://user-images.githubusercontent.com/222581/198045851-693c0357-540c-4c64-bca4-93012a1b7bc2.png)

Lite:
[![lite-subplots](https://user-images.githubusercontent.com/222581/198046519-cae9dda0-dc0e-4584-b638-1e1663a60d48.png)](https://user-images.githubusercontent.com/222581/198045875-dae5a05d-be7f-424e-888f-4863d5822224.png)

I have compared `matplotlib.rcParams` on both platforms and found that the only difference is `{..., "backend": "agg", ...}` on Jupyter Lite, which I don't think is determinative.

**Comment by posita** [comment]
Replacing ...

``` python
    fig = matplotlib.pyplot.figure()
    xmin, ymin, dx, dy = 0.0, 0.0, 1.0, 1.0  # 0.1, 0.1, 0.9, 0.9
    ax = fig.add_axes((xmin, ymin, dx, dy))
```

... with ...

``` python
    _, ax = matplotlib.pyplot.subplots()
```

Has the effect of producing _more_ padding in Jupyter Lite's rendering, which (for me at least) is a real head-scratcher.

**Comment by posita** [comment]
Here are more where the same code was used in each environment:

Lab:
[![lab-wonky](https://user-images.githubusercontent.com/222581/198073220-14482918-dfa4-44fc-9601-49cd90b68d2f.png)](https://user-images.githubusercontent.com/222581/198073211-d8be63de-b63f-41ab-a8b5-37cdbbd271ac.png) [![lab-wonky-hbar](https://user-images.githubusercontent.com/222581/198073219-ab963195-68a6-4d51-8611-76469c34f2e1.png)](https://user-images.githubusercontent.com/222581/198073217-73394c61-5a7e-45f6-a714-be202b044670.png)

Lite:
[![lite-wonky](https://user-images.githubusercontent.com/222581/198073576-5fc39070-323f-45eb-88f7-ed02812b2ce3.png)](https://user-images.githubusercontent.com/222581/198073565-d177177e-669e-47d9-837f-ebd4cde38a45.png) [![lite-wonky-hbar](https://user-images.githubusercontent.com/222581/198073573-62e733dd-d765-422c-95ff-7ccb0b2ad534.png)](https://user-images.githubusercontent.com/222581/198073571-38bb6850-b7bd-4d18-9b9d-f24db72df4b0.png)

**Comment by posita** [comment]
> I wonder if this is an artifact from [pyolite's matplotlib rendering patch(es)](https://github.com/jupyterlite/jupyterlite/blob/c9846beca88cd84e15119547b00240515c7e6f6d/packages/pyolite-kernel/py/pyolite/pyolite/patches.py#L17-L22)?

I think this is it. If I replace my calls to `matplotlib.pyplot.show()` with a reproduction of that patch, I get nearly identical output in both Lab and Lite. So maybe this is a parity issue between `show()` and `savefig(..., format="png")`? I'm a bit out of my depth with this one, but is there a way to bring those more in line with each other outside of hacking on `matplotlib`?

**Comment by posita** [comment]
Here's a pretty good demonstration of how `savefig` clips (e.g.) the title of a pie chart:

``` python
import matplotlib.pyplot
import base64, io
from enum import Enum
from ipywidgets import widgets
from fractions import Fraction
from itertools import chain

data = {3: Fraction(1, 216), 4: Fraction(1, 72), 5: Fraction(1, 36), 6: Fraction(5, 108), 7: Fraction(5, 72), 8: Fraction(7, 72), 9: Fraction(25, 216), 10: Fraction(1, 8), 11: Fraction(1, 8), 12: Fraction(25, 216), 13: Fraction(7, 72), 14: Fraction(5, 72), 15: Fraction(5, 108), 16: Fraction(1, 36), 17: Fraction(1, 72), 18: Fraction(1, 216)}

class Format(str, Enum):
    NATIVE = "native"
    PNG = "png"
    SVG = "svg"

class PngImage:
    def __init__(self, data):
        self.data = data

    def _repr_png_(self):
        return base64.b64encode(self.data).decode()

class SvgImage:
    def __init__(self, data):
        self.data = data

    def _repr_svg_(self):
        return self.data.decode()

@widgets.interact
def show(output_to_format = Format, use_subplots: bool = True):
    with matplotlib.style.context("bmh"):
        if use_subplots:
            _, ax = matplotlib.pyplot.subplots()
        else:
            fig = matplotlib.pyplot.figure()
            xmin, ymin, dx, dy = 0.1, 0.1, 0.9, 0.9
            ax = fig.add_axes((xmin, ymin, dx, dy))
        unique_outcomes = sorted(data.keys())
        ax.set_title(
            "Super duper duper long title that will probably exceed the width of the pie chart",
            fontdict={"fontweight": "bold",},
        )
        outcomes, values = zip(*((outcome, float(value)) for outcome, value in data.items()))
        ax.pie(outcomes, values)
        if output_to_format is Format.NATIVE:
            matplotlib.pyplot.show()
        else:
            buf = io.BytesIO()
            matplotlib.pyplot.savefig(buf, format=output_to_format)
            if output_to_format is Format.PNG:
                display(PngImage(buf.getvalue()))
            elif output_to_format is Format.SVG:
                display(SvgImage(buf.getvalue()))
            else:
                assert False, "should never be here"
            matplotlib.pyplot.clf()

print(matplotlib.__version__)
```

Spoiler alert: It's not limited to PNGs.

| | Using `subplots` | Using `add_axes` |
|:---:|:---:|:---:|
| `show()` | [![native-subplots](https://user-images.githubusercontent.com/222581/198141980-37191377-fd34-4706-bacd-2aca7d50158b.png)](https://user-images.githubusercontent.com/222581/198141979-942f5f88-8142-4562-8701-75d34cdd47c3.png) | [![native-manual-axes](https://user-images.githubusercontent.com/222581/198141978-86a2e73f-5d2c-44f9-98d4-c1e0ec9a415b.png)](https://user-images.githubusercontent.com/222581/198141976-60c64524-a43f-47b4-b8b7-aff36901556f.png) |
| `savefig(..., format="png")` | [![png-subplots](https://user-images.githubusercontent.com/222581/198141985-5aeb1bfa-a3bc-439a-a650-17273c398208.png)](https://user-images.githubusercontent.com/222581/198141984-5b79321e-4361-49d9-a98d-216cb7b9504e.png) | [![png-manual-axes](https://user-images.githubusercontent.com/222581/198141982-12bdd901-a652-4f18-acd8-47cb4930f4f7.png)](https://user-images.githubusercontent.com/222581/198141981-04877a9c-077e-4b09-a64d-ec956f6e680b.png) |
| `savefig(..., format="svg")` | [![svg-subplots](https://user-images.githubusercontent.com/222581/198141995-b150ba6d-7576-452e-b812-2479fc91e378.svg)](https://user-images.githubusercontent.com/222581/198141994-36699e76-d185-4c8d-a749-a1c178149c1a.svg) | [![svg-manual-axes](https://user-images.githubusercontent.com/222581/198141991-533cc098-102b-43ef-908b-9f15f2f7ce14.svg)](https://user-images.githubusercontent.com/222581/198141987-fff4f0b3-8a7b-4f92-b977-9de9be7a2f65.svg) |

**Comment by posita** [comment]
Closing in favor of matplotlib/matplotlib#24281. Will reopen if appropriate.

**Comment by posita** [comment]
Reopening because `matplotlib` rejected the issue as theirs: https://github.com/matplotlib/matplotlib/issues/24281#issuecomment-1292695079

**Comment by posita** [comment]
Okay, after reading https://github.com/matplotlib/matplotlib/issues/24281#issuecomment-1292717346 _et seq._ as well as the referenced material (esp. https://github.com/jupyter/notebook/issues/2640#issuecomment-579369065) I think the best way to bring Jupyter Lite into parity with Jupyter Lab is to change [this line](https://github.com/jupyterlite/jupyterlite/blob/c9846beca88cd84e15119547b00240515c7e6f6d/packages/pyolite-kernel/py/pyolite/pyolite/patches.py#L19) from ...

``` python
        matplotlib.pyplot.savefig(buf, format="png")
```

... to ...

``` python
        matplotlib.pyplot.savefig(buf, format="png", bbox_inches="tight")
```

**Comment by kolibril13** [comment]
Hi @posita !
I did not look into your code in detail, but here are my inputs on the margin issue:
I've noted this margin issue before when creating a Jupyter lite demo for [jupyter_compare_view](https://github.com/Octoframes/jupyter_compare_view).
The way I solved it was by using `fig.tight_layout()`.
Here is a minimal example:
```py
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots(figsize=(5, 5), facecolor="purple")
array = np.fromfunction(lambda i, j: np.sin(j), (15, 15))
ax.axis("off")
ax.imshow(array, cmap="YlGnBu")
#fig.tight_layout()
plt.show()
```
I've asked jklymak [in the matplotlib discourse](https://discourse.matplotlib.org/t/is-there-a-way-to-display-an-image-using-the-whole-canvas/23029/8?u=kolibril13) about the margin, and it turns out that the ipython default is:
`%config InlineBackend.print_figure_kwargs = {'bbox_inches':'tight'}` as written [here](
https://ipython.readthedocs.io/en/stable/interactive/magics.html?highlight=tight#magic-matplotlib).
JupyterLite does not have this parameter set as far as I know.
To make this issue easier to discuss, would you mind opening a new issue in JupyterLite with a minimal example? (Feel free to use my example code).
From my experience, it's easier for maintainers to work with short issue reports and minimal examples than with large ones.

**Comment by posita** [comment]
Closing in favor of #856.

**Comment by posita** [comment]
Thanks for the call-out, @kolibril13! I don't think `fig.tight_layout` addresses the issue, though. I tried to make that clear(er) in #856 (especially via the [included example](https://github.com/jupyterlite/jupyterlite/issues/856#issuecomment-1295665450), but please let me know if you think that issue needs more detail/color.
