### ISSUE TITLE
Allow extracting federated extensions from `.conda` packages

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlite/jupyterlite#877]
### Problem

`conda-forge` has transitioned to only building `.conda` packages. 

### Proposed Solution

Expand the federated extensions logic to look inside the double-wrapped archive. Old packages will not be transmuted, so we need to handle both.

### Additional context

May require a new (optional) dependency for dealing with `zstd` files.

**Comment by jtpio** [comment]
Ah interesting.

I see there is some information in the docs: https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/packages.html#conda-file-format
