### ISSUE TITLE
Real Time Collaboration

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#88]
With JupyterLab `3.1.0a8` shipping with the initial RTC work, we might want to start considering what enabling real time collaboration would look like with JupyterLite.

### Problem

Enable real time collaboration with JupyterLite. Questions:

- should that apply to anyone using the same JupyterLite deployment (that might be too disruptive as a default)
  - this will already be useful to users opening multiple tabs with the same notebook
- should we enable it on the demo website by default?
  -  maybe we'll need some kind of token sharing mechanism (implemented as a separate plugin) to let people copy and send links to other folks

### Proposed Solution

Incremental steps we can take:

- start using the `3.1.0-alpha.x` `@jupyterlab` packages
- enable the `collaborative` flag in PageConfig
- use a different provider than the default websocket provider (will require a change upstream to allow for more flexibility)

**Comment by bollwyvl** [comment]
Very pro this!

Semi-related: I am pursuing a monkeypatch-tastic approach on
jupyterlab-video chat, which I would combine with making the labextension
work without the server, which acts as a room metadata storage, but isn't
strictly required.

I think Jitsi has Good Enough information theory components to work as an
on-by-default bus on rtfd.io.
 the lab integration has an opt-in setting to allow for creating
unobfuscated room names, including a router URL, and then they take care of
all the trust.

**Comment by jtpio** [comment]
For reference #89 added a plugin to replace the default provider:

https://github.com/jtpio/jupyterlite/blob/695373748db6c5aa015224e94d4aa8679eb34ef2/packages/application-extension/src/index.ts#L51-L64

We can maybe switch to using the `WebrtcProvider` instead, and add a way to share tokens between users via query string parameters so they can connect to the same rtc room.

**Comment by jtpio** [comment]
Closing as fixed by #109.

Follow-up items are in https://github.com/jupyterlite/jupyterlite/issues/241
