### ISSUE TITLE
Migrate to `hatch`

### ISSUE THREAD

**Issue by jtpio** [jupyterlite/jupyterlite#881]
### Problem

Most Jupyter projects have now switched to using `hatch` for packaging: https://hatch.pypa.io/latest/

To keep things consistent and limit the number of different tools, we could consider switching to `hatch` here as well. And use its plugin system to extend functionality if needed.

### Proposed Solution

- [ ] Switch from `flit` to `hatch`
- [ ] Use `hatch` for versioning instead of `tbump` (if possible)

### Additional context

There is also a post of this on the Jupyter blog: https://blog.jupyter.org/packaging-for-jupyter-in-2022-c7be64c38926

**Comment by bollwyvl** [comment]
-0: No dog in this fight, definitely feeling some tool fatigue these days. if it works (and after every new version of pip comes out), builds byte-for-byte reproducible tarballs/wheels, and doesn't introduce too much custom metadata, woot woot. 

>  plugin system to extend functionality

yeah... as a `$DAY_JOB` packager of tediously more complex things, of which python is just one, i generally run screaming from extensible python build systems, magic private environments, etc. I am very much -1 to having `hatch` (or any other build backend) managing the nodejs environment: the error messages (which are frequent with the kind of crap we do) are just awful, and blindly assuming you have to do _everything_ every time will be very frustrating.

**Comment by jtpio** [comment]
> definitely feeling some tool fatigue these days

Exactly the reason for opening this issue and proposing this change :+1: 

> I am very much -1 to having hatch (or any other build backend) managing the nodejs environment:

This mostly comes from https://github.com/jupyterlab/hatch-jupyter-builder. We probably don't need it for lite and keep the existing separation just like it is now (hopefully).
