### ISSUE TITLE
Clipboard access

### ISSUE THREAD

**Issue by stuaxo** [jupyterlite/jupyterlite#883]
Since pyodide runs in a worker, it the clipboard isn't accessible (the navigator is a WorkerNavigator).

It would be good if there was a way to interface with the clipboard, (including the usual browser permissions etc).

**Comment by jtpio** [comment]
FYI @stuaxo I put together a simple widget to do something like this, available here: https://github.com/jtpio/ipyclipboard

You can try it in JupyterLite with the Pyodide kernel: https://jtpio.github.io/ipyclipboard/notebooks/index.html?path=example.ipynb

Closing as fixed, feel free to open an issue or PR there if you would like to improve it, thanks!
