### ISSUE TITLE
Data uploaded to the system gets trimmed, even if its bellow 2MB.

### ISSUE THREAD

**Issue by dgcmain** [jupyterlite/jupyterlite#888]
## Description

Upload a .csv file and the data gets trimmed to a certain row, instead of show the full file like its supposed.

File sizes tested: 1.6mb, 1.8mb, 1.4mb

## Reproduce

1. Go to Upload Data, upload a csv file of more than 1.5mb
2. Open the file with the previewer (or a notebook) and see how the file is trimmed.

## Expected behavior

The file should load completely.

**Comment by dgcmain** [comment]
@bollwyvl @jtpio do you consider this bug relevant?

**Comment by jtpio** [comment]
Thanks @dgcmain for reporting.

Yes this seems like an issue with how JupyterLite handles file uploads.

**Comment by rafpyprog** [comment]
I am facing the same problem. There's a work around if you are working with csv files and Pandas. Compress the file using zip to reduce the file size. Pandas is able to read the zip file using the _pd.read_csv_ method.
