### ISSUE TITLE
delay kernel ready status

### ISSUE THREAD

**Issue by stevejpurves** [jupyterlite/jupyterlite#897]
### Problem
When starting a `jupyterlite` server using the `pyolite` kernel, a client receives a `kernel-ready` message before `pyolite` initialization has finished. Even though the kernel blocks(awaits) it's ready promise before executing, there is no way for the frontend to signal that the kernel is not yet ready.

### Proposed Solution

Delay the ready signal until `pyodide` iniitialisation completes

### Additional context

related issue: https://github.com/executablebooks/thebe/issues/580

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlite/jupyterlite/pull/900
