### ISSUE TITLE
Bundle `fastparquet` or `pyarrow` to read parquet files in `pandas`

### ISSUE THREAD

**Issue by kuatroka** [jupyterlite/jupyterlite#903]
### Problem

Currently there seems to be no way to read parquet files through `pandas` with `read_pandas` as the engine needs to be specified. It can be either `fastparquet` or `pyarrow`. I tried to install it with `pip`, `micropip` or `piplite` but I'm getting an error that none of these packages has wheels.

### Proposed Solution

Please bundle one of these engines directly to the `jupyterlite` page, so we can import not only `.csv`, but also the much lighter files like `parquet`. Thanks

**Comment by bollwyvl** [comment]
Yep, you'd need to request these (or, ideally,  contribute them yourself) upstream on https://github.com/pyodide/pyodide
