### ISSUE TITLE
Loading a different version of a package included in `pyodide`

### ISSUE THREAD

**Issue by jobovy** [jupyterlite/jupyterlite#904]
## Description

I embed a jupyterlite REPL to allow people to try my ``galpy`` code on its documentation site ([here](https://docs.galpy.org/en/latest/#try-galpy)), but I want to allow users to use the latest development version of the code there. But because ``galpy`` is included in the ``pyodide`` distribution, the version that is loaded whenever I include an `import galpy` statement in the cell where I try to load the latest version is the default ``pyodide`` version. 

I believe this happens because ``loadPackagesFromImports`` is called before any cell is run:
https://github.com/jupyterlite/jupyterlite/blob/31d91cacc86ef109eac558487f2efaf37acc1571/packages/pyolite-kernel/py/pyolite/pyolite/kernel.py#L86-L97

So even if the cell includes a command to install a different version (e.g., ``await piplite.install(...)``), the default version of the package is loaded first.

## Reproduce

Running
```
import pyodide_js
await pyodide_js.loadPackage(['numpy','scipy','matplotlib','astropy','future','setuptools','https://www.galpy.org/wheelhouse/galpy-latest-cp310-cp310-emscripten_3_1_14_wasm32.whl'])
import galpy; print(galpy.__version__)
```
prints `1.8.0`, while running
```
import pyodide_js
await pyodide_js.loadPackage(['numpy','scipy','matplotlib','astropy','future','setuptools','https://www.galpy.org/wheelhouse/galpy-latest-cp310-cp310-emscripten_3_1_14_wasm32.whl'])
```
and in the next cell
```
import galpy; print(galpy.__version__)
```
prints `1.8.2.dev0`.

I know I probably shouldn't be using `pyodide_js.loadPackage` here, but I believe the same will happen with ``micropip.install`` or ``piplite.install``. I use ``pyodide_js.loadPackage`` because my wheel does not have a valid name (I should probably change that!).

## Expected behavior

Load the requested version. Not sure how though! Options might include:
* Have a configuration parameter giving packages _never_ to load from the default distribution and then replace the ``_load_packages_from_imports`` call with something that uses [``pyodide.code.find_imports``](https://pyodide.org/en/stable/usage/api/python-api/code.html#pyodide.code.find_imports), pops packages never to load, and then runs ``loadPackage``.
* Search the code to be run for custom installation commands (like ``micropip.install`` etc.) and then pop any package that will be customly installed. That seems difficult though, because the wheel name doesn't necessarily include the package name.

## Context

- JupyterLite version: [latest](https://jupyterlite.readthedocs.io/en/latest/_static/lab/?path=intro.ipynb) 
- Operating System and version: Mac OS Ventura
- Browser and version: Chrome 107.0.5304.121 (Official Build) (arm64)

<details><summary>Browser Output</summary>
<pre>
​ URI mismatch, attempting to load package galpy from https://www.galpy.org/wheelhouse/galpy-latest-cp310-cp310-emscripten_3_1_14_wasm32.whl while it is already loaded from default channel. To override a dependency, load the custom package first.
</pre>
</details>

**Comment by bollwyvl** [comment]
[Extra wheels](https://jupyterlite.readthedocs.io/en/latest/howto/python/wheels.html) will only be honored by [`%pip install` or `await piplite.install`](https://jupyterlite.readthedocs.io/en/latest/howto/python/packages.html#installing-packages-at-runtime).

I believe the `pyodide`-distributed ones will always win, however, so you'd have to ship your own [custom pyodide](https://jupyterlite.readthedocs.io/en/latest/howto/python/pyodide.html) which patched out the offending packages from [`repodata.json`](https://cdn.jsdelivr.net/pyodide/v0.21.3/full/repodata.json).

**Comment by jobovy** [comment]
> I believe the `pyodide`-distributed ones will always win, however, so you'd have to ship your own [custom pyodide](https://jupyterlite.readthedocs.io/en/latest/howto/python/pyodide.html) which patched out the offending packages from [`repodata.json`](https://cdn.jsdelivr.net/pyodide/v0.21.3/full/repodata.json).

Thanks, that would indeed be another way to do it. Because I already use my own fork of `jupyterlite` itself, I think I'll just patch that instead, but perhaps I'll leave this open to see whether anybody else has a better idea.
