### ISSUE TITLE
JupyterLite doesn't display plt plots by default

### ISSUE THREAD

**Issue by antocuni** [jupyterlite/jupyterlite#906]
## Description

This bug was originally found while investigating this PyScript issue: https://github.com/pyscript/pyscript/issues/983

As discussed with @jtpio in real life, the following piece of code behaves differently in Jupyter and JupyterLite: in Jupyter, it displays a plot; in JupyterLite, it displays `<matplotlib.collection.PathsColletion ...>`.

If you add `%matplotlib_inline`, it works as expected.

## Reproduce

```python
import pandas as pd
import matplotlib.pyplot as plt
url = "https://raw.githubusercontent.com/Cheukting/pyscript-ice-cream/main/bj-products.csv"

# try to autodetect whether it's jupyter or jupyterlist
try:
    from pyodide.http import open_url
except ImportError:
    print("Normal jupyter")
else:
    print("jupyterlite!")
    url = open_url(url)

df = pd.read_csv(url)
plt.scatter(df['rating'], df['rating_count'])
```

## Expected behavior

Jupyter and JupyterLite should behave the same.

**Comment by martinRenou** [comment]
Thanks for opening an issue!

That rings a bell now. We fixed a similar issue in jupyterlite-xeus-python.

If you use normal Jupyter, the inline backend is used by default:
![Screenshot from 2022-12-09 16-41-24](https://user-images.githubusercontent.com/21197331/206738925-6e51c262-30a7-46dc-b007-af341dbb3632.png)

So we mimick the same behavior in xeus-python now: https://github.com/jupyter-xeus/xeus-python-shell/pull/16

I guess we should do the same in pyolite.
