### ISSUE TITLE
Installing JupyterLite as a pwa fails on iPadOS

### ISSUE THREAD

**Issue by dhombios** [jupyterlite/jupyterlite#910]
## Description

Installing jupyterlite on android results in an application indistinguishable from the ones provided in the play store (from the point of view of the user) as it normally happens with any pwa. 

However, doing the same on iPadOS just generates a bookmark that opens safari and tries to connect to jupyterlite website. If no internet connection is available, it won't be loaded (doing the same with Vs code for the web allows using it offline as any other app)

## Reproduce

1. Open safari 
2. Go to https://jupyterlite.github.io/demo/lab/index.html
3. Add to Home Screen
4. Go to Home Screen and press jupyterlite icon
5. https://jupyterlite.github.io/demo/lab/index.html will open in safari 

It seems that iPadOS is not recognizing jupyterlite as a pwa

## Expected behavior

Pressing jupyterlite icon should open jupyterlite as a separate app instead of opening its website in Safari

## Context

- JupyterLite version: Version 0.1.0-beta.15
- Operating System and version: iPadOS 16.1.1
- Browser and version: Safari

<details><summary>Browser Output</summary>
<pre>
Browser output is not available in Safari in iPadOS 
</pre>
</details>

**Comment by bollwyvl** [comment]
PRs welcome! I don't have a device to test this on.

**Comment by jtpio** [comment]
Yes any help would be really appreciated!

> Installing jupyterlite on android results in an application indistinguishable from the ones provided in the play store (from the point of view of the user) as it normally happens with any pwa.

This should probably be mentioned in the documentation at some point since it's quite of a cool feature :+1: 

<img src="https://user-images.githubusercontent.com/591645/207124737-aa7fa22b-ce48-4812-afc0-75b351f62278.jpg" height="512">

**Comment by dhombios** [comment]
Taking into account that all its features seem to work properly, I think it might be a problem with the manifest. Maybe safari requires an additional field

Regarding the documentation, it is a really nice feature, as it allows bringing jupyter to tablets

**Comment by dhombios** [comment]
Looking at the manifest, it may be a problem with the display option. It seems that iPadOS does not support minimal-ui and therefore it is using browser. It seems that there is an option for changing that behavior according to this website: https://web.dev/add-manifest/

**Comment by dhombios** [comment]
As it's been a while since the last message and it doesn't seem that any contributor has the tools required to test it on an iPad, I could try the suggested modifications. However, I don't have a Mac so I won't be able to provide debug information

How could I build Jupiter lite locally from source to test a version with a modified manifest?

**Comment by jtpio** [comment]
Thanks @dhombios.

> How could I build Jupiter lite locally from source to test a version with a modified manifest?

You could follow the dev instructions in https://jupyterlite.readthedocs.io/en/latest/contributing.html for example.

**Comment by dhombios** [comment]
After tweaking the manifest a bit I have gotten Jupiter lite to run as an installed app on iPad offline:

![image](https://user-images.githubusercontent.com/27309564/212499671-dd7c39d7-bcd8-49ab-ae86-ef161429c34a.png)

Additionally, it works fine on android, windows and Linux.

However, display_override doesn't seem to be supported by safari, so the only way to get it installed is to set display to standalone instead of minimal-ui.

Before opening a pull request, is there any reason why minimal-ui was chosen instead of standalone?

**Comment by jtpio** [comment]
> Before opening a pull request, is there any reason why minimal-ui was chosen instead of standalone?

According the git history, the initial value was `standalone` but it was then switched to `minimal-ui` in https://github.com/jupyterlite/jupyterlite/commit/d0915e33fa0b7576b5b6bbee6714a45076bb8389 (as part of https://github.com/jupyterlite/jupyterlite/pull/686).

Although there doesn't seem to be some info about this, maybe @martinRenou remembers why.
