### ISSUE TITLE
How to use the `jupyter lite build` contents flag with multiple directories?

### ISSUE THREAD

**Issue by startakovsky** [jupyterlite/jupyterlite#915]
### Problem

Documentation does not provide an example of how to list multiple content directories when building. See [here](https://jupyterlite.readthedocs.io/en/latest/howto/content/files.html)

### Suggested Improvement

I do not know how to do this, which is why I'm submitting this issue.

**Comment by jtpio** [comment]
@startakovsky normally you should be able to specify `--contents` multiple times. For example:

```bash
jupyter lite build --contents first-folder --contents second-folder
```

Or via a `jupyter_lite_config.json`:

```json
{
  "LiteBuildConfig": {
    "contents": ["first-folder", "second-folder"]
  }
}
```

**Comment by startakovsky** [comment]
This is very helpful. I am going to learn more about the config module now. Thank you.

**Comment by jtpio** [comment]
Closing as answered, feel free to re-open or open a new issue if you have other questions!
