### ISSUE TITLE
Make jupyterlite support ipyevents

### ISSUE THREAD

**Issue by hbredin** [jupyterlite/jupyterlite#918]
### Problem

I am working on [a custom widget](https://github.com/hbredin/pyannotebook) that internally relies on [ipyevents](https://github.com/mwcraig/ipyevents) (that is meant to catch keyboard and mouse events).

`ipyevents` works with regular jupyter notebooks but not with `jupyterlite`.

### Proposed Solution

Make `jupyterlite` support `ipyevents` (but it might be the other way around).

### Additional context

This problem can be reproduced by running the [short example](https://ipyevents.readthedocs.io/en/latest/events.html#Short-example) and noticing that keyboard and mouse events are not caught.

**Comment by bollwyvl** [comment]
Did you build a site that includes the [labextension](https://jupyterlite.readthedocs.io/en/latest/howto/configure/simple_extensions.html)? The frontend components need to be available at build time so they can be served to the browser.

**Comment by hbredin** [comment]
Thanks @bollwyvl, I did not know that and only ran `%pip install ipyevents` in the first cell of the jupyterlite instance available at https://jupyter.org/try-jupyter/lab/.

Now that I do know that, I did manage to build and serve a juyterlite instance with ipyevents support. 

Thanks!

**Comment by bollwyvl** [comment]
:fire: good luck!
