### ISSUE TITLE
Loading vanilla Seaborn dataset errors out: `urlopen error unknown url type: https`

### ISSUE THREAD

**Issue by startakovsky** [jupyterlite/jupyterlite#919]
## Description

I was going through the [seaborn tutorial](https://seaborn.pydata.org/tutorial/introduction.html) and JupyterLite failed at the first example because it couldn't load the dataset due to something to do with https. The error is that it uses an https protocol. This sort of reminds me of [#744] but I don't see a similar fix.

## Reproduce

```python
%pip install seaborn

import seaborn as sns

# Load an example dataset
tips = sns.load_dataset("tips")
```

## Output

```
---------------------------------------------------------------------------
URLError                                  Traceback (most recent call last)
Cell In[1], line 6
      3 import seaborn as sns
      5 # Load an example dataset
----> 6 tips = sns.load_dataset("tips")

File /lib/python3.10/site-packages/seaborn/utils.py:582, in load_dataset(name, cache, data_home, **kws)
    580 cache_path = os.path.join(get_data_home(data_home), os.path.basename(url))
    581 if not os.path.exists(cache_path):
--> 582     if name not in get_dataset_names():
    583         raise ValueError(f"'{name}' is not one of the example datasets.")
    584     urlretrieve(url, cache_path)

File /lib/python3.10/site-packages/seaborn/utils.py:508, in get_dataset_names()
    502 """Report available example datasets, useful for reporting issues.
    503 
    504 Requires an internet connection.
    505 
    506 """
    507 url = "https://github.com/mwaskom/seaborn-data"
--> 508 with urlopen(url) as resp:
    509     html = resp.read()
    511 pat = r"/mwaskom/seaborn-data/blob/master/(\w*).csv"

File /lib/python3.10/urllib/request.py:216, in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    214 else:
    215     opener = _opener
--> 216 return opener.open(url, data, timeout)

File /lib/python3.10/urllib/request.py:519, in OpenerDirector.open(self, fullurl, data, timeout)
    516     req = meth(req)
    518 sys.audit('urllib.Request', req.full_url, req.data, req.headers, req.get_method())
--> 519 response = self._open(req, data)
    521 # post-process response
    522 meth_name = protocol+"_response"

File /lib/python3.10/urllib/request.py:541, in OpenerDirector._open(self, req, data)
    538 if result:
    539     return result
--> 541 return self._call_chain(self.handle_open, 'unknown',
    542                         'unknown_open', req)

File /lib/python3.10/urllib/request.py:496, in OpenerDirector._call_chain(self, chain, kind, meth_name, *args)
    494 for handler in handlers:
    495     func = getattr(handler, meth_name)
--> 496     result = func(*args)
    497     if result is not None:
    498         return result

File /lib/python3.10/urllib/request.py:1419, in UnknownHandler.unknown_open(self, req)
   1417 def unknown_open(self, req):
   1418     type = req.type
-> 1419     raise URLError('unknown url type: %s' % type)

URLError: <urlopen error unknown url type: https>
```

## Context

JupyterLite Version 0.1.0b15
Chrome Browser Version 108.0.5359.98 (Official Build) (arm64)

**Comment by jtpio** [comment]
Thanks @startakovsky, that is indeed a limitation for now, which I think is tracked in the Pyodide repo.

As an alternative you should be able to fetch the data sets by making manual queries to the following repo: https://github.com/mwaskom/seaborn-data

Using `from js import fetch` for example.

**Comment by christianprim** [comment]
Or use in the meantime this very handy patch:

```
%pip install pyodide-http

import pyodide_http
pyodide_http.patch_all()
```

After this patch `urllib` works with jupyterlite.

(This should be part of pyodide or a package always loaded in jupyterlite...)

**Comment by jtpio** [comment]
Ah nice, didn't that `pyodide-http` had a patch for `urllib` as well. 

Maybe that should indeed be something that goes into Pyodide by default at some point.

In the meantime we could also mention it somewhere in the JupyterLite docs.

Thanks for sharing!

**Comment by bollwyvl** [comment]
> or a package always loaded in jupyterlite...

We _just_ got _out_ of the patching of packages business (`matplotlib` and `pillow`), and will hopefully _reduce_ the number of things that get loaded at runtime without being useful for _every_ kernel (#914). 

If that one is successful, we might have the means for `--piplite-urls` to become more useful, where packages described that way would have their top-level imports extracted, so they can be automatically installed. But a notebook would _still_ have to `import pyodide_http` and `pyodide_http.patch_all()` to get the behavior.
