### ISSUE TITLE
Unable to enter newline in code cell in Retro without appending a trailing space first

### ISSUE THREAD

**Issue by westurner** [jupyterlite/jupyterlite#921]
## Description

Unable to enter newline or indeed more than one line of code in a code cell in Retro (Jupyter Notebook) without appending a trailing space first

## Reproduce

1. Go to Retro mode
2. Click on 'append cell' below'
3. Type e.g. `import math, sympy as sy`
4. Press enter. The cursor returns to the previous line.

Workaround:

3. Add a trailing space.
   Type e.g. `import math, sympy as sy `
4. Press enter

## Context

- JupyterLite version: ?
  - code mirror?
- Operating System and version:
- Browser and version: latest mobile chrome

**Comment by jtpio** [comment]
Thanks @westurner for the report.

Do you know if this also happens with Notebook 7? The latest `main` can be tested on Binder: https://mybinder.org/v2/gh/jupyter/notebook/main?urlpath=tree

If not then the issue will probably be fixed as part of #826.

**Comment by jtpio** [comment]
Just checked on the latest demo site and it seems to be working fine:

https://github.com/jupyterlite/jupyterlite/assets/591645/059dae54-8263-4f53-b6d8-7584fbe917cd

Closing as likely fixed by #826, thanks!
