### ISSUE TITLE
.conda Archive contains unknown compression format .tar.zst

### ISSUE THREAD

**Issue by christianprim** [jupyterlite/jupyterlite#927]
## Description

Build fails with federated extension `jupyterlab_widgets-3.0.4-pyhd8ed1ab_0.conda`. The conda archive contains an unknown compression format .tar.zst.

Error-Log

```
. pre_build:federated_extensions:extract:jupyterlab_widgets-3.0.4-pyhd8ed1ab_0.conda
. pre_build:federated_extensions:extract:pkg-jupyterlab_widgets-3.0.4-pyhd8ed1ab_0.tar.zst
TaskError - taskid:pre_build:federated_extensions:extract:pkg-jupyterlab_widgets-3.0.4-pyhd8ed1ab_0.tar.zst
PythonAction Error
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/doit/action.py", line 461, in execute
returned_value = self.py_callable(*self.args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/jupyterlite/addons/base.py", line 329, in extract_one
raise ValueError(f"Unrecognized archive format {archive.name}")
ValueError: Unrecognized archive format pkg-jupyterlab_widgets-3.0.4-pyhd8ed1ab_0.tar.zst
```
## Reproduce

1. Use `jupyter_lite_config.json` from the examples-folder
2. Execute `python -m pip install jupyterlite[all] libarchive-c && jupyter lite build`

(I don't know if one really needs to install libarchive-c explicitly. But the changelog v0.1.0b15 suggests it)

## Expected behavior

No error in the building process.

## Context

- JupyterLite version: [v0.1.0b16](https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0b16)
- Operating System and version: python:3 (Dockerimage)

**Comment by bollwyvl** [comment]
If you are using `.conda` packages as sources, I guess the expectation was that one would be using `conda` (but probably `mamba`) to manage the build environment, which provides the underlying `libarchive` binary.

With the `pip` version (which does appear to be failing to import: perhaps try a `python -c 'import libarchive'` to get more errors?), you may well need to find some of your own dependencies for heavy-duty binaries with whatever your container's OS package manager provides, e.g. `apt|aur|dnf install libarchive` (and, potentially `zstd`).

However, if that's the _only_ `.conda` package you are using, it should also be easy to find the corresponding `.whl` that would replace it.

**Comment by christianprim** [comment]
I don't think, a missing package is the problem here. One can provide that with the package manager provided by the os as stated in the last comment.

The problem is AFAIK in the code itself:

`py/jupyterlite/src/jupyterlite/addons/federated_extensions.py` (line 130ff)

```
            if local_path.name.endswith((".whl", ".tar.bz2")):
                yield from self.copy_simple_archive_extensions(local_path)
            elif local_path.name.endswith(".conda"):
                yield from self.copy_conda2_extensions(local_path)
            else:  # pragma: no cover
                raise NotImplementedError(f"unknown archive {suffix}")
```
It accepts `.conda` but no `.tar.zst`. And a federated extension using a `.zst`-archive is proposed in the example directory. It's not a custom install of mine.

**Comment by christianprim** [comment]
And here in the code, `zst` is also missing:

`py/jupyterlite/src/jupyterlite/addons/base.py` (line 321)
```
        if archive.name.endswith(EXTENSION_ZIP):
            with zipfile.ZipFile(archive) as zf:
                zf.extractall(dest)
        elif archive.name.endswith(EXTENSION_TAR):
            mode = "r:bz2" if archive.name.endswith(".bz2") else "r:gz"
            with tarfile.open(archive, mode) as tf:
                self.safe_extract_all(tf, dest)
        else:
            raise ValueError(f"Unrecognized archive format {archive.name}")
```

**Comment by bollwyvl** [comment]
Right: the `.conda` archive, much like a `.whl`, is secretly a `.zip`, extraction of which _is_ supported by stdlib python, so it can get that far. That's why the first line of your log succeeded.

Inside _that_, there are two `.tar.zst` files inside it, one of which contains the files in `{prefix}/share/jupyter/labextension`... these cannot be extracted with stdlib python, or apparently the as-installed `libarchive-c` in the system under test.

The fact that the `ValueError` is thrown means it's not going inside [this branch](https://github.com/jupyterlite/jupyterlite/blob/08e35d8afe7337eedeb5cb64c9e0653643ed36b8/py/jupyterlite/src/jupyterlite/addons/base.py#L310). Again, a try of `python -c "import libarchive"` will likely complain something is missing, or the `pip` distribution is broken.

**Comment by christianprim** [comment]
Sorry for the noise! That was really a problem with the missing `libarchive13`-package in the docker. Thx for the help!

**Comment by qqdaiyu55** [comment]
`libarchive-c` is not that easy to be installed & used in Mac OS or windows.
My solution on it:
- install `conda-package-handling`
- Unpack `.conda` to the folder with `cph extract EXTENSION.conda`
- Create `.tar.bz2` compressed file with `cph create EXTENSION EXTENSION.tar.bz2`
