### ISSUE TITLE
Allow addons to register short CLI args

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlite/jupyterlite#929]
### References
- from https://github.com/jupyterlite/jupyterlite/pull/854/files#r1055746387

### Problem

Any third-party addons can only specify "extra long" traitlets args.

```
jupyter lite build --XeusPythonEnv.environment_file=custom.yml
```

#854 brings this to a head, where we already have documentation and use in the wild that references the few CLI args for the pyodide-based functionality. It doesn't seem we need to _needlessly_ break backward CLI compatibility, aside from a new line in a `requirements.txt` for `pyodide-kernel`.

### Proposed Solution
- _Core_ `Addons` (e.g. in this repo) would continue to have config set in the `LiteBuildConfig`.
  - #854 already removes the `pyodide` and `piplite` ones
- allow `Addon`s _may_ specify a static mapping of CLI arguments to traits:
  - `pyodide-kernel`
    - `extra_args = {"piplite-wheels": "piplite_urls", "pyodide": "pyodide_url"}`
  - `xeus-python`
    - `extra_args = {"environment-file": "environment_file"}`
- in the main app, capture [`extra_args`](https://github.com/ipython/traitlets/blob/main/traitlets/config/application.py#L408) 
  - hand them down as appropriate to all addons that want them
- include the all the traits' `help` in the `jupyter lite --help`
  - could show potential collisions
    - but, in the future, if `xeus-python` can also consume `pyodide` wheels, _a la_ `conda-pack`, all the better!

### Additional context

- I don't know of a _good_ example of this pattern on `traitlets`
  - eventually might be worth hoisting

**Comment by bollwyvl** [comment]
It looks like the `extra_args` are semi-inflexible... looking into loading the `entry_point`s first and extending the flags, as then it seems the auto-discovery mechanism might work more predictably.

**Comment by martinRenou** [comment]
great! Thanks
