### ISSUE TITLE
For Notebook in Local Files, /drive points to JupyterLite Storage when Notebook is in the top level directory.

### ISSUE THREAD

**Issue by tanaga9** [jupyterlite/jupyterlite#942]
### Problem

Unstable references from /drive in JupyterLite with jupyterlab-filesystem-access extension
https://github.com/jupyterlab-contrib/jupyterlab-filesystem-access/issues/48
![211135747-b3e4c502-cdd8-4128-aa11-9b8dd2b59481](https://user-images.githubusercontent.com/6501421/211285715-f51edae3-0400-4a4e-bd80-23c5a423fcc5.png)

- Sometimes /drive refers to JupyterLite Storage
- Sometimes /drive refers to Local Files

I don't know the conditions for either behavior. (when Notebook is in the top level directory ?)

I guessed the [Storage Settings](https://jupyterlite.readthedocs.io/en/latest/howto/configure/storage.html#settings-storage) in JupyterLite is involved.

Because it seemed that JupyterLite and jupyterlab-filesystem-access extension conflicted on /drive.
(Can you see what's going on?)

I tried setting `jupyter-lite.json#jupyter-config-data/contentsStorageDrivers` to `["FileSystem"]`.
([FileSystem is a Drive Name](https://github.com/jupyterlab-contrib/jupyterlab-filesystem-access/blob/043521aeb090ccb67aa9ca867082a7ef042a4467/src/drive.ts#L7))

```
{
    "jupyter-config-data": {
      "contentsStorageDrivers": ["FileSystem"]
    },
    "jupyter-lite-schema-version": 0
}
```

This attempt failed.

### ~~Suggested Improvement~~

~~Document how to stabilize /drive references with jupyterlab-filesystem-access extension.~~

### Expected

For local file notebooks, /drive always points to JupyterLite storage.

**Comment by martinRenou** [comment]
The current behavior is that any Notebook started from the local file system extension would use this local directory as `/drive` and any Notebook started from the JupyterLite storage would use the JupyterLite storage.

The reasoning behind this is that notebooks from a local folder would sometimes load local data files (`.csv`, etc.) so they need access to those.

For now this is not configurable but we could make it configurable.

What kind of behavior would you like to see? Do you want to always have `/drive` point to the jupyterlite storage?

**Comment by tanaga9** [comment]
Thanks a lot @martinRenou

> What kind of behavior would you like to see? Do you want to always have /drive point to the jupyterlite storage?

I want to always have /drive point to the Local Files (Storage provided by jupyterlab-filesystem-access extension)
(not jupyterlite storage)

It seems that the location of the notebook that reads /drive affects the behavior now.

- Notebook in `JupyterLite Storage`
    - /drive refers to `JupyterLite Storage` (-> /drive can point to local files, it doesn't matter)
- Notebook in `Local Files`
    - Notebook is directly in **the top directory**: /drive refers to `JupyterLite Storage` (-> **I want to have /drive point to the `Local Files`**)
    - Notebook is in **some subdirectory**: /drive refers to `Local Files`

`JupyterLite Storage` means a asyncStorage or webSQLStorage or localStorageWrapper or memoryStorageDriver.
`Local Files` means native files provided by the OS.

**Comment by martinRenou** [comment]
It all looks good to me except that one:

> Notebook is directly in the top directory:
/drive refers to JupyterLite Storage (-> I want to have /drive point to the Local Files)

which looks like a bug. It should point to the local file storage.

**Comment by tanaga9** [comment]
> which looks like a bug. It should point to the local file storage.

I couldn't determine if this is a JupyterLite bug or a jupyterlab-filesystem-access extension bug.

**Comment by tanaga9** [comment]
I want this bug fixed.
Setting change is workaround until then (but it also doesn't work now)
