### ISSUE TITLE
Could we have a jupyterlite demo based on pyodide-0.23.0a1 on python-3.11 ? 

### ISSUE THREAD

**Issue by stonebig** [jupyterlite/jupyterlite#957]
### Problem

Have a simple way to assess pyodide performance improvement with python-3.11

### Proposed Solution

Have Access on a live demo of jupyterlite in  both python 3.10 and python 3.11 based pyodide

**Comment by jtpio** [comment]
Just opened a draft PR to start testing the new version on the ReadTheDocs preview: https://github.com/jupyterlite/jupyterlite/pull/962

**Comment by stonebig** [comment]
Many thanks ! It's was very helpfull
