### ISSUE TITLE
[development environment]: Module not found error for ipykernel-6.9.2

### ISSUE THREAD

**Issue by savakarrohan** [jupyterlite/jupyterlite#958]
## Description
I made a new local clone of the repository and created a new environment using the binder details mentioned in the documentation.
[located here](https://jupyterlite.readthedocs.io/en/latest/contributing.html#prerequisites)
There appears to be a module versioning error, that occurs when I run the command `yarn bootstrap`

## Reproduce
- New clone of the repository
- change the working directory to the repository
- `conda env update --file .binder/environment.yml`
- `conda activate jupyterlite-dev`
- `yarn bootstrap`

## Error log
```
lerna info filter [ '@jupyterlite/app' ]

> @jupyterlite/app:build

$ webpack
@jupyterlite/app: [webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve '../pypi/ipykernel-6.9.2-py3-none-any.whl' in 'D:\StockWhiz\StockWhiz_DevFiles\jupyterlite\packages\pyolite-kernel\lib'
@jupyterlite/app:     at D:\StockWhiz\StockWhiz_DevFiles\jupyterlite\node_modules\webpack\lib\Compilation.js:2016:28
@jupyterlite/app:     at D:\StockWhiz\StockWhiz_DevFiles\jupyterlite\node_modules\webpack\lib\NormalModuleFactory.js:798:13
```
## Diagnosis
There is an installation of ipykernel @ version ~6.20.2
So ipykernel is being added but this requires version 6.9.2 so the command below will replace the above version
I ran the command 
- `pip install ipykernel==6.9.2`

## Expected behavior
- Correct version of ipykernel to be installed.
- No extra installations required.

## Solution
Add `ipykernel==6.9.2` to the binder `environment.yml` file.

**Comment by savakarrohan** [comment]
I would also like to point that I have the following error when running `doit` post environment installation
```Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\jupyterlite-dev\lib\site-packages\doit\action.py", line 461, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "D:\StockWhiz\StockWhiz_DevFiles\jupyterlite\py\jupyterlite\src\jupyterlite\addons\base.py", line 306, in extract_one
    shutil.rmtree(dest)
  File "C:\ProgramData\miniconda3\envs\jupyterlite-dev\lib\shutil.py", line 749, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\ProgramData\miniconda3\envs\jupyterlite-dev\lib\shutil.py", line 614, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\ProgramData\miniconda3\envs\jupyterlite-dev\lib\shutil.py", line 614, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\ProgramData\miniconda3\envs\jupyterlite-dev\lib\shutil.py", line 614, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 5 more times]
  File "C:\ProgramData\miniconda3\envs\jupyterlite-dev\lib\shutil.py", line 619, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\ProgramData\miniconda3\envs\jupyterlite-dev\lib\shutil.py", line 617, in _rmtree_unsafe
    os.unlink(fullname)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\StockWhiz\\StockWhiz_DevFiles\\jupyterlite\\examples\\.cache\\archives\\jupyterlab_miami_nights-0.3.2-pyhd8ed1ab_0.tar.bz2\\share\\jupyter\\labextensions\\@timkpaine\\jupyterlab_miami_nights\\themes\\@timkpaine\\jupyterlab_miami_nights\\3b5adc929c114d1cd0fc91cd735847b6.ttf'
```
This seems like a double \ is being added

**Comment by bollwyvl** [comment]
The missing module is because it isn't built yet. Keep scrolling on those
docs, and try:

    doit build

Before any fine-grained yarn tasks.

The paths _are_ "doubled" (escaped) because windows paths use as a path
delimiter the escape character from POSIX, which is closer to what python
"thinks" in natively. So it's escaping the escape. No worries there.

But the "Not Found" is due to that path being too long for windows, to
maintain compatibility with MS-DOS. You can change your registry to enable
long paths, but I don't remember how.

Alternately, try a much shorter path, like `d:\jl`, but that's just saving
30 characters or so, and some of the extension paths are very long.

**Comment by savakarrohan** [comment]
Thank you so much, this definetly worked,
For completion's sake, I will add some comments here 
---
## Path too long
On Windows one can change the registry editor settings as follows
- `win+r` and type `regedit` to open registry editor,
- Navigate to the key `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled`
- double click and set the value to 1
- if `LongPathsEnabled` is not available create a new `DWORD(32-bit)` value using right click

## doit
`doit` should be run first before any yarn tasks

Should I add these comments to part of the contributing guide? just in case?
