### ISSUE TITLE
No plotly support?

### ISSUE THREAD

**Issue by BartlomiejLewandowski** [jupyterlite/jupyterlite#970]
## Description
I'm trying to run plotly within jupyterlite. The documentation README states that it is supported. I've searched for a demo, and indeed there was a plotly demo, but the file no longer exists. Was the support dropped?

What options do I have for interactive charts in jupyterlite?
## Reproduce

Using the below code

```
import chart_studio.plotly as py
import plotly.figure_factory as ff
import pandas as pd

#df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/school_earnings.csv")

table = ff.create_table(df)
py.iplot(table, filename='jupyter-table1')
```

## Expected behavior

A table is shown.

## Context

Got the following error:
`
MaxRetryError: HTTPSConnectionPool(host='api.plotly.com', port=443): Max retries exceeded with url: /v2/grids (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))`

Reading about the issue a bit more I understand that sockets are not available, so I decided to try the offline mode - 
```

import plotly.graph_objects as go
fig = go.Figure(
    data=[go.Bar(y=[2, 1, 3])],
    layout_title_text="A Figure Displayed with fig.show()"
)
fig.show()

```
This time the error was 
`
ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed`

- JupyterLite version: not sure, https://jupyter.org/try-jupyter/lab/ url
- Operating System and version: Mac OSX
- Browser and version: Chrome

**Comment by BartlomiejLewandowski** [comment]
Related https://github.com/jupyterlite/jupyterlite/issues/320

**Comment by bollwyvl** [comment]
We've tried to bring it back, but the most recent version of `plotly` doesn't seem to detect the environment properly: https://github.com/jupyterlite/jupyterlite/pull/950

It's possible one could dig in further, but it's likely any synchronous IO will still be broken, if it needs that.

**Comment by oscarpereztuta** [comment]
@jtpio I believe you can close this one #950 fixed the issue.

**Comment by jtpio** [comment]
Right, thanks @oscarpereztuta!
