### ISSUE TITLE
Video tag doesn't work

### ISSUE THREAD

**Issue by koki0702** [jupyterlite/jupyterlite#971]
## Description

When video tags are inserted in markdown, sometimes they are displayed correctly and sometimes nothing is displayed (a black screen is displayed).

## Reproduce

Insert the markown below.

```
<video src="https://drive.google.com/uc?export=view&id=1fgAjTaSb5hGEIFnV7rDQdlV4kXogwjjK" controls></video>
```

As shown below, sometimes the correct video is displayed and sometimes a black screen is displayed.

<img width="670" alt="image" src="https://user-images.githubusercontent.com/515809/216528394-f8380c31-7471-43ec-b8c7-c816c6ae1637.png">

<img width="347" alt="image" src="https://user-images.githubusercontent.com/515809/216528304-fe0c9878-fe57-4493-8391-329efa521d6e.png">

**Comment by bollwyvl** [comment]
Some more browser console log information would be useful, or a link to a site where this is being observed.

**Comment by jtpio** [comment]
> `<video src="https://drive.google.com/uc?export=view&id=1fgAjTaSb5hGEIFnV7rDQdlV4kXogwjjK" controls></video>`

@koki0702 it looks like this Google Drive URL might not be the correct one. Also if I recall correctly the Google Drive shared links  don't point to the video / images directly. They have additional UI elements to download the video. You might have to right click on the video and select "Copy Video Link" to get the link to the raw video (not sure that's the right way to do it though).

Testing with the example video from https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video" looks fine:

```html
<video src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm" controls></video>
```

https://user-images.githubusercontent.com/591645/230568766-394ac9ab-f617-4197-9186-ab57dc957bc8.mp4

**Comment by jtpio** [comment]
Closing as answered as this doesn't appear to be an issue in JupyterLite.

Feel free to open new issues if you would like to discuss more, thanks!
