### ISSUE TITLE
Bug: content cache shared between JupyterLite instances hosted on the same server

### ISSUE THREAD

**Issue by nthiery** [jupyterlite/jupyterlite#977]
## Description

If a web server serves several jupyterLite instances in different directories,
then the browser is confused and stick to the content of the first jupyterlite
instance that was visited.

## Reproduce

1. Go to https://tutoriels-jupyter.pages.in2p3.fr/lite/lab?path=README.ipynb
2. See that the title is:  "À la découverte de l’écosystème Jupyter et des carnets numériques"
3. Go to https://tutoriels-jupyter.pages.in2p3.fr/rennes/lite/lab?path=README.ipynb
4. See that the title is still the same
5. Clear cache or open a new private navigation tab
6. Go again to https://tutoriels-jupyter.pages.in2p3.fr/rennes/lite/lab?path=README.ipynb
7. See the correct title: "Mini-site JupyterLite pour l’Université de Rennes"

## Expected behavior

See directly the correct content.

## Analysis

The caching is presumably based on the host only instead of host + path of the root

## Context

- JupyterLite version: Version 0.1.0-beta.16
- Operating System and version: Ubuntu 20.04
- Browser and version: Firefox, Chromium

<details><summary>Browser Output</summary>
<pre>
manifest.webmanifest:1 Manifest: property 'url' ignored, should be within scope of the manifest.
manifest.webmanifest:1 Manifest: property 'url' of 'shortcut' not present.
manifest.webmanifest:1 Manifest: property 'url' ignored, should be within scope of the manifest.
manifest.webmanifest:1 Manifest: property 'url' of 'shortcut' not present.
remoteEntry.d6df56cd69f4640706bc.js:1 Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/settingregistry (required ^3.5.2)
f @ remoteEntry.d6df56cd69f4640706bc.js:1
remoteEntry.d6df56cd69f4640706bc.js:1 Unsatisfied version 6.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/services (required ^6.5.2)
f @ remoteEntry.d6df56cd69f4640706bc.js:1
remoteEntry.d6df56cd69f4640706bc.js:1 Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/translation (required ^3.5.2)
f @ remoteEntry.d6df56cd69f4640706bc.js:1
remoteEntry.d6df56cd69f4640706bc.js:1 No satisfying version (^3.5.2) of shared module @jupyterlab/outputarea found in shared scope default.
Available versions: 3.5.1 from _JUPYTERLAB.CORE_OUTPUT
p @ remoteEntry.d6df56cd69f4640706bc.js:1
remoteEntry.d6df56cd69f4640706bc.js:1 Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/rendermime (required ^3.5.2)
f @ remoteEntry.d6df56cd69f4640706bc.js:1
remoteEntry.d6df56cd69f4640706bc.js:1 Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/logconsole (required ^3.5.2)
f @ remoteEntry.d6df56cd69f4640706bc.js:1
remoteEntry.d6df56cd69f4640706bc.js:1 Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/mainmenu (required ^3.5.2)
f @ remoteEntry.d6df56cd69f4640706bc.js:1
remoteEntry.d6df56cd69f4640706bc.js:1 Unsatisfied version 3.5.1 from _JUPYTERLAB.CORE_OUTPUT of shared singleton module @jupyterlab/notebook (required ^3.5.2)
f @ remoteEntry.d6df56cd69f4640706bc.js:1
remoteEntry.176149dcbfb677ea36fb.js:1 Unsatisfied version 6.0.2 of shared singleton module @jupyter-widgets/base (required ^1.0.4 || ^2 || ^3 || ^4)
l @ remoteEntry.176149dcbfb677ea36fb.js:1
injectStylesIntoStyleTag.js:190 The keyword 'slider-vertical' specified to an 'appearance' property is not standardized. It will be removed in the future.
A @ injectStylesIntoStyleTag.js:190
service-manager.ts:45 JupyterLite ServiceWorker was already registered
index.ts:235 Kernel filesystem and JupyterLite contents will be synced
568.9ca0150d166d080b7a8a.js?v=9ca0150d166d080b7a8a:1 JupyterLab extension jupyterlab-jupytext is activated
568.9ca0150d166d080b7a8a.js?v=9ca0150d166d080b7a8a:1 Jupytext: adding command=jupytext:ipynb with rank=1
568.9ca0150d166d080b7a8a.js?v=9ca0150d166d080b7a8a:1 Jupytext: adding command=jupytext:auto:light with rank=2
568.9ca0150d166d080b7a8a.js?v=9ca0150d166d080b7a8a:1 Jupytext: adding command=jupytext:auto:percent with rank=3
568.9ca0150d166d080b7a8a.js?v=9ca0150d166d080b7a8a:1 Jupytext: adding command=jupytext:auto:hydrogen with rank=4
568.9ca0150d166d080b7a8a.js?v=9ca0150d166d080b7a8a:1 Jupytext: adding command=jupytext:auto:nomarker with rank=5
568.9ca0150d166d080b7a8a.js?v=9ca0150d166d080b7a8a:1 Jupytext: adding command=jupytext:md with rank=6
568.9ca0150d166d080b7a8a.js?v=9ca0150d166d080b7a8a:1 Jupytext: adding command=jupytext:md:myst with rank=7
568.9ca0150d166d080b7a8a.js?v=9ca0150d166d080b7a8a:1 Jupytext: adding command=jupytext:Rmd with rank=8
568.9ca0150d166d080b7a8a.js?v=9ca0150d166d080b7a8a:1 Jupytext: adding command=jupytext:qmd with rank=9
568.9ca0150d166d080b7a8a.js?v=9ca0150d166d080b7a8a:1 Jupytext: adding command=jupytext:custom with rank=10
568.9ca0150d166d080b7a8a.js?v=9ca0150d166d080b7a8a:1 Jupytext: adding command=jupytext:none with rank=11
112.8cb647c0c1061fe0516b.js?v=8cb647c0c1061fe0516b:1 JupyterLab extension jupyterlab-rise is activated!
/rennes/lite/nbdime/api/isgit?1676101132255:1          Failed to load resource: the server responded with a status of 404 ()
/rennes/lite/nbdime/api/isgit?1676101132339:1          Failed to load resource: the server responded with a status of 404 ()
tutoriels-jupyter.pages.in2p3.fr/:1 Uncaught (in promise) Response
tutoriels-jupyter.pages.in2p3.fr/:1 Uncaught (in promise) Response
index.ts:65 Pyolite contents will be synced with Jupyter Contents
pyodide.asm.js:10 Loading distutils
pyodide.asm.js:10 Loaded distutils
pyodide.asm.js:10 Python initialization complete
pyodide.asm.js:10 distutils already loaded from default channel
pyodide.asm.js:10 Loading micropip, pyparsing, packaging
pyodide.asm.js:10 Loaded pyparsing, packaging, micropip
pyodide.asm.js:10 Loading jedi, parso, decorator, pygments, six
pyodide.asm.js:10 Loaded parso, jedi, decorator, pygments, six
13broadcast.ts:62 Uncaught (in promise) TypeError: Cannot destructure property 'path' of 'a' as it is null.
    at BroadcastChannel._onMessage (broadcast.ts:62:13)
tutoriels-jupyter.pages.in2p3.fr/:1 The keyword 'slider-vertical' specified to an 'appearance' property is not standardized. It will be removed in the future.
</pre>
</details>

## Typical use case

A teacher is hosting several jupyterlite instances, one for each of their course, on their web site.

**Comment by bollwyvl** [comment]
Thanks for the reproducer.

A domain hosting independent "logical" sites can be configured with multiple storage names for [contents](https://jupyterlite.readthedocs.io/en/latest/howto/content/files.html#customizing-content-storage) and [settings](https://jupyterlite.readthedocs.io/en/latest/howto/configure/storage.html#settings-storage) instead of the default of `JupyterLite Storage`.

To separate them entirely, in the first site:

```json
{
  "jupyter-config-data": {
    "settingsStorageName": "À la découverte de l’écosystème Jupyter et des carnets numériques",
    "contentsStorageName": "À la découverte de l’écosystème Jupyter et des carnets numériques"
  }
}
```

And the other one:

```json
{
  "jupyter-config-data": {
    "settingsStorageName": "Mini-site JupyterLite pour l’Université de Rennes",
    "contentsStorageName": "Mini-site JupyterLite pour l’Université de Rennes"
  }
}
```

Or, one could just set the `contentsStorageName`, such that preferences (like chosen theme, font size, etc.) are persisted between the different sites.

Note that changing these will lead to apparent total data loss for any user-authored content.

It gets a little messier around different _versions_ of JupyterLite on the same site, as the ServiceWorker which enables syncing files to the kernel, is a little more picky... we likely need to hoist that to a configuration parameter as well.

**Comment by bollwyvl** [comment]
Please open a new issue if you encounter issues with the solution as documented.
