### ISSUE TITLE
post_build:contents:contents fails if there is a folder with multibyte characters

### ISSUE THREAD

**Issue by katotetsuro** [jupyterlite/jupyterlite#984]
## Description

post_build:contents:contents fails if there is a folder with multibyte characters in the name

## Reproduce

Build jupyterlite as follows

```
mkdir -p contents/multibyte_character_folder_あ 
touch contents/multibyte_character_folder_あ/foo.txt
jupyter lite build --contents contents
``` 

outputs the following error

```
.  post_build:contents:contents:multibyte_character_folder_あ
Couldn't fetch //multibyte_character_folder_%E3%81%82 as Jupyter contents.  HTTP 404: Not Found (file or directory does not exist: 'multibyte_character_folder_%E3%81%82')
                If this folder, or one of its parents, starts with a `.`, you can
                enable indexing hidden files with a `jupyter_lite_config.json` such as:

                    "ContentsManager": {
                        "allow_hidden": true
                    }

                Alternately, to skip it:

                    "LiteBuildConfig": {
                        "extra_ignore_contents": [
                            "/\.<the offendings path name>"
                        ]
                    }
                
TaskFailed - taskid:post_build:contents:contents:multibyte_character_folder_あ
Python Task failed: '<bound method ContentsAddon.one_contents_path of <jupyterlite.addons.contents.ContentsAddon object at 0x105ab6b80>>' returned False
```

## Expected behavior

The post_build process completes normally.

## Context

I think this problem has occurred since the following commit to use `as_uri`

https://github.com/jupyterlite/jupyterlite/commit/a9372f178accf2aa4b0523de32256a4e6e19e23b

I don't know what kind of problem exists in a Windows environment (avoided the conversion of \ to / in as_posix?), but if you want to convert to a path relative to self.output_files_dir, it may be replaced by the following code

```
listing_path = str(output_file_dir.relative_to(self.output_files_dir))
```

- JupyterLite version: 0.1.0b18
- Operating System and version: MacOS 12.6
- Browser and version: N/A

**Comment by katotetsuro** [comment]
This appears to be the same problem
https://github.com/jupyterlite/jupyterlite/issues/1069

**Comment by theonewolf** [comment]
@katotetsuro I agree, it is related to URL encoding the folder names, but not decoding them for file system ops.
