### ISSUE TITLE
Reorganizing packages and dependencies

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlite/jupyterlite#993]
### Problem

With #854  close to merge, we've introduced some new complexity. We probably need to think more about both near- and further term packaging to avoid sacrificing flexibility _or_ compatibility.

### Proposed Solution

Definitely a strawman, but: targeting a notional `0.1.1b0` release, split the package on PyPI, but keep in this repo:

#### `jupyterlite-core 0.1.1b0`

This package would allow for really minimal or custom sites (such as kernels) to avoid features (e.g. kernels) they didn't ask for.

  - requires
    - `doit`
    - `jupyter-core`
  - provides 
    - `jupyter lite` CLI entrypoint
    - constants 
    - all actual addon implementations
    - core `app` bundle (with all `lab`, `retro` and `repl`)
      - splitting them is a pain, and probably not worth the squeeze
    - all the `[extras]` (still as `[extras]`)
    - tests
    - the JS kernel
    - maybe replace `python-libarchive-c` with something more portable/maintained

#### `jupyterlite 0.1.1b0`

This package would allow for better enabling the 80% case of:

> i got some python notebooks that pip install stuff, and want a site

   - provides
     - shims for `.constants` and `.addons.base`
       - toss a _reasonable_ number of warnings (ideally, one) when these are imported
       - don't shim `.tests`
   - requires
     - `jupyterlite-core[lab] 0.1.0b0`
       - this would fulfill `[contents,translation,check]`
     - `jupyterlite-pyodide-kernel`
     - `[extras]` that match all the existing ones
   - _maybe_ requires
     -  `jupyterlab-widgets` (just for completeness of what we've invested a lot of time into)

### Additional context

In making these changes, we should try to find in-the-wild, published downstreams that extend e.g. `addons.base.BaseAddon`, and take pains not to break their stuff... if they're well behaved, they have been pinning to a specific release, so it's likely we wouldn't be able to install them directly, but a `canary` repo in this site might be able to handle some short-lived submodules/patches.

A future version, number to be determined, might drop the `jupyterlab-widgets` and `jupyter-pyodide-kernel`.

**Comment by jtpio** [comment]
Thanks for summarizing this in a new issue :+1: 

> targeting a notional 0.1.1b0 release

Why not just continue with `0.1.0b19` and then soon after start targeting rc and then finally 0.1.0. So we can finally use a proper version number.

> This package would allow for really minimal or custom sites (such as kernels) to avoid features (e.g. kernels) they didn't ask for.

Looks like we could pretty much rename the existing `jupyterlite` package in this repo to `py/jupyterlite-core`. And then add a sibling for the jupyterlite` metapackage as mentioned above.

**Comment by jtpio** [comment]
Once we have the new `jupyterlite-core` package in the repo we can make a (first manual) release of it on PyPI and start updating `jupyterlite-xeus-python` and `jupyterlite-pyodide-kernel` to use it.
