### ISSUE TITLE
Remove more of the `pyolite` hangover

### ISSUE THREAD

**Issue by bollwyvl** [jupyterlite/jupyterlite#995]
### Problem

After #854, there are still some dangling references to `pyolite` that will cause confusion on the docs, etc.

### Proposed Solution

Remove the dangling references:

- constants ([renamed downstream](https://github.com/jupyterlite/pyodide-kernel/pull/19/files#diff-e90896b3695e1a7c57b585dc7c63ca9f80329d4ea5dc1935523c63fa30c8928aR14))
- schema entries (https://github.com/jupyterlite/pyodide-kernel/pull/19/commits/015e1a390e88a6012b66ee2a9a53989be285ee57)
- kernelspec/icon (https://github.com/jupyterlite/pyodide-kernel/pull/19#issuecomment-1462252729)

Update docs:

- use the new in-place schema from `jupyterlite-pyodide-kernel`
  - describe migration approaches

### Additional context

- probably blocked by 
  - #994 
  - https://github.com/jupyterlite/pyodide-kernel/pull/19

**Comment by jtpio** [comment]
We could also enable another tag (for example `0.1.0b18`) on ReadTheDocs for now as the default, instead of `latest`.

And default back to `latest` when ready.

**Comment by bollwyvl** [comment]
Yes, we should have had tags on all along :blush:

**Comment by jtpio** [comment]
Just tried to activate `v0.1.0b18` but it failed to build: https://readthedocs.org/projects/jupyterlite/builds/19713568/

**Comment by bollwyvl** [comment]
yep. more languages more problems.

**Comment by jtpio** [comment]
This was fixed in https://github.com/jupyterlite/jupyterlite/pull/964, but after the `0.1.0b18` release.

I pushed a (temporary `0.1.0-beta`) tag pointing to 7971e0aa67b65f9df204f9ab12b0e727b0e9e952 for now, and enabled it on ReadTheDocs: https://jupyterlite.readthedocs.io/en/0.1.0-beta/

**Comment by jtpio** [comment]
Opened https://github.com/jupyterlite/jupyterlite/pull/997
